inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.properties
- Support "ANY" as a scope (although it is a really really bad implementation and we really need a better concept selection UI!)
=> #10 - Refactor concept features

pom.xml
- Update dependency version to 2.3.0
=> #19 - Upgrade to RDF4J 2.3.0

inception-app-webapp/pom.xml, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation.adoc, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings.adoc, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/systemproperties.adoc, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/upgrade.adoc, inception-doc/src/main/resources/META-INF/asciidoc/common/systemrequirements.adoc, inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/database.adoc, inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/setup.adoc, inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc, inception-doc/src/main/resources/META-INF/asciidoc/user-guide/installation.adoc, inception-doc/src/main/resources/META-INF/asciidoc/user-guide/upgrade.adoc, pom.xml
- Adjusted documentation to INCEpTION
=> #20 - Modularize documentation

inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- fixbug #41 , remove the implicit learning record
- feature #58 , update al sidebar if the user sets annotation in right sidebar
- Please note that the current webanno master branch is 3.5.0, but inception master uses webanno branch 3.4.0
=> active learning sidebar event updates

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/SubjectObjectFeatureEditor.java
=> #16 - Mark slots as "not to be filled"

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/IriConstants.java, inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBases.java
- Add Wikidata SPARQL endpoint
- Fix IRIs
=> #135 - Default Wikidata URIs/IRIs wrong

inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- executeQuery shows the original mtas message for query syntax errors
=> #108 - Show mtas syntax errors

inception-active-learning/marker-wicket-module, inception-active-learning/pom.xml, inception-app-ui-search/marker-wicket-module, inception-app-ui-search/pom.xml, inception-app-webapp/marker-wicket-module, inception-app-webapp/pom.xml, inception-html-editor/marker-wicket-module, inception-html-editor/pom.xml, inception-imls-external/marker-wicket-module, inception-imls-opennlp/marker-wicket-module, inception-pdf-editor/marker-wicket-module, inception-pdf-editor/pom.xml, inception-recommendation/marker-wicket-module, inception-recommendation/pom.xml, inception-ui-core/marker-wicket-module, inception-ui-core/pom.xml, inception-ui-dashboard/marker-wicket-module, inception-ui-dashboard/pom.xml, inception-ui-kb/marker-wicket-module, inception-ui-kb/pom.xml, pom.xml
- Introduced profile, added marker files, and removed resource configuration in individual modules
=> #144 - Introduce profile for Wicket modules

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/PropertyFeatureEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/QualifierFeatureEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/SubjectObjectFeatureEditor.java
- Adjust to changes in Webanno
=> #176 - Move ID-setting code from feature editors into FeatureEditorPanelContent

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java, inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/model/KnowledgeBase.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseListPanel.java
- kbs are sorted from A-Z now, ignoring the case
=> #185 - Sort Knowledge Bases in Project Settings

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptInfoPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptListPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptTreePanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/PropertyListPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/PropertyPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/event/AjaxConceptSelectionEvent.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/event/AjaxPropertySelectionEvent.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementGroupPanel.java
- selection-changed-events contain information whether listpanels should be redrawn or not
=> #217 - Concept tree loses scrolling position on select

inception-app-webapp/src/main/resources/META-INF/security-context.xml
- Avoid redirection of login screen to favicon by allowing access to it without authentication
=> #187 - Favicon is wrong

README.md
Help people interested in this repository understand your project by adding a README.
=> #192 - Add README

inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java
- Using forEachOrdered seems to help
=> #307 - NPE when using recommenders on NE with a value but no identifier

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.html
- Move checkboxes up and fix indentation
=> #314 - Re-order items in KB settings

pom.xml
- Upgrade Spring Boot 1.5.10 -> 1.5.13
- Upgrade DKPro Core 1.9.1 -> 1.9.2
=> #331 - Upgrade dependencies

inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- avoid to pass the JCAS to the confirm action
=> #311 - Non-serializable field in active learning code

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.properties
- add disabled "read-only"-checkbox for remote KBs in KB settings
=> #377 - disable "read-only"-checkbox in kb settings instead of hiding it

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBInstance.java
If there is no language field, just create literal using name.
=> #353 - Create Instance throws Null Pointer Exception

inception-recommendation-api/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/model/db-changelog.xml
- Added liquibase config for the new column
=> #336 - NamedEntityLinker broken

inception-kb/pom.xml, inception-log/pom.xml, inception-recommendation-api/pom.xml, inception-recommendation/pom.xml, inception-search-core/pom.xml, inception-ui-kb/pom.xml, pom.xml
- Spring -> 5.0.7
- Spring Boot -> 1.5.14
=> #389 - Upgrade dependencies

inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- Use feasureSupport.renderFeatureValue()
=> #391 Unable to index non-string primitive features

inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/model/LoggedEvent.java, inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/LearningRecord.java, inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Recommender.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/model/Index.java
- Add strategy = GenerationType.IDENTITY
=> #403 - Fix generated value annotations

inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/util/CasUtil.java
- Add loaded annotations to result list
I also need this in master, as REC says we will not release stable too soonish.
=> #409 - Recommendations not shown

inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/model/LoggedEvent.java, inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/LearningRecord.java, inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Recommender.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/model/Index.java
Merge 0.4.x into master before our emergency release.
=> Release/413 release 0.4.1 for external recommender

inception-active-learning/pom.xml, inception-app-ui-search/pom.xml, inception-app-webapp/pom.xml, inception-build/pom.xml, inception-concept-linking/pom.xml, inception-doc/pom.xml, inception-html-editor/pom.xml, inception-imls-core/pom.xml, inception-imls-external/pom.xml, inception-imls-opennlp/pom.xml, inception-imls-stringmatch/pom.xml, inception-kb/pom.xml, inception-log/pom.xml, inception-pdf-editor/pom.xml, inception-recommendation-api/pom.xml, inception-recommendation/pom.xml, inception-search-core/pom.xml, inception-search-mtas/pom.xml, inception-support/pom.xml, inception-ui-core/pom.xml, inception-ui-dashboard/pom.xml, inception-ui-kb/pom.xml, pom.xml
=> #413 - Release 0.4.1

pom.xml
- Update commons-lang3 version to 3.7
=> #432 - Cannot export project with "WebAnno TSV3" format

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java, inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/SPARQLQueryStore.java, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
=> #428 SPARQL query does not define required prefixes

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java, inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/PropertyListPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseWrapper.java
- Issue #421 
- Issue because of NO subClassOf property found in KB. 
Solution Description: 
- Initialize base properties while registering or updating KB
- Base Properties : subClassOf, comment  and label 
- When updating KB , delete the list of older base properties.
=> #421 Cannot create subclass issue

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java, inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/PropertyListPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseWrapper.java
Reverts inception-project/inception#437
Request to revert. Issue needs further discussion and evaluation.  New PR open #450
=> Revert "#421 Cannot create subclass issue"

inception-active-learning/pom.xml, inception-app-ui-search/pom.xml, inception-app-webapp/pom.xml, inception-build/pom.xml, inception-concept-linking/pom.xml, inception-doc/pom.xml, inception-html-editor/pom.xml, inception-imls-core/pom.xml, inception-imls-external/pom.xml, inception-imls-opennlp/pom.xml, inception-imls-stringmatch/pom.xml, inception-kb/pom.xml, inception-log/pom.xml, inception-pdf-editor/pom.xml, inception-recommendation-api/pom.xml, inception-recommendation/pom.xml, inception-search-core/pom.xml, inception-search-mtas/pom.xml, inception-support/pom.xml, inception-ui-core/pom.xml, inception-ui-dashboard/pom.xml, inception-ui-kb/pom.xml, pom.xml
=> Release for 0.4.2

inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplWikiDataIntegrationTest.java
Right now, the support for reified WikiData is only partial. For instance, in the knowledge base view, concepts cannot be listed. Write an integration test that checks whether the support is fully functional.
=> Feature/191 WikiData Integration test

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AbstractInfoPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AnnotatedListIdentifiers.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AnnotatedListIdentifiers.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptInstancePanel.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptInstancePanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/InstancePanel.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/InstancePanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePage.properties
- KB concept mentions in Instance Info panel
=> #170 Panel on KB UI with Search functionality for KB entries

inception-app-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.html, inception-app-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Made input field larger and resizable
=> #477 - Search input field too small

pom.xml
- DKPro Core 1.9.2 -> 1.9.3
- WebAnno 3.5.0-beta-3
=> #471 - Upgrade dependencies (0.5.0)

inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/knowledgebase-profiles.yaml
- Set the description IRI to the schema.org IRI
=> #473 - No entity description for UKP_WIKIDATA

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementGroupPanel.java
- Adding base properties : Label and description properties in dropdown list for Statement Editor
=> #479 Label and description properties not available

inception-kb/pom.xml, pom.xml
=> #19 - Upgrade to RDF4J 2.3.2

inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/FeatureIndexingSupport.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/PrimitiveUimaIndexingSupport.java, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java, inception-search-mtas/src/main/resources/META-INF/asciidoc/user-guide/search-mtas.adoc, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupport.java, inception-ui-kb/src/test/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupportTest.java, pom.xml
- Index source and target of relations specifically
- Use "-" instead of "." to separate special suffixes (this also affects ".exact" which changes to "-exact")
- Update documentation (including some reformatting)
- Upgrade MTAS
- Added profile to facilitate building the docs much faster
=> #489 - Better indexing of relations

inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchService.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/IndexScheduler.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/TaskConsumer.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexDocumentTask.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/Task.java, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java, inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java, inception-search-mtas/src/test/resources/log4j2.xml
- Created new IndexDocumentTask to be called asynchronously whenever a
new annotation is made
=> #462 - Improve speed of annotation

inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/knowledge_base.adoc
=> #491 Documentation for Statement validation

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- Check for the SYSTEM folder on startup and rename it if it is present
=> #508 - Presence of deprecated RDF4J SYSTEM repository may cause trouble

inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseExporterTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplImportExportIntegrationTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/util/TestFixtures.java, inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/exporter/RecommenderExporterTest.java, inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java, inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java, inception-ui-kb/src/test/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupportTest.java, pom.xml
- Set project mode when projects are created in tests
- Upgrade to WebAnno 3.5.0-beta-4
=> #531 - Update unit tests to compensate for mandatory project mode

inception-active-learning/pom.xml, inception-app-ui-search/pom.xml, inception-app-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/SearchPage.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/WicketApplication.properties, inception-html-editor/pom.xml, inception-imls-external/pom.xml, inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalClassifier.java, inception-recommendation/pom.xml, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java, inception-search-mtas/pom.xml, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java, inception-ui-core/pom.xml, inception-ui-dashboard/pom.xml, inception-ui-kb/pom.xml, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AbstractInfoPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AnnotatedListIdentifiers.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptTreePanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/InstanceListPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/QualifierFeatureEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/SubjectObjectFeatureEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/QualifierEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementGroupPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/editor/StatementEditor.java, pom.xml
- Switched dependencies and adjusted code
Requires: https://github.com/webanno/webanno/pull/995
=> #528 - Upgrade to Wicket 8

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java
- Issue related to query for loading child concepts
- Fix bug with a condition on evaluateListQuery
- Add Junit test case for child concepts
=> #536 Wine ontology KB page fails to load

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/NumericLiteralValueSupport.java
- Refactor code to be null-resistant
=> #546 - NPE in NumericLiteralValueSupport due to bad null check

inception-app-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/SearchPageMenuItem.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/menu/AgreementPageMenuItem.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/menu/AnnotationPageMenuItem.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/menu/CurationPageMenuItem.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/menu/MonitoringPageMenuItem.java, inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/page/evaluation/EvaluationPageMenuItem.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePageMenuItem.java
=> #550 - Adjust to changes from WebAnno issue 1065

inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingService.java
- Show IRI of the concept along with the description in the tooltip/popup
=> #553 Show IRI in description tooltip/popup

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
=> #552 Duplicates in concept feature editor

inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
=> #575 - Adjust to WebAnno 1084 - Registry for layer types

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/ProjectRecommendersPanel.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderProjectSettingsPanelFactory.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseProjectSettingsPanelFactory.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.java
- Replaced ProjectSettingsPanel annotation with a registry/factory mechanism
=> #589 - Introduce registry for project settings panels

inception-concept-linking/pom.xml, inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingService.java, inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/ConceptLinkingServiceTest.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/scheduling/RecommendationScheduler.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/IndexScheduler.java
- Remove Resource, PostConstruct and PreDestroy annotations and use Autowired, InitializingBean and DisposableBean instead
- Removed duplicate dependencies
=> #584 - Fix build on Java 11

inception-imls-opennlp/pom.xml, inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/DocumentSampleStream.java, inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java, inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderFactory.java, inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTraits.java, inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTest.java, inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderTest.java, inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderTest.java, inception-imls-opennlp/src/test/resources/de/tudarmstadt/ukp/dkpro/core/api/datasets/lib/sentence-classification-en.yaml
- Basic implementation of a recommender based on the OpenNLP Document Categorizer
=> #590 - Sentence-level recommender

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java
- Made the language field not mandatory
- Removed unnecessary LambdaAjaxFormComponentUpdatingBehavior
- Ensure that feedback messages are shown if the form is not valid
=> #586 - Unable to configure KB without language

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/scheduling/tasks/PredictionTask.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/scheduling/tasks/SelectionTask.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/scheduling/tasks/TrainingTask.java
- Implemented the lazy loading
=> #594 - Load CASes during training/prediction/evaluation lazily

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
=> #607 - KB indexes stored in the wrong location

inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommender.java, inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderFactory.java
- Remove hardcoded URL
- Mark context for external recommender always ready
=> #612 - External recommender does not recommend things

pom.xml
- spring boot -> 1.5.17.RELEASE
- spring core -> 5.1.1.RELEASE
- assertj -> 3.11.1
- mockito -> 2.23.0
- commons-compress -> 1.18
- WebAnno -> 3.5.0-beta-6
=> #573 - Upgrade dependencies (0.6.0)

pom.xml
- Update to WebAnno 3.5.0-beta-9 which fixes the problem
=> #644 - Unable to access annotations screen

inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- Changed method of obtaining the type system to include internal types
=> #642 - Document cannot be indexed by Mtas, unable to read CAS

inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderIntegrationTest.java, inception-imls-stringmatch/pom.xml, inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java, inception-imls-stringmatch/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_string.adoc, inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderTest.java, inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngineFactory.java
- Report the relative frequency of the label for a given word as the score
- Honor the maxRecommendations setting
=> #652 - Probabilities from string matching recommender are not useful for active learning

inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/adapter/RecommendationSpanRenderer.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
- Refactored RecommendationUserState to be simpler without internal maps
- Store preferences (including showAll flag) per project
Not fixing this in 0.6.x because I took the opportunity to also refactor the managing of the state internally a bit.
=> #674 - "Show all" in recommender side bar is global, not per project

inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java, inception-search-mtas/src/main/resources/META-INF/asciidoc/user-guide/search-mtas.adoc, inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserLuceneTest.java, inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java
- Skip indexing of zero-width annotations
- Document behavior
- Updated unit test to check that zero-width annotations are skipped
=> #648 - Error indexing zero-width annotations with MTAS

inception-app-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
=> #571 - Search highlight appears in wrong document

inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/util/QueryUtil.java
- Quote the query in single quotes as Virtuoso requires it
- If possible, add an asterisk to the last word for a prefix query (same as we do for Lucene)
=> #690 - Full text search against Virtuoso KBs not working if there are spaces

inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommender.java, inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/RemoteStringMatchingNerRecommender.java
- Explicitly set charset in more places.
=> #706 - External recommender tests fail on Windows

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptInstancePanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.java
- Set concept/property/instance label language when creating a new concept/property/instance
=> #711 - New concepts have no label (no reification)

inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java, inception-ui-core/src/main/resources/META-INF/asciidoc/user-guide/dashboard_projects-list.adoc
- Added toggle buttons to filter projects by role
- Documented new functionality
=> #713 - Add project role filter to project overview list

inception-search-mtas/pom.xml, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java, inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java
- Support attach-feature on relation layers
=> #724 - Dependency relations cause NPE during MTAS indexing

inception-app-webapp/src/main/resources/META-INF/rest-context.xml, inception-app-webapp/src/main/resources/META-INF/security-context.xml, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
- Protect swagger UI for access only for ROLE_REMOTE
- Remove unnecessary entries from `rest-context.xml`
- Add references to remote API and webhook sections in the admin documentation
=> #728 - Make remote API support official

inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java
- Cap the score at 0 - do not return lower values.
=> #754 - String recommender doesn't activate for zero threshold

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/exporter/ExportedRecommender.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/exporter/RecommenderExporter.java
=> #756 - Exporting recommender uses wrong field names

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/log/RecommenderEvaluationResultEventAdapter.java
* The Logged Event of the type RecommenderEvaluationResultEvent also adds recommender id in the details column.
- recommender id added to RecommenderEvaluationResultEvent details
=> #770 - Include more info in recommender events

inception-doc/src/main/resources/META-INF/asciidoc/developer-guide.adoc, inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/HtmlAnnotationEditor.java, inception-log/pom.xml, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepository.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/ExportedLoggedEvent.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/RawJsonDeserializer.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/model/LoggedEvent.java, inception-log/src/main/resources/META-INF/asciidoc/developer-guide/log-adapter.adoc, inception-log/src/main/resources/META-INF/asciidoc/developer-guide/log.adoc, inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporterTest.java, inception-log/src/test/resources/log4j2.xml
- Added LoggedEventExporter
* Create project
* Export project
* Import project again
* Look at logged events table in the database
=> #266 - Support import/export in logging module

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java, inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java, inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/less/inception-ui-kbp.less, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupport.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/NumericLiteralValueSupport.java
- Disable FTS for ZBW endpoints
- Define explicit root for GND and YAGO
- Improve mapping for YAGO
- Avoid line-breaks in the concept tree
- Allow owl:Thing to be used as a root concept
- Handle decimal values using the numeric editor
* Create KBs from the updated profiles
* Try browsing on the KB page
* Try linking an entity mention to a concept from them
=> #847 - Fix/improve default KB profiles

inception-pdf-editor/pom.xml, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfAnnoPanel.java, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfAnnoRenderer.java, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/DocumentModel.java, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/Offset.java, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfAnnoModel.java, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfExtractFile.java, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/Relation.java, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/Span.java, inception-pdf-editor/src/main/js/pdfanno/src/core/src/UI/span.js, inception-pdf-editor/src/main/js/pdfanno/src/pdfanno.js, inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoModelTest.java, inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java
Possibility to create span annotations within PDF editor view.
Closes #838 
1. Open a PDF file in PDF editor view
2. Select a layer
3. Select some text in PDF
4. Annotation should appear after a short time
5. Annotation should also appear when changeing to brat editor
=> #838 - Creation of spans in PDF editor

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/IriInfoBadge.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/IriInfoBadge.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementGroupPanel.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementGroupPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/editor/IRIValuePresenter.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/editor/IRIValuePresenter.java
- Factor IRI badge out into a re-usable class
- Add IRI badge to IRI-value statements in presentation mode
- Move IRI badge to the front of property labels in the statement group so they are all nicely aligned
- Optimized the loading of the KBObject in the IRI Value presenter to avoid unnecessary KB queries
**Note:** Made this a 0.7.1 feature since it is small and very useful.
- Open KB
- Look for IRI-valued statments
- Click on IRI badge to see if IRI tooltip appears and shows the expected value
=> #870 - IRI info for IRI-valued statements

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/RdfUtils.java, inception-scheduling/pom.xml, inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseIriPanel.java, pom.xml
- Set Java source/target version back to 8
- Depend on release version of WebAnno
- Check if INCEpTION compiles and starts
=> #894 - Allow INCEpTION to run on Java 8

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementGroupPanel.java
* remove duplicates from property choice when creating a new statement
* create a new statement in the KB. See if the property choice shows any duplicates. 
=> #812 Property choice shows duplicates when creating new statements

inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java, inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporterTest.java
- Check if there actually is an event log to import and skip importer if there is none
* Import the project attached in the issue description of #901 
=> #901 - Import fails if project archive does not include event log

inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/InspectableThreadPoolExecutor.java, inception-scheduling/src/test/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceTest.java
- Use a fair queue
- Ignore the order of tasks in the unit test
* Check that unit test still runs - reproducing the original error is hardly possible
=> #906 - SchedulingServiceTest fails sporadically

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java, inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java, inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/Task.java, inception-scheduling/src/test/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceTest.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/TaskConsumer.java, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- Add 'origin' to enqueue
- Set logging to debug
- Annotate stuff
- See in the log that tasks are started for reasons
=> #924 - Improve debugging of scheduler

pom.xml
- WebAnno 3.6.0-beta-1
- UIMA 2.10.3
* Basically compile, run, and see if anything is broken ;)
=> #941 - Upgrade dependencies (0.8.0)

inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/traits/ElasticSearchProviderTraitsEditor.html
- Put each group of elements into a form group
=> #942 - Layout of elastic search traits is broken

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/GeneralSettingsPanel.java
- Removed unnecessary Lambda adapter
- Removed unnecessary empty lambda in change behavior
- Moved validator into an inner class instead of using lambda
- Unrelated change: add scrollbar to KB page sidebar if page gets rather small (containing concept tree and properties...)
=> #953 - Exception when reloading page

inception-app-webapp/pom.xml, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/LifFormatSupport.java
- Added LIF support component
* Try importing a LIF file (mind that LIF files with envelope are presently not supported, so it may be necessary to remove the outer JSON Object from the LIF file and retain only the `payload`).
=> #956 - Add LIF support

inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTest.java
- Seems to be up again - unignoring test
* Run the `OpenNlpDoccatRecommenderTest`
=> #970 - https://archive.ics.uci.edu is down

inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java
- Reactivated test against YAGO
* Run `KnowledgeBaseServiceRemoteTest`
=> #890 - YAGO SPARQL endpoint not reachable

inception-scheduling/src/test/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceTest.java
- Fix test by changing condition for waiting until test is ready for assertion
* Run the unit tests repeatedly
* Make a release and see that it does not crash due to this
=> #906 - SchedulingServiceTest fails sporadicall

pom.xml
- Update WebAnno dependency
1. Create two POS annotations
2. Try creating a dependency annotation between them
=> #1035 - Cannot create relations

inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/model/CandidateEntity.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java, inception-kb/src/test/resources/data/README.txt, inception-kb/src/test/resources/data/penn.owl
- Set the default value for Levenshtein features to MAX_INT
=> #1037 - Bad default value for Levenshtein features

inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- After all the by-score ranking add an additional step sorting alphabetically when there is a score tie
=> #1043 - KB items with the same score not sorted alphabetically

inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java, inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java, inception-example-imls-data-majority/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommenderTest.java, inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommender.java, inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java, inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommender.java, inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java, inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java, inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java, inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTest.java, inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderTest.java, inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderTest.java, inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java, inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderTest.java, inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/evaluation/EvaluationResult.java, inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngine.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
Use an evaluation result object as the return type of the recommenders' evaluate method to later populate with statistics. At the moment it contains info on data set sizes and the previous default score.
* nothing to test
=> #653 Build evaluation result object

inception-example-imls-data-majority/pom.xml, inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java, inception-example-imls-data-majority/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommenderTest.java
Evaluation of DataMajorityRecommender threw nullpointer exception. Now, evaluation is skipped if too little annotations with a label exist.
* Configure DataMajorityNerRecommender on NER layer on value feature
* Create a couple of annotations and always leave the value feature empty
=> #1073 NPE in DataMajorityNerRecommender

.github/ISSUE_TEMPLATE/release-bugfix.md, .github/ISSUE_TEMPLATE/release-feature.md, inception-app-webapp/pom.xml, inception-app-webapp/src/main/docker/Dockerfile, inception-app-webapp/src/main/docker/README.md, inception-app-webapp/src/main/docker/docker-compose.yml, inception-app-webapp/src/main/resources/application.properties, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc, pom.xml
* Adding the docker stuff to 0.8.0
* Run `mvn -Pdocker clean install docker:build` and then start a container of this type `docker run -v /path/on/host/inception/repository:/export -p port-on-host:8080 inceptionproject/inception-snapshots:latest`
* Run `mvn -Pdocker clean install docker:build -Ddocker.image.name="inceptionproject/inception"` and then start a container of this type `docker run -v /path/on/host/inception/repository:/export -p port-on-host:8080 inceptionproject/inception:latest`
* In both cases, check that INCEpTION started by going to `localhost:8080`
=> #1047 - Docker backport

inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurity.java
*  Fix web security frame options
* Check that the PDF editor loads
=> #1111 - PDF editor is denied to be embedded

inception-app-webapp/src/main/docker/README.md, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc, inception-doc/src/main/resources/META-INF/asciidoc/developer-guide.adoc, inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/release.adoc, inception-doc/src/test/java/de/tudarmstadt/ukp/inception/doc/GenerateDocumentation.java
* Release documentation
* Make a release
=> #1106 - Add release documentation

inception-imls-dl4j/pom.xml, inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java, pom.xml
- Upgrade to latest DL4J
- Fix unit tests which should be testing on NER but wrongly initialize a POS recommender
* Build the DL4J module, run unit tests
=> #1155 - Upgrade to DL4J 1.0.0-beta4

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/chart/ChartPanel.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/chart/resources/chart.js
- Bug fix
* Javascript bug fix
* Removed `tag.put("my:canvas.chartid", getMarkupId());`
=> #808 Project Settings Panel for Simulated Evaluation

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/editor/StatementEditor.java
- readItem should ignore non-enabled KBs
- the StatementEditor should consider only items from the current KB for linking
=> #1170 - Concept value editor on KB page tries all KBs

inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.java
- Fix bad lookup of source document by title instead of looking it up by ID
=> #1126 - PubAnnotation Import Exception

pom.xml
- Spring -> 5.1.7.RELEASE
- Spring Boot -> 1.5.21.RELEASE
- Wicket JQuery UI -> 8.3.0
* Build, run, check if things still work
=> #1187 - Upgrade dependencies

pom.xml
- Update to WebAnno 3.6.0-beta-7 which fixes this issue
* Export something as TCF
=> #1185 - Can't export Weblicht TCF

inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database_mysql.adoc
* fix typo in the admin guide
* regenerate the documentation
* no
* PR updates documentation
=> Fix filename of the MySQL client conf

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java, inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- Obtain the document ID from the CasMetadata
=> #1208 - No recommendations if document title doesn't match file name

pom.xml
- Upgrade to WebAnno 3.6.0-SNAPSHOT to get fix for upstream issue
=> #1276 - Scheduler schedules training twice

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
- Gracefully handle the case where a recommender factory cannot be found
=> #1277 - Exception when recommender factory is not available

inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurity.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/session/SessionListener.java, inception-app-webapp/src/main/resources/META-INF/preAuthSecurity-context.xml, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
- Fix typo in context file
- Fixed injection of user repository
* Add the following lines to the `settings.properties` file
```
auth.mode                     = preauth
auth.preauth.header.principal = remote_user
auth.preauth.newuser.roles    = ROLE_PROJECT_CREATOR
auth.user.admin.roles         = ROLE_ADMIN
```
* Install ["Modify headers"](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj) plugin into Chrom
* Set the header `remote_user` to e.g. `dummy@somewhere.org`
* Access INCEpTION
* The application should log you in automatically and create the user `dummy@somewhere.org`. You can verify either by setting the header to "admin" or by commenting the extra lines from the settings.properties file, restarting …
=> #1282 - External authentication not working

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
* - Clone the prediction CAS for every recommender
1. Add two recommender for NER, e.g. String and OpenNLP
2. Do annotations so that both give recommendations
3. Check that annotations are not duplicated like 
=> #1272 - String matcher duplicates recommendations

inception-app-webapp/pom.xml, pom.xml
- Added dependencies on the tagsets UI
- Upgraded WebAnno dependency to a version which includes the tagsets UI html templates
* Access the tagset panel in the project settings
=> #1297 - Tagsets panel missing from project settings

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- Clear the task counter when the session ends
- Added additional trace-level log messages
* Cannot really be tested manually
=> #1307 - Task counter not cleared when logging out

inception-doc/pom.xml, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose.yml
- Embed script into admin guide and replace `latest` in script with the proper version
* Build and check that the Docker Compose script properly appears in the documentation
=> #1312 - Embed Docker Compose script into documentation

inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
- add handling of armed slots in PDF editor to fix linking of spans
* Have two layers, one with a link feature to the other
* In the PDF editor create a span and try to link another one to it
=> #1310 - Linking of spans not working in PDF editor

.gitignore, inception-app-webapp/pom.xml, inception-doc/pom.xml, inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/setup.adoc, inception-doc/src/main/resources/META-INF/asciidoc/docinfo.html, inception-doc/src/test/java/de/tudarmstadt/ukp/inception/doc/GenerateDocumentation.java, inception-recommendation-api/src/main/resources/META-INF/asciidoc/developer-guide/implementing_recommender_tutorial.adoc, inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- Add intellij and git to setup documentation
* Build the documentation and read it
=> #918 - Refactor dev documentation

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java, inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- Combine monkey patching of type system and cloning of CAS into a single step to improve performance
* Create a project with recommenders, annotate and see if the recommender work
=> #1335 - Recommendationservice performance

inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommenderContext.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
Add `User` to the `RecommenderContext` so that `RecommendationEngine` can access user information, if needed.
=> #1332 - User information in recommender context

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java, inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Use selectAt() and fetch first annotation instead of selectSingleAt
=> #1376 - Error accepting recommendations

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/DisabledKBWarning.java
- Use a proper auto-complete field for the scope
- Fix saving/loading of the scope
=> #1368 - unable to set correct scope for KB feature

inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/ElasticSearchProvider.java
- Use the simpleQueryStringQuery instead of the termQuery
=> #1393 - Elastic search repos accept only lower-case single-term queries

inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/feature/ImageFeatureSupport.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- Do not generate lazy details for unset features
=> #1389 - Infobox does not show for Named Entities

inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderFactory.java
- Add sentence anchor mode to `ExternalRecommenderFactory::accepts`
* Create a sentence anchored layer
* Check that you can create an external recommender on this layer
=> #596 - Support sentence-level annotation in external recommender

inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/ExternalSearchProvider.java, inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/ExternalSearchService.java, inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/ExternalSearchServiceImpl.java, inception-external-search-elastic/pom.xml, inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/ElasticSearchProvider.java, inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/PubAnnotationProvider.java, inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/DocumentDetailsPage.java
- Obtain the document title from ElasticSearch indexes
- Display the title on the results page and on the detail page
- When building the index, set the "title" metadata entry
- Search the index from the search page
=> #1406 - Display document title in search results

inception-app-webapp/pom.xml, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/UimaInlineXmlTeiFormatSupport.java, pom.xml
- Enable writing of TEI
- Add UIMA Inline XML writer
* Export as TEI
* Export as inline XML
=> #1423 - Support inline XML formats

inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategy.java, inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/model/PubAnnotationDocumentSection.java, inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderIntegrationTest.java, inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/util/CasAssert.java, inception-imls-lapps/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/lapps/traits/LappsGridRecommenderTraitsEditor.java, inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/trie/Trie.java, inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBInstance.java, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/RegionExtractor.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
In this PR, I refactor the variable names with leading underscore by removing the underscore.
=> Refactor/#1433 Rename the classes and fileds

inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.html, inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
- apply accordion style to the document annotation list
- if no feature preview is available show nothing instead of the document annotation label
* Play around with the document metadata sidebar
=> #1492 - New style for document metadata sidebar

inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/AnnotationSuggestion.java
- Generate the Optional in the getter, not in the constructor to make the field serializable
=> #1498 - Active learning complains about not serializable confidence explanation

inception-build/src/main/resources/inception/checkstyle.xml, pom.xml
- UIMA 3.1.0 -> 3.1.1
- Roll back to checkstyle 8.23 since IDE plugins are not supporting 8.26 yet.
* Build and run
=> #1456 - Upgrade dependencies

inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseSubPropertyLabelTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- Disabling ZBW GND tests for now
* Nothing to test
=> #1522 - GND tests not running

inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- Use selectSentenceCovering instead of selectSentenceAt
=> #1524 - Cannot find sentence for mention

inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- Cannot resolve a FS from a synthetic VID
- No need to send offsets to annotation editor extensions
- Formatting
=> #1513 - PDF editor crashes when clicking on recommendation

inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- Added another icon to open the IRI in a new browser window/tab
* Link an entity to some knowledge base item and see that the link appears / disappears if you unlink
* Click link to open IRI in the browser
=> #1484 - make tooltip for KB instance URI clickable

inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
- Write event log in batches (time-based)
- Flush on shutdown
- Flush if tool many events are in memory
* Perform some actions and see if the event log gets updated
=> #1527 - Batch event log writes

inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_home.adoc, inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings.adoc, inception-layer-docmetadata/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_docmeta.adoc
Added some clarification that the file needs to be created and linked to the explanation on application home folder
* Read the documentation
=> #1518 Document where the settings.properties file lives

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
- Set outer traits form to be always multipart
=> #1552 - Changing recommender type throws exception

inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommender.java
- Add try-with-resources to close the responses when they are no longer needed.
=> #1570 - External recommender forgets to close responses

inception-imls-external/pom.xml, inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommender.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchCasUtils.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchService.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/index/PhysicalIndex.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/IndexScheduler.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexAnnotationDocumentTask.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexSourceDocumentTask.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/Task.java, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- Added dealing with the CAS wrapper
- Fixed concurrent access caused by the indexing service
* Use the application
* check for ClassCastExceptions because which mean that the proxy may need to be removed via `getRealCas()`
* check for exceptions due to cross-thread access to the CAS
=> #1572 - Safeguard CAS against concurrent accesses

inception-app-webapp/pom.xml, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/ImsCwbFormatSupport.java, inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc, inception-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-imscwb.adoc
- Added r/w format support for IMS CWB format
- Added documentation
* Check that the new format appears in the format lists when importing/exporting
* Try exporting a pos/lemma annotated text in the format
* Try importing e.g. a part of a file from the Wacky Corpora (not too large ;)
=> #1582 - Support IMS CWB format

inception-imls-dl4j/pom.xml, pom.xml
- DL4J 1.0.0-beta4 -> 1.0.0-beta6
* Use application
=> #1590 - Upgrade dependencies (0.15.0)

inception-app-webapp/pom.xml, inception-doc/pom.xml, inception-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-imscwb.adoc, inception-doc/src/test/java/de/tudarmstadt/ukp/inception/doc/GenerateDocumentation.java, pom.xml
- Disable auto-conversion of tabs to spaces
* Copy VRT example to a file and then try importing it
=> #1597 - Several format examples cannot be used copy-paste

inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.html
- Add missing css
* Add some navbar items like to your settings.properties and see that navbar items look reasonable
```
style.header.icon.myOrganization.linkUrl=https://www.informatik.tu-darmstadt.de/ukp/ukp_home/index.en.jsp
style.header.icon.myOrganization.imageUrl=https://www.informatik.tu-darmstadt.de/media/ukp/logo/csm_UKP_Logo_97cd40_01_60fd855e34.png
style.header.icon.mySupport.linkUrl=https://www.tu-darmstadt.de/datenschutzerklaerung.de.jsp
style.header.icon.mySupport.imageUrl=https://public.ukp.informatik.tu-darmstadt.de/jck/privacy.png
```
=> #1637 - Navbar items do not have fixed height

inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
* Fixes NPE when storing curation settings for a user.
* see Issue
=> #1633 Exception when session expires

inception-concept-linking/pom.xml, inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java, inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinkerTraits.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.html
- Use annotation boundaries
- Fix empty bean jackson serialization
- Allow overlapping suggestions for different features
* See bug report
=> #1602 - NEL only looks for first word and not entire span

inception-doc/src/main/resources/META-INF/asciidoc/common/systemrequirements.adoc, pom.xml
- Upgrade to Servlet API 4.0.1 (compatible with the embedded Tomcat 9)
- Update system requirements
=> #1655 - Exception when opening login page

inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/sidebar/ImageSidebar.java, inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerSupport.java, inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java, inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java, inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/VisibilityCalculationTests.java
- Check for existence of layer/feature support in several places where the layers/features are accessed
=> #1672 - Resilience against missing feature/layer supports

inception-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-tei.adoc
Corrected the info on TEI format.
=> #1675 Documentation for TEI P5 format is wrong

inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- Fix NPE if layer does not have any features
* Create a layer without a feature
* Open a document for annotation
=> #1533 - Periodical commit of MTAS index

inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java, inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/index/PhysicalIndexRegistryImpl.java, inception-search-mtas/src/main/resources/META-INF/spring.factories
- Fixed auto-configuration of default indexing engine
- Avoid exceptions if no engine is configured
=> #1679 - Cannot delete project

inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
- Avoid NPE if user owning a session being destroyed does not exist in the system
- Load the user object only once in the process
* Log in without the fix and observe stack trace
* Log in with the fix and observer it is gone
=> #1654 - NPE on session destruction

inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_jar.adoc
* Update documentation for deployment via systemd
* Build docu
=> #1695 - Update documentation for deployment via systemd

inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Lazily load CAS during bulk operation
- Lazily upgrade CAS during bulk operation
* Create a project with two documents
* Create an annotation in the first document (e.g. POS)
* Add a new annotation layer
* Create an annotation of the new layer in the first document
* Attempt a bulk annotation using this annotation from the first document to annotate a search match in the second document
=> #1662 - Impossible to create annotations via Search

inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/exporter/DocumentRepositoryExporter.java, inception-log/pom.xml, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java
- Improve performance when importing log in projects with very many documents
- Fixed logging in DocumentRepositoryExporter
* Export / import projects
=> #1709 - Improve speed when importing/deleting large projects

inception-app-webapp/pom.xml, inception-app-webapp/src/main/resources/application.properties, inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationEditorExtension.java, inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/feature/ImageFeatureEditor.html, inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java, inception-testing/src/main/java/de/tudarmstadt/ukp/inception/support/test/recommendation/RecommenderTestHelper.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java, pom.xml
* Adjusted to upstream API changes
* Upgrade Wicket JQuery/Kendo
* Fixed warning on the KB settings panel in the project settings
* Annotate :)
=> #1711 - Adjust to api changes: Improve annotation detail sidebar architecture and performance

inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
- Check that pageOffset is set
* See bug
=> #1721 - Using PDF editor with wrong format

inception-app-webapp/src/main/resources/log4j2.xml, inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/AnnotationSuggestion.java, inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
- API adjustment
- Shorter extension ID for recommendations to save bandwidth
- Avoid Wicket warning in recommendation sidebar
=> #1717 - Adjust to upstream changes: Improve brat rendering

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java, inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePage.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.java
- Add user friendly mount path to KB page
- Use page parameters to specify KB
* Create some kbs, play with the KB dropdown and see that the URL works
=>  #1729 - Make KB links beautiful

pom.xml
- Spring Boot 2.2.6 -> 2.3.0
- Spring Security 5.2.3 -> 5.3.3
=> #1732 - Upgrade dependencies (0.17.0)

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java, inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/yaml/KnowledgeBaseProfile.java, inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseProfileDeserializationTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java, inception-kb/src/test/resources/log4j2.xml, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java, pom.xml
* Disable Yago
* Try to create remote YAGO kb
=> #1708 - Disable Yago

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/InstanceListPanel.html
Two scrollbars on the instance panel on the KB Page.
* Changed html to remove one scrollbar in `InstanceListPanel`
* Configure wine kb
* Open KB Page and select Region
* List of instances should only have one scrollbar now
=> #1730 Instances/Mention box has two scrollbars

inception-imls-dl4j/pom.xml, inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java
DL4j de.tudarmstadt.ukp.inception.recommendation.imls.dl4j.pos.DL4JSequenceRecommenderTest.thatPosPredictionWorks
de.tudarmstadt.ukp.inception.recommendation.imls.dl4j.pos.DL4JSequenceRecommenderTest.thatNerPredictionWorks
no longer passed when building with `-Pfull-tests`.
* Cases need to be added to casStorageSession to clear check when upgrading due to change in webanno
* build with `-Pfull-tests` or
* run tests as junit tests
=> #1766 Unit tests on master are failing on Jenkins

inception-imls-lapps/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/lapps/LappsGridRecommenderConformityTest.java
Getting response *unauthorized* from service, but service is open to all users to my knowledge (no username/password). So, ignore tests when we get this status.
* Updated lappsgrid tests to ignore tests when http response is 401
**How to test**
* Run unit tests
=> #1803 LAPPSGrid NER tests fail

inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/tutorial.js
*  Took out explanation on agreement menu item
* Follow the tutorial by clicking the start tutorial button on the projects page.
=> #1807 Adapt tutorial to agreement menu item change

inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java
* Ignoring DL4J NER tests for now until resource can be updated in dkpro
=> #1816 Some DL4J tests fail

inception-app-webapp/src/main/resources/application.properties, inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowActionBarExtension.java, inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowDocumentNavigationActionBarExtension.java
=> #1813-Last-activity-link-do-not-work-anymore

inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- Display the project ID in developer mode
* Start INCEpTION with Wicket debug mode enabled and look for the project ID on the project overview page
=> #1832 - Display project id in developer mode

inception-external-search-pubannotation/pom.xml, inception-external-search-pubannotation/src/test/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/PubAnnotationProviderTest.java, inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java, inception-ui-kb/pom.xml, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/sass/KnowledgeBasePageLRR.java, pom.xml
- Adjust to changes in WebAnno made for the upgrade to Wicket 9
* No specific testing procedure
=> #1830 - Upgrade to Wicket 9

inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/setup.adoc, inception-doc/src/main/resources/META-INF/asciidoc/user-guide/getting-started.adoc
* added Github-Link in developer documentation
* added hint to not extract the example project to getting started
* Build the dev documentation
* Read the section on source code management
* Build the user documentation
* Read the Section Download and import an Example Project -> Step 1
* [ x] PR updates documentation
=> #1848 - Documentation-improvements

pom.xml
- Mockito 3.3.3 -> 3.6.0
- AssertJ 3.15.0 -> 3.18.1
- Spring 5.2.7 -> 5.3.1
- Spring Boot 2.3.4 -> 2.4.0
- Wicket 9.1.0 -> 9.2.0
- Wicektstuff 9.1.0 -> 9.2.0
- Wicket JQuery 9.0.0 -> 9.1.0
=> #1859 - Upgrade dependencies

inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java, inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java, inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Also index layers that do not have any features
- Improve trace log
- Fix issue in the search sidebar that it was displaying "1-10 of 1" results - now does "1-1 of 1".
=> #1860 - Layers without features are not indexed for search

inception-external-search-solr/pom.xml, inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/SolrSearchProvider.java, inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/SolrSearchProviderFactory.java, inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/config/SolrSearchDocumentRepositoryAutoConfiguration.java, inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/traits/SolrSearchProviderTraits.java, inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/traits/SolrSearchProviderTraitsEditor.java, inception-external-search-solr/src/test/java/de/tudarmstadt/ukp/inception/externalsearch/solr/SolrSearchProviderTest.java, installEclipseSettings.sh, pom.xml
* Support for Solr as external document repository
=> #276 Support solr based external indexes

inception-imls-weblicht/pom.xml, pom.xml
- Adjust TCF library version to the same one that DKPro Core 2.1.0 is using
* Try exporting a document as TCF
* Actually, we should also test if using a TCF pipeline as a recommender still works....
=> #1898 - TCF export not working

inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- Check for empty query after cleaning, not before
- 
=> #1903 - Exception when searching for single character with embedded KB

inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/InspectableThreadPoolExecutor.java, inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java, inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/Task.java
- If an equivalent task has already been passed to the thread pool, put a new task into a separate queue outside the threadpool
=> #1905 - Equivalent tasks run in parallel

inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/setup.adoc
* Add more documentation for Intellij
* Build and then read the documentation
=> #1848 - Documentation improvements

inception-app-webapp/pom.xml, pom.xml
* Add json logger for log4j2
* Use `<JsonTemplateLayout eventTemplateUri="classpath:LogstashJsonEventLayoutV1.json"/>` in the log4j2.xml
=> #1915 - Add json logger for log4j2

inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepository.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java, inception-ui-core/pom.xml, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/ActivitiesDashlet.html, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/ActivitiesDashlet.java, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/ActivitiesDashlet.properties, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.java
- Reduce database accesses made by recent activity dashlet
- Improved visual
- Discern properly between annotation and curation
=> #1917 - Recent activity does not discern well between annotation and curation

inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImplTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplImportExportIntegrationTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplQualifierIntegrationTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplWikiDataIntegrationTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseSubPropertyLabelTest.java, inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImplIntegrationTest.java, inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java, inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
* Upstream depends on liquibase now but we do not want liquibase to be auto-discovered by integration tests.
* Run build
=> Adjust to upstream changes

inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/CurrentProjectDashlet.html, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/CurrentProjectDashlet.java, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/Dashlet_ImplBase.java
- Allow project managers to edit the project name directly in the dashboard simply by clicking on it
* Open project dashboard as a project manger / non-manager
* Try clicking on the project title to change it
=> #1938 - Edit project name directly on dashboard

inception-recommendation/pom.xml, inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/evaluation/EvaluationSimulationPageMenuItem.java, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menu/CurationPageMenuItem.java, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menu/ProjectSettingsPageMenuItem.java
- Make project settings item visible to global admins
- Make evaluation item visible only to project managers and only if there are actually any recommenders
* Try the dashboard with different user roles
=> #1936 - Change menu item visibility

inception-app-webapp/pom.xml, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicProjectInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicRelationLayerInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicRelationTagSetInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicSpanLayerInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicSpanRecommenderInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicSpanTagSetInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/StandardProjectInitializer.java, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java, inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/QuickProjectInitializer.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/initializers/FactLayerInitializer.java
- Added dropdown to the project create button on the project overview page
- Added two project templates: basic and standard
* Try creating projects with and without the template mechanism
=> #1943 - Quickly create simple project

inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicAnnotatorWorkflowActionBarItemGroup.java, inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowDocumentNavigationActionBarExtension.java, inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/workflow/WorkflowExtension.java
- Fix access to traits which had been throwing an exception causing the annotation view not to move on
=> #1968 - Finishing document does not move on

inception-kb/pom.xml, inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplWikiDataIntegrationTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/util/TestFixtures.java
- Added YAGO 4 profile
- Re-enabled YAGO tests
- Consolidate fixtures code
* Create KB using the YAGO 4 profile and try using it on the KB page and for linking
=> #1973 - YAGO 4 profile

inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java, inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- Switch to endpoint http://de.dbpedia/sparql which seems to work
* Set up a KB using the DBPedia builtin profile and check it it looks ok and works ok
=> #1931 - DBPedia tests time out and fail

inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSettingsPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSpecificSettingsPanel.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSpecificSettingsPanel.java, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.html, inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java
- When choosing a local KB in the KB creation wizard, set the FTS to Lucene
* Create a local KB and check the FTS setting
* Also try first going into creating a local KB, then back up into creating a remote KB
=> #1977 - KBs start out without FTS support

pom.xml
- Remove unused dependency management for ancient dom4j version
* No specific test procedure.
=> No issue: Remove unused managed dependency

inception-imls-dl4j/pom.xml, inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java
- Updated dependencies
- Removed test ignores
=> #1819 - Re-enable DL4J NER tests

inception-ui-core/pom.xml, inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.html, inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java, inception-ui-dashboard/pom.xml, pom.xml
* Added a visual effect on the login page
* Visit the login page ;)
=> No issue: Added a visual effect on the login page.

inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/startup/StartupNoticeValve.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/startup/startup.html, inception-app-webapp/src/main/resources/log4j2.xml
- When running with the embedded web server, display a boot up notice while INCEpTION has not fully initialized itself
* Start the JAR version
* Access the application URL (by default `http://localhost:8080`) quickly after startup
* Very early accesses may yield a connection refused messaged. Slightly later ones should bring up the boot screen. The boot screen should auto-refresh automatically switch over to become the login screen once the app has started.
=> #2004 - Exception when trying to access a page while application is still booting up

inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java, inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java, inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasStorageServiceAction.java, inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasStorageServiceLoader.java, inception-ui-project/pom.xml, inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
- Add support for safely performing force bulk actions on CASes such as repairing / analyzing them
- Use this support in the ProjectCasDoctorPanel
* Create project
* Import document
* Try repairing it
=> #1788 - INCEpTION cannot repair CAS, ignoring that leads to crashes

inception-log/pom.xml, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/EventLoggingAdapter.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/FeatureValueUpdatedEventAdapter.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/ExportedLoggedEvent.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/model/FeatureChangeDetails.java, inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/model/LoggedEvent.java, inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/adapter/FeatureValueUpdatedEventAdapterTest.java, inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
- Slight refactoring to make code more testable
- Added feature name information
- Added unit test which checks how the FeatureValueUpdatedEvent is logged to JSON
=> #2007 - Feature name is not logged properly in event log

inception-brat-editor/pom.xml, inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java, pom.xml
- Upgrade to same JSoup version that DKPro Core is using
- Catch even errors (throwable) and report an error in the UI in such cases
* Import HTML file
=> #2016 - Importing html files no longer works

inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/HtmlAnnotationEditor.java, inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
* Cleaning up code
* Fixed off-by-one issue when creating / rendering annotations
* Fixed issue that some info/error messages did not show up
* Use the HTML editor
=> #2023 - Improve html editor code

inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/FeatureFilter.java, inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapter.java, inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java, inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java, inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java, inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTest.java
- Fixed issue
- Cleaned up additional unit tests
- Moved comparison of annotations into the adapters
=> #2037 - Agreed relation annotations don't move to the curator panel

inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserSelectionPanel.java
=> #2045 - Error when property hideUsers is set

inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java, inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/DanglingRelationsCheck.java, inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingRelationsRepair.java, inception-diag/src/main/resources/META-INF/asciidoc/user-guide/casdoctor.adoc, inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Delegate deletion of attached relations properly to the respective adapter
- Added / expanded checks and repairs to test for this kind of dangling relations
=> #2075 - Deleting a span to which relations connect leaves dangling relations

inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/Selection.java, inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationEditorExtension.java, inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationVID.java, inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/CurationVIDTest.java
- Fix issue by adapting CurationVID parsing / generation
- Use ! character to separate username from payload because ! is not allowed in usernames
=> #2077 - Unable to merge via curation siderbar if username contains "."

inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- If stacking is allowed, generate a new annotation instead of updating an existing one
=> #2083 - Accepting recommendations removes previous annotations

inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionWebInitializer.java, inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/logging/LoggingFilter.java
- Initialize repository location in MDC in logging filter
* Not exactly sure how to test....
=> #2071 - Error in string interpolation in log4j2.xml or ctx:repositoryPath not defined

inception-app-webapp/pom.xml, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/ProjectInitializersAutoConfiguration.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicProjectInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicRelationLayerInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicRelationTagSetInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicSpanLayerInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicSpanRecommenderInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicSpanTagSetInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/EntityLinkingProjectInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/NamedEntityIdentifierStringRecommenderInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/StandardProjectInitializer.java, inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/WikiDataKnowledgeBaseInitializer.java, inception-app-webapp/src/main/resources/META-INF/spring.factories
- Switch to auto-configuration
- Add conditionals on the availabiltiy of recommender / KB services
=> #2089 - Disabling KB or recommender service prevents startup

inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/vue/VueBehavior.java
*  Put vue app and component load in block to avoid reassigning constants
As discussed only changed scopes instead of checking for already existing resources to avoid more complex management of vue components at this moment.
* Would need to add another VueBehavior on the same page as already existing one
=> #2101 Multiple Vue components on one page

inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/admin/AdminDashboardPage.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
- Do not display link to admin dashboard to users who are not admins (i.e. project creators) - project creators can upload and manage their projects from the project overview and project dashboards
* Log in as project creator and check if project administration via project overview and project settings is sufficient
=> #2122 - Error 403 on Administration

inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/config/BratAnnotationEditorProperties.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/config/BratAnnotationEditorPropertiesImpl.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java, inception/inception-brat-editor/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/BratRendererTest.java, inception/inception-io-text/src/main/java/de/tudarmstadt/ukp/clarin/webanno/text/TextFormatSupport.java, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/AnnotatorsPanel.java
- Switch replacement character back to NBSP by default
- Added option to configure the replacement character
=> #2125 - Configurable whitespace replacement character

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/export/ExportDocumentDialogContent.java, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ProjectPageBase.java
- Made error / access control handling on ProjectPageBase more robust
- Fixed error feedback in ExportDocumentDialogContent
* See https://github.com/inception-project/inception/issues/2002#issuecomment-804461281
=> #2130 - Exporting broken document not handled well

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImpl.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageServiceSharedAccessCacheAdapter.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageSession.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/config/CasStorageProperties.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/config/CasStoragePropertiesImpl.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplDatabaseTest.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplTest.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/ImportExportServiceImplTest.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentsExporterTest.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporterTest.java, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_apache.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_nginx.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_cas-storage_cache.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc, inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/AeroRemoteApiControllerTest.java, inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java, inception/inception-versioning/src/test/java/de/tudarmstadt/ukp/inception/versioning/VersioningServiceImplTest.java
- Make the CAS cache parameters configurable
- Add JMX inspection for the shared CAS cache
- Added documentation for the new settings
- Fixed a few minor issues in the documentation
* Start with different heap sizes and see what the max CAS cache size logged at startup says
* Try overriding the defaults by setting the new properties in the config file
* Connect via JMX and check the new shared CAS cache statistics
=> #2138 - Configurable CAS cache properties

inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/DebouncingTask.java, inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java, inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/Task.java
- Add DebouncingTask and ability in the schedule to support debouncing
- Also support tasks that are not associated with a specific user (i.e. SYSTEM tasks)
=> #1289 - Debounce scheduler job submission

inception/inception-html-editor/pom.xml, inception/inception-html-recogito-editor/pom.xml, inception/pom.xml
- Mockito 3.7.0 -> 3.8.0
- AssertJ 3.18.1 -> 3.19.0
- Springdoc 1.5.5 -> 1.5.6
- Wicket 9.2.0 -> 9.3.0
- Wicketstuff 9.2.0 -> 9.3.0
- Wicket JQuery UI 9.2.0 -> 9.3.1
- Wicket JQuery Selectors 3.0.2 -> 3.0.3
- Wicket Webjars 3.0.2 -> 3.0.3
- Bootstrap 4.5.3 -> 4.6.0-1
=> #2161 - Upgrade dependencies

inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/ProjectRecommendersMenuItem.java, inception/inception-ui-external-search/pom.xml, inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/config/ExternalSearchUIAutoConfiguration.java, inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/project/ProjectDocumentRepositoriesMenuItem.java, inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/project/ProjectDocumentRepositoriesPage.java, inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/config/KnowledgeBaseServiceUIAutoConfiguration.java, inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBaseMenuItem.java
- Move management of the settings items into the respective auto-config
=> #2167 - Project setting items not disappearing for disabled modules

inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ProjectPageBase.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPageMenuItem.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectSettingsPage.java
- Fix cancelling project creation when project was created from project overview
- Fix projects page menu item icon on admin dashboard
* Create project via the projects overview page and cancel
* Create project via the project settings page accessible from the admin dashboard and cancel
=> #2170 - Cancelling project creation creates error

inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurity.java, inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/SpringAuthenticatedWebSession.java, inception/inception-sharing/pom.xml, inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.html, inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ProjectPageBase.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
- Move session tracking in the Spring Security session registry from the LoginPage into the SpringAuthenticatedWebSession
- Allow unauthenticated access to the page for joining a project via invite link
- Allow logging in via the page for joining a project via invite link
- Improve messages when trying to access a project page the user has no permission to access
- Fix infinite redirect when a user tries to access a project dashboard to which the user has no permission
- Do not show dashboard link in the menubar if the user is not authenticated
* Follow an invite link without logging in first
* Follow an invite link after having logged in
=> #2184 - Log in via invite acceptance page

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotationPreference.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationPreferencesDialogContent.html, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationPreferencesDialogContent.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationPreferencesDialogContent.properties, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/UserPreferencesServiceImpl.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarPanel.java, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- Allow configuring left/right sidebar size independently
- Also fixes bug that left sidebar on curation page did not respect the size setting (#2194)
* Try configuring sidebar sizes on annotation / curation pages
=> #2203 - Configure left/right sidebar independently

inception/inception-html-editor/pom.xml, inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/config/HtmlAnnotationEditorSupportAutoConfiguration.java, inception/inception-io-html/LICENSE.txt, inception/inception-io-html/pom.xml, inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/HtmlFormatSupport.java, inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/LegacyHtmlFormatSupport.java, inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/dkprocore/CasXmlHandler.java, inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/dkprocore/HtmlDocumentReader.java, inception/inception-io-html/src/test/java/de/tudarmstadt/ukp/inception/io/html/dkprocore/HtmlDocumentReaderTest.java, inception/inception-io-html/src/test/resources/html/test-document.xmi, inception/inception-io-html/src/test/resources/html/test-document.xml, inception/inception-io-html/src/test/resources/html/test-with-head-and-doctype.html, inception/inception-io-html/src/test/resources/html/test-with-head-and-doctype.xmi, inception/inception-io-html/src/test/resources/html/test-with-head.html, inception/inception-io-html/src/test/resources/html/test-with-head.xmi, inception/inception-io-html/src/test/resources/html/test.html, inception/inception-io-html/src/test/resources/html/test.html.dump, inception/inception-io-html/src/test/resources/log4j2.xml, inception/pom.xml
- Fixed issue using a HTML reader code copied over from DKPro Core - as long as there is no DKPro Core release including the fix
- Split HTML IO code into separate module
=> #2177 - Minmal HTML document cannot be imported

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ChainRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/NopRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer_ImplBase.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VArc.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VSpan.java
- Cache type information over multiple invocations
- Split up rendering method into multiple smaller methods
- Pull out some common code into the abstract base class
- No need to give features to VObjects if a label hint is set (at least I'm pretty sure that is not necessary...)
* No particular test procedure
=> #2201 - Refactor rendering

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java
- The "allFeaturesCache" must be cleared after the layer configuration has been changed
=> #2223 - Render cache not cleared after adding slot feature

inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- Speak of "sentences" instead of "items"
- Add help cursor on inactivity badge to indicate that there is a tooltip
- Use select.coveredBy instead of indexCovered
- Shortcut extractAnnotatedSpans if there are no annotations to start with
=> #2227 - Slightly improve OpenNLP NER

inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/InviteService.java, inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/InviteServiceImpl.java, inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/config/InviteServiceAutoConfiguration.java, inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/config/InviteServiceProperties.java, inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/config/InviteServicePropertiesImpl.java, inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/InviteProjectSettingsPanel.java, inception/inception-sharing/src/test/java/de/tudarmstadt/ukp/inception/sharing/InviteServiceImplTest.java
- Introduce property to define a base URL for invites
- Use the base URL if set, otherwise try Wicket
- Centralize link generation in the backend
=> #2237 - Allow backend code to generate an invite link

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialog.java
* Fixes bug and returns to the project dashboard when pressing cancel
=> #2229 - UI: "Cancel" in curation modal does not return to project dashboard

inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.html, inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java, inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/ChartPanel.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.html, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Comment out chart from recommender sidebar
- Improve recommender sidebar layout
- Avoid redrawing BootstrapSelect components too often as part of selection / annotation because they seem to have a memory leak
- Remove outdated callbacks
* No specific test procedure - probably use the different sidebars to see if their behavior broke in specific cases (not sure which)
=> #2098 - Annotation gets slower and slower followed by aw snap

inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/ProjectInitializersAutoConfiguration.java, inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicProjectInitializer.java, inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicRelationLayerInitializer.java, inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/initializers/BasicRelationRecommenderInitializer.java, inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/config/StringMatchingRecommenderAutoConfiguration.java, inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/relation/StringMatchingRelationRecommenderFactory.java, inception/inception-imls-stringmatch/src/main/resources/META-INF/asciidoc/admin-guide/settings_string_relation_recommender.adoc
- Add relation recommender if available
- Change property enabling the relation recommender to match other similar properties
* Enable the string matching relation recommender
* Create a new "basic span/relation" project using the quick project creation
=> #2246 - Simple span/relation project should include relation recommender

inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureTestSuite_ImplBase.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/SpanLayerSupport.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ChainRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/NopRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VObject.java, inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapterTest.java, inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRendererTest.java, inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRendererTest.java, inception/inception-brat-editor/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/BratRendererTest.java, inception/inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTestBase.java, inception/inception-pdf-editor/src/test/java/de/tudarmstadt/ukpinception/pdfeditor/pdfanno/model/PdfAnnoRendererTest.java, inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java
* Alternative approach to the nicer relations
* Disable visibility of relations, enable "long relation" coloring on the target span layer of the relations, try annotating
=> 2176 nicer relations rec

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasMetadataUtils.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageDriver.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageMetadata.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasStorageServiceImpl.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/FileSystemCasStorageDriver.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/config/CasStorageServiceAutoConfiguration.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportCuratedDocumentsTask.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporter.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasStorageServiceImplTest.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentImportExportServiceImplTest.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplConcurrencyTest.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentsExporterTest.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporterTest.java, inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/CasStorageService.java, inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
- Introduce CasStorageDriver interface
- Extract relevant methods into a FileSystemCasStorageDriver
- Deprecate and/or remove methods which allow file-level access to the CAS at the level of the CasStorageService and above
=> #2302 - Introduce a low-level CAS storage interface

inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- First resolve attachment (if possible) and then check for null/zero and try indexing
=> #2308 - NullPointerException during indexing

inception/inception-example-imls-data-majority/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/datamajority/DataMajorityNerRecommender.java, inception/inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommender.java, inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java, inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java, inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java, inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/relation/StringMatchingRelationRecommender.java, inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java, inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java, inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/evaluation/ConfusionMatrix.java, inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/evaluation/EvaluationResult.java, inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/evaluation/LabelPair.java, inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Progress.java, inception/inception-recommendation-api/src/test/java/de/tudarmstadt/ukp/inception/recommender/api/evaluation/ConfusionMatrixTest.java, inception/inception-recommendation-api/src/test/java/de/tudarmstadt/ukp/inception/recommender/api/evaluation/EvaluationResultTest.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.html, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderStatusDetailPanel.html, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderStatusDetailPanel.java, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/bootstrap/BootstrapModalDialog.html, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/bootstrap/BootstrapModalDialog.java, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss
- Added confusion matrix as to the recommender sidebar on the annotation page
- Added more helpful information to the evaluation results object so we can access it in the UI
- Make information about when the next evaluation run is due accessible in the UI
* Open the recommender sidebar while annotating
* Watch the information presented
* Check out the confusion matrix
=> #2319 - More user-accessible information about how the recommenders work

inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/model/WorkloadManagementServiceImpl.java
- Add missing transactional annotation
=> #2318 - Importing project fails with Transaction Error

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/PagingStrategy.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/TokenWrappingPagingStrategy.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/Unit.java, inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/TokenWrappingPagingStrategyTest.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.java
- Fix issue
* Try viewing a text with multiple empty lines (>2)  between two text lines in the brat@120 view
=> #2315 Error: Illegal argument exception position xxxx is not in any row

inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java, inception/inception-ui-project/pom.xml, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java
- If there is a tie between the top scores, then do not apply and instead ask user to annotate more
=> #2072 - String matcher suggestions applied non-deterministically?

inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java, inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- Added method to retrieve projects and permission levels in a single go from the project service
- Use the new method to optimize DB access in the projects overview page
* Use the project dashboard page
=> #2333 - Improve project dashboard performance

inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java
- Fix training capability setting
=> #2339 - Named entity linker does not generate suggestions

inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
=> #2344 - Selecting a stacked relation highlights both

inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
- Do not remove non-word characters from the UI name if the feature has already been saved - only do so when initially creating the feature
=> #1806 - Feature name cannot be changed to characters other than ASCII

inception/inception-app-webapp/src/assembly/documentation.xml
- Use "." instead of "/" to specify the output directory - makes lot more sense as well....
* Check build log on Windows
=> #1925 - Assembly reports error when building documentation on Windows

inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
* Avoid adding unupgraded cas to session by only updating paging during document load
* see issue
* also try other ways to load the annotation page you can think of
* try changing editors in the preferences and paging through the document
=> #2380 Missing new layer type when using activity link

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java, inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java, inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBaseProperties.java, inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBasePropertiesImpl.java, inception/inception-kb/src/main/resources/META-INF/asciidoc/admin-guide/settings_knowledgebase.adoc
- Listen for project deletion event and delete the KBs
- Added option to delete orphaned KBs during startup
=> #2392 - Deleting a project does not remove the KBs

inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/tutorial.js
- Reduce margin around target elements to zero so user can really not click anywhere but on the highlighted element - this helps preventing the user to escape the tutorial in an irregular way
- Formatting
- In the farewell step, disable the sidebar elements until the user has clicked "Thanks" or skipped the step and thereby ended the tutorial
* Do the tutorial
* Try escaping the tutorial by clicking on things that the tutorial does not point to
* Abort the tutorial at steps where the tutorial had disabled elements and check that the elements are re-enabeld
=> #2310 - Tutorial UI elements sometimes clog up in top-left corner

inception/pom.xml
- RDF4J 3.6.3 -> 3.7.1
* No specific procedure
=> #2286 - Upgrade dependencies

inception/inception-app-webapp/pom.xml, inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_general.adoc, inception/inception-plugin-manager/pom.xml, inception/inception-plugin-manager/src/main/java/de/tudarmstadt/ukp/clarin/webanno/plugin/config/PluginManagerAutoConfiguration.java, inception/inception-plugin-manager/src/main/resources/META-INF/spring.factories, pom.xml
- Add feature flag for plugin manager
* Turn on plugins and install an example plugin
=> #2420 - Disable plugin manager by default

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateUtils.java, inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/MatchResult.java, inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexAnnotationDocumentTask.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexSourceDocumentTask.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/ReindexTask.java, inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java, inception/inception-search-mtas/src/test/resources/log4j2.xml, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss, inception/inception-ui-search/pom.xml, inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.html, inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java, inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.scss, inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebarCssReference.java
- Better control of the interaction between incoming and already enqueued tasks
- Incoming re-indexing tasks trump enqueued (re)indexing tasks
- Incoming source/anno indexing tasks are queued after re-indexing tasks
* Try stressing the indexing / search functionality
=> #2252 - Issue with MTASDocumentIndexing tasks interaction

inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/faq.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/getting-started.adoc
- Remove confusing and outdated comments about commands to set username/pw and stuff
* Check if the documentation is understandable and helpful.
=> #2463 - Missing commands in Admin docs

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/config/BackupProperties.java, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_internal-backup.adoc
- Enable minimal backup with 2 CASes and 24 hours in between them
* Check if the backup files appear after 24 h ;)
=> #2472 - Enable minimal internal backups

inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentServiceImpl.java, inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/SourceDocument.java, inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
- Drop unused columns
- Remove unused columns from query and entity
* Start up application and see if it runs, try accessing e.g. the curation page
=> #2486 - Remove unused db colums

inception/inception-ui-core/pom.xml, inception/pom.xml
- Switch to JSASS 5.10.5 from kasta-ua
* Try and run on different OSes / arches
=> #2493 - Switch to a JSASS version that runs on Apple Silicon

inception/inception-app-webapp/pom.xml, inception/pom.xml
- Remove MySQL driver
* No specific test procedure. MariaDB should just take over automatically.
=> #2499 - Stop bundling MySQL driver

inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/troubleshooting.adoc, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
- Added system property to reset the password
- Documented the procedure
* Try the documented procedure
=> #2503 - Reset admin password

inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchService.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/model/Monitor.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/model/Progress.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexAnnotationDocumentTask.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexSourceDocumentTask.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexingTask_ImplBase.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/ReindexTask.java, inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java, inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Display progress information then search is not possible
* Add like 50 documents to a project
* Open search sidebar
* Enter a query into the search field
* Open search options and click reindex
* Quickly click on search
=> #2511 - Progress info for indexing

inception/inception-curation-legacy/pom.xml, inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentServiceImpl.java, inception/inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/CurationDocumentServiceImplTest.java, inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
- Fix query
- Added missing `@Transactional` annotation
* Create a project
* Upload a document
* Mark document as finished on the annotation page
* Open the curation page
* Check that the finished document is listed for curation
=> #2524 - Curation no longer works

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- Redirect to a URL without document ID when accessing the page the first time instead of just rewriting history
* Also try accessing page directly via open dialog
* Also try on annotation page as well as on curation page
=> #2522 - Opening sidebar changes document

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportCuratedDocumentsTask.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/CuratedDocumentsExporter.java
* open nested session before document export to temporarily lock cas
* Have a document whose curation is in progress and try exporting the project
* Have a document whose curation is finished and try exporting only curated document
* Try other ways to export for fun
=> #2541 Cannot export project when curation started

inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- When performing a bulk-operation, check if the selected annotation is afterwards still in the CAS and if not unselect it
* Note that if you want to bulk-delete annotations using a search, an annotation of the layer you want to delete must be selected and then all other annotations matching search results as well as the type of the selected layer get removed. In particular, it is not possible to bulk-delete an annotation of layer X by searching for annotations on layer X, select and annotation of a different layer Y at a position where no X exists.
=> #2491 - Bulk-deletion does not unselect annotation

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportCuratedDocumentsTask.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportFullProjectTask.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportServiceImpl.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/AnnotationDocumentExporter.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/exporters/SourceDocumentExporter.java, inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExportService.java, inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java, inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepository.java, inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java, inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java, inception/inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporterTest.java
- check if export has been interrupted
- pass on `InterruptedException`
* Click to export the project
* Cancel the export
=> #2544 Export cannot be cancelled

inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/getting-started.adoc
- Moved up "Project Settings" and "Structure of an Annotation Project" (and everything contained within them) one level. This fixes the sidebar error. 
=> #2383 - getting started sidebar

inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/feedback/FeedbackPanelExtension.js
- Fixed recommender feedback messges injected via websocket
=> #2475 - Upgrade to Bootstrap 5

inception/inception-app-webapp/pom.xml, inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java, inception/inception-boot-loader/src/main/java/de/tudarmstadt/ukp/inception/bootloader/ExtensibleClasspathEnabledWarLayoutFactory.java, inception/inception-export/pom.xml, inception/inception-security/pom.xml, inception/pom.xml
- JUnit 5.7.1 -> 5.7.2
- Mockito 3.8.0 -> 3.12.4
- AssertJ 3.19.0 -> 3.20.2
- Swagger 2.1.9 -> 2.1.10
- SLF4J 1.7.30 -> 1.7.32
- Log4J 2.14.0 -> 2.14.1
- Tomcat 9.0.45 -> 9.0.52
- MariaDB driver 2.7.1 -> 2.7.4
- Hibernate 5.5.7 -> 6.2.0
- Wicket Bootstrap 6.0.0-M2 -> 6.0.0-M3
- Jackson 2.12.3 -> 2.12.5
- FontAwesome 5.15.2 -> 5.15.3
- Commons CSV 1.8 -> 1.9.0
* ...
* ...
=> #2286 - Upgrade dependencies (21.0)

inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- Check if the principal in the session is a User object or a String and handle both cases (probably we should only handle the case it is a User object...)
=> #2578 - Error when clearing recommender data from session

inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer_ui.js
- Remove code we (probably?) don't need anymore
- In particular remove the keypress handler which prevented tab from working (no idea why this only started to make problems now)
=> #2605 - Cannot switch between inputs using tab anymore

inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/PairwiseCodingAgreementTable.java, inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/unitizing/PairwiseUnitizingAgreementTable.java, inception/inception-support/pom.xml, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/bootstrap/PopoverBehavior.java
- Added customized PopoverBehavior class which fixes the problem - should be removed when upstream has a release including the fix
=> #2597 - Tooltips and export on agreement page broken

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationPreferencesDialogContent.java
- Added missing negation in condition
=> #2616 - Cannot change visibility of layers anymore

inception/inception-versioning/pom.xml, inception/inception-versioning/src/main/java/de/tudarmstadt/ukp/inception/versioning/config/VersioningServiceAutoConfiguration.java, inception/inception-versioning/src/main/java/de/tudarmstadt/ukp/inception/versioning/ui/VersioningMenuItem.java, inception/inception-versioning/src/main/java/de/tudarmstadt/ukp/inception/versioning/ui/VersioningPreferencesPage.html, inception/inception-versioning/src/main/java/de/tudarmstadt/ukp/inception/versioning/ui/VersioningPreferencesPage.java
- Hook versioning up into the project settings
=> #2624 - Versioning not reachable via "normal" project settings

inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/vue/VueBehavior.java
* add vue script on dom ready header item
* configure the logged events notification with settings  `websocket.loggedevent.enabled=true` and `websocket.enabled=true`
* as an admin open the annotation page
* make sure that you see the scroll icon in the footer while navigating the page (e.g. opening/closing sidebar)
=> #2627 Create Vue app also on page refresh

inception/pom.xml
=> #2630 - Upgrade dependencies

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ChainRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/NopRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer_ImplBase.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java, inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java, inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/api/DiffAdapter.java, inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/relation/RelationDiffAdapter.java, inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/span/SpanDiffAdapter.java, inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/util/TestFixtures.java, inception/inception-project-export/pom.xml, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/AnnotatorsPanel.java, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/render/AnnotationStateColoringStrategy.java
- Pull code to select relevant annotations in a part of the document out into a separate method in the TypeAdapter and in the DiffAdapter (code duplication atm)
- Cleaning up a bit
- Validate annotation states parameter in AnnotationStateColoringStrategy - it must not be null
* Check behavior of curation for sentence-crossing annotations that are only partially visible in the current document page in curation
=> #2635 - Unable to render: null

inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, inception/inception-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_navigation.adoc
- Add SHIFT-DELETE as a short cut for deleting the currently selected annotation
* Create an annotation
* Delete it using SHIFT-DELETE
=> #2306 - Delete shortcut for annotations

inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/AnnotatorsPanel.java
- Pre-fill annotation states map with an empty map for each user
* Use curation
=> #2641 - NPE in curation

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
- Update methods to react to empty optionals
=> #2694 - Unsupported features not properly detected

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratLazyDetailsLookupService.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratLazyDetailsLookupServiceImpl.java, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.java
- Turn yield into a lazy detail
* View an annotation project with (dependency) relations and check if the yield appears in the popover
=> #2700 - Improve performance of relation yield or make it optional

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanOverlapBehavior.java, inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanOverlapBehaviorTest.java
- Optimize loops that check for overlapping
- Added unit tests to ensure the loops still work as before
=> #2703 - Improve performance of SpanOverlapBehavior

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateImpl.java
- Only reset if the new project is different from the current project
=> #2711 - Script direction may unintentionally reset to project default

inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_nginx.adoc
- Update NGINX docu
* Deploy an NGINX and see whether it works
=> #2719 - Update nginx docu

inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/TagSet.java
- Changed default to creating closed tagsets
* Create a new tagset
* Check that adding tags to the tagset is not permitted
=> #2672 - Make tagset default closed

inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Remember the current default layer at the beginning of the create action and reset it at the end
* Create two POS annotations
* Select another span layer
* Optionally create an annotation with that span layer
* Then create a dependency relation between the two POS
* Press reload in the browser to check if the default layer has changed or try to create another annotation at a location that already has a POS annotation
=> #2709 - Creating a relation changes the active span layer

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorDefaultPreferencesPropertiesImpl.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/UserPreferencesServiceImpl.java, inception/inception-app-webapp/src/main/resources/application.yml, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/actionbar/script/ScriptDirectionActionBarExtension.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/preferences/BratAnnotationEditorManagerPrefPanel.html, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/preferences/BratAnnotationEditorManagerPrefPanel.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/preferences/BratAnnotationEditorManagerPrefPanel.properties, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/preferences/BratAnnotationEditorManagerPrefs.java
- Allow setting the default page size in the project settings
- Increase default page size to 10
* Change the default page size in the project settings
* Log in as a new user or at least as one that has not yet changed anything in the annotation page preferences
=> #2233 - Allow to set Page size as Admin for a project to something higher than 5

inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/ProjectUsersPanel.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserPermissionsPanel.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserSelectionPanel.java
- Prevent managers from removing themselves from a project
- Fix ability to add users with a display name to a a project
* Try removing yourself from a project you are the manager on
* Try adding a user with a display name to a project
=> #1205 - Project disappears after removing all roles

inception/inception-preferences/src/main/java/de/tudarmstadt/ukp/inception/preferences/PreferencesServiceImpl.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java, inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java, inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/Task.java, inception/inception-scheduling/src/test/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceTest.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexingTask_ImplBase.java
- Change getUser() to return an optional
- Fix NPE
=> #2756 - NPE when looking for scheduled jobs to cancel

inception/inception-app-webapp/pom.xml, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/EditorAjaxRequestHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/ExtensionActionHandler.java, inception/inception-recommendation/pom.xml, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java, inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.java
- Fix generic request handler to properly forward extension action to extension
- Fix recommender extension accept
- Display a success message when saving tagset details
=> #2769 - Accepting suggestions no longer works

inception/inception-diag/pom.xml, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/CasDoctor.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorAutoConfiguration.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorProperties.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorPropertiesImpl.java, inception/inception-diag/src/main/resources/META-INF/spring.factories
- Use a properties class instead of value annotations for injecting the CasDoctor settings
=> #2773 - Introduce properties class for CasDoctor settings

inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_nginx.adoc
- Add documentation for ws via Nginx
- Add more documentation for CSRF
* Apply documentation and test
=> #2735 - Document websocket reverse proxy config

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/FeatureEditorListPanel.java
- Display link role on mouse over
- Fix display of no-data-notice when there are no features on a layer
* Try out link features with tagsets and descriptions on the tags
=> #2782 - Display descriptions when hovering over link feature role label

inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
- If the user has already logged in, use the users identity ot join the project
=> #2760 - Using guest link accounts and real user has some strange interactions

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/action/AnnotationActionHandler.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/ChainAdapter.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/RelationAdapter.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/SpanAdapter.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/Selection.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/SelectAnnotationHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/experimental/api/AnnotationSystemAPIImpl.java, inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerAdapter.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Make use of VID during selection
- Fix issue that chain links can no longer be selected
- Bit of cleaning up here and there
=> #2788 - Selection of chain layer links no longer working

inception/inception-bootstrap/src/main/ts_template/package.json, inception/inception-brat-editor/src/main/ts_template/package.json, inception/inception-diam-editor/src/main/ts_template/package.json, inception/inception-diam/src/main/ts_template/package.json, inception/inception-html-recogito-editor/src/main/ts_template/package.json, inception/inception-ui-kb/src/main/ts_template/package.json, inception/inception-ui-search/src/main/ts_template/package.json
- Use npm bin
* Build INCEpTION and see whether it runs and shows proper CSS
=> #2790 - Build command for npm packages does not work on windows

inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.html, inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.properties
- Changed label
* Look at the join-project page
=> #2801 - Change label for guest account "I already have an account"

inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- Add auto-escaping in simplified search mode
=> #2831 - Cannot search for this & that in annotation sidebar

inception/inception-brat-editor/src/main/ts/brat/visualizer/Visualizer.ts
- Fix calculation of start position
=> #2837 -  When marking a sequence in RTL it marks only the last character

inception/inception-pdf-editor/pom.xml, inception/pom.xml
- pdfbox 2.0.15 -> 2.0.25
- fontbox 2.0.15 -> 2.0.25
- Spring 5.3.14 -> 5.3.15
- Spring Boot 2.6.1 -> 2.6.3
- Spring Security 5.6.0 -> 5.6.1
- SpringDoc 1.6.1 -> 1.6.5
- Swagger 2.1.11 -> 2.1.12
- SLF4J 1.7.32 -> 1.7.35
- Tomcat 9.0.56 > 9.0.58
- Hibernate 5.6.3 -> 5.6.5
- Wicket JQuery UI 9.5.0 -> 9.7.0
- Jackson 2.13.0 -> 2.13.1
=> #2839 - Upgrade dependencies

.gitignore, inception/inception-brat-editor/src/main/ts/brat/annotator_ui/AnnotatorUI.ts, inception/inception-brat-editor/src/main/ts/brat/visualizer/Visualizer.ts
- Fix attribute names for start/end markers
=> #2849 - Arrow heads in relations missing

inception/inception-brat-editor/src/main/ts/brat/visualizer/Visualizer.ts
- Fix font-zoom not having any effect at all
- Improve handling of font-zoom option
- Fix ufoCatcher and revese-chunk logic for RTL mode
=> #2686 POS tags and dependency tags are crossing into each other visually

inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/SourceDocumentStateStats.java, inception/inception-api/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/SourceDocumentStateStatsTest.java
- Annotation is in progress as long as not all documents have been annotated
- If annotation is done, then curration is in progress as long as not all documents have been curated
- Updated test for project state calculation
=> #2829 - Project considered done when first document is curated

inception/inception-pdf-editor/src/main/js/pdfanno/package-lock.json, inception/inception-pdf-editor/src/main/js/pdfanno/package.json
=> #2781 - Upgrade dependencies (23.0)

inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc, inception/inception-imls-elg/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_elg.adoc
=> #2813 - Recommender calling out to an ELG service

inception/pom.xml
=> #2781 - Upgrade dependencies

inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionApplicationContextInitializer.java, inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialogManager.java, inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneUserInterface.java, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/SettingsUtil.java
- Added option to locate settings file to tray menu
- Improve logging about settings file during startup
- Log the URL to access INCEpTION after startup
* Use the "Locate settings file" option
=> #1518 - Document where the settings.properties file lives

inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/LayerSelectionPanel.html, inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.html, inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.java, inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.properties
- Replace kendo choices with native HTML choices to avoid dropdown from closing when making a choice
* Try out dropdowns and their contents on the dynamic workload management page
=> #2893 - Annotators dropdown in dynamic workload management broken

inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc
* Add explanations about how to use JAVA_OPTS to increase available memory.
=> #2885 - Document java options e.g. for increasing memory limit

inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LoadAnnotationsHandler.java, inception/inception-diam/src/main/ts/diam/DiamAjaxImpl.ts, inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
- Allow optionally specifying a begin/end in DiamAjax.loadAnnotations()
* No particular test procedure - check if annotation editors still work
=> #2906 - Allow partial rendering via DIAM AJAX

inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
- Filter sentence layer from selection list
- Code cleaning
* Try creating a recommender and check if the sentence layer can be selected
=> #2915 - Sentence layer should not be selectable as recommender target

inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/DeleteAnnotationHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/config/DiamAutoConfig.java, inception/inception-diam/src/main/ts/diam/DiamAjaxImpl.ts, inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
- Added JS and backend code for deleting a given annotation
=> #2918 - Allow deleting an annotation via DIAM

inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactAnnotatedText.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactAnnotationMarker.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactSerializerImpl.java, inception/inception-js-api/src/main/ts/src/model/compact/CompactAnnotatedText.ts, inception/inception-js-api/src/main/ts/src/model/compact/CompactAnnotationMarker.ts
- Send annotation markers to frontend in compact serialization
=> #2920 - Send annotation markers via DIAM compact format

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RenderNotificationRenderStep.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/event/RenderAnnotationsEvent.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactAnnotatedText.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactSerializerImpl.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactTextMarker.java, inception/inception-js-api/src/main/ts/src/model/compact/CompactAnnotatedText.ts, inception/inception-js-api/src/main/ts/src/model/compact/CompactTextMarker.ts, inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebar.java, inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Allow sending text markers to editor via compact protocol
- Fix using the window offsets from the render request when rendering text highlights, in particular in the search and active learning sidebars
=> #2922 - Send text markers via DIAM compact format

inception/inception-brat-editor/src/main/ts_template/package-lock.json, inception/inception-brat-editor/src/main/ts_template/package.json, inception/inception-external-editor/src/main/ts_template/package-lock.json, inception/inception-external-editor/src/main/ts_template/package.json, inception/inception-html-editor/src/main/ts_template/package-lock.json, inception/inception-html-editor/src/main/ts_template/package.json, inception/inception-html-recogito-editor/src/main/ts_template/package.json, inception/inception-js-api/src/main/ts_template/package-lock.json, inception/inception-js-api/src/main/ts_template/package.json, inception/pom.xml
- Control various JS dependencies via Maven properties.
=> #2931 - Use Maven properties to control some JS dependencies

inception/inception-external-editor/pom.xml, inception/inception-html-editor/pom.xml, inception/inception-html-recogito-editor/pom.xml, inception/inception-pdf-editor/pom.xml, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/ServletContextUtils.java
- Fix phases for TS/JS sub-builds
* Test DIAM based-editors
=> #2935 - DIAM-based editors not working

inception/pom.xml
- Tomcat 9.0.60 -> 9.0.62
* No specific test
=> #2933 - Upgrade dependencies

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/exception/WicketExceptionUtil.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/ConstraintsInUseIndicator.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/MultiSelectTextFeatureEditor.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/TextFeatureEditorBase.java
- Pull out class
- Also introduce an exception handling utility class
* Use the normal an multi-value string features
=> #2938 - Pull constraints indicator into a re-usable class

inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/preferences/BratAnnotationEditorManagerPrefPanel.java, inception/inception-pdf-editor/pom.xml
- Set JS build phase properly (ts-build-phase is an unset property when the TS profile is not in use)
* Try opening a PDF file in the annotation editor
=> #2946 - PDF editor resources missing from release

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java, inception/inception-brat-editor/pom.xml, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/schema/BratSchemaGeneratorImpl.java
- Catch no results exception if dependency layer is not there - if it is not there, we do not care...
- Improve error message in findLayer()
=> #2948 - Error when dependency layer has been deleted from project

inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneUserInterface.java
- Check whether browsing dir action is supported
- Show custom popup otherwise
* Try to locate the settings properties path for an unsupported OS
=> #2952 - Error when trying to locate settings file under Windows

inception/pom.xml
- slf4j 1.7.35 -> 1.7.36
- log4j 2.17.1 -> 2.17.2
- Groovy 3.0.9 -> 3.0.10
- RDF4J 3.7.6 -> 3.7.7
=> #2962 - Upgrade dependencies

inception/inception-workload/pom.xml, inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/config/WorkloadManagementAutoConfiguration.java, inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/event/exporter/ExportedWorkloadManager.java, inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/event/exporter/WorkloadManagerExporter.java, inception/inception-workload/src/test/java/de/tudarmstadt/ukp/inception/workload/exporter/WorkloadManagerExporterTest.java
- Added exporter and test
* See issue
=> #2956 - Workload settings not included in exported projects

inception/pom.xml
- Wicket 9.8.0 -> 9.9.1
- Wicketstuff 9.8.0 -> 9.9.0
=> #2912 - Upgrade dependencies

inception/inception-brat-editor/src/main/ts/brat/visualizer_ui/VisualizerUI.ts
- Use closing tags instead of a self-closing tag to fix HTML structure
- Cleaning up
=> #2969 - Multiple lazy details do not show up properly

inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/upgrade_notes.adoc
=> #2976 - Add upgrade notes to documentation

inception/inception-doc/src/main/resources/META-INF/asciidoc/developer-guide.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/release.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/running.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/setup.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/setup_eclipse.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/setup_intellij.adoc
- Split dev documentation into more files
- Explain how to run INCEpTION as a Spring Boot app from the IDE
- Remove explanation of a WTP-based setup
=> #2974 - Update developer documentation

inception/inception-pdf-editor/pom.xml, inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfAnnoPanel.java
- Use a full URL for accessing the callbacks instead of trying to calculate a relative URL
=> #2980 - Cannot open PDF from recent activities

inception/inception-pdf-editor/src/main/js/pdfanno/package-lock.json, inception/inception-pdf-editor/src/main/js/pdfanno/package.json
=> #2983 - Upgrade dependencies (23.2)

inception/pom.xml
- Swagger 2.1.13 -> 2.2.0
- Hibernate Validator 6.2.0 -> 7.0.4
=> #2912 - Upgrade dependencies (24.0)

inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserSelectionPanel.java
- Do nothing if there are no values in the field when pressing add
=> #2987 - Error when pressing "add" when no user is selected

inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- Perform merge via the type adapter to generate the event which triggers rendering
=> #2994 - Merging a slot link does not trigger rendering

inception/pom.xml
=> #3005 - Upgrade dependencies (23.3)

inception/pom.xml
- Upgrade swagger annotations to a version that includes the missing class
=> #3022 - Cannot access AERO swagger UI

inception/pom.xml
- antisamy 1.6.4 -> 1.6.7
* No particular test procedure
=> #3024 - Upgrade dependencies (23.4)

inception/inception-app-webapp/src/main/resources/application.yml, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_reverse_proxy.adoc
- Add setting to application.yml
- Remove setting from documentation
* Run behind a reverse proxy after removing the `NATIVE` setting from the `settings.properties`
=> #3026 - Facilitate running behind reverse proxy

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Replace a direct call to WebAnnoCasUtils.setFeature with a call to the adapter.setFeature
* Try working with slot features, in particular deleting slot fillers to see if they are properly deleted
=> #3031 - setFeatureValue logic should be directly in feature supports

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/NumberFeatureTraits.java
- Ignore unknown features via annotation
=> #3034 - NumberFeatureTraits should ignore unknown traits

inception/pom.xml
- Jackson 2.13.1 -> 2.13.3
- AssertJ 3.21.0 -> 3.22.0
- Comment out unused remote repository
=> #3046 - Upgrade dependencies

inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database_mariadb.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_reverse_proxy.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_caddy.adoc
* Fix admin documentation
* Document caddy
* Build documentation and have a look
=> #3035 - Document caddy

inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java, inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java, inception/inception-kb-fact-linking/src/main/java/de/tudarmstadt/ukp/inception/kb/factlinking/feature/FactLinkingServiceImpl.java, inception/inception-kb-fact-linking/src/main/java/de/tudarmstadt/ukp/inception/kb/factlinking/feature/PropertyFeatureSupport.java, inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java, inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePageMenuItem.java, inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- Skip disabled KB in various cases where it would otherwise be queried
- If a project contains only disabled KBs, disable the KB menu item
=> #3067 - KB still used even when disabled

inception/pom.xml
- Spring 5.3.19 -> 5.3.20
- Spring Boot 2.6.7 -> 2.6.8
- Spring Security 5.6.2 -> 5.6.5
- Springdoc 1.6.7 -> 1.6.8
- Tomcat 9.0.62 -> 9.0.63
=> #3073 - Upgrade dependencies (23.6)

inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- Added parameter to AERO "import project" endpoint
* Import a project and turn the parameter on
=> #3063 - Add "create missing users" option to project import AERO endpoint

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java, inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/LayerExporter.java, inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml, inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/MorphologicalFeaturesLayerInitializer.java, inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- Fix morph feature type on import of project
- Fix morph feature type when starting the application via a repeatable liquibase changeset
- Create morph feature with the proper type when setting up a new project
* Export a project from 23.5, then import it into a fixed version and check the DB
* Start application on a DB where the morph feature has the wrong value
* Create a new project and check the morph feature type
=> #3080 - Token "morph" feature has wrong type

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceEventAdapter.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/annotationservice/config/AnnotationSchemaServiceAutoConfiguration.java, inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/event/AfterProjectRemovedEvent.java, inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AfterProjectRemovedEventAdapter.java, inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java, inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java, inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- Cancel scheduled tasks when a project is being deleted
- Block new tasks from being scheduled for the project
- Block new indexing when a project is being deleted
- Stop background tasks more effectively when project is being deleted
* Tricky - import a large project which takes long to e.g. re-index and then delete it while the indexing is still running and watch what happens
=> #2881 - Document Deletion not working

inception/inception-diag/pom.xml, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/CasDoctor.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/ChecksRegistry.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/ChecksRegistryImpl.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/RepairsRegistry.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/RepairsRegistryImpl.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/DanglingRelationsCheck.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/FeatureAttachedSpanAnnotationsTrulyAttachedCheck.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/LinksReachableThroughChainsCheck.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoMultipleIncomingRelationsCheck.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/RelationOffsetsCheck.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorAutoConfiguration.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/ReattachFeatureAttachedSpanAnnotationsAndDeleteExtrasRepair.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/ReattachFeatureAttachedSpanAnnotationsRepair.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/ReindexFeatureAttachedSpanAnnotationsRepair.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RelationOffsetsRepair.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingChainLinksRepair.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingFeatureAttachedSpanAnnotationsRepair.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingRelationsRepair.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveZeroSizeTokensAndSentencesRepair.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/Repair.java, inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/UpgradeCasRepair.java, inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/diag/repairs/RemoveDanglingRelationsRepairTest.java, inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsIndexedCheckTest.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
- Convert from reflections to Spring
=> #3090 - Use extension point instead of reflections for CasDoctor

inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java, inception/inception-export/pom.xml, inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- Use XMI as the fallback format
* Import a PDF and then select AUTO as the export format for the project - should fall back to XMI since there is no writer for the PDF format
=> #3094 - Switch fallback format to XMI

inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceControllerImpl.java
- Allow admins to download project as well
=> #3099 - Admins can start export but only managers can download

inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FusekiFtsQuery.java, inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/RdfCollection.java, inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java, inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/StardogEntitySearchService.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java, inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- Add internal FTS result limiting for Stardog and Fuseki
* Try with a very large KB
=> #3102 - Limit FTS results to speed up queries

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplConcurrencyTest.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplDatabaseTest.java, inception/inception-api-formats/pom.xml, inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java, inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentImportExportService.java, inception/inception-export/pom.xml, inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java, inception/inception-export/src/test/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImplTest.java, inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java, inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImpl2Test.java, inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImplTest.java, inception/inception-workload-matrix/src/test/java/de/tudarmstadt/ukp/inception/workload/matrix/MatrixWorkloadExtensionImplTest.java
- Tentatively extract a read and a write method from the import/export service and put it into the format support
=> #3104 - More power to the format supports

inception/inception-remote/src/main/resources/META-INF/asciidoc/admin-guide/remote-api-webhooks.adoc
- Add examples of WebHook payloads
* Actually, also added a tip on how to test WebHooks using a simple Python server ;)
=> #3110 - WebHook payload examples

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasPersistenceUtils.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/FileSystemCasStorageDriver.java, inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/config/RepositoryProperties.java
- Remove extra verification
- Add property to re-enable extra verification
=> #3116 - Remove workaround and extra verification for UIMA-6162

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VDocument.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactAnnotatedText.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactSerializerImpl.java, inception/inception-js-api/src/main/ts/src/model/compact/CompactAnnotatedText.ts
- Return window begin/end in the DIAM response
=> #3118 - Get window offsets from DIAM response

inception/inception-api-dao/pom.xml, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasPersistenceUtils.java, inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/FileSystemCasStorageDriver.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/CasPersistenceUtilsTest.java, inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/config/RepositoryProperties.java, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_repository.adoc, inception/inception-pdf-editor/pom.xml, inception/pom.xml
- Add optional compression using Snappy (off by default)
- Add tests for writing/reading compressed and uncompressed CASes
=> #3120 - Improve persistence time using fast compression

inception/inception-app-webapp/pom.xml, inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java, inception/inception-project-initializers-doclabeling/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/doclabeling/BasicDocumentLabelingProjectInitializer.java, inception/inception-project-initializers-sentencelabeling/LICENSE.txt, inception/inception-project-initializers-sentencelabeling/pom.xml, inception/inception-project-initializers-sentencelabeling/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/sentencelabeling/SentenceLabelLayerInitializer.java, inception/inception-project-initializers-sentencelabeling/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/sentencelabeling/SentenceLabelRecommenderInitializer.java, inception/inception-project-initializers-sentencelabeling/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/sentencelabeling/SentenceLabelTagSetInitializer.java, inception/inception-project-initializers-sentencelabeling/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/sentencelabeling/SentenceLabelingProjectInitializer.java, inception/inception-project-initializers-sentencelabeling/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/sentencelabeling/config/InceptionSentenceLabelingProjectInitializersAutoConfiguration.java, inception/inception-project-initializers-sentencelabeling/src/main/resources/META-INF/spring.factories, inception/inception-project-initializers-sentencelabeling/src/main/resources/de/tudarmstadt/ukp/inception/project/initializers/sentencelabeling/SentenceLabelingProjectInitializer.md, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java, inception/pom.xml
- Added sentence-labeling initializer including a recommender
* Create a project using the new initializer and annotate something
=> #3129 - Quick project initializer for sentence labelling tasks

inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_unsupervised.adoc
- Documented a few settings useful for unsupervised installation
=> #3144 - Document tips for unsupervised installation

inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java, inception/inception-model/pom.xml, inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ProjectUserPermissions.java, inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/ProjectUsersPanel.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserPermissionsPanel.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserSelectionPanel.java
- Allow seeing permissions for missing users
- Allow editing the permissions for missing users
* Import a project from another instance containing permissions for users not present in the current instance
* Visit the users panel in the project settings of the imported project
* Try changing/revoking permissions for the missing user
=> #3152 - Permissions for missing users should be visible in the project settings

inception/inception-pdf-editor/src/main/ts/src/main.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/UI/relation.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/UI/span.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/UI/utils.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/annotation/abstract.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/annotation/container.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/annotation/relation.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/annotation/span.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/render/appendChild.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/render/renderKnob.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/render/renderRelation.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/core/src/render/renderSpan.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/page/pdf/PDFAnnoPage.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/page/textLayer.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/page/util/analyzer.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/page/util/window.ts, inception/inception-pdf-editor/src/main/ts/src/pdfanno/pdfanno.ts
- TS quickfixes
- Fix position of annotations when resizing the browser window and when expanding/collapsing the thumbnail sidebar
* Open/close the thumbnail sidebar
* Resize the browser window
=> #3126 - Upgrade to PDF.js v2

inception/pom.xml
- spring 5.3.20 -> 5.3.21
- spring-boot 2.6.8 -> 2.6.9
- spring-security 5.6.5 -> 5.6.6
- tomcat 9.0.63 -> 9.0.64
=> #3157 - Upgrade dependencies

inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/Webhook.java, inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookService.java, inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/json/ProjectStateChangeMessage.java, inception/inception-remote/src/main/resources/META-INF/asciidoc/admin-guide/remote-api-webhooks.adoc, inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookServiceTest.java
- Option to send custom header / value with webhook
- Document new option
- Test new option
=> #3148 - Send credentials along with webhook

inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- If there is an exception when opening an MTAS index, try deleting it and then try opening it again (needs to be manually rebuilt afterwards of course)
* Upgrade to 24.0
* Open a document for annotation
* Trigger a re-index from the annotation sidebar
* Downgrade to 23.9
* Try searching via the annotation sidebar (should not give results)
* Trigger a re-index from the annotation sidebar
* Try searching via the annotation sidebar (should work now)
=> #3169 - Cannot rebuild MTAS index if it is corrupt

inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/component/DocumentNamePanel.html, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/component/DocumentNamePanel.java
- Contain information in badges and add icons
* Open annotation page and have a look
=> #3178 - Improve style of document info panel on annotation page

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialog.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialogPanel.html, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialogPanel.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/open/OpenDocumentDialogPanel.properties, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/dialog/ConfirmationDialog.java, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/dialog/ConfirmationDialogContentPanel.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html, inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicAnnotatorWorkflowActionBarItemGroup.html, inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicAnnotatorWorkflowActionBarItemGroup.java, inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.html
* Use the open document dialog on the annotation/curation pages
=> #3176 - Switch from ModalWindow to ModalDialog

inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ChainRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VRange.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VTextMarker.java, inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRendererTest.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java, inception/inception-brat-editor/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImplTest.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactTextMarker.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java, inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebar.java, inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Use range-clipping everywhere that markers are generated
* Try functionality which uses markers in different editors, e.g. search, active learning, etc.
=> #3189 - Marker may have bad offset

inception/inception-bootstrap/src/main/ts/bootstrap/inception-custom.scss, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaBehavior.java, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties, inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.html, inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Move the clear and export buttons to the top
- Switch to a bootstrap-styled navigator and only show the current page in it
* Try the search sidebar
=> #3188 - Improve search sidebar

inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditorFactory.java, inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfFormatSupport.java, inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/config/PdfAnnotationEditorSupportAutoConfiguration.java, inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/PdfAnnotationEditorFactory.java, inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/config/PdfAnnotationEditor2SupportAutoConfiguration.java, inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/format/PdfFormatSupport.java
- Rename old PDF editor and format to "PDF (legacy)" in the UI
- The new one is now "PDF" and is enabled by default
=> #3096 - New PDF editor

inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateRelationAnnotationHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CustomActionHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/DeleteAnnotationHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/ExtensionActionHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/FillSlotWithExistingAnnotationHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/FillSlotWithNewAnnotationHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LazyDetailsHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LoadAnnotationsHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/SelectAnnotationHandler.java, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationEditorExtension.java, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/config/CurationSidebarAutoConfiguration.java
- Improve error messages in AJAX action handlers
- Add editability check in curation extension
- Add editability check in recommender extension
* Try making changes to already finished documents via recommendations
* Try making changes to already finished documents via experimental curation sidebar
=> #3201 - Can still accept/reject suggestions on closed document

inception/inception-html-recogito-editor/src/main/ts/recogito/RecogitoEditor.ts
- Add context-menu support (i.e. right-click on annotation)
* Right-click on a span annotation
=> #3206 - Add context menu support to RecogitoJS editor

inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Document_Test.java, inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Project_Test.java, inception/inception-search-core/pom.xml, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/config/SearchServiceAutoConfiguration.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/model/AnnotationSearchState.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/model/BulkIndexingContext.java, inception/inception-search-mtas/pom.xml, inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java, inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java, inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java, inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUpgradeTest.java, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaForm.java, inception/inception-ui-dashboard/pom.xml, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/annotation/AnnotationPreferencesProjectSettingsPanel.html, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/annotation/AnnotationPreferencesProjectSettingsPanel.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/annotation/AnnotationSearchStatePanel.html, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/annotation/AnnotationSearchStatePanel.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/annotation/AnnotationSearchStatePanel.properties, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/annotation/DefaultAnnotationSidebarStatePanel.html, inception/inception-ui-kb/src/test/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupportTest.java
- Added option to disable case sensitive search in the annotation project settings which then lower-cases all text and queries
* Disable case-sensitivity, re-build index and query with mixed cases
=> #2433 - Case Insensitive Token Search

inception/inception-app-webapp/pom.xml, inception/inception-io-intertext/LICENSE.txt, inception/inception-io-intertext/pom.xml, inception/inception-io-intertext/src/main/java/de/tudarmstadt/ukp/inception/io/intertext/Intertext.css, inception/inception-io-intertext/src/main/java/de/tudarmstadt/ukp/inception/io/intertext/IntertextCssReference.java, inception/inception-io-intertext/src/main/java/de/tudarmstadt/ukp/inception/io/intertext/IntertextFormatSupport.java, inception/inception-io-intertext/src/main/java/de/tudarmstadt/ukp/inception/io/intertext/IntertextReader.java, inception/inception-io-intertext/src/main/java/de/tudarmstadt/ukp/inception/io/intertext/config/IntertextAutoConfiguration.java, inception/inception-io-intertext/src/main/resources/META-INF/spring.factories, inception/pom.xml
* Import intertext file
* Export as UIMA XMI
=> #3204 - Add support for the intertext format

inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/GetCollectionInformationHandler.java, inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/LoadConfHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/DiamAjaxBehavior.java
- Replace custom AJAX handler with DIAM handler
- Add general server-side timing to DIAM handler
=> #3132 - Clean up brat editor

inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.html, inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.java, inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.properties, inception/inception-workload-dynamic/src/main/resources/META-INF/asciidoc/user-guide/workload_dynamic.adoc
- Remove flaky part of the annotators dialog which has meanwhile been mostly superseded by the ability to click on the badges
- Remove the info column which didn't include any information that isn't already in the table anyway
- Add information about the "touch" action to the documentation
* No specific test procedure - buggy functionality was removed
=> #3228 - Flipped Behavior in Change document status

inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicAnnotatorWorkflowActionBarItemGroup.java, inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/support/AnnotationStateList.java
- Only documents in which the annotator state is "in progress" should be marked as abandoned
- When an annotator marks a document as finished, it should be recorded as an explicit annotator action
=> #3229 - Every document becomes abandoned

inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java, inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImplTest.java
- Workaround UIMA bug which causes garbage collection to be ineffective
- Added test that workaround works
=> #3248 - Garbage collection on document open is ineffective

inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexAnnotationDocumentTask.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexSourceDocumentTask.java, inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexingTask_ImplBase.java
- To not pass CAS on to the search service
- Indexing tasks read annotation/source documents by themselves
* Make annotations and then search for them
* See if the index gets updated in a timely fashion and the search reflects the annotations being made (or deleted)
=> #3251 - Improve reaction times by offloading work to the indexing tasks

inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/AnnotatorsPanel.java, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.java
- Open the annotator CASes in exclusive/non-upgrade mode rather than in shared-read-only/auto-upgrade mode to ensure the IDs are stable
=> #3258 - Curation broken after fixing CAS upgrade issue

inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AttachedAnnotationListPanel.java
- Hide "jump to relation" option when there is no relation to jump to
=> #3261 - "Jump to relation" breaks for Link features

inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashlet.vue, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.html
=> #3271 - Scrollbars at wrong positions for large project descriptions of activity lists

inception/inception-ui-dashboard-activity/pom.xml, inception/inception-ui-dashboard-activity/src/main/ts/esbuild-runner.config.js, inception/inception-ui-dashboard-activity/src/main/ts/src/ActivitiesDashlet.svelte, inception/inception-ui-dashboard-activity/src/main/ts/test/ActivitiesDashlet.test.ts, inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json, inception/inception-ui-dashboard-activity/src/main/ts_template/package.json, inception/pom.xml
- Fix build of the new activities dashlet
- Added tests
* Use the activities dashlet
=> #3269 - Migrate the recent activities dashlet from vue to svelte

inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- Ensure that there are no duplicates in the map
* Not sure
=> #3279 - Exception in Recommender Service

inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/NameUtil.java, inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- Check for reserved usernames
- Check for control characters
=> #3287 - Better username validation

inception/inception-brat-editor/src/main/ts/brat/visualizer/Visualizer.ts
- These are properties, not functions
=> #3290 - Spurious JS error in brat editor

inception/inception-guidelines/src/main/java/de/tudarmstadt/ukp/inception/guidelines/settings/ImportGuidelinesPanel.java, inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/settings/StringMatchingRecommenderTraitsEditor.java, inception/inception-imls-weblicht/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/weblicht/traits/WeblichtRecommenderTraitsEditor.java, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/bootstrap/BootstrapFileInput.java, inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/bootstrap/BootstrapFileInputField.java, inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSpecificSettingsPanel.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectImportPanel.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/constraints/ProjectConstraintsPanel.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java, inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetImportPanel.java
- Introduce local versions of the Bootstrap upload components that initialize themselves for FontAwesome glyphs and that ensure that Bootstrap JS is loaded before their own JS code
* Try out the difference places where files can be uploaded and check if they look and work ok
=> #3297 - Upload field style looks broken

inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/bootstrap/BootstrapWizard.html, inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSpecificSettingsPanel.html
- Give the dialog a fixed size
- Also fix display of pre-configured remote KB profiles
* Create a new KB and check if the dialog looks good
=> #3296 - Knowledge base wizard looks odd

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainRenderer.java
=> #3306 - Rendering chain annotations is broken

inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Fix deletion of only the link
=> #3307 - Deleting a chain link deletes the previous span as well

inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/RootConceptsPanel.java
- Fix what was probably a copy/paste bug adding the data to the wrong field in the KB entity.
=> #3310 - Trying to add root concepts adds additional search properties instead

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/RatingFeatureEditor.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/RadioGroupStringFeatureEditor.java, inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/feature/FeatureEditor.java, inception/inception-brat-editor/src/main/ts/brat/annotator_ui/AnnotatorUI.ts, inception/inception-brat-editor/src/main/ts/brat/dispatcher/Dispatcher.ts, inception/inception-brat-editor/src/main/ts/brat/visualizer/Visualizer.ts, inception/inception-brat-editor/src/main/ts/scss/style-vis.scss, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CustomActionHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/config/DiamAutoConfig.java, inception/inception-diam/src/main/ts/diam/DiamAjaxImpl.ts, inception/inception-pdf-editor/src/main/ts/src/PdfAnnotationEditor.ts, inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/span.ts, inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- Delay DIAM calls if necessary to give feature editors a moment to commit
- Remove commit delay (in backend) from feature editors to give them priority
- When opening context menu via DIAM, give feature editors time to commit
- Use DIAM to open context menu in brat
- Fix feature editor committing value when selecting a new span in pdf editor
- Mark more "custom action" code as deprecated
- Suppress rendering while performing a selection and render afterwards if new data has been recieved (brat)
* See issue description - try different editors
=> #3242 - Tag not saved when moving to next tag

inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/ActionFactory.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/PostActionScrollToAndHighlight.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/PostActionScrollToAndSelect.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/RequestIdKey.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/UndoPanel.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/UndoRedoState.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/AnnotationAction_ImplBase.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/CreateChainLinkAnnotationAction.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/CreateChainSpanAnnotationAction.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/CreateRelationAnnotationAction.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/CreateSpanAnnotationAction.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/DeleteRelationAnnotationAction.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/DeleteSpanAnnotationAction.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/RedoableAnnotationAction.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/UndoableAnnotationAction.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/UpdateFeatureValueAnnotationAction.java
- Undo all actions that happened within one request. E.g. when deleting a span with attached relations, restore all the relations along with the span
* Create some spans and connect them with relations
* Delete one of the spans
* Undo/redo the deletion - the relations should also come back along with the span
=> #3244 - Undo/redo feature

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorDefaultPreferencesProperties.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorDefaultPreferencesPropertiesImpl.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationPreferencesDialogContent.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/UserPreferencesServiceImpl.java, inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/config/AnnotationEditorProperties.java, inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/editorstate/AnnotationPreference.java, inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_annotation-editor.adoc, inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/config/AnnotationEditorPropertiesImpl.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationInfoPanel.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/LayerSelectionPanel.java, inception/inception-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_span_forward.adoc, inception/inception-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_settings.adoc, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ApplicationPageBase.html
- Remove code to not remembering layer
- Remove related documentation
=> #2258 - Remove not remembering layer

inception/inception-doc/src/main/resources/META-INF/asciidoc/docinfo.html, inception/inception-external-editor/src/main/ts/src/ExternalEditorFactory.ts, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ApplicationPageBase.html
-  #3326 - Remove unnecessary type attribute for JavaScript resources in HTML code
-  #3326 - Add alt attribute to img element in HTML code
-  #3326 - Remove wrong </meta> in HTML code
=> #3326 - Fix some warnings and errors in HTML code

inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorPage.html
=> #3333 - Error in error page template

inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/dkprocore/HtmlDocumentReader.java, inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/dkprocore/internal/JSoupUtil.java, inception/inception-io-html/src/test/java/de/tudarmstadt/ukp/inception/io/html/dkprocore/HtmlDocumentReaderTest.java, inception/inception-io-html/src/test/resources/html/test-document.xmi, inception/inception-io-html/src/test/resources/html/test-document.xml, inception/inception-io-html/src/test/resources/html/test-with-head-and-doctype.xmi, inception/inception-io-html/src/test/resources/html/test-with-head.xmi, inception/pom.xml
=> #3317 - Update dependencies (24.2)

inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ProjectDocumentsPanel.java, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentImportedEvent.java
- Fix update of document table after importing a document
* Import a document
* Check that the document table shows the new document
=> #3330 - Improve document management in project settings

inception/inception-active-learning/pom.xml, inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.html, inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java, inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
- When a suggestion had no label show `<no label>` as the label in the history
- Fix not jumping when accepting/rejecting an annotation without feature values
- Fix sidebar layout
- Fix error message when acceping/rejecting an annotation via the main editor
=> #3187 - Active learning fails to jump on suggestions without feature values

inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/pipeline/RenderingPipelineImpl.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Display a flash message when there is no prev/next annotation
* Use the buttons
=> #3350 - Display message when there is no next or prev annotation

inception/pom.xml
- elasticsearch 6.8.23 -> 7.10.2
* See https://github.com/inception-project/inception/issues/3349
=> #3354 - Upgrade dependencies

inception/inception-app-webapp/pom.xml, inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc, inception/inception-external-search-elastic/pom.xml, inception/inception-external-search-opensearch/LICENSE.txt, inception/inception-external-search-opensearch/marker-wicket-module, inception/inception-external-search-opensearch/pom.xml, inception/inception-external-search-opensearch/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/opensearch/OpenSearchProvider.java, inception/inception-external-search-opensearch/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/opensearch/OpenSearchProviderFactory.java, inception/inception-external-search-opensearch/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/opensearch/config/OpenSearchDocumentRepositoryAutoConfiguration.java, inception/inception-external-search-opensearch/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/opensearch/traits/OpenSearchProviderTraits.java, inception/inception-external-search-opensearch/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/opensearch/traits/OpenSearchProviderTraitsEditor.html, inception/inception-external-search-opensearch/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/opensearch/traits/OpenSearchProviderTraitsEditor.java, inception/inception-external-search-opensearch/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/opensearch/traits/OpenSearchProviderTraitsEditor.properties, inception/inception-external-search-opensearch/src/main/resources/META-INF/asciidoc/user-guide/external-search-repos-opensearch.adoc, inception/inception-external-search-opensearch/src/main/resources/META-INF/spring.factories, inception/inception-external-search-opensearch/src/test/java/de/tudarmstadt/ukp/inception/externalsearch/opensearch/OpenSearchProviderTest.java, inception/inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/traits/PubAnnotationProviderTraitsEditor.html, inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/model/RemoteRepositoryTraits.java, inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/project/DocumentRepositoryEditorPanel.html, inception/pom.xml
- Support for OpenSearch
- Documentation
- Update also parts of the ElasticSearch support documentation
- Add JsonIgnoreProperties to some traits classes that didn't have it yet
=> #3356 - Support for external OpenSearch document repositories

inception/inception-external-search-solr/pom.xml, inception/inception-external-search-solr/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/solr/SolrSearchProvider.java, inception/inception-external-search-solr/src/test/java/de/tudarmstadt/ukp/inception/externalsearch/solr/SolrSearchProviderTest.java, inception/inception-external-search-solr/src/test/resources/log4j2.xml, inception/inception-external-search-solr/src/test/resources/solr/core/conf/lang/stopwords_en.txt, inception/inception-external-search-solr/src/test/resources/solr/core/conf/params.json, inception/inception-external-search-solr/src/test/resources/solr/core/conf/protwords.txt, inception/inception-external-search-solr/src/test/resources/solr/core/conf/schema.xml, inception/inception-external-search-solr/src/test/resources/solr/core/conf/solrconfig.xml, inception/inception-external-search-solr/src/test/resources/solr/core/conf/stopwords.txt, inception/inception-external-search-solr/src/test/resources/solr/core/conf/synonyms.txt, inception/inception-external-search-solr/src/test/resources/solr/solr.xml
- Start an embedded Solr server and test against it
=> #3361 - Unit tests for Solr support

inception/inception-app-webapp/pom.xml, inception/inception-external-search-elastic/src/main/resources/META-INF/asciidoc/user-guide/external-search-repos-elasticsearch.adoc, inception/pom.xml
- elasticsearch 7.10.2 -> 7.17.6
- Remove elasticsearch support from webapp module
* Maybe see what happens to projects that had an ElasticSearch repo configured - do they crash badly?
=> #3363 - Remove ElasticSearch support from the application

inception/inception-brat-editor/src/main/ts/brat/annotator_ui/AnnotatorUI.ts, inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/relation.ts, inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/span.ts, inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/utils.ts, inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/span.ts, inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/render/renderSpan.ts, inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/utils/relation.ts, inception/inception-pdf-editor2/src/main/ts/src/pdfanno/page/textLayer.ts, inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.ts
- Cleaning up code
- Prevent double-click from creating two annotations
* Try double-clicking to create an annotation in the PDF editor
=> #3371 - Double-click in PDF editor creates two annotations

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/filters/ProjectRoleFilterPanel.html, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/filters/ProjectRoleFilterPanel.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/filters/ProjectRoleFilterStateChanged.java, inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/PermissionLevel.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/open/AnnotationDocumentTable.html, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/open/OpenDocumentDialogPanel.java, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.html, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserTable.html, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/actionbar/opendocument/CurationDocumentTable.html, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/actionbar/opendocument/CurationOpenDocumentDialogPanel.java, inception/inception-ui-dashboard/pom.xml, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectEntry.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectListDataProvider.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectListFilterState.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectListSortKeys.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.properties
- Add filter field on in the project overview
- Add paging in the project overview
- Make a bunch of other search fields a little nicer by adding an icon
- Change the role filter panel on the project overview page to use icons instead of text
* Use the project overview page
=> #3374 - Make project overview searchable

inception/inception-recommendation/pom.xml, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/evaluation/EvaluationSimulationPageMenuItem.java, inception/inception-ui-agreement/pom.xml, inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementPageMenuItem.java, inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPageMenuItem.java, inception/inception-ui-core/pom.xml, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/menu/MenuItem.java, inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPageMenuItem.java, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPageMenuItem.java, inception/inception-ui-dashboard/pom.xml, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/DashboardMenu.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/ProjectSettingsDashboardMenuItem.java, inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/ProjectSettingsMenuItemBase.java, inception/inception-ui-external-search/pom.xml, inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPageMenuItem.java, inception/inception-ui-kb/pom.xml, inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePageMenuItem.java, inception/inception-ui-project/pom.xml, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPageMenuItem.java, inception/inception-workload-dynamic/pom.xml, inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPageMenuItem.java, inception/inception-workload-matrix/pom.xml, inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPageMenuItem.java
- Add keyboard shortcuts to dashboard panels on the normal project dashboard (not the project settings)
* Hover with the mouse over the dashboard menu items to see the shortcuts
* Try them
=> #3377 - Keyboard shortcuts for dashboard panels

inception/inception-bootstrap/src/main/ts_template/package-lock.json, inception/inception-brat-editor/src/main/ts_template/package-lock.json, inception/inception-diam/src/main/ts_template/package-lock.json, inception/inception-external-editor/src/main/ts_template/package-lock.json, inception/inception-html-editor/src/main/ts_template/package-lock.json, inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json, inception/inception-js-api/src/main/ts_template/package-lock.json, inception/inception-pdf-editor/src/main/ts_template/package-lock.json, inception/inception-pdf-editor2/src/main/ts_template/package-lock.json, inception/inception-project-export/src/main/ts_template/package-lock.json, inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json, inception/inception-ui-kb/src/main/ts_template/package-lock.json, inception/inception-ui-search/src/main/ts_template/package-lock.json, inception/pom.xml
- rdf4j 4.1.1 -> 4.1.2
- jena 4.5.0 -> 4.6.1
- bootstrap 5.2.0 -> 5.2.1
- antisamy 1.6.7 -> 1.7.1
- maven-surefire-plugin 3.0.0-M6 -> 3.0.0-M7
=> #3339 - Update dependencies (25.0)

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ColorRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/FocusMarkerRenderer.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RenderNotificationRenderStep.java, inception/inception-brat-editor/src/main/ts_template/package-lock.json, inception/inception-diam-editor/pom.xml, inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/experimental/editor/diamdebugeditor/DiamDebugEditorComponent.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/websocket/ViewportDefinition.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController.java, inception/inception-diam/src/main/ts_template/package-lock.json, inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController_ViewportRoutingTest.java, inception/inception-external-editor/src/main/ts_template/package-lock.json, inception/inception-html-editor/src/main/ts_template/package-lock.json, inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json, inception/inception-js-api/src/main/ts/src/diam/DiamWebsocket.ts, inception/inception-js-api/src/main/ts_template/package-lock.json, inception/inception-js-api/src/main/ts_template/package.json, inception/inception-pdf-editor/src/main/ts_template/package-lock.json, inception/inception-pdf-editor2/src/main/ts_template/package-lock.json, inception/inception-project-export/src/main/ts/build.mjs, inception/inception-project-export/src/main/ts_template/package-lock.json, inception/inception-project-export/src/main/ts_template/package.json, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationRenderer.java, inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationRenderer.java, inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json, inception/inception-ui-kb/src/main/ts_template/package-lock.json
- Use render pipeline in DiamWebsocketController
- Allow using any available serialization support in conjunction with WebSocket communitation
=> #3382 - Full render pipeline for DIAM websocket

inception/inception-recommendation-api/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/model/db-changelog.xml
- Removed the unused changeset
=> #3380 - Remove unused outdated db migration

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ColorRenderer.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/EditorAjaxRequestHandler.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/SelectAnnotationHandler.java, inception/inception-diam/src/main/ts/src/diam/DiamAjaxImpl.ts, inception/inception-diam/src/main/ts/src/diam/DiamWebsocketImpl.ts, inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts, inception/inception-js-api/src/main/ts/src/diam/index.ts, inception/inception-js-api/src/main/ts/src/editor/AnnotationEditorFactory.ts, inception/inception-js-api/src/main/ts/src/editor/index.ts, inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationRenderer.java
- Add scroll-to option to select-annotation call
=> #3391 - DIAM select should optionally scroll editor to selected annotation

inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/config/AnnotationAutoConfiguration.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorDefaultPreferencesPropertiesImpl.java, inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/UserPreferencesServiceImpl.java, inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController.java, inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController_ViewportRoutingTest.java
- If editor state is not availble, look up visibility preferences directly and apply them
=> #3393 - Layer visibility preferences do not affect DIAM websocket

inception/inception-diam-editor/pom.xml, inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/experimental/editor/diamdebugeditor/DiamAnnotationBrowser.java, inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/experimental/editor/diamdebugeditor/DiamSidebar.html, inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/experimental/editor/diamdebugeditor/DiamSidebar.java, inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/experimental/editor/diamdebugeditor/DiamSidebarFactory.java, inception/inception-diam-editor/src/main/ts/.eslintrc.yml, inception/inception-diam-editor/src/main/ts/build.mjs, inception/inception-diam-editor/src/main/ts/esbuild-runner.config.js, inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte, inception/inception-diam-editor/src/main/ts/src/AnnotationsByPositionList.svelte, inception/inception-diam-editor/src/main/ts/src/DiamAnnotationBrowser.svelte, inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte, inception/inception-diam-editor/src/main/ts/src/SpanText.svelte, inception/inception-diam-editor/src/main/ts/src/Utils.ts, inception/inception-diam-editor/src/main/ts_template/package-lock.json, inception/inception-diam-editor/src/main/ts_template/package.json, inception/inception-js-api/src/main/ts/src/model/AnnotatedText.ts, inception/inception-js-api/src/main/ts/src/model/Argument.ts, inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactAnnotatedText.ts, inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactArgument.ts, inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactRelation.ts
- Adding a annotation browsing sidebar
- Sidebar has two modes at: grouping by position and grouping by label
- Recommendations are shown alongside annotations
- Clicking an annotation selects it and reveals it in the main editor
* Open the annotation list sidebar and try it
=> #3395 - Allow browsing through annotations

inception/inception-brat-editor/src/main/ts/brat/visualizer/Visualizer.ts
- Request full data if differential update fails
=> #3405 - Editor may remain empty if differential update fails

inception/inception-search-mtas/src/main/resources/META-INF/asciidoc/user-guide/search-mtas.adoc
- Improve documentation for relation queries
* Read documentation, try the queries
=> #3408 - Better documentation of relation queries

inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaMenuItem.java
- Do not log exceptions for common errors during context menu actions
* Try using the context menu to create a relation in a location where no relation can be created
=> #2356 - Reduce exceptions thrown to reduce log pollution

inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilter.java, inception/inception-security/src/test/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilterTest.java, inception/inception-security/src/test/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImplTest.java
- Fix pre-auth bug
- Added more unit testing - in particular around pre-auth
=> #3438 - External pre-auth broken in INCEpTION 25.0

inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.html, inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java
- Add the flash message
- Remove border around non-editable project ID field
* Make a change in the project settings and press the save button
=> #3444 - Add flash message when saving project details

inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionServletContextInitializer.java
- Set Cross-Origin-Opener-Policy to same-origin
* Not sure - needs to be deployed in different scenarios I suppose.
=> #3443 - Set Cross-Origin-Opener-Policy header

inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/AnnotationDocumentExporter.java, inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- Also export the INITIAL_CAS in the secodary format.
* Export a project and check if the INITIAL_CAS is included in the secondary format
=> #3448 - Include the INITIAL_CAS in the secondary format

inception/inception-recommendation-api/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/model/db-changelog.xml
- Remove quotes around column name on non-PostgreSQL changeset
* Start app with embeddded database
=> #3451 - HsqlException: user lacks privilege or object not found: maxRecommendations

inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/InceptionSecurityRemoteApiAutoConfiguration.java
- Enable CORS on the remote API endpoint
=> #3459 - Enable CORS on the remote API endpoint

inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfExtractFile.java
- Disable external entity handling
=> #3464 - Disable external entity handling
