- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/PDFExtractor.java
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.java
> #3466 - Fix resource leaks

- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/Metrics.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/StatisticsExporter.java
- Use equals instead of == operator
- Also introduce a couple of constants to indicate coupling
> #3470 - Fix string comparison using ==

- inception/pom.xml
- maven-dependency-analyzer 1.12.0 -> 1.13.0
> #3431 - Update dependencies

- inception/inception-sharing/pom.xml
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
- inception/inception-support/pom.xml
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/DescriptionTooltipBehavior.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/markdown/MarkdownUtil.java
- inception/inception-ui-dashboard/pom.xml
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/CurrentProjectDashlet.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectEntry.java
- inception/inception-ui-kb/pom.xml
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseInfoPanel.java
- inception/pom.xml
- Use a terse sanitizer when displaying the short project description
- Use a more flexible renderer in other places
> #3481 - Improve short project descriptions in project overview

- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/pom.xml
- jquery-ui -> 1.13.2
- wicket jquery 9.8.1 -> 9.11.0
- Regenerate package-lock.json files
> #3476 - Update dependencies (25.2)

- inception/pom.xml
> #3496 - Update dependencies

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/feature/FeatureSupport.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupServiceImpl.java
- inception/inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/feature/ImageFeatureSupport.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureSupport.java
- Add display of tag description(s) in info popup
> #3494 - Display of label description when hovering over the label

- inception/inception-remote/pom.xml
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/InceptionSecurityRemoteApiAutoConfiguration.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/RemoteApiProperties.java
- inception/inception-remote/src/main/resources/META-INF/asciidoc/admin-guide/remote-api.adoc
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Authentication_Jwt_Test.java
- inception/inception-security/pom.xml
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2Adapter.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImpl.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ApplicationPageBase.java
- inception/pom.xml
- Added ability to configure an OAuth2-based authentication to the remote API
- Added test
- Added documentation
> #3508 - OAuth2 login to remote API

- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentImportExportService.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditorFactory.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicy.java
- inception/inception-external-editor/src/test/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicyTest.java
- inception/inception-external-editor/src/test/java/de/tudarmstadt/ukp/inception/externaleditor/policy/SafetyNetDocumentPolicyTest.java
- inception/inception-external-editor/src/test/resources/log4j2-test.xml
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/WatchedResourceFile.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- Add logging of masked attributes and elements for debugging
- Improve WatchedResourceFile to work with URLs
- Use WatchedResourceFile in ExternalAnnotationEditorFactory
> #3495 - Configurable editor content policies

- inception/pom.xml
- Spring Security 5.7.4 -> 5.7.5
- Spring Boot 2.7.4 -> 2.7.5
> #3517 - Update dependencies

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Keep clear button always enabled
- Fix re-rendering of sidebar after clearing
> #3525 - Cannot clear selection in read-only document

- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
- Turned them into a "plain text" form field because they are not really disabled - they are read-only
> #3456 - Internal Name text fields not greyed out

- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/DescriptionTooltipBehavior.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/markdown/MarkdownLabel.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/markdown/MarkdownUtil.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/markdown/TerseMarkdownLabel.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/CurrentProjectDashlet.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectEntry.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseInfoPanel.java
- Introduce a MarkdownLabel and a TerseMarkdownLabel
> #3531 - Improve handling of markdown

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/keybindings/KeyBindingsConfigurationPanel.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/keybindings/KeyBindingsPanel.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/keybindings/KeybindingLabel.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/filters/AnnotationDocumentStateFilterPanel.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/filters/ProjectRoleFilterPanel.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/filters/SourceDocumentStateFilterPanel.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationDocumentState.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/PermissionLevel.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/SourceDocumentState.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/dialog/ChallengeResponseDialogContentPanel.html
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/dialog/ConfirmationDialog.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/HasSymbol.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/SymbolLabel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserStateFilterPanel.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/BratSuggestionVisualizer.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.properties
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/MergeDialog$ContentPanel.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/MergeDialog.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AnnotatedListIdentifiers.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/AnnotatorStateCell.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/CurationStateSymbolLabel.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/CuratorColumn.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/SourceDocumentStateColumn.java
- Centralize handling of symbols and similar cases
> #3535 - Better centralize symbol handling

- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
- Fixed typo in parameter constant
> #3540 - Parameter to disable auto login does not work

- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIBuiltInAutoConfiguration.java
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIPreAuthenticatedAutoConfiguration.java
- inception/inception-app-webapp/src/main/resources/log4j2.xml
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/InceptionSecurityRemoteApiAutoConfiguration.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/InceptionSecurityAutoConfiguration.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/InceptionSecurityActuatorAutoConfiguration.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/InceptionSecurityWebUIApiAutoConfiguration.java
- Enable web-related configurations only when running with an enabled web server
* Try running a CLI command
> #3542 - CLI mode does not work

- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.html
- Fix Chrome recommendations on login page
> #3326 - HTML errors and warnings

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CurationUndoActionBarExtension.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/config/CurationUIAutoConfiguration.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPageMenuItem.java
- inception/inception-ui-curation/src/main/resources/spring.factories
- Enable undo/redo on the curation page
* Well, try undo/redo on the curation page
> #3520 - Undo / Redo feature in curation

- .gitignore
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_nginx.adoc
- Suggest using the remote IP as the forwarded-for header
> #3547 - Improve nginx documentation

- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsStartAndEndWithinSentencesCheck.java
- Check if an layer type is actually an annotation type otherwise skip the check
* See issue
> #3552 - AllAnnotationsStartAndEndWithinSentencesCheck crashes with Exception

- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/editors.adoc
* Add editors overview in documentation
> #3558 - Add editors overview in documentation 

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/logging.adoc
- Added a bit of documentation of the logging as well as how to configure the logger to output JSON instead of plain text
> #3544 - Documentation for JSON logging

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/ProjectSettingsDashboardPageBase.properties
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.java
- Fix error about missing property in the reset document dialog
- Fix message in the project deletion confirmation dialog
* See issue
> #3561 - Error when trying to reset a document

- inception/pom.xml
- Attach JS NPM artifacts to Maven build
* Check if the artifact ends up in the Maven repo
> #3566 - Attach JS NPM artifacts to Maven build

- inception/inception-preferences/src/main/java/de/tudarmstadt/ukp/inception/preferences/exporter/DefaultProjectPreferencesExporter.java
- inception/inception-preferences/src/main/java/de/tudarmstadt/ukp/inception/preferences/model/DefaultProjectPreference.java
- inception/inception-preferences/src/test/java/de/tudarmstadt/ukp/inception/preferences/exporter/DefaultPreferenceExporterTest.java
- Set the project on import
- Extend the test to cover checking that the project is properly set
> Issue #3568: Project-level preferences not properly imported

- inception/inception-io-nif/NOTICE.txt
- inception/inception-io-nif/pom.xml
- inception/inception-io-nif/src/main/java/org/dkpro/core/io/nif/NifReader.java
- inception/inception-io-nif/src/main/java/org/dkpro/core/io/nif/NifWriter.java
- inception/inception-io-nif/src/main/java/org/dkpro/core/io/nif/internal/DKPro2Nif.java
- inception/inception-io-nif/src/main/java/org/dkpro/core/io/nif/internal/ITS.java
- inception/inception-io-nif/src/main/java/org/dkpro/core/io/nif/internal/NIF.java
- inception/inception-io-nif/src/main/java/org/dkpro/core/io/nif/internal/Nif2DKPro.java
- Backport NIF implementation from DKPro Core 2.3.0-SNAPSHOT since it has not been released yet
> #3572 - NIF export does not work

- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/InceptionSecurityActuatorAutoConfiguration.java
- Also enable CSRF on the Spring Actuator endpoint
* Try accessing the endpoint
> #3452 - Enable Spring MVC CSRF protection on UI API and view endpoints

- inception/pom.xml
- postgres-driver 42.5.0 -> 42.5.1
> #3584 - Update dependencies

- inception/inception-api-render/pom.xml
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/model/Range.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/selection/Selection.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VID.java
- inception/inception-diam/pom.xml
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compact/CompactRangeList.java
- inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandlerTest.java
- Clip selection and span creation to the document boundaries
> #3583 - Error when browser selects across document boundaries

- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/CasXmlHandler.java
- Invoke listeners later to fix bug
> #3590 - CasXmlHandler listeners invoked too early

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xml/XmlCas2SaxEvents.java
- inception/inception-io-intertext/src/main/java/de/tudarmstadt/ukp/inception/io/intertext/IntertextReader.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/Cas2SaxEvents.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/XmlNodeUtils.java
- inception/inception-io-xml/src/test/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/XmlNodeUtilsTest.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/xml/TextSanitizingContentHandler.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollection.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionIOUtils.java
- Avoid sending non-captured text to the browser
> #3592 - Non-captured text is being sent to browser in XML-based editors

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorJSResourceReference.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.js
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.properties
- Move JS from the HTML page template to a separate JS file which we load via Wicket
> #3600 - JS controlling element switch in ADEP does not load

- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIBuiltInAutoConfiguration.java
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIPreAuthenticatedAutoConfiguration.java
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIShared.java
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionServletContextInitializer.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/InceptionSecurityWebUIApiAutoConfiguration.java
- Enable CSP for the view URLs (`/ui`) which is used in particular by the HTML-based editors
> #3602 - Enable Spring MVC CSP

- inception/inception-export/pom.xml
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/LayerImportExportUtils.java
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectImportExportUtils.java
- inception/inception-remote/pom.xml
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- inception/inception-ui-project/pom.xml
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectImportPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.properties
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetImportPanel.java
- inception/inception-versioning/src/main/java/de/tudarmstadt/ukp/inception/versioning/VersioningServiceImpl.java
- inception/pom.xml
- Move tagset and layer export/import code from UI to LayerImportExportUtils
- Moved method to check if a ZIP file is a project archive to ProjectImportExportUtils
> #3618 - Move more code from UI to backend

- inception/pom.xml
- spring-security 5.7.5 -> 5.8.0
> #3616 - Upgrade dependencies

- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIBuiltInAutoConfiguration.java
- inception/inception-app-webapp/src/main/resources/application.yml
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
- inception/inception-remote/src/main/resources/META-INF/asciidoc/admin-guide/remote-api.adoc
- inception/inception-security/pom.xml
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/OverridableUserDetailsManager.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/Realm.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/SpringAuthenticatedWebSession.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityAutoConfiguration.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/PreAuthUtils.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/preauth/ShibbolethRequestHeaderAuthenticationFilter.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/saml/Saml2Adapter.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/saml/Saml2AdapterImpl.java
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-authentication-auto-login.adoc
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-authentication-oauth2.adoc
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-authentication-policy.adoc
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-authentication-preauth.adoc
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-authentication-saml2.adoc
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-authentication.adoc
- inception/inception-security/src/test/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImplTest.java
- inception/inception-security/src/test/java/de/tudarmstadt/ukp/inception/security/saml/Saml2AdapterImplTest.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/Saml2LoginPanel.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/Saml2LoginPanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
- inception/pom.xml
> #3606 - Support for SAML2 IdPs

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/misc/ReorderableTagAutoCompleteField.java
- inception/inception-bootstrap/src/main/ts/bootstrap/inception-feature-editors.scss
- inception/inception-bootstrap/src/main/ts/bootstrap/shim-kendo.scss
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/StyledComboBox.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/kendo/KendoStyleUtils.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/KBHandleTemplate.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/KnowledgeBaseItemAutoCompleteField.java
- Fixed style
- Includes some fix backports from main
* Look at the dropdowns of the concept feature editor, multi-value concept feature editor, string feature editor, multi-value string feature editor
> #3634 - Dropdowns look odd

- inception/pom.xml
> #3617 - Upgrade dependencies

- inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactAnnotatedText.ts
> #3638 - CompactAnnotatedText v2 makeMarkerMap is buggy

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
- Fix the getPrev and getNext methods
* Use the buttons
> #3640 - Prev/next annotation buttons sometimes hang

- inception/inception-js-api/src/main/ts/src/util/ViewportTracker.ts
- If no new elements are loaded by a tracking change (i.e. only elements were removed) do not trigger the callback
- If a section selector is defined, try to always load annotations for the entire section
> #3644 - Potential endless loop in viewport tracker when editor changes document layout

- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserTableDataProvider.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/actionbar/opendocument/CurationDocumentTableDataProvider.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectListDataProvider.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentSelectColumn.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTableDataProvider.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/support/AnnotationQueueOverviewDataProvider.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/DocumentMatrixDataProvider.java
- Display how many docuement are selected after a (bulk)-select action
- Consider filter when applying bulk (un)selection
> #3622 - Bulk action does not take state filter into account

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/LabelRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainRenderer.java
- Avoid LabelRenderer step overriding label hints that were set earlier in the rendering process
> #3650 - Link label shows layer name instead of label

- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/request/RenderRequest.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VRange.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LoadAnnotationsHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compactv2/CompactSerializerV2Impl.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compactv2/CompactTextMarker.java
- inception/inception-diam/src/main/ts/src/diam/DiamAjaxImpl.ts
- inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
- Added option to disable span clipping (compact v2 only)
> #3660 - Option to disable span clipping

- inception/inception-app-webapp/pom.xml
> #3670 - Remove LIF support

- inception/inception-external-editor/src/main/ts/src/ExternalEditorFactory.ts
- Add a forwarding of keyboard events from within the iframe to the outside document
> #1535 - Keyboard shortcuts do not work when focus is in certain editors

- inception/inception-brat-editor/src/main/ts/src/annotator_ui/AnnotatorUI.ts
- inception/inception-brat-editor/src/main/ts/src/style-vis.scss
- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- inception/inception-diam/src/main/ts/src/diam/DiamWebsocketImpl.ts
- Clean up a few warnings
- Send extension actions through DIAM
* Try e.g. rejecting an annotation
> #3675 - Clean up more brat code

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ColorRenderer.java
- When coloring, sort layers by "creation order" to ensure colors do not shift when a new layer is added
> #3656 - The color of the existing layers changes after adding another layer

- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
* Fix visibility condition
* See issue
> #3610 - Minimizing icon in document level feature is wrong after updating feature

- inception/pom.xml
- spring-boot 2.7.6 -> 2.7.7
- spring-security 5.7.5 -> 5.7.6
- springdoc 1.6.13 -> 1.6.14
- groovy 3.0.13 -> 3.0.14
- wicket-bootstrap 6.0.0-M8 -> 6.0.0
- wicket-spring-boot 3.1.6 -> 3.1.7
- elasticsearch 7.17.7 -> 7.17.8
- opensearch 1.3.6 -> 1.3.7
- mock-oauth2-server 0.5.6 -> 0.5.7
- fastutil 8.5.9 -> 8.5.11
- byte-buddy 1.12.19 -> 1.12.20
- caffeine 3.1.1 -> 3.1.2
> #3683 - Update dependencies

- inception/pom.xml
- wicket-spring-boot 3.1.7-> 3.1.6 -- downgrade due to Problem with 3.1.7 MarcGiffing/wicket-spring-boot#199
- tomcat 9.0.69 -> 9.0.70
* Try annotating a document...
> #3688 - Update dependencies

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- Take a detour over the type name since the actual type instance may not be found in the target CAS (same type name, but different type system versions)
* Try out test project attached to issue
> #3523 - Infinite merging of annotations on custom layers

- inception/inception-brat-editor/src/main/ts/src/annotator_ui/ResizeManager.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/MoveSpanAnnotationHandler.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Fix resizing to the start of the document
- Properly update the detail panel when the currently selected annotation is resized
* Try resizing spans in the brat editor
> #283 - Resize span

- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/config/ProjectInitializersAutoConfiguration.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/empty/EmptyProjectInitializer.java
- Template added
* Try using the new template
> #3511 - Add empty project template

- inception/inception-io-lif/pom.xml
- inception/pom.xml
- pom.xml
- groovy 3.0.14 -> 4.0.7
* Try importing a file in LIF format
> #3706 - Update dependencies (26.6)

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseIriPanel.html
- Remove bootstrap form-control class from Kendo components
* See issue
> #3714 - Layout of combo boxes for KB IRI settings is broken

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/AnnotationSchemaService.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LazyDetailsHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailQuery.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupService.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupServiceImpl.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsResponse.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/BratSuggestionVisualizer.java
- Fix bug
- Rename some methods
- Change getTag() signature to return an optional
- Display a message if the feature value is not in the tagset
- Undeprecate lazy details classes
> #3737 - Lazy detail lookup error if value is not in tagset

- inception/inception-brat-editor/src/main/ts/src/util/ScrollbarWidth.ts
- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- Cache scrollbar width
- Little bit of code cleaning
> #3755 - Cache scrollbar width instead of calculating it on each render action

- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- Improve visuals
* Use annotation sidebar with recommendations
**Demo**
> #3758 - Display suggestion score in annotation sidebar

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/Utils.ts
- inception/inception-js-api/src/main/ts/src/util/ViewportTracker.ts
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- Added an option in the group-by-label view of the annotation sidebar to sort by scores
- Use annotation sidebar in a project with active recommenders
> #3762 - Ability to sort annotation sidebar by recommender scores

- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialogManager.java
- Consider the context path when constructing the URLs
> #3775 - Browser opens wrong URL if context path is set

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Do not set the focus unit index when saving an annotation
> #3779 - Accepting an annotation in an editor using NoPagingStrategy jumps to top

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- Force-refresh the data provider after importing projects
- Add a light background to the freshly imported projects
> #3781 - When importing multiple projects overview does not update

- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/inception/ui/project/dangerzone/ProjectDangerZonePanel.java
- Check if the project being deleted is the project currently being shown on a project-specific page and only then redirect to the application homepage (i.e. the project overview page)
> #3784 - Deleting a project in admin view should not redirect to project overview

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationRenderer.java
- In rendering requests from the sidebar, there is no AnnotatorState - so we need to use another approach to determine if we are on the curation page. Following the same approach as we use in the RecommendationRenderer
> #3786 - Annotation sidebar does not show annotations from other users in curation mode

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationEditorExtension.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/config/CurationSidebarAutoConfiguration.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationRenderer.java
- inception/inception-ui-curation/src/test/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationVIDTest.java
- Implement scrollTo action for the curation sidebar extension
- Change the curation sidebar extension ID from "curationEditorExtension" to "cur"
> #3788 - Jumping to a curation item via sidebar does not work

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
- inception/inception-recommendation/src/main/resources/META-INF/asciidoc/admin-guide/settings_recommender.adoc
- inception/inception-search-core/src/main/resources/META-INF/asciidoc/admin-guide/settings_search.adoc
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/config/StatsServiceUIAutoConfiguration.java
- Global feature toggle for statistics sidebar
- Global feature toggle for recommender sidebar
- Update documentation
* Disable the sidebars via the `settings.properties` file and check if they are really disabled
> #3790 - Feature toggles for more sidebars

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoChoiceDescriptionScriptReference.java
- Do not make title bold in reorderable lists
- Show score at end instead of in next line
* See issue description (use different string and concept feature editors and check if the look good)
> #3743 - Labels in feature editors look bold

- inception/inception-annotation-storage/src/test/java/de/tudarmstadt/ukp/inception/annotation/storage/CasStorageServiceImplTest.java
- inception/inception-annotation-storage/src/test/java/de/tudarmstadt/ukp/inception/annotation/storage/driver/filesystem/CasPersistenceUtilsTest.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
- inception/inception-support/NOTICE.txt
- inception/inception-support/src/main/java/org/apache/uima/cas/impl/FixedBinaryCasSerDes.java
- Added hot-fix while UIMA 3.4.1 has not yet been released
> #3799 - Reading CAS rarely fails with IndexOutOfBoundsException 

- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewController.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- Change URL scheme for loading resources
> #3773 - Support loading resources from documents that are actually archives

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/DisabledKBWarning.java
- Fix problem by setting selected item in auto-complete field before triggering the AJAX change event
- Also fix warning logged by DisabledKBWarning because string resource model value was retrieved in constructor
> #3813 - Cannot set value in concept feature editor when there are constraints

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Ignore jump request if the target annotation is actually not a text-level annotation but a document-level annotation (no offsets)
> #3801 - Error trying to undo document-level annotation action

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectListDataProvider.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.properties
- Added ability to sort project dashboard by different criteria
* Change the sort order on the project overview screen
> #3783 - Ability to sort projects by created date

- inception/pom.xml
- UIMA Java SDK 3.4.0 -> 3.4.1
> #3571 - Update dependencies

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
> #3841 - NPE when trying to join project through invite link

- inception/inception-pdf-editor2/src/main/ts/src/PdfAnnotationEditor.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.css
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.ts
- Highlight the entire target section after a jump
- Use a pulsing highlight
* Try jumping to locations in a PDF e.g. using the annotation sidebar
> Issue #3844: Improve scroll-target highlighting in PDF editor

- inception/pom.xml
> Issue #3571: Update dependencies

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/LabelRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainRenderer.java
- Cherry-pick fix for this from 02a78793bfc82c7073a3cba8bce80603e24853c9 which apparently got discarded during some empty merge
> #3858 - Labels of linked features are not visible

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarIcon.java
- Initialize editor in the same way when curtation is enabled via URL as when it is enabled manually
- Note this will create an AnnotationDocument for the CURATION_USER in the DB - this should not be relevant and used by other code - but it might come unexpected to some code, so it need to be monitored
> #3860 - Error merging curation suggestion in sidebar curation mode using direct URL access

- inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/view/DocumentViewExtensionPoint.java
- inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/view/DocumentViewExtensionPointImpl.java
- inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/view/DocumentViewFactory.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditor.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentIFrameView.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentIFrameViewFactory.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xml/XmlDocumentIFrameView.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xml/XmlDocumentIFrameViewFactory.java
- inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/annotatorjs/AnnotatorJsHtmlAnnotationEditor.java
- inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentIFrameView.java
- inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentIFrameViewFactory.java
- inception/inception-html-recogito-editor/src/main/java/de/tudarmstadt/ukp/inception/recogitojseditor/RecogitoHtmlAnnotationEditor.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationDocument.java
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfDocumentIFrameView.java
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfDocumentIFrameViewFactory.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/PdfAnnotationEditor.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/view/PdfDocumentIFrameView.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/view/PdfDocumentIFrameViewFactory.java
- Replace AnnotationDocument with SourceDocument
> #3855 - Editor views only need a SourceDocument

- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/dialog/ChallengeResponseDialogContentPanel_ImplBase.html
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/dialog/ChallengeResponseDialogContentPanel_ImplBase.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/DeleteLayerConfirmationDialogContentPanel.html
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/DeleteLayerConfirmationDialogContentPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/DeleteLayerConfirmationDialogContentPanel.properties
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.properties
- Switch to a dedicated deletion confirmation dialog for the layer deletion which lists which layers/features are blocking deletion
* Try deleting a layer that is used by one or more link features and/or relation layer
**Demo**
> #3857 - Provide information why a layer cannot be deleted

- inception/inception-image/pom.xml
- inception/inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/sidebar/ImageSidebar.java
- inception/pom.xml
- Remove automatic image border coloring code
> #3871 - Remove automatic border color in image sidebar

- inception/inception-app-webapp/pom.xml
- inception/inception-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-doc/pom.xml
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- inception/pom.xml
- jquery 3.6.0/3.6.3 -> 3.6.4
- regenerate package-lock.json files
> #3873 - Upgrade dependencies

- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- Consider spacing elements when looking for chunks
> #3890 - Annotations not created if mouse is released on empty space

- inception/inception-feature-lookup/src/main/java/de/tudarmstadt/ukp/inception/feature/lookup/LookupFeatureEditor.java
- Fix problem by setting selected item in auto-complete field before triggering the AJAX change event
> #3895 - Cannot set value in lookup feature editor when there are constraints

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectListSortState.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectListSortStrategy.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.properties
- Remember the sort order in a per-user preference
* Change the sort order on the project overview page
* Log out and back in
* Go to a different page (e.g. into a project) and then go back to the project overview
* In every case, the sort order you set should be remembered
> #3900 - Remember project list sort order

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/XmlDocumentViewControllerImplBase.java
- If the format already provides a policy, do not consider the editor policy anymore
> #3907 - Consider editor policy only if format does not offer policy

- inception/inception-docker/src/main/docker/Dockerfile
- Update packages as part of build
> #3920 - Upgrade packages when building Docker container

- inception/inception-io-json/src/main/resources/META-INF/asciidoc/user-guide/formats-uimajson-legacy.adoc
- Fix property in documentation
* Check documentation
> #3935 - Documentation lists wrong property to re-enable legacy UIMA JSON format

- inception/pom.xml
> #3932 - Upgrade dependencies

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningServiceImpl.java
- inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanAdapterTest.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- Merge span label into existing span if that span has no value for the given label yet
> #3940 - Merge label into eligible existing annotation even when stacking is enabled

- inception/inception-ui-core/pom.xml
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/footer/VersionFooterItem.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/footer/WarningsFooterItem.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/about/AboutFooterItem.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/config/CoreUiAutoConfiguration.java
- Switch core UI footer items to auto-configuration
> #3953 - Switch core footer items to auto-configuration

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureSupport.java
- Handle case where feature value is null
> #3965 - NPE when multi-value feature has no value

- inception/inception-app-webapp/pom.xml
- inception/inception-io-webanno-tsv/pom.xml
- inception/inception-plugin-parent/pom.xml
- inception/pom.xml
- slf4j 1.7.36 -> 2.0.7
- tomcat 9.0.71 -> 9.0.74
- wicket 9.12.0 -> 9.13.0
- wicketstuff 9.12.0 -> 9.13.0
- wicket-bootstrap 6.0.1 -> 6.0.3
- asciidoctor-plugin 2.2.2 -> 2.2.3
- asciidoctor 2.5.7 -> 2.5.8
- asciidoctor-diagram 2.2.4 -> 2.2.7
- jackson 2.14.1 -> 2.14.2
- log4j-slf4j-impl -> log4j-slf4j2-impl (crossgrade)
> #3886: Upgrade dependencies

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/RatingFeatureEditor.html
> #3978 - Radio-button based number input has broken layout

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/settings/CurationProjectSettingsPanel.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/settings/MergeStrategyPanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/settings/ProjectSettingsPanelBase.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ProjectDocumentsPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
- Moving the traits merge settings refresh to the change callback seems to work
> #3972 - Changing merge type does not refresh traits panel in project settings

- inception/inception-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- Update package-lock.json files
> #3975 - Upgrade dependencies

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/TypeAdapter_ImplBase.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationAdapter.java
- inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/adapter/TypeAdapter.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- Introduce a bunch of convenience methods to facilitate access to features and feature supports
- Add convenience method to ConceptFeatureSupport to access KBHandle for a given concept
> #3980 - Improve TypeAdapter APIs

- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/SpringAuthenticatedWebSession.java
- Send AuthenticationSuccessEvent on password-based login
* See issue
> #3984 - Last login field of users not update

- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/LearningRecordService.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/LearningRecord.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/exporter/ExportedLearningRecord.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/exporter/LearningRecordExporter.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/LearningRecordServiceImpl.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/exporter/LearningRecordExporterTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/exporter/RecommenderExporterTest.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/SpringAuthenticatedWebSession.java
- Add learning records to project export and also import them back again
- Bit of minor cleaning up here and there
* Make some annotations using recommenders
* Export project and check project.json file for learning records
> #3973 - Include learning records in project export

- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/RelationPosition.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/RelationSuggestion.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SpanSuggestion.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- Use builders when extracting suggestions
- Slightly improve extraction loops to improve performance
- Make relation suggestion extraction more robust
- Remove redundant parameters from some internal methods
- Better consider sessionOwner vs. dataOwner
> #3969 - Review and improve visibility calculation code

- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.properties
- Add third option for exporting the full UIMA type system for a project (without internal types)
* Go to the layers panel in the project settings
* Select a layer so that the detail panel appears
* Choose **UIMA XML (full project type system)** from the dropdown list.
> #4004 - Ability to export full type system from layer detail panel

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/TypeAdapter_ImplBase.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainAdapter.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainLayerSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationAdapter.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanAdapter.java
- inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/adapter/TypeAdapter.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerAdapter.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- Introduce new method that takes an event supplier
- Deprecate old method
- Switch to using new method
> #4009 - Avoid event instantiation when event is not going to be sent

- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception/inception-external-search-pubannotation/src/main/resources/META-INF/asciidoc/user-guide/external-search-repos-pubannotation.adoc
- inception/inception-external-search-pubmed/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubmed/config/PubMedDocumentRepositoryAutoConfiguration.java
- inception/inception-external-search-pubmed/src/main/resources/META-INF/asciidoc/user-guide/external-search-repos-pmc.adoc
- inception/inception-io-bioc/src/main/resources/META-INF/asciidoc/user-guide/formats-bioc.adoc
- inception/inception-io-bioc/src/test/java/de/tudarmstadt/ukp/inception/io/bioc/BioCXmlDocumentReaderTest.java
- Added documentation for PMC external repo
- Added documentation for BioC format
> #3918 - PubMed Central support

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationDocumentServiceImpl.java
- Remove duplicate `@PreAuthorize` annotation
> #4016 - Error when accessing a document for curation

- inception/inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/PubAnnotationProvider.java
- inception/inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/model/PubAnnotationDocumentSection.java
- inception/inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/traits/PubAnnotationProviderTraits.java
- Update PubAnnotation URL
- Minor cleanup
* See issue
> #4027 - Access to PubAnnotation no longer working

- inception/inception-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- Regenerate package-lock.json files
> #3673 - Update dependencies

- inception/inception-html-editor/src/main/ts/build.js
- Fix target package for compiled JS code
* Check if AnnotatorJS editor still works
> #4030 - Move AnnotatorJS code to different package

- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/preferences/DiamSidebarManagerPrefs.java
- Remove calls that log the message
> #4038 - Odd message logged to stdout

- inception/inception-app-webapp/pom.xml
- inception/pom.xml
- Add sentry dependencies
* Try configuring a connection to Sentry via properties set in the `settings.properties` file
> #4026 - Support for error tracking with Sentry

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
- Fix logging of start and end events for selection, training and prediction and always show the time the steps too in the recommender log
* In a project that uses recommenders, open the recommender log from the sidebar and look for lines indicating the start/end of a particular task.
> #1066 - Recommender status info

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditor.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditorBase.java
* Fix class cast exception
* Try opening the annotation browser sidebar when editing a document in the annotation editor
> #4040 - Ability to store preferences from client-side code

- inception/inception-app-webapp/pom.xml
- inception/pom.xml
- Add sentry log4j dependency
- sentry 6.20.0 -> 6.22.0
* Probably follow the sentry documentation on the sentry homepage ;)
> #4026: Support for error tracking with Sentry

- inception/inception-diam/pom.xml
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/FillSlotWithExistingAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/FillSlotWithNewAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/MoveSpanAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/ScrollToHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/wicket-package.properties
- inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandlerTest.java
- inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/annotatorjs/AnnotatorJsHtmlAnnotationEditor.java
- inception/pom.xml
- Remove redundant code
- Clean up code
* Try playing around with slot annotations, e.g. using the `SemPred` and `SemArg` layers from the **Standard project** template.
> #4060 - Clean up redundant code in annotation handlers

- inception/inception-js-api/src/main/ts/src/util/ViewportTracker.ts
- Change viewport tracking from an exclude list to an include list.
* No specific test procedure - basically play around with editors that use the tracker
> #4062 - ViewportTracker should focus on block-like elements

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringRulesConfigurationPanel.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringRulesConfigurationPanel.java
- Added buttons to change the order of coloring rules
* Create several rules
* Use the buttons to change the order
* Save, leave and come back to see if the order persists
> #4075 - Re-ordering of coloring rules

- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectAccessImpl.java
- Change condition for accessing a project to allow admin users as well
> #4086 - Admin cannot export project unless also a manager

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- inception/inception-diam-editor/src/main/ts/src/Utils.ts
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventWebsocketControllerImplTest.java
- Render the layer name instead of "no label" if an annotation does not have a label yet
- Extend some timeouts to avoid flaky tests
* Look at the annotation sidebar to check if annotations without a label value are rendered as the layer name (in parentheses)
> #3700 - Difference between annotation sidebar and brat on annotations without label

- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
- inception/inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiffTest.java
> #4100 - Error curating documents with multi-value string features

- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/relation.ts
- Disable arc creation on synthetic annotations (i.e. anything containing a ':')
* Try creating a relation starting at a suggestion
> #4011 - PDF editor error "Relations cannot be created from/to synthetic annotations"

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainLayerTraitsEditor.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- Restore i18n string that seems to be still in use...
> #4112 - Cannot edit coference layer anymore

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/RatingFeatureEditor.java
- Use Wicket Radio instead of Kendo Radio
> #4114 - Radio buttons editor for numeric features looks broken

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/ConceptFeatureTraits.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/ConceptFeatureTraits_ImplBase.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/MultiValueConceptFeatureTraits.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseExporterTest.java
- Fix issue by also checking for "kb-multi" when remapping KB IDs during import
- Updated unit test
> #4118 - KB link of multi-value concept feature lost on export and import

- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/selection/Selection.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Perform sanity check on VID when selecting a span or arc
- Remove unused and not checkable setAnnotation(VID) method
> #4122 - Try catching bad selections early

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
- Better placement of log message - only when recommenders are really seen
- Avoid scheduling any reommender tasks at all if project has no enabled recommenders
> #4124 - Reduce log-spam from SelectionTask

- inception/inception-bootstrap/src/main/ts/bootstrap/inception-actionbar.scss
- inception/inception-bootstrap/src/main/ts/bootstrap/inception-dashboard.scss
- inception/inception-bootstrap/src/main/ts/bootstrap/shim-kendo.scss
- inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/annotatorjs/AnnotatorJsHtmlAnnotationEditor.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/DashboardMenu.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/IriInfoBadge.html
- Fix style of Kendo tooltips
- Fix issue that opening KB IRI badge could trigger page reload
- Make dashboard sidebar always dark
- Fix action bar button styling
> #1336 - Add dark mode

- inception/inception-html-recogito-editor/src/main/ts/src/recogito/InceptionEditorColors.scss
- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.scss
- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.ts
- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditorFactory.ts
- Pull in 487a89082d51f1c415d2fbb23e18bb89e1e32266 from https://github.com/inception-project/inception-recogito-editor-plugin
* Try using the Recogito editor
> #4132 - Update Recogito editor

- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/exception/IllegalNameException.java
- Forward extension of the uploaded file to the import service
- Check project and document names for validity during remote API uploads
> #4137 - Importing annotations with NIF format, raises error on remote api endpoint

- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/abstract.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.ts
- Switch over to the new format
* Try the PDF editor
> Issue #4148: Switch PDF editor to compact model v2

- inception/inception-imls-external/pom.xml
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommender.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/model/Metadata.java
- inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderIntegrationTest.java
- inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/MockRemoteStringMatchingNerRecommender.java
> #1861 - Add viewport offsets to external recommender

- Jenkinsfile
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- Display right sidebar only if there is at least one span-level annotation layer
* Check that sidebar is visible in projects that contain at least one (enabled) span annotation layer
> #4163 - Right sidebar visible even if there are not text-level layers

- Jenkinsfile
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java
- inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController_ViewportRoutingTest.java
- Set document text and offsets before shortcutting out of the pre-render step if there are no layers to be rendered
> #4161 - Error opening document in project without layers

- inception/inception-imls-opennlp/pom.xml
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTraits.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderTraits.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderTraits.java
- opennlp 1.9.3 -> 2.3.0
- improve handling of adaptive features during prediction
> #4150 - Upgrade dependencies

- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasMetadataUtils.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasStorageServiceImpl.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasStorageSession.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/OpenCasStorageSessionForRequestFilter.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/driver/filesystem/CasPersistenceUtils.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/driver/filesystem/FileSystemCasStorageDriver.java
- inception/inception-io-bioc/src/test/java/de/tudarmstadt/ukp/inception/io/bioc/BioCXmlDocumentReaderTest.java
- inception/inception-io-tei/NOTICE.txt
- inception/inception-io-xmi/NOTICE.txt
- inception/inception-io-xmi/pom.xml
- inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/inception/io/xmi/BinaryCasFormatSupport.java
- inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/inception/io/xmi/dkprobackport/BinaryCasReader.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchCasUtils.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
> #4178 - Clean up and modernize CAS storage code

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationEditorDefaultPreferencesPropertiesImpl.java
- inception/inception-app-webapp/src/main/resources/application.yml
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/config/BratAnnotationEditorPropertiesImpl.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorPropertiesImpl.java
- Remove overrides in application.yml
* Check if minimal internal CAS backup is enabled by default
* Check if auto-scroll is disabled by default
* Check if single-click selection is enabled by default
> #4182 - Internal backups not enabled by default

- inception/inception-log/src/main/resources/de/tudarmstadt/ukp/inception/log/model/db-changelog.xml
> #4186 - Reduce loading time for recent activity in dashboard

- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- Use the layer name if available
* Create annotation without features and create an annotation of that layer in the Apache Annotator editor
> #4198 - Show layer name instead of no-label

- inception/inception-export/pom.xml
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/LayerImportExportUtils.java
- Align JSON layer export again to general project export code
> #4201 - Layer export as JSON does not include coloring rules

- pom.xml
- wicketstuff 9.14.0 -> 9.15.0
> #4192 - Upgrade dependencies

- inception/inception-kb/pom.xml
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- Disable transaction isolation during KB import
* Import a large KB
> #4219 - Improve speed of importing a large KB

- inception/inception-dependencies/pom.xml
- pom.xml
- opensearch 1.3.12 -> 1.3.13
- opensearch-runner 1.3.7.0 -> 1.3.13.0
- commons-pool2 -> 2.12.0
- commons-dbcp2 -> 2.10.0
- commons-io 2.13.0 -> 2.14.0
- snappy 1.1.10.4 -> 1.1.10.5
- spring-boot 2.7.14 -> 2.17.15
- spring-data 2.7.14 -> 2.17.15
- sentry 6.29.0 -> 6.30.0
> #4221 - Upgrade dependencies

- inception/inception-dependencies/pom.xml
- inception/inception-tutorial/pom.xml
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.css
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
- inception/inception-ui-dashboard/pom.xml
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/DashboardMenu.java
- pom.xml
- Drop hover.css
- Drop animate.css
> #4230 - Upgrade dependencies

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/events/BeforeDocumentOpenedEvent.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/event/HybridApplicationUIEventRouter.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarBehavior.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarFactory.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarIcon.java
- Use alternative approach to react to the URL parameters
* Try enabling/disabling the sidebar-curation-mode via URL
> #4235 - Direct access-by-URL to sidebar curation mode sometimes does not work

- inception/inception-app-webapp/src/test/java/de/tudarmstadt/ukp/inception/InceptionRemoteApiJwtIntegrationTest.java
- Change test to run on random free port
> #4243 - Make JWT integration run on random free port

- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/markdown/MarkdownUtil.java
- Relax sanitation policy used when rendering Markdown
> #4245 - Headings in project descriptions do not work

- inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/Tsv3XDeserializer.java
- inception/inception-io-webanno-tsv/src/test/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3XReaderTest.java
> #4247 - Relation offsets not set properly when importing TSV 3.x files

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/editor/state/AnnotatorStateImpl.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/editorstate/AnnotatorDocumentNavigation.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/editorstate/AnnotatorState.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIShared.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ProjectPageBase.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/AccessDeniedPage.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/AccessDeniedPage.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorPage.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarBehavior.java
- Redirect to dashboard if possible and to dead-end page if not possible
> #4266 - Improve backToProject call

- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.ts
- Switch to the new protocol
* Enable the RecogitoJS editor and try annotating a HTML file
> #4269 - Switch RecogitoJS editor to compact_v2 model

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByPositionList.svelte
- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.ts
- inception/inception-js-api/src/main/ts/src/widget/AnnotationDetailPopOver.svelte
- inception/inception-ui-dashboard-activity/src/main/ts/src/ActivitiesDashlet.svelte
- Added the popover
- Also replace the legycy sr-only BS class with the new one visually-hidden
* Hover over an annotation (span or relation) in the RecogitoJS editor
> #4274 - Add popover in RecogitoJS editor

- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- Changed approach to access resources to one which works around the internal caching performed by the URL class
> #4276 - Improve resource loading

- inception/inception-log/pom.xml
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AuthenticationSuccessEventAdapter.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/EventLoggingAdapter.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/HttpSessionDestroyedEventAdapter.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/model/SessionDetails.java
- Added two new logged events derived from the authentication successful and dession destroyed events
* Log in and log out and then check the event log
* Also try logging in and then letting the session expire and check the log then
> #4282 - Capture start and end of user session in event log

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- Only display the message when the feature has a tagset
* See issue
> #4297 - Popover always showing "tag not in tagset" even if feature has no tagset at all

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- Display error if there is an error, display reason for state if there is a reason, if nothing is known yet display waiting
* See issue
> #4298 - Recommender status says "Waiting for evaluation" for recommenders that cannot be evaluated

- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialogManager.java
- Switch some messages to the boot logger
* Start up application and check log
> #4304 - Log more startup messages through boot logger

- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentImportExportService.java
- inception/inception-external-editor/src/main/resources/META-INF/asciidoc/developer-guide/external-editor.adoc
- inception/inception-io-intertext/src/main/java/de/tudarmstadt/ukp/inception/io/intertext/IntertextFormatSupport.java
- inception/inception-io-xml/pom.xml
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/CustomXmlFormatFactory.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/CustomXmlFormatLoader.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/CustomXmlFormatPluginDescripion.java
- Ability to add custom XML formats similar to editor plugins - but just defining the content policy and CSS
* Still quite experimental - I'll document it eventually...
> #4308 - Support for custom XML formats

- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/StandardProjectInitializer.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectTemplateSelectionDialogPanel.html
- Make border of template cards darker
- Change title and description of the old standard project
> #4229 - Better project template selection

- pom.xml
> #4326 - Upgrade dependencies

- inception/inception-io-json/src/main/java/de/tudarmstadt/ukp/inception/io/jsoncas/UimaJsonCasFormatSupport.java
- inception/inception-io-json/src/main/resources/META-INF/asciidoc/user-guide/formats-uimajson.adoc
> #4335 - Promote UIMA JSON CAS 0.4.0 to non-experimental

- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.ts
- Remove spurious empty highlights
> #4338 - Spurious empty highlights in RecogitoJS editor

- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.css
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.properties
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTableSortKeys.java
> #4342 - Show document size in documents table

- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/ProjectSettingsExporter.java
- Set the current date if no dates are specified in the project export
> #4349 - Project has date in the 70ies if no data is set in JSON

- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/AnnotationResizeHandle.svelte
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditorFactory.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditorFactory.ts
- Always add the wrapper
- Adjust code for vertical selection highlight and resize handles to calculate their positions relative to the wrapper
* Try annotating HTML and other XML texts using RecogitoJS and Apache Annotator editor plugins
> #4351 - Always introduce wrapper element in Apache and Recogito

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectListSortState.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectListSortStrategy.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.properties
- Added sorting by update date
- Added icons to upload and new project buttons
* Try sorting by "recent update"
> #4353 - Ability to sort documents by update date

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/SuggestionExtraction.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplTest.java
> #4362 - Move suggestion extraction from RecommendationService into separate class

- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/exporters/SourceDocumentExporter.java
- inception/inception-documents/src/test/java/de/tudarmstadt/ukp/inception/documents/exporters/SourceDocumentExporterTest.java
- inception/inception-export-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExporter.java
- inception/inception-kb/pom.xml
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-schema/src/test/java/de/tudarmstadt/ukp/inception/schema/exporters/LayerExporterTest.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/io/FastIOUtils.java
- Use modern Java constructs
- Added test for SourceDocumentExporter
> #4360 - Clean up code

- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/PrimitiveUimaIndexingSupport.java
- Get feature value through feature support which returns null if the feature does not actually exist
> #4390 - Error when indexing multi-value string features

- inception/inception-brat-editor/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImplTest.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/UnreachableAnnotationsCheck.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/recommendation/MetadataSuggestionSupport.java
- inception/inception-pdf-editor/pom.xml
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/LearningRecordService.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/SuggestionSupport.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/SuggestionSupport_ImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/relation/RelationSuggestionSupport.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/SuggestionSupportRegistryImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/span/SpanSuggestionSupport.java
- inception/inception-recommendation/src/main/resources/META-INF/asciidoc/developer-guide/recommendation.adoc
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/relation/RelationSuggestionVisibilityCalculationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/WebAnnoCasUtil.java
- Fix suggestion registry class name
- Wrote a very few words of documentation
- Bit of cleaning
> #2696 - Document-level recommendations

- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/BioCFormatSupport.java
- Enable writer in format support
> #4395 - BioC export cannot be enabled

- inception/inception-external-search-pubmed/pom.xml
- inception/inception-external-search-pubmed/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubmed/pmcoa/PmcOaClient.java
- inception/inception-external-search-pubmed/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubmed/traits/PubMedProviderTraits.java
- inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/DocumentDetailsPage.java
- inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/ResultRowView.html
- inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.html
- Added better error message
- Slightly changed the looks of the external search page
* Try searching for a document which is not open access and then try opening it
> #4397 - Better error message when PMC document cannot be found

- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/OllamaRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/PredictionContext.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommenderContext.java
- Show the name
* Check the recommender log
> #4400 - Display recoomender name in log instead of RecommenderContext

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- Collect fresh suggestions in a list and only merge them with the actual reconciled suggestions shortly before returning the results
> #4404 - Some suggestions are not shown right away

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/exporter/OverlapIteratorTest.java
- Fix bug in the overlapiterator used when hiding suggestions
- Fix bug in the logic that decides to hide suggestions overlapping with annotations on non-stacking layers
> #4402 - Some suggestions are not hidden even though they cannot be accepted

- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
- inception/inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommenderTest.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngine.java
- Added test
- Fix evaluation when there is no label
* See issue
> #4408 - String Matching Recommender does not evaluate on annotations without label

- inception/inception-external-search-pubmed/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubmed/PubMedCentralProvider.java
- inception/inception-external-search-pubmed/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubmed/PubMedCentralProviderFactory.java
- inception/inception-external-search-pubmed/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubmed/traits/PubMedProviderTraitsEditor.html
- inception/inception-external-search-pubmed/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubmed/traits/PubMedProviderTraitsEditor.properties
- inception/inception-external-search-pubmed/src/main/resources/META-INF/asciidoc/user-guide/external-search-repos-pmc.adoc
- inception/inception-support-bootstrap/src/main/java/de/tudarmstadt/ukp/inception/bootstrap/BootstrapFeedbackPanel.js
- Change the filter
- Add note to the documentation and UI about open access
- Fix issue in feedback panel that it would also auto-hide alerts outside the panel
* Check documentation
> #4412 - PMC search returns some results that cannot be imported

- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception/inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderTest.java
- Learn from unlabelled annotations
* See issue
> #4410 - OpenNLP multi-token sequence classifier does not learn from annotations without labels

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
- Stop iterating over the B list when the offsets there start to have gone beyond the end of the current A.
> #4421 - Improve performance of the overlap iterator

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- Do not show message when tag is blank
* Try annotating something with a feature that has a tagset
> #4423 - Popover always showing "tag not in tagset" even if tag is in tagset

- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/OllamaRecommenderTraitsEditor.properties
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/jinjava/AnnotationWrapper.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/jinjava/CasWrapper.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/prompt/PerAnnotationContextGenerator.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/prompt/PerDocumentContextGenerator.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/prompt/PerSentenceContextGenerator.java
- inception/inception-imls-ollama/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_ollama.adoc
- inception/inception-imls-ollama/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/presets.yaml
- inception/inception-imls-ollama/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/jinjava/CasWrapperTest.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.html
- Allow accessing annotations from the CAS in the prompt template
- Added some documentation
* Try out the recommender
> #4292 - ollama-based recommender

- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/SpringAuthenticatedWebSession.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.java
- Delegate loging out of Spring Security to the actual logout handlers used by the Spring Security LogoutFilter
> #4439 - Logout may sometimes be incomplete

- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/CasDoctor.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/WicketUtil.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- Buffer the headers and commit them only at the end of the request
- Avoid generating a timer header in CasDoctor if no checks are enabled
> #4438 - Buffer server side timing headers

- inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceControllerImplTest.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityProperties.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityPropertiesImpl.java
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-authentication-policy.adoc
- inception/inception-security/src/test/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImplTest.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- Added option
* Try enabling the option and creating a user with a space in their name
> #4442 - Option to allow spaces in usernames

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/settings_security-policy.adoc
- Move authentication to a top-level section in the sidebar
* Check documentation
> #4444 - Make authentication settings more prominent in admin manual

- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/FeatureSupport.java
- inception/inception-search-core/pom.xml
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/PrimitiveUimaIndexingSupport.java
- inception/inception-search-core/src/test/java/de/tudarmstadt/ukp/inception/search/PrimitiveUimaIndexingSupportTest.java
- Fixed indexing
- Added tests
> #4448 - Error when trying to index boolean feature values when CAS has not upgraded yet

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/processor/BulkProcessingPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/BulkPredictionTask.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/Task.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/TaskScope.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/controller/SchedulerController.java
- inception/inception-ui-scheduling/src/main/java/de/tudarmstadt/ukp/inception/ui/scheduling/TaskMonitorFooterItem.java
- inception/inception-ui-scheduling/src/main/java/de/tudarmstadt/ukp/inception/ui/scheduling/TaskMonitorPanel.java
- inception/inception-ui-scheduling/src/main/java/de/tudarmstadt/ukp/inception/ui/scheduling/controller/SchedulerControllerImpl.java
- inception/inception-ui-scheduling/src/main/ts/src/TaskMonitorPanel.svelte
- Set the task scope to PROJECT
- Validate additional mandatory properties of the bulk prediction process
- Set the project in the bulk prediction task
* Log in
* Start a longer running bulk recommender process
* Log out
* Log back in
* Check if the process still runs
> #4452 - Keep recommender process running when user logs out

- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/strategy/DefaultMergeStrategy.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/strategy/MergeIncompleteStrategy.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- When determining agreement, completeness, etc, the CURATION_USER must not be considered
* Experiment with different annotations on the curation page
> #4458 - Fully agreeing annotations shown as disagreement in overview sidebar

- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandle.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBObject.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptTreePanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptTreeProvider.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.properties
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/local/LocalRepositorySettingsPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/remote/RemoteRepositorySettingsPanel.java
- Expand tree and scroll to class if possible when a class is selected
- Cleaning up and modernizing code a bit
> #4461 - Show class in class tree when selecting a class

- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/local/LocalRepositorySettingsPanel.java
- Added the profile
* Try creating a local KB using the profile
> #4466 - Add SNOMED CT knowledge base profile

- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/markdown/MarkdownUtil.java
- Adjust the markdown handling to allow links with standard protocols and the decorate these links.
* Add external links in markdown fields, e.g. project description
> #4465 - Mark external links from markdown sources and open them in new window

- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
- Set the confirm action before showing the dialog to make sure it takes effect
> #4473 - Deleting feature only works the second time

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/config/ExternalEditorPropertiesImpl.java
- Introduce setters for these configuration properties so they can be set from the settings.properties file
* Try setting the properties in the settings.properties file.
> #4478 - Some external editor configuration properties cannot be configured

- inception/inception-ui-scheduling/src/main/java/de/tudarmstadt/ukp/inception/ui/scheduling/controller/SchedulerControllerImpl.java
- Check if user is null before calling a method on it
> #4482 - Error when fetching state of background tasks from UI

- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/validation/ValidationUtils.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.html
- Generate error comment for required features for "virtual" features as well
> #4484 - Error marker on annotations with required concept feature is missing

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/config/ExternalEditorPropertiesImpl.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/config/Source.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/SafetyNetDocumentPolicy.java
- inception/inception-io-html/src/main/resources/META-INF/asciidoc/user-guide/formats-mhtml.adoc
- inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandlerTest.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
- Better control over blocking/allowing images in the safety net
- Fix scrollbar breaking out of container on project overview page
* Enable MHTML as described in the documentation
* Import a MHTML document with images (embedded images should render)
* Import a normal HTML file with external image references (images should render as placeholders - maybe suboptimal...)
> #4469 - Support for MHTML web page archives

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- Improve styling of concept feature editor
* Use the concept feature editor
> #4379 - Suppress or mark concepts in the search that are marked as owl:deprecated

- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectAccess.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectAccessImpl.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/SanitizingHtmlLabel.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/WicketUtil.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.properties
- Open the "new project" dialog if user can create projects but does not have any yet
* Log in to an account that can create projects but has none yet -> dialog
* Log in to an account that cannot create projects but has none yet -> no dialog
* Log in to an account that can create projects and has projects already -> no dialog
> #4493 - Present project templates to new users who do not have a project yet

- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/validation/ValidationUtils.java
- Fix displaying validation comments in the brat editor
- Fix validation of required multi-value string/concept features
> #4495 - Error marker on annotations with required multi-value features is missing

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/link/LinkFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/link/LinkFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationAdapter.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupServiceImpl.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/relation/StringMatchingRelationRecommender.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommenderTypeSystemUtils.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/SuggestionSupport.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/ArcPosition_ImplBase.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/ArcSuggestion_ImplBase.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/LinkPosition.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/LinkSuggestion.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/link/LinkSuggestionRenderer.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/link/LinkSuggestionSupport.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/relation/ArcSuggestionRenderer_ImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/relation/ArcSuggestionSupport_ImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/relation/RelationSuggestionSupport.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/link/LinkSuggestionExtractionTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/link/LinkSuggestionVisibilityCalculationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/relation/RelationSuggestionVisibilityCalculationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/Fixtures.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/adapter/TypeAdapter.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/LinkWithRoleModel.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- Allow recommenders to generate suggestions for link features
* Set up a project with a `webanno.custom.Arg` layer
* Set up a project with a `webanno.custom.Span` layer
* Add a link feature from Span to Arg
* Set up an external recommender with the following predict function
```
def predict(self, cas: Cas, layer: str, feature: str, project_id: str, document_id: str, user_id: str):
Sentence = cas.typesystem.get_type("de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Sentence")
LinkHost = cas.typesystem.get_type(layer)
LinkType = cas.typesystem.get_type(layer+"ArgsLink")
SlotFiller = cas.typesystem.get_type("webanno.custom.Arg")
FSArray = cas.typesystem.get_type(TYPE_NAME_FS_ARRAY)
canidateHosts = cas.select(LinkHost)
for …
```
> #4491 - Support for link feature recommendations

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_azure.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database_mariadb.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database_mysql.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_java.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_kubernetes.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_cas-storage.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/common/systemrequirements.adoc
- Add Azure tips
- Better structure MySQL tips
- Update MariaDB setup
- Update system requirements
* Read docs
> #4499 - Tips for deployment on Azure

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/export/ExportDocumentDialogContent.java
- inception/inception-app-webapp/pom.xml
- inception/inception-bom/pom.xml
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/formats.adoc
- inception/inception-export-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/DocumentImportExportService.java
- inception/inception-io-brat/LICENSE.txt
- inception/inception-io-brat/pom.xml
- inception/inception-io-brat/src/main/java/de/tudarmstadt/ukp/inception/io/brat/BratFormatSupport.java
- inception/inception-io-brat/src/main/java/de/tudarmstadt/ukp/inception/io/brat/config/BratAutoConfiguration.java
- inception/inception-io-brat/src/main/resources/META-INF/asciidoc/user-guide/formats-brat.adoc
- inception/inception-io-brat/src/main/resources/META-INF/spring.factories
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/settings/FormatDropdownChoice.java
- inception/installEclipseSettings.sh
- inception/pom.xml
- Added experimental brat export
* Enable the experimental format in the `settings.properties` file
* Try exporting one of your annotated documents using the format
> #4498 - Support exporting in brat format

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectTemplateSelectionDialogPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/SparqlPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/SparqlPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/TupleQueryResultDataProvider.java
- Added SPARQL query UI
* Activate developer mode
* Access knowledge-base page of a project
* Click the SPARQL button
* Run a query
> #4503 - SPARQL query UI for developers

- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
- Change HPO URL to one that always has the latest version
* Create KB using HPO profile
> #4509 - Download the latest HPO version when creating a local HPO knowledge-base

- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseIriPanel.html
- Use simple, non-classified HPO
- Add icons to the KB mapping settings
* Set up an HPO KB from the local profile
> #4511 - Improve HPO knowledge base profile

- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/FeatureType.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
- Generate proper UI name for scoped features
> #4518 - Wrong feature type shown in dropdown when scope is set in concept feature settings

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningServiceImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/bool/BooleanFeatureSupport.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommenderFactory.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/settings/StringMatchingRecommenderTraitsEditor.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/span/SpanSuggestionSupport.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/FeatureUtil.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/ICasUtil.java
- Boolean features now seem to work in String Matching recommender and Active Learning Sidebar
* Try configuring a string matcher recommender for a boolean feature
* Use the recommender normally and with active learning
> #4525 - Support recommendations for non-string primitive features

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningServiceImpl.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/keybindings/KeyBindingsPanel.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/RadioGroupStringFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/RadioGroupStringFeatureEditor.java
- Display key bindings in the radio group editor
- Hide the key bindings toggle below it
* Try using the radio group string feature editor with key bindings
> #4528 - Display key bindings in radio group string feature editor

- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/DiamSidebarFactoryUserPreferences.schema.json
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLayerList.svelte
- inception/inception-diam-editor/src/main/ts/src/DiamAnnotationBrowser.svelte
- inception/inception-diam-editor/src/main/ts/src/Utils.ts
- Add by-layer grouping mode
* Try grouping annotations by layer in the annotation sidebar
> #4537 - Ability to group annotations by layer

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AbstractInfoPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/IriInfoBadge.html
- Fix input group
- Slightly improve layout in general
> #4543 - UI for creating new concept or properties has broken layout

- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-dependencies/pom.xml
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-scheduling/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- pom.xml
- commons-logging 1.2 -> 1.3.0
- javassist 3.29.2 -> 3.30.2
- commons-compress 1.25.0 -> 1.26.0
- commons-validator 1.7 -> 1.8.0
- mockito 5.7.0 -> 5.10.0
- log4j2 2.22.1 -> 2.23.0
- postgres 42.6.1 -> 42.7.2
- okio 3.6.0 -> 3.8.0
- bootstrap 5.3.2 -> 5.3.3
> #4545 - Upgrade dependencies

- inception/inception-pdf-editor2/src/main/ts/src/PdfAnnotationEditor.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/model/AbstractAnnotation.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/model/RelationAnnotation.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/model/SpanAnnotation.ts
- Added support for context menu in PDF editor
> #4547 - Cannot create long-distance relation in PDF editor

- inception/inception-brat-editor/src/main/ts/src/dispatcher/Dispatcher.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer_ui/VisualizerUI.ts
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporterTest.java
- inception/inception-export/pom.xml
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/JsonImportUtil.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/LayerImportExportUtils.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/TagsetImportExportUtils.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/config/DocumentImportExportServiceAutoConfiguration.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/ProjectLogExporter.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/ProjectMetaInfExporter.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/ProjectSettingsExporter.java
- inception/inception-export/src/test/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImplTest.java
- inception/inception-export/src/test/java/de/tudarmstadt/ukp/inception/export/SegmentationUtilsTest.java
- inception/inception-export/src/test/java/de/tudarmstadt/ukp/inception/export/exporters/ProjectPermissionsExporterTest.java
- inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/AnnotationDocumentsExporterTest.java
- inception/inception-ui-kb/pom.xml
- Clean up code in the document export module
- Remove unused and deprecated old brat comment popup code
> #4550 - Clean up code

- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
- Add recommendation to use ELK to generate missing statements and to enable the read-only mode
* Try the described approach
> #4560 - Describe how to use ELK to process Snomed before import

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database_mariadb.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose-mysql8.yml
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose.yml
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/upgrade_backup.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/common/systemrequirements.adoc
- Improve backup documentation
- Update system requirements description
- Update MariaDB and MySQL version in Docker compose files
- Replace mentions of mysql with mariadb where possible
* Try following the guides and report any problems
> #4565 - Improve system-level backup documentation

- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkPredictionTask.java
- Move processing data code into its own method
> #4576 - Allow setting a document-level annotation when bulk processing

- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/LayerExporter.java
- Include this setting when importing/exporting annotation features
* Enable the setting on a feature
* Export project
* Import project
* Check if setting is still enabled in the new project
> #4569 - Feature visibility on hover not exported correctly

- inception/inception-dependencies/pom.xml
> #4541 - Upgrade dependencies

- inception/inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/PubAnnotationProvider.java
- inception/inception-external-search-pubmed/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubmed/PubMedCentralProvider.java
- inception/inception-external-search-pubmed/src/test/java/de/tudarmstadt/ukp/inception/externalsearch/pubmed/PubMedProviderTest.java
- inception/inception-external-search-pubmed/src/test/java/de/tudarmstadt/ukp/inception/externalsearch/pubmed/pmcoa/PmcOaClientTest.java
- Re-enable tests
* Just run the tests in the pubmed module
> #4556 - Unable to access PMC BioC service

- inception/inception-annotation-storage-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasStorageService.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasStorageServiceImpl.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/driver/CasStorageDriver.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/driver/filesystem/FileSystemCasStorageDriver.java
- inception/inception-documents-api/src/main/java/de/tudarmstadt/ukp/inception/documents/api/DocumentService.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.css
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.properties
- Added CAS size column
* See documents table in project settings
> #4591 - Display size of initial CAS in document table

- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/model/KnowledgeBase.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseExporterTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplImportExportIntegrationTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor_ImplBase.java
- Run the three queries in parallel using the default worker pool
- Bit of cleaning up stuff
* Try linking stuff to knowledge bases
> #4611 - Run the three SPARQL queries in the concept linker in parallel

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- Fix lazy details for concept feature suggestions
* Configure a recommender on a concept feature
* Hover with the moues over a suggestions to check if label and description appear
> #4554 - Allow displaying comments from annotators on hover when curating using curation sidebar on the annotation page

- .gitattributes
- .github/workflows/maven.yml
- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/test/java/de/tudarmstadt/ukp/inception/InceptionRemoteApiJwtIntegrationTest.java
- inception/inception-curation/pom.xml
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationDocumentService.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/MoveSpanAnnotationHandler.java
- inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController_ViewportRoutingTest.java
- inception/inception-documents-api/src/main/java/de/tudarmstadt/ukp/inception/documents/api/DocumentService.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/FullTextIndexUpgradeTest.java
- inception/inception-log/pom.xml
- inception/inception-pdf-editor2/src/test/java/de/tudarmstadt/ukp/inception/pdfeditor2/format/VisualPdfReaderTest.java
- inception/inception-project-api/pom.xml
- inception/inception-project-api/src/main/java/de/tudarmstadt/ukp/inception/project/api/ProjectService.java
- inception/inception-schema-api/pom.xml
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/AnnotationSchemaService.java
- Save editor CAS after a resize action
> #4618 - Resizing a span does not update annotations on disk

- inception/inception-imls-azureai-openai/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/imls/azureaiopenai/presets.yaml
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/response/MentionsFromJsonExtractor.java
- inception/inception-imls-ollama/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/presets.yaml
- inception/inception-imls-ollama/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/response/MentionsFromJsonExtractorTest.java
- Improve sampling
- Fix extraction of mentions when there is no label at all
- improve presets
* Try using Ollama or Azure AI for few shot learning - in particular using spans without labels
> #4628 - Better results when using unlabelled annotations for few-shot learning

- inception/inception-documents-api/pom.xml
- inception/inception-documents-api/src/main/java/de/tudarmstadt/ukp/inception/documents/api/DocumentService.java
- inception/inception-documents-api/src/main/java/de/tudarmstadt/ukp/inception/documents/api/DocumentStorageService.java
- inception/inception-documents/pom.xml
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentStorageServiceImpl.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/config/DocumentServiceAutoConfiguration.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/exporters/SourceDocumentExporter.java
- inception/inception-documents/src/test/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImplConcurrencyTest.java
- inception/inception-documents/src/test/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImplTest.java
- inception/inception-documents/src/test/java/de/tudarmstadt/ukp/inception/documents/exporters/SourceDocumentExporterTest.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfDocumentIFrameView.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/view/PdfDocumentIFrameView.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTableExportActionColumn.java
> #4634 - Pull document file storage code out of document service into a new service

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLayerList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByPositionList.svelte
- inception/inception-diam-editor/src/main/ts/src/DiamAnnotationBrowser.svelte
- inception/inception-diam-editor/src/main/ts/src/Utils.ts
- Added filtering to all three annotation sidebar modes
* Use the filtering functionality
> #4638 - Ability to filter annotation sidebar by covered text

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/keybindings/KeyBindingsConfigurationPanel.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupServiceImpl.java
- inception/inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/DocumentAnnotationPanel.java
- inception/inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/SpanAnnotationPanel.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/rendering/Renderer.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementPage.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/StatisticsAnnotationSidebar.java
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.java
- Handle several missing FeatureSupport more gracefully in various places
> #4647 - Better handling of unsupported annotation feature types

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/upgrade_notes.adoc
- inception/inception-docker/src/main/docker/Dockerfile
- Introduced APP_ARGS and JAVA_MEM_OPTS
- Added note to upgrade guide
* Try overriding memory settings using `JAVA_MEM_OPTS`
* Try adding e.g. `--help` to `APP_ARGS`
> #4652 - Ability to specify INCEpTION command line arguments when using docker

- inception/inception-diam-editor/pom.xml
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/DiamAnnotationBrowser.java
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/DiamSidebar.html
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/DiamSidebar.java
- inception/inception-diam-editor/src/main/ts/src/DiamAnnotationBrowser.svelte
- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- inception/inception-diam/pom.xml
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/ShowContextMenuHandler.java
- inception/inception-external-editor/pom.xml
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditorBase.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- Added right-click menu to annotation sidebar
* Select a span annotation in the annotation sidebar (e.g. using the crosshairs button)
* Right-click on another cross-hairs button and select **Link to...**
> #4657 - Allow creating long-distance relations between spans in the annotation sidebar

- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/markdown/MarkdownUtil.java
- inception/inception-ui-dashboard/pom.xml
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/admin/dashlet/ClientUrlAjaxBehavior.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/admin/dashlet/SystemStatusDashlet.html
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/admin/dashlet/SystemStatusDashlet.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/admin/dashlet/SystemStatusDashlet.properties
- Move most details to the developer mode
- Added a kind of checklist for reverse proxy settings
- Filter anonymous sessions from the active users list
- Add "anonymousUser" to the reserved user names
* Run behind a reverse proxy and see if you see any problems on the admin page
> #4645 - Self-help info for reverse proxy problems

- inception/inception-imls-stringmatch/pom.xml
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/relation/StringMatchingRelationRecommenderFactory.java
- inception/inception-project-initializers-basic/pom.xml
- inception/inception-project-initializers-basic/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/basic/BasicRelationLayerInitializer.java
- inception/inception-project-initializers-basic/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/basic/BasicRelationRecommenderInitializer.java
- inception/inception-project-initializers-basic/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/basic/BasicSpanLayerInitializer.java
- Make basic span and relation layers cross-sentence by default
* Create a new project using the "Basic annotation" template and try annotating stuff
* See if the recommenders work
> #4671 - Make basic relation layer be cross-sentence by default

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/open/AnnotationDocumentTable.html
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/open/AnnotationDocumentTable.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/open/AnnotationDocumentTable.properties
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/open/AnnotationDocumentTableDataProvider.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/actionbar/opendocument/CurationDocumentTable.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/actionbar/opendocument/CurationDocumentTable.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/actionbar/opendocument/CurationDocumentTable.properties
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/actionbar/opendocument/CurationDocumentTableDataProvider.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/actionbar/opendocument/CurationDocumentTableSortKeys.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTableDataProvider.java
- Added "updated" and "created" columns to the open document dialog on the curation and annotation pages
- Fix NPE when sorting documents by date in the documents panel of the project settings if a document has no date
* Check if the columns are there and sort by them
> #4667 - Ordering documents to annotate

- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIBuiltInAutoConfiguration.java
- Remove extra slash in Spring Security rule
> #4685 - Invite links lead to standard login page instead of the join-project page

- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatMetadataRecommenderFactory.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderFactory.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTraitsEditor.java
- Add support for boolean features to the doccat recommender
- Fix issue editing the traits of the doccat recommender
* Configure a doccat recommender for a boolean feature sentence-level layer (or document-metadata layer)
* Make some annotations and check if the recommender kicks in
> #4525 - Support recommendations for boolean features

- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDao.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/InitialAccountCreationPanel.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/InitialAccountCreationPanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LocalLoginPanel.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LocalLoginPanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.properties
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/Saml2LoginPanel.java
- Instead creating a default account admin account with a default password, force the user to set an admin password on the first login
* Run a fresh installation without any accounts, set password, log in
* Run with account recovery mode
> #4165 - Error when creating default account

- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-export-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/DocumentImportExportService.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditor.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditorBase.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/config/ExternalEditorLoader.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/config/ExternalEditorPluginDescripion.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/model/AnnotationEditorProperties.java
- inception/inception-html-apache-annotator-editor/pom.xml
- inception/inception-html-apache-annotator-editor/src/main/java/de/tudarmstadt/ukp/inception/apacheannotatoreditor/ApacheAnnotatorHtmlAnnotationEditor.java
- inception/inception-html-apache-annotator-editor/src/main/java/de/tudarmstadt/ukp/inception/apacheannotatoreditor/ApacheAnnotatorHtmlAnnotationEditorFactoryUserPreferences.schema.json
- inception/inception-html-apache-annotator-editor/src/main/ts/esbuild-runner.config.js
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.scss
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditorFactory.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorState.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorToolbar.svelte
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/SectionAnnotationCreator.scss
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/SectionAnnotationCreator.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/SectionAnnotationVisualizer.scss
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/SectionAnnotationVisualizer.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/main.ts
- inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/MHtmlFormatSupport.java
- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/TeiXmlDocumentFormatSupport.java
- inception/inception-io-tei/src/main/ts/src/TeiXmlDocument.scss
- inception/inception-io-tei/src/main/ts/src/layout.scss
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/CustomXmlFormatFactory.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/CustomXmlFormatPluginDescripion.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.properties
- Add infrastructure for section-level label summaries
- Define section elements for TEI and MHTML
* Import a TEI or MHTML document
* Enable section labels in the toolbar
* Annotate something
> #4693 - Display annotation labels per section

- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/webanno.js
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.html
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/support/AnnotationStateList.java
- Fix assign document dropdown in dynamic workload mode by also not considering clicks in Kendo popups with regards to closing Bootstrap popups
- Fix layout of the dropdown
- Bit of modernizing
* See issue
> #3441 - Assigning a document to an annotator in dynamic mode

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AdditionalMatchingPropertiesPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.properties
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/RootConceptsPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/local/LocalRepositorySettingsPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/local/LocalRepositorySettingsPanel.java
> #4697 - Remove clear button from knowledge base project settings

- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
> #4707 - Proper query for existsCurationDocument

- inception/inception-agreement/pom.xml
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/PerDocumentAgreementResult.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/perdoc/PerDocumentAgreementTable.html
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/perdoc/PerDocumentAgreementTable.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/perdoc/PerDocumentAgreementTable.properties
- Added summary statistics
* Use per-document agreement calculation
> #4704 - Per-document agreement across all annotators

- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/TeiXmlDocumentPolicy.yaml
- inception/inception-io-tei/src/main/ts/src/TeiXmlDocument.scss
- inception/inception-io-tei/src/main/ts/src/linguistic-teitok.scss
- inception/inception-io-tei/src/main/ts/src/typography.scss
- Added more styling to support TEITOK a bit better
* Import TEI files from http://teitok.clul.ul.pt/teitok/cta/index.php?action=textos
> #4716 - Improve TEI styling for documents following TEITOK

- inception/inception-constraints/src/main/resources/META-INF/asciidoc/user-guide/constraints.adoc
- Added relation example
* Read the example and try to understand
> #4720 - Document how to define a constraint on a relation layer

- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/DeleteAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/SelectAnnotationHandler.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- Select accepted recommendation to it opens in the detail panel
> #4724 - When accepting a suggestion the resulting should be opened in the detail panel but is not

- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/LearningRecordService.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/exporter/LearningRecordExporter.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/exporter/LearningRecordExporterTest.java
- Batched import for learning records
> #4730 - Reduce time to import for projects with many learning records

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.java
- Changed the icons for curation and annotation to match the respective target state icon that is reached when the icon is clicked
> #2675 - Make finish document use a checkmark instead of a lock

- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditorFactory.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/SectionAnnotationVisualizer.ts
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts/src/widget/AnnotationDetailPopOver.svelte
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-scheduling/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- Change the import for bootstrap
- Update package-lock files
> #4747 - Cannot re-use AnnotationDetailPopOver in downstream code

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/filters/SourceDocumentStateFilterPanel.java
- Moved setOuptuMarkupId to the right constructor
* See issue
> #4738 - Filtering documents on open in curation mode

- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateRelationAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/DeleteAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/ExtensionActionHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/FillSlotWithExistingAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/FillSlotWithNewAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/MoveSpanAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/ShowContextMenuHandler.java
- Check if page is editable directly when the change request is recieved
> #4756 - Annotation can almost be resized despite document being finished

- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsIndexedCheckTest.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.css
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.java
> #4766 - Add ID column to documents table in dev mode

- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
- inception/inception-diag/pom.xml
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsStartAndEndWithCharactersCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorAutoConfiguration.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/TrimAnnotationsRepair.java
- inception/inception-diag/src/main/resources/META-INF/asciidoc/user-guide/casdoctor.adoc
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/Task.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- inception/inception-ui-project/pom.xml
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/CasDoctorTask_ImplBase.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/CheckTask.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/LogMessageSet.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/RepairTask.java
- Added repair
- No longer force-enable server-side timings in dev mode
- Show progress of checks and repairs in task tray
* Run checks / repairs
> #4772 - Repair to trim whitespace off annotations

- pom.xml
> #4785 - Upgrade dependencies

- inception/inception-brat-editor/src/main/ts/src/BratEditor.ts
- inception/inception-brat-editor/src/main/ts/src/annotator_ui/AnnotatorUI.ts
- inception/inception-brat-editor/src/main/ts/src/dispatcher/Dispatcher.ts
- inception/inception-brat-editor/src/main/ts/src/util/Util.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- inception/inception-ui-scheduling/src/main/ts/src/TaskMonitorPanel.svelte
- Fix issue by no considering a right-click to be the start of a selection action
- Comment out / remove several JS logging statements
- Fix error when turning on brat profiling due to imbalanced profileStart/profileEnd calls
> #4799 - Relation only becomes visible when mouse is moved in brat editor

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
- Only show accessible features in the dropdown
> #4802 - Source and target features should not be selectable on a relation recommender

- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneUserInterface.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/logging/RingBufferAppender.java
- inception/inception-ui-core/pom.xml
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/log/LogPage.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/log/LogPage.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/log/LogPage.properties
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/log/LogPageMenuItem.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectPageMenuItem.java
- Added log page
* Use the log page
> #4805 - Log page for administrators

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- inception/inception-diam-editor/pom.xml
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/DiamAnnotationBrowser.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateRelationAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/EditorAjaxRequestHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/ShowContextMenuHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/config/DiamAutoConfig.java
- inception/inception-diam/src/main/ts/src/diam/DiamAjaxImpl.ts
- inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandlerTest.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditorBase.java
- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.ts
- inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderSslTest.java
- inception/inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTest.java
- inception/inception-pdf-editor2/src/main/ts/src/PdfAnnotationEditor.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/relation.ts
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookServiceTest.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/editor/action/AnnotationActionHandler.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/ContextMenu.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/LayerSelectionPanel.java
- Allow creating relations in PDF editor if even if there is a need to show a diambiguation popup asking which relationt to create
- Allow creating relations in recogito editor if even if there is a need to show a diambiguation popup asking which relationt to create
- Allow creating relations via annotation sidebar if even if there is a need to show a diambiguation popup asking which relationt to create
- Remove "Whoops - multiple layers" message from annotation sidebar if a span layer is selected that allows for multiple relation layers
* Use cross-layer relations in different editors and via the link-to context menu in the annotation sidebar as well as in editors
> #1319 - Cross-Layer Relations

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/RadioGroupStringFeatureEditor.java
- inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderSslTest.java
- inception/inception-pdf-editor/src/main/ts/pdfjs-web/viewer.html
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/view/pdfjs/PdfJsViewerPage.java
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookServiceTest.java
- Render tags in bold when constraint
> #4815 - Constraint tags are not rendered in bold in radio-group string feature editor

- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
- Add instruction on converting the RD2 data to OWL
> #4813 - SNOMED-CT instructions miss conversion step from RD2 to OWL

- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowDocumentNavigationActionBarExtension.java
- Cancel endless recursion between by not setting/loading the document again if the document loaded in the editor is already the document selected by the dynamic workload manager
* Set project workload mode to dynamic
* Log in as a user who is an annotator only (not manager or curator)
* Access the annotation page
> #4819 - Error when opening annotation page as annotator in dynamic workflow mode

- inception/inception-app-webapp/src/main/resources/application.yml
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
> #4824 - Project users in project settings not sorted by name

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/admin/dashlet/SystemStatusDashlet.html
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/admin/dashlet/SystemStatusDashlet.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/admin/dashlet/SystemStatusDashlet.properties
- Show more info, in particular in dev mode
* Run INCEpTION behind reverse proxy
* Enable dev mode
* Access administration page
> #4832 - Improve self-help for reverse proxies

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/NopRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanCrossSentenceBehavior.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanLayerBehavior.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanOverlapBehavior.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRendererTest.java
- inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRendererTest.java
- inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/AnnotationEditorBase.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/request/RenderRequest.java
- inception/inception-brat-editor/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImplTest.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/span/SpanDiffAdapter.java
- inception/inception-diam-compactv2/src/test/java/de/tudarmstadt/ukp/inception/diam/model/compactv2/CompactSerializerV2ImplTest.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LoadAnnotationsHandler.java
- inception/inception-diam/src/main/ts/src/diam/DiamAjaxImpl.ts
- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.ts
- inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VArc.java
- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VDocument.java
- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VSpan.java
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.ts
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/rendering/Renderer.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRenderer.java
- Make it work for link features
> #4809 - Connecting annotation and entity with arc over different pages

- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/Configuration.java
- Extras should be stored per groupId
> #4835 - Error when trying to open certain documents with stacked annotations for curation

- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
- Control the JUL bridge using a property separate from the dev mode property
* Enable dev mode and try connecting to the INCEpTION VM using VisualVM
> #4846 - Control JUL bridge using a dedicated property

- pom.xml
- wicket 9.17.0 -> 9.18.0
- wicketstuff 9.17.0 -> 9.18.0
- wicket-jquery 9.12.0 -> 9.18.0
> #4854 - Upgrade dependencies

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationEditorExtension.java
- Look up lazy details based on the diff configuration representative instead of the curation CAS/VID
> #4853 - Detail popover on curation suggestions does not show lazy details when using sidebar curation mode

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- Remove document from disk before writing the re-merged version to avoid timestamp conflicts
* See issue
> #4869 - Cannot re-merge curation document

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/BrowseKnowledgeBaseDialogContentPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureEditor.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureEditor.java
- Added the browser to the multi-value editor
- Move the browser button to the label line
* Try the browser in the multi-value editor
> #4875 - Add knowledge-base browser to multi-value concept feature editor

- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts/audit-resolve.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package.json
- inception/inception-pdf-editor2/src/main/ts/audit-resolve.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-scheduling/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- inception/update-package-lock.sh
- Update package-lock.json files
- Switch to different audit package since we have to ignore pdfjs during audits for the time being
> #4880 - Upgrade dependencies

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRenderer.java
- Skip over non-text-level annotations while rendering
> #4891 - Exception in sidebar curation mode when document-level annotations exist

- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- Also index curator data when re-indexing the proejct
> #4911 - No results when searching as curator after re-indexing project

- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionApplicationContextInitializer.java
- inception/inception-app-webapp/src/test/java/de/tudarmstadt/ukp/inception/db/InceptionMySql_8_4_IntegrationTest.java
- inception/inception-dependencies/pom.xml
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/db/InceptionMySQLDialect.java
- pom.xml
- Added custom dialect for MySQL connections and apply necessary settings during application startup
- Added integration test
> #4915 - Support for MySQL 8

- inception/inception-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/ConstraintsServiceImpl.java
- inception/inception-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/model/ParsedConstraints.java
- inception/inception-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/model/Scope.java
- inception/inception-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/ConstraintsServiceImplTest.java
- Fixed merging
- Added test
* Try working with rules distributed over multiple rule sets using one scope per rule set
> #4921 - Constraints do not work properly when rules are distributed over multiple rulesets

- inception/inception-export-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExporter.java
- inception/inception-export-api/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExporterTest.java
> #4919 - Unable to import project with knowledge-based exported by INCEpTION 33.0 (again)

- .github/workflows/maven.yml
- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionApplicationContextInitializer.java
- inception/inception-app-webapp/src/main/resources/log4j2-spring.xml
- inception/inception-app-webapp/src/test/java/de/tudarmstadt/ukp/inception/db/InceptionMSSQLServerIntegrationTest.java
- inception/inception-curation/src/main/resources/de/tudarmstadt/ukp/inception/curation/db-changelog.xml
- inception/inception-dependencies/pom.xml
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
- inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
- inception/inception-preferences/src/main/resources/de/tudarmstadt/ukp/inception/preferences/model/db-changelog.xml
- inception/inception-recommendation-api/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/model/db-changelog.xml
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java
- inception/inception-sharing/src/main/resources/de/tudarmstadt/ukp/inception/sharing/model/db-changelog.xml
- inception/inception-workload/src/main/resources/de/tudarmstadt/ukp/inception/workload/model/db-changelog.xml
- pom.xml
- Added MS SQL Server JDBC driver
- Added integration test
> #4916 - Support for MS SQL Server

- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/Offsets.java
- inception/inception-brat-editor/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImplStaticsTest.java
- inception/inception-brat-editor/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImplTest.java
- Fix splitting annotations over multiple rows
**Screenshot**
> #4935 - Incorrect repetitions of sentences

- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureTestSuite_ImplBase.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/DiffResult.java
- inception/inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiffTest.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/ThresholdBasedMergeStrategyTraitsEditor.html
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/strategy/DefaultMergeStrategy.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/strategy/MergeIncompleteStrategy.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/strategy/ThresholdBasedMergeStrategy.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkTest.java
- inception/inception-ui-curation/src/main/resources/META-INF/asciidoc/user-guide/curation.adoc
- Added parameter descriptions to the dialog
- Improved merge documentation
- Improved unit tests for CasDiff
> #4950 - Display helpful information in the dialog for the threshold-based merge strategey

- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/TaskMonitor.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
> #4964 - Flash message shown when trying to query during index rebuild shows wrong progress

- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/SpringAuthenticatedWebSession.java
- Fix login using external Keycloak / OAuth / SAML
* Try logging in using OAuth / Keycloack
> #3611 - Upgrade to Spring 6, Boot 3, Wicket 10, etc.

- inception/inception-io-imscwb/pom.xml
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/ImageExtractor.java
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfextract/PDFExtractor.java
- inception/inception-pdf-editor2/pom.xml
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/format/VisualPdfReader.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/view/PdfDocumentIFrameView.java
- inception/inception-pdf-editor2/src/test/java/de/tudarmstadt/ukp/inception/pdfeditor2/format/VisualPdfReaderTest.java
- inception/inception-pdf-editor2/src/test/java/de/tudarmstadt/ukp/inception/pdfeditor2/visual/VisualPDFTextStripperTest.java
- pom.xml
- pdfbox 2.0.30 -> 3.0.2
- jsoup 1.16.1 -> 1.18.1
> #1571 - Upgrade dependencies

- .gitignore
- inception/inception-dependencies/pom.xml
- inception/inception-security/pom.xml
- pom.xml
> #4909 - Upgrade dependencies

- .gitignore
- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/pre-defined-knowledge-bases/wine.rdf
- Added labels for all properties
- Added nicer labels for classes
> #4978 - Properties in the example wine ontology do not appear in concept feature editor

- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.java
- Catch exceptions and render "error" in the size column of the respective document
> #4992 - Cannot access document panel anymore if a source document has gone missing

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainRenderer.java
> #4999 - Chain layers not rendered

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/UndoPanel.java
- Catch exception if undo is not supported and ignore it
> #5001 - Error when trying to delete a chain layer element

- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasKey.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatMetadataRecommenderFactory.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderFactory.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderFactory.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/gazeteer/GazeteerServiceImpl.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/gazeteer/model/GazeteerEntry.java
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/tagset/TagSetExtractionTask.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/RecommenderGeneralSettings.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.properties
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- Added export option for the OpenNLP models
- Added option to hide export option for annotators
* Try exporting the model from one of the OpenNLP-based recommenders from the recommender sidebar.
> #5003 - Allow exporting models from the OpenNLP recommenders

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- inception/pom.xml
- Check the resource filename and set a content type
> #5019 - SVGs embedded in MHTML files are not rendered

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/relation/StringMatchingRelationRecommender.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/SuggestionSupport_ImplBase.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/event/RecommendationRejectedEvent.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/ArcPosition_ImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/log/RecommendationRejectedEventAdapter.java
- Fix exception when trying to reject a relation suggestion
> #5008 - Cannot reject relation from relation recommender

- .github/workflows/maven.yml
- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-scheduling/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- pom.xml
> #5022 - Upgrade dependencies

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureSupport.java
- Allow handling single-value strings coming from recommenders
* See issue
> #5007 - Lazy details on suggestions for multi-value concept features fail rendering

- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java
- If a concept has already been linked, skip it and suggest the next one - still offer up to max-recommendation suggestions if available
* Create wikidata linking project
* Set named entity layer to stacking
* Configure an entity linking recommender (if none exists yet)
* Create a named entity annotation and see three suggestions
* Accept one
* Create another one and see that up to three new suggestions are made - the accepted one is not suggested again
> #4753 - Entity linker should skip already linked concepts

- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/about/AboutFooterPanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/about/AboutPage.java
- Filter out duplicate lines
* Check for duplicates
> #5029 - Duplicate lines on the about page

- inception/inception-app-webapp/src/main/resources/application.yml
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/CspProperties.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/CspPropertiesImpl.java
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/settings_security-csp.adoc
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- Make frame-ancestors configurable
- Adjust a few additional settings
* If you embed INCEpTION in an IFrame, set the new frame-ancestor setting
> #5027 - Add more CSP configurations

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
- Skip action buttons during tab navigation
* See issue
> #5040 - Improve feature form tab navigation

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkFeature.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkTest.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController.java
- inception/inception-ui-curation/src/test/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRendererTest.java
- Added another test case
- Fixed bug in selecting the correct target when comparing non-link features
* No need - there is a unit test
> #5009 - Better handling of stacked annotations with link features in curation

- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-export/src/test/java/de/tudarmstadt/ukp/inception/export/SegmentationUtilsTest.java
- inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/MHtmlDocumentReader.java
- inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/dkprocore/CasXmlNodeVisitor.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/SegmentationUtils.java
- Added new signature to the tokenizer call
- Added test
- Consolicated existing code
> #5043 - Ability to specify token breaking zones when calling tokenizer

- inception/inception-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/evaluator/ConstraintsEvaluator.java
> #5050 - Tags on the second level of conditional features cannot be selected

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/UserPreferencesServiceImpl.java
- Increase default number of rows to 20
* Create a new project and open a document in brat view
> #5066 - Increase default number of rows for brat editors

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebarState.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarTabbedPanel.java
- Expand the sidebar by default when first opening the annotation page
* Create a new project an open the annotation page
> #5068 - Show annotation sidebar by default

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/MergeDialog$ContentPanel.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/MergeDialog.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/MergeDialog.properties
- Focus response field by default
- Center label of response field
- Make update defaults switch always visible in button bar
- Use feedback panel instead of feedback field to show feedback, e.g. if challenge was not met
* Try curation merge dialog
> #5094 - Improve curation merge dialog layout

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/NumberFeatureTraits.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/NumberFeatureTraitsEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/NumberFeatureTraitsEditor.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.properties
- Fix ability to turn off limiting
- Slightly improve form layout
* See issue
> #5101 - Limited option on integer features cannot be turned off

- inception/inception-project-initializers-phi/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/phi/PhiProjectInitializer.java
- inception/inception-project-initializers-wikidatalinking/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/neannotation/EntityAnnotationProjectInitializer.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/QuickProjectInitializer.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectTemplateSelectionDialogPanel.html
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectTemplateSelectionDialogPanel.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/examples_ribbon.svg
- Add a ribbon to the project templates that come with examples
* Check the ribbons and create a project with example data
> #5109 - Mark project template that have examples

- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/recommendation/MetadataSuggestionSupport.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/relation/ArcSuggestionSupport_ImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/span/SpanSuggestionSupport.java
- Unwrap the value obtained from the feature support before comparing it to the suggested value
> #5115 - Suggestions for concept features never hidden due to overlapping

- inception/inception-guidelines/src/main/java/de/tudarmstadt/ukp/inception/guidelines/GuidelinesDialogContent.html
- inception/inception-guidelines/src/main/java/de/tudarmstadt/ukp/inception/guidelines/GuidelinesDialogContent.java
- inception/inception-guidelines/src/main/java/de/tudarmstadt/ukp/inception/guidelines/wicket-package.properties
- Fixed title
- Improved layout
* Check dialog
> #5117 - Guidelines dialog has wrong title

- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/evaluation/ConfusionMatrix.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/evaluation/EvaluationResult.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderStatusDetailPanel.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderStatusDetailPanel.java
- Add better coloring and better explanations
* Open confusion matrix from recommender sidebar and try understanding it
> #5121 - Improve recommender confusion matrix

- inception/inception-project-initializers-wikidatalinking/pom.xml
- inception/inception-project-initializers-wikidatalinking/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/neannotation/EntityAnnotationProjectInitializer.java
- inception/inception-project-initializers-wikidatalinking/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/neannotation/NamedEntitySampleDataTagSetInitializer.java
- inception/inception-project-initializers-wikidatalinking/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/wikidatalinking/config/WikiDataLinkingProjectInitializersAutoConfiguration.java
- inception/inception-project-initializers-wikidatalinking/src/main/resources/de/tudarmstadt/ukp/inception/project/initializers/neannotation/data/foodista_blog_2024_09_18_the-schoolhouse-district-of-downtown-woodinville-washington.txt
- inception/inception-project-initializers-wikidatalinking/src/main/resources/de/tudarmstadt/ukp/inception/project/initializers/neannotation/tagsets/foodista.json
- Made the tagset consistent with the example data
- Added another unannotated document to the example data
* See issue
> #5119 - Tagset in named entity example data does not match data

- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
- Hide required and remember options except on certain primitive features and strings
- Improve feature details visuals a bit
* Use the feature detail settings
> #5125 - Remember and required option available on some features that do not support them

- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityAutoConfiguration.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/UserProfileProperties.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/UserProfilePropertiesImpl.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/SettingsUtil.java
- Move profile accessibility setting to property bean
* Enable/disable the profile access setting and check if it works
> #3415 - Move all configuration options to Spring configuration beans

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- Enable by default
* Check if the mode is activated by default
> #5127 - Enable score on curation suggestions by default

- inception/inception-imls-hf/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/hf/client/HfHubClientImpl.java
- inception/inception-imls-hf/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/hf/model/HfModelCard.java
- Search only for models compatibe with the endpoints service
* Try using the Huggingface recommender
> #5130 - Searching Huggingface hub should only return endpoint-compatible models

- inception/inception-project-initializers-wikidatalinking/pom.xml
- inception/inception-project-initializers-wikidatalinking/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/neannotation/EntityAnnotationProjectInitializer.java
- inception/inception-project-initializers-wikidatalinking/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/wikidatalinking/config/WikiDataLinkingProjectInitializersAutoConfiguration.java
- Added keybindings
* Create a project from the template with and without sample data
* Check if the keybindings are there when sample data is enabled
> #5133 - Add keybindings to named entity template sample data

- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/client/ChatGptClientImpl.java
- inception/inception-imls-hf/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/hf/client/HfHubClientImpl.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/client/OllamaClientImpl.java
- Set a 10 second timeout for model listing calls
* See issue
> #5149 - Page hangs when listing LLM models is not possible

- inception/inception-io-tei/marker-wicket-module
- inception/inception-pdf-editor/pom.xml
- inception/inception-tutorial/pom.xml
- Ensure resources are included in TEI IO module
- Exclude some files from rat check with fail to pass sometimes (probably bug in rat)
> #5152 - Formatting broken when opening TEI files

- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportServiceImpl.java
- Set slug on exported project
> #5163 - Slug in exported project is always null

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/ActionBar.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowDocumentNavigationActionBarExtension.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/config/DynamicWorkloadManagerAutoConfiguration.java
> #5129 - Dynamic workflow may kick in for curator when try to view document from non-curator

- inception/inception-dependencies/pom.xml
- inception/inception-imls-ollama/pom.xml
- inception/pom.xml
- pom.xml
- groovy 4.0.23 -> 4.0.24
- jboss-logging 3.6.0 -> 3.6.1
- tomcat 10.1.31 -> 10.1.33
- hibernate 6.5.2 -> 6.6.2
- opensearch 2.17.1 -> 2.18.0
- rdf4j 5.0.2 -> 5.0.3
- asciidoctorj-pdf 2.3.18 -> 2.3.19
- byte-buddy 1.15.7 -> 1.15.10
- nimbus-jose-jwt 9.44 -> 9.46
- hsqldb 2.7.3 -> 2.7.4
- checkstyle 10.20.0 -> 10.20.1
> #5078 - Upgrade dependencies

- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRenderer.java
- Fix render logic to ensure we actually use an endpoint that has been rendered in showAll mode
* See issue
> #5096 - Relations disappear after merging their target/source

- inception/inception-diam-editor/src/main/ts/src/SpanText.svelte
- Fixed issue
* Observe spacing of text in left annotation overview sidebar
> #5170 - Extra or missing spaces between span text and following text in annotation sidebar

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderer.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/relation/RelationDiffAdapter.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRenderer.java
- The curation sidebar renderer should not warp the virtual beyond-end-of-window-VIDs into curation VIDs
> #5168 - Relations and links starting or ending beyond the current window are not visible in integrated curation

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLayerList.svelte
- Display count
* Look at annotation sidebar in group-by-layer or group-by-label mode
> #5172 - Display item count in groups in annotation sidebar

- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommenderTraits.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/settings/StringMatchingRecommenderTraitsEditor.html
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/settings/StringMatchingRecommenderTraitsEditor.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/settings/StringMatchingRecommenderTraitsEditor.properties
- Added minimum term length setting for learning
- Added regular expression to exclude certain kinds of terms
* Try out the new settings
> #5176 - Ability to prevent string matcher from learning things

- inception/inception-imls-azureai-openai/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/azureaiopenai/client/AzureAiOpenAiClientImpl.java
- inception/inception-imls-azureai-openai/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/azureaiopenai/client/ChatCompletionRequest.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/chatgpt/ChatGptRecommender.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/chatgpt/client/ChatCompletionRequest.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/chatgpt/client/ChatCompletionTimeInfo.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/chatgpt/client/ChatCompletionUsage.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/chatgpt/client/ChatGptClientImpl.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/chatgpt/client/RateLimitInfo.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/traits/DoubleOption.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/traits/LlmRecommenderTraitsEditor_ImplBase.html
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/traits/LlmRecommenderTraitsEditor_ImplBase.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/traits/Option.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/traits/OptionsPanel.html
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/traits/OptionsPanel.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/OllamaRecommenderTraitsEditor.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/client/OllamaClientImpl.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/client/OllamaGenerateRequest.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/client/OllamaMetrics.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/client/OllamaMetricsImpl.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/client/OllamaOptions.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/config/OllamaRecommenderAutoConfiguration.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/http/HttpClientImplBase.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/http/HttpClientUtils.java
- Added advanced options. Currently visible by default, but might hide them behind a feature switch before release.
- Collect additional information from LLM calls
* Try the options
> #5174 - Add support for additional LLM options

- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/DocumentMatrixRow.java
- Curation states must have precedence
* See issue
> #5186 - Matrix workload table shows annotation in progress even though curation has started

- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/AgreementSummary.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/AgreementUtils.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasure.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureSupport.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureSupportRegistry.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureSupportRegistryImpl.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureSupport_ImplBase.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasure_ImplBase.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/cohenkappa/CohenKappaAgreementMeasureSupport.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/fleisskappa/FleissKappaAgreementMeasureSupport.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalpha/KrippendorffAlphaAgreementMeasureSupport.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalphaunitizing/KrippendorffAlphaUnitizingAgreementMeasure.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalphaunitizing/KrippendorffAlphaUnitizingAgreementMeasureSupport.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/AbstractCodingAgreementMeasureSupport.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/CodingAgreementMeasure_ImplBase.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/task/CalculatePairwiseAgreementTask.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/task/CalculatePerDocumentAgreementTask.java
- inception/inception-dependencies/pom.xml
- inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementPage.html
- inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementPage.java
- inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementService.java
- inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementServiceImpl.java
- pom.xml
- Add option to calculate agreement only based on only the position of the spans
* Try calculating agreement using the **Layer name : <position>** option.
> #5190 - Inter-annotator agreement for span layer independently of features

- inception/inception-html-apache-annotator-editor/src/main/java/de/tudarmstadt/ukp/inception/apacheannotatoreditor/ApacheAnnotatorHtmlAnnotationEditorFactoryUserPreferences.schema.json
- Added preference settings to schema file
> #5194 - Preferences when opening document in HTML editor

- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.scss
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/SectionAnnotationCreator.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/SectionAnnotationVisualizer.ts
- Suppress re-rendering while still scrolling
- Optimize rendering of section headers
- Optimize handling of temporary markers
* Try editing HTML files
> Issue #5159: Improve HTML render performance

- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/UserProfilePropertiesImpl.java
- Change default for the profile access setting
* Check that in a fresh installation the user profile is accessible by non-admin users
> #5201 - Users should be able to change their own password by default

- inception/inception-diam/pom.xml
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/messages/MViewportUpdate.java
- inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController_ViewportRoutingTest.java
- inception/inception-diam/src/test/resources/log4j2-test.xml
- inception/inception-project-export/pom.xml
- inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceControllerImplTest.java
- inception/inception-recommendation/pom.xml
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RRecommenderLogMessage.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventWebsocketControllerImplTest.java
- inception/inception-recommendation/src/test/resources/log4j2-test.xml
- inception/inception-testing/pom.xml
- inception/inception-testing/src/main/java/de/tudarmstadt/ukp/inception/support/test/websocket/WebSocketSessionTestHandler.java
- inception/inception-testing/src/main/java/de/tudarmstadt/ukp/inception/support/test/websocket/WebSocketStompTestClient.java
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/config/WebsocketSecurityConfig.java
> #5209 - Improve websocket testing

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringServiceImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/TypeAdapter_ImplBase.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/Task.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/adapter/TypeAdapter.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- Do not add unsupported features to type adapters
- Better error message when trying to access an unsupported feature
> #5215 - Potential bug when trying to use unsupported features

- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/DefaultAgreementTraitsEditor.html
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/DefaultAgreementTraitsEditor.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/DefaultAgreementTraitsEditor.properties
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.properties
- Removed old linkCompareBehavior setting which no longer exists and was replaced by the multiplicity setting in the feature configuration
> #5217 - Exception when calculating Span Layer - Link Feature Agreement

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/editor/state/AnnotatorStateImpl.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateRelationAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandler.java
- Make the mechanism work again
> #5213 - Remember option for layer's feature is not working

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/filters/AnnotationDocumentStateFilterPanel.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/filters/SourceDocumentStateFilterPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/open/OpenDocumentDialogPanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
> #5205 - Tooltips for document states

- inception/inception-assistant/pom.xml
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/AssistantServiceImpl.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/AssistantServiceUserPreferences.schema.json
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/ChatContext.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/model/MTextMessage.java
- inception/inception-assistant/src/main/ts/src/AssistantPanel.svelte
- inception/inception-assistant/src/main/ts/src/AssistantState.ts
- inception/inception-imls-azureai-openai/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/azureaiopenai/AzureAiOpenAiRecommender.java
- inception/inception-imls-azureai-openai/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/azureaiopenai/client/ChatCompletionRequest.java
- inception/inception-imls-azureai-openai/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/azureaiopenai/client/OpenAiClientTest.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/prompt/JinjaPromptRenderer.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/traits/ChatBasedLlmRecommenderImplBase.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/OllamaRecommender.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/client/OllamaClient.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/client/OllamaClientImpl.java
- inception/inception-imls-ollama/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/client/OllamaClientImplTest.java
- Added speech syntesis option in the sidebar
* If your browser supports speech synthesis, click on the speaker icon in the assistant sidebar
* Ask the assistant something - the response should be spoken
> #5233 - Support speech synthesis for assistant

- inception/inception-assistant/pom.xml
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/documents/CasChunker.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/documents/UpdateDocumentIndexTask.java
- inception/inception-assistant/src/test/java/de/tudarmstadt/ukp/inception/assistant/documents/CasChunkerTest.java
> #5235 - Assistant index chunks should not overlap

- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VArc.java
- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VSpan.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
> #5239 - Relation Layer Coloring Rule Not Applied in Interface

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderProperties.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderPropertiesImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RRecommenderLogMessage.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventFooterPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventWebsocketControllerImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/NonTrainableRecommenderActivationTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
- inception/inception-recommendation/src/main/ts/src/RecommendationEventFooterPanel.svelte
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- No longer generate flash message when annotation has been deleted
* Delete annotation
> #5206 - Reduce visual clutter caused by flash messages

- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-scheduling/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- Update package-lock.json files
> #5249 - Upgrade dependencies

- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/AssistantServiceImpl.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/config/AssistantDocumentIndexProperties.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/config/AssistantDocumentIndexPropertiesImpl.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/config/AssistantPropertiesImpl.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/config/AssistantToolProperties.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/documents/CasChunker.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/documents/Chunk.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/documents/DocumentContextRetriever.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/documents/UpdateDocumentIndexTask.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/userguide/UserGuideRetriever.java
- inception/inception-assistant/src/main/resources/META-INF/asciidoc/admin-guide/settings_assistant.adoc
- inception/inception-assistant/src/test/java/de/tudarmstadt/ukp/inception/assistant/documents/CasChunkerTest.java
- inception/inception-assistant/src/test/java/de/tudarmstadt/ukp/inception/assistant/documents/DocumentContextRetrieverTest.java
- Added new options
- Added test
- Added documentation
* Try enabling overlap by setting it at least to 1 (one sentence)
> #5245 - Support overlapping and merging chunks

- inception/inception-assistant/src/main/ts/src/AssistantPanel.svelte
- Added the copy button
* Try the copy button
> #5247 - Allow copying assistant messages

- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-scheduling/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- Update package-lock.json files
> #5251 - Upgrade dependencies

- .github/workflows/maven.yml
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchQueryRequest.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/model/AnnotationSearchState.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUtils.java
- inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/annotation/AnnotationSearchStatePanel.html
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/annotation/AnnotationSearchStatePanel.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/annotation/AnnotationSearchStatePanel.properties
- inception/inception-ui-search/pom.xml
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsProviderWrapper.java
- Make search case-insensitive by default
- The results in the sidebar should continue to have the proper case
* Create a new project and use the search
> #5256 - Make search case-insensitive by default

- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/documents/UpdateDocumentIndexTask.java
- Add document IDs as searchable fields so that updater can check if a document is already present or not
- Instead of doing nothing when no document remains in the project, make sure that any documents still in the index get properly removed
* See issue
> #5263 - Assistant index does not update correctly when documents are added or removed

- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/format/VisualPdfReader.java
- Added workaround for the bug in pdfbox while we don't have a fixed release yet
* Import e.g. the PDF linked in the Jira issue
> #5258 - PDFs with diacritics on surrogate Unicode characters are not correctly extracted

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkFeature.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkTest.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeTestBase.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CurationTestUtils.java
- inception/inception-curation/src/test/resources/desc/type/webannoTestTypes.xml
- When searching for the best host to merge a link to, consider all link features, not only the link feature currently being merged
- Added test
* See issue
> #5274 - Link merged to wrong host when candidate hosts only differ in links

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarBehavior.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- Assign the proper source users for the new document before triggering the auto-merge in onPreparingToOpenDocumentEvent
- Remove assignment of source users later onDocumentOpened
> #5278 - Merge sometimes not working when switching between documents in integrated curation mode

- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java
- Use the central TrimUtils in the brat visualizer instead of a local copy (which was out-of-sync)
> #5269 - Non-break space character in PDF causing load problem with text Brat sentence view

- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/prompt/PerParagraphContextGenerator.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/traits/ChatBasedLlmRecommenderImplBase.java
- inception/inception-imls-llm-support/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/prompt/PerParagraphContextGeneratorTest.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/client/OllamaChatRequest.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/llm/InteractiveRecommenderSidebar.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/llm/InteractiveRecommenderSidebar.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/llm/InteractiveRecommenderSidebar.properties
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTaskTest.java
- Fix options in OllamaRecommender again
- Fix paragraph context generation when document starts with empty paragraph
- Allow accumulating suggestions in interactive recommender
* Try using interactive recommender sidebar
> #5283 - Improve usability of interactive recommender sidebar

- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/LayerImportExportUtils.java
- Include show-on-hover when exporting/importing layers to/from JSON
> #5288 - Show on hover setting not exported correctly

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/link/LinkFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/link/LinkFeatureTraits.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/link/LinkFeatureTraitsEditor.java
- inception/inception-api-annotation/src/main/resources/META-INF/asciidoc/user-guide/projects_layers_feature_link.adoc
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/Configuration.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/api/Position_ImplBase.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/docmeta/DocumentPosition.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/relation/RelationPosition.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/span/SpanDiffAdapter.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/span/SpanPosition.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkFeature.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeOperationResult.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkTest.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeRelationTest.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CurationTestUtils.java
- inception/inception-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedProject.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/MaterializedLink.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/AnnotationBuilder.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/FeatureStructureBuilder.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/AnnotatorsPanel.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationEditorExtension.java
- Better support for selecting suitable link hosts and link targets
- More trace logging
- Fix a couple of NPEs
* Try using the curation functionality
> #5291 - Improve curation and auto-merging of link features

- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java
- If two tokens are directly adjacent without space, make sure that the "brat tokens" we send to the frontend do include that token boundary
* See issue.
> #5297 - Visual spacing in brat between directly adjacent tokens

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/menu/ContextMenuItemContext.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/menu/ContextMenuItemExtension.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/menu/ContextMenuItemRegistryImpl.java
- inception/inception-assistant/pom.xml
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/AssistantService.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/AssistantServiceImpl.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/ChatContext.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/config/AssistantAutoConfiguration.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/contextmenu/CheckAnnotationContextMenuItem.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/contextmenu/CheckAnnotationTask.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/sidebar/AssistantSidebarFactory.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/ShowContextMenuHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/config/DiamAutoConfig.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/lambda/LambdaMenuItem.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/ContextMenu.html
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarPanel.java
- Added the context menu item
- Bits of cleaning up here and there
- Added ability to show icons in context menu items
- Added ability to show a sidebar panel on some action (e.g. showing the assistant when performing the check action)
* Enable assistant
* Create some span annotation, best with some label
* Right-click on the annotation and select "Check"
> #5306 - Add context menu item to annotation to check it using assistant

- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/rendering/Renderer.java
> #5310 - Feature name displayed in validation messages is UIMA name not UI name

- inception/inception-assistant/pom.xml
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/AssistantService.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/AssistantServiceImpl.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/ChatContext.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/config/AssistantProperties.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/config/AssistantPropertiesImpl.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/model/MCallResponse.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/model/MChatMessage.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/sidebar/AssistantSidebar.html
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/sidebar/AssistantSidebar.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/sidebar/AssistantSidebarPrefs.java
- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/sidebar/WatchAnnotationTask.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/recommendation/MetadataSuggestionSupport.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/TrainingInstance.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/llm/InteractiveRecommenderSidebar.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/InviteProjectSettingsPanel.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/json/JSONUtil.java
- Added check option accessible by right-clicking on a span annotation
- Added watch mode that continually monitors new annotations and comments if it thinks something needs to be changed
- Added new queuing mode to the scheduling service which just executes tasks one after the other
- Added debug mode toggle to the assistant sidebar
* Try right-clicking on a span and select "Check"
* Try enabling watch mode on the assistant sidebar
> Issue #5314: Option for the assistant to check annotations

- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/traits/LlmRecommenderImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/event/RecommenderUpdatedEvent.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-support-bootstrap/src/main/java/de/tudarmstadt/ukp/inception/bootstrap/IconToggleBox.java
- Try reactivating non-trainable recommenders in particular after changing recommender-relevant settings in the project settings.
- Fix potential NPE in the IconToggleBox
- Better error when trying to run an LLM annotator without prompt
> #5319 - Changing recommender settings disables recommenders until session is reset

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/export/CurationWorkflowExporter.java
- Serialize the exported object, not the internal object
* Export project and check the JSON file inside it for stray project IDs
> #5330 - CurationWorkflow export includes extraneous data

- inception/inception-project-initializers-wikidatalinking/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/wikidatalinking/ProfileBasedKnowledgeBaseInitializer.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/KnowledgeBaseInitializer.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseTemplateSelectionDialogPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseTemplateSelectionDialogPanel.java
- Added KB info to selection dialog
* ...
> #5325 - Simpler way of adding pre-defined knowledge bases

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- listEnabledRecommenders should not return unsupported recommenders
> #5151 - Unsupported recommenders trigger error on annotation page

- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporterTest.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/export/CurationWorkflowExporterTest.java
- inception/inception-documents/src/test/java/de/tudarmstadt/ukp/inception/documents/exporters/SourceDocumentExporterTest.java
- inception/inception-export-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectImportRequest.java
- inception/inception-external-search-core/src/test/java/de/tudarmstadt/ukp/inception/externalsearch/exporter/DocumentRepositoryExporterTest.java
- inception/inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/exporter/GazeteerExporterTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseExporterTest.java
- inception/inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporterTest.java
- inception/inception-preferences/src/test/java/de/tudarmstadt/ukp/inception/preferences/exporter/DefaultPreferenceExporterTest.java
- inception/inception-preferences/src/test/java/de/tudarmstadt/ukp/inception/preferences/exporter/UserProjectPreferenceExporterTest.java
- inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/AnnotationDocumentsExporterTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/exporter/LearningRecordExporterTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/exporter/RecommenderExporterTest.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_ProjectExport_Test.java
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/MockAeroClient.java
- inception/inception-schema/src/test/java/de/tudarmstadt/ukp/inception/schema/exporters/LayerExporterTest.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/User.java
- inception/inception-sharing/src/test/java/de/tudarmstadt/ukp/inception/sharing/project/exporters/ProjectInviteExporterTest.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/ProjectImportPanel.java
- inception/inception-workload/pom.xml
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/model/WorkloadManager.java
- inception/inception-workload/src/test/java/de/tudarmstadt/ukp/inception/workload/exporter/WorkloadManagerExporterTest.java
- Added importPermissions flag
- Added ability for project creators to import like they can via the UI
- Added test
* Try out, e.g. via swagger
> #3149 - Project creators cannot import projects through remote API

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- More robust checking of orphans
> #5092 - Error when checking for orphaned KBs

- inception/inception-boot-loader/src/main/java/de/tudarmstadt/ukp/inception/bootloader/ExtensibleClasspathEnabledWarLauncher.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java
- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/LoadingSplashScreen.java
- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialogManager.java
- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneUserInterface.java
- Keep the icon there
- Also set application name on MacOS
> #5344 - Tray icon should not disappear when starting from terminal

- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LinkToContextMenuItem.java
- Also allow chain layers in the LinkToContextMenuItem
* Try it
> #5346 - Link-to context action not available for coreference layers

- inception/inception-recommendation-api/pom.xml
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngine.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/model/DirtySpot.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- Introduce APIs necessary for incremental updates
> #5318 - Ability to update recommenders incrementally

- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/AgreementServiceImpl.java
- Include covered text in JSON and CSV export as well
* Try exporting as CSV or JSON
> #5339 - Export diff data in CSV format to facilitate external processing

- inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/AnnotationEditorExtension.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkFeature.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeRelation.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeSpan.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/PerCasMergeContext.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationMergeService.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationMergeServiceImpl.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationEditorExtension.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarFactory.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRenderer.java
> #5359 - Clean up curation code a bit

- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/editors.adoc
- inception/inception-doc/src/test/java/de/tudarmstadt/ukp/inception/doc/GenerateDocumentation.java
- inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/config/HtmlSupportAutoConfiguration.java
- inception/inception-io-html/src/main/resources/META-INF/asciidoc/user-guide/formats-htmldoc.adoc
- inception/inception-ui-core/src/main/resources/META-INF/asciidoc/user-guide/users.adoc
- Enable HTML format by default
* Start INCEpTION without having HTML format enabled manually and check if it is accessible
> #5368 - Promote HTML format out of experimental status

- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/config/PdfAnnotationEditorSupportAutoConfiguration.java
- inception/inception-pdf-editor2/src/main/resources/META-INF/asciidoc/user-guide/formats-pdf.adoc
- Turn off legacy PDF editor by default
- Remove legacy PDF from user documentation
> #5370 - Turn off legacy PDF editor by default and remove legacy PDF format from documentation

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringServiceImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SegmentationUnitAdapter.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/UnitEvent.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/UnitMergedEvent.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/UnitSplitEvent.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/MergeUnitAnnotationAction.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/SplitUnitAnnotationAction.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/undo/actions/UnitAnnotationActionUndoSupport.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/config/AnnotationUIAutoConfiguration.java
- Fix undo/redo for splitting/merging tokens
* Try splitting / merging tokens and then undoing/redoing
> #1778 - Make tokenization editable

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainAdapter.java
> #5365 - Error when linking single-element chain to start of another chain

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkFeature.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkTest.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CurationTestUtils.java
> #5402 - Unable to merge link

- inception/inception-js-api/src/main/ts/src/util/ViewportTracker.ts
- Consider elements visualized as list-items as valid leaf candidates
> #5411 - Annotations on list may not render in Apache Annotator editor

- inception/inception-brat-editor/src/main/ts/src/style-ui.scss
- inception/inception-brat-editor/src/main/ts/src/style-vis.scss
- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.scss
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.svelte.ts
- inception/inception-js-api/src/main/ts/src/style/InceptionEditorColors.scss
- inception/inception-pdf-editor2/src/main/ts/src/PdfAnnotationEditor.scss
- inception/inception-pdf-editor2/src/main/ts/src/PdfAnnotationEditor.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.ts
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchQueryRequest.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsProvider.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsProviderWrapper.java
- highlight all matches
- highlight selected match specially
* Try out in apache annotator editor and brat editor
> #5422 - Highlight all search matches instead of only the selected one

- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/webanno.js
- inception/inception-ui-search/pom.xml
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.html
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.utf8.properties
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchHistoryItem.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchHistoryMetaDataKey.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchHistoryPanel.html
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchHistoryPanel.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchHistoryState.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchRequest.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsProvider.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsProviderWrapper.java
- Added persistent search history with pinning ability
* Try using the search history functionality
> #5427 - Add search history

- inception/inception-assistant/src/main/ts_template/package-lock.json
- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts/build.mjs
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts/build.mjs
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-io-xml/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts/audit-resolve.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts/audit-resolve.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-scheduling/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- pom.xml
* svelte 5.25.12 -> 5.33.3 (fixes XHTML support)
* Update package-lock.json files
> #5380 - Upgrade dependencies

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/span/SpanSuggestionSupport.java
> #5444 - Error when recommender recommender predicts null for multi-value string feature

- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/faq.adoc
- inception/inception-guidelines/src/main/resources/META-INF/asciidoc/user-guide/guidelines.adoc
- inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/knowledge_base.adoc
- inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_tagsets.adoc
- inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_users.adoc
- Update some parts of the documentation to be more readable
> #5456 - Improve documentation

- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutTimer.js
- Improve logout timer script to be more resilient against browser energy saving measures
> #5477 - Logout timer may freeze

- inception/inception-documents-api/src/main/java/de/tudarmstadt/ukp/inception/documents/api/SourceDocumentStateStats.java
- Check if a project has no documents at all and if so return state NEW
> #5484 - Project state should be NEW and not CURATION_FINISHED for projects without and documents

- pom.xml
- DKPro Parent POM 32 -> 33
* Run build
* Run release build
> #5489 - Upgrade dependencies

- pom.xml
* groovy 4.0.26 -> 4.0.27
* junit-jupiter 5.12.2 -> 5.13.3
* junit-platform 1.12.2 -> 1.13.3
* mockito 5.17.0 -> 5.18.0
* xmlunit 2.10.0 -> 2.10.3
* testcontainers 1.21.0 -> 1.21.3
* pdfbox 3.0.4 -> 3.0.5
* spring 6.2.6 -> 6.2.8
* spring.boot 3.4.5 -> 3.5.3
* spring.data 3.4.5 -> 3.5.3
* spring.security 6.4.5 -> 6.5.1
* springdoc 2.8.6 -> 2.8.9
* swagger 2.2.30 -> 2.2.34
* log4j2 2.24.3 -> 2.25.1
* sentry 7.22.5 -> 7.22.6
* tomcat 10.1.39 -> 10.1.43
* jetty 12.0.19 -> 12.0.23
* mariadb.driver 3.5.3 -> 3.5.4
* mssql.driver 12.10.0.jre11 -> 12.10.1.jre11
* mysql.driver 9.2.0 -> 9.3.0
* postgres.driver 42.7.5 -> 42.7.7
* hibernate 6.6.13.Final -> 6.6.20.Final
* wicketstuff 10.4.0 -> 10.5.0
* wicket-bootstrap 7.0.9 -> 7.0.10
* wicket-webjars 4.0.6 -> 4.0.8
* lucene 9.12.1 …
> #5474 - Upgrade dependencies

- inception/inception-support/pom.xml
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/PipedStreamResource.java
- inception/inception-ui-agreement/pom.xml
- inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementPage.java
- inception/inception-ui-project/pom.xml
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/SourceDocumentTable.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsExporter.java
- inception/inception-ui-search/src/test/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsExporterTest.java
- inception/inception-workload-matrix/pom.xml
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.html
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
- Added export button to export table in CSV format
* Try the new export button
> #5392 - Monitoring page to support CSV export of the table view

- inception/inception-documents-api/src/main/java/de/tudarmstadt/ukp/inception/documents/api/DocumentService.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-export-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/DocumentImportExportService.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroAnnotationController.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/ReindexTask.java
- ReindexTask only goes over supported document types
> #5502 - Error when ReindexTask hits an unsupported document

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.utf8.properties
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/local/LocalRepositorySettingsPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/local/LocalRepositorySettingsPanel.java
- Added a notice to the import panel for local KBs that is only shown when the KB has not been saved yet (i.e. only in the wizard phase)
* Create a new local KB - notice should show on the import step in the wizard
* Notice should not be displayed in the KB settings editor (which re-uses the panel)
> #1650 - Advise user that importing content into a knowledge base is optional

- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsStartAndEndWithinSentencesCheck.java
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/formats.adoc
- inception/inception-export-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/DocumentImportExportService.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-export/src/test/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportSerivceImplStaticsTest.java
- inception/inception-pdf-editor2/pom.xml
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/config/PdfAnnotationEditor2SupportAutoConfiguration.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/format/PdfJsonCasFormatSupport.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/format/PdfXmiCasFormatSupport.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/format/VisualPdfWriter.java
- inception/inception-pdf-editor2/src/main/resources/META-INF/asciidoc/user-guide/formats-pdf.adoc
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroDocumentController.java
- Option to export PDF with PDF annotations
- Option to additionally include UIMA CAS JSON or XMI
* Try exporting the different PDF flavours 
> #5514 - Export PDF with annotations

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/misc/UimaPrimitiveFeatureSupport_ImplBase.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/TypeAdapter_ImplBase.java
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureTraitsEditor.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/recommendation/MetadataSuggestionSupport.java
- inception/inception-layer-relation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/recommender/RelationSuggestionSupport.java
- inception/inception-layer-span/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/recommender/SpanSuggestionSupport.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/SuggestionSupport_ImplBase.java
- inception/inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/SpanAnnotationPanel.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/adapter/TypeAdapter.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/FeatureEditor.java
> #5518 - Extract feature implementations into separate modules

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationDocumentServiceImpl.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationServiceImpl.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/ExternalSearchServiceImpl.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/gazeteer/GazeteerServiceImpl.java
- inception/inception-imls-weblicht/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/weblicht/chains/WeblichtChainServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/component/DocumentNamePanel.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/model/WorkloadManagementServiceImpl.java
- Use read-only transactions in many places
> #5536 - Use read-only transactions when possible

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/RecommendableFeatureTrait.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/TypeAdapter_ImplBase.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/editorstate/FeatureState.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/editorstate/SuggestionState.java
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/InputFieldStringFeatureEditor.java
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureTraits.java
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureTraitsEditor.html
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureTraitsEditor.java
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureTraitsEditor.utf8.properties
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/SuggestionStatePanel.html
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/SuggestionStatePanel.java
- inception/inception-io-html/src/test/resources/html/test-document.xmi
- inception/inception-io-html/src/test/resources/html/test-with-head-and-doctype.xmi
- inception/inception-io-html/src/test/resources/html/test-with-head.xmi
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/SuggestionSupport_ImplBase.java
- inception/inception-schema-api/.activate-run-jcasgen
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/AnnotationSchemaService.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/adapter/TypeAdapter.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/FeatureSupport.java
- inception/inception-schema-api/src/main/resources/META-INF/org.apache.uima.fit/types.txt
- inception/inception-schema-api/src/main/resources/de/tudarmstadt/ukp/inception/annotation/type/inception-static.xml
- inception/inception-schema-api/suppressions.xml
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/pom.xml
- Added optional retention mechanism to string features
* Try the new option on string features
> #5534 - Option to retain recommender scores when accepting an annotation

- inception/inception-layer-chain-api/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/api/ChainLayerTraits.java
- inception/inception-layer-chain-api/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/api/ChainRenderMode.java
- inception/inception-layer-chain/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainLayerTraitsEditor.html
- inception/inception-layer-chain/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainLayerTraitsEditor.java
- inception/inception-layer-chain/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainRenderModeSelect.java
- inception/inception-layer-chain/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainRenderer.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.utf8.properties
- inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
- Added render mode to chain traits
* Switch render mode to "when selected" or "never" and check if it works
> #5551 - Option to render chain links only on currently selected chain

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderLocalTestScenarios.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/util/TestFixtures.java
- Send user agent along when talking to a SPARQL endpoint
> #5562 - WikiData queries fail requesting a user-agent

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-log-ui/src/test/java/de/tudarmstadt/ukp/inception/websocket/WebSocketIntegrationTest.java
- Ensure not to override OAuth headers when setting user agent headers / vice versa
> #5562 - Wiki data queries fail requesting a user agent

- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-project-api/src/main/java/de/tudarmstadt/ukp/inception/project/api/ProjectService.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/InceptionDaoAuthenticationProvider.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/User.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImpl.java
- inception/inception-security/src/test/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImplTest.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/InviteServiceImpl.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/AddProjectUserPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/DeleteProjectBoundUserConfirmationDialogContentPanel.html
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/DeleteProjectBoundUserConfirmationDialogContentPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/DeleteProjectBoundUserConfirmationDialogContentPanel.utf8.properties
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/ProjectUserDetailPanel.html
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/ProjectUserDetailPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserSelectionPanel.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/event/MatrixWorkloadUpdateDocumentStateTask.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/service/MatrixWorkloadServiceImpl.java
- Allow project manager to delete project-bound users
* Try creating and deleting a project bound user
> #5578 - Allow management of project-bound users

- inception/inception-feature-string/pom.xml
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureTraitsEditor.java
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureTraitsEditor.html
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureTraitsEditor.java
- inception/inception-schema-api/pom.xml
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/DisableRetainSuggestionInfoConfirmationDialogContentPanel.html
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/DisableRetainSuggestionInfoConfirmationDialogContentPanel.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/DisableRetainSuggestionInfoConfirmationDialogContentPanel.utf8.properties
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/RetainSuggestionInfoPanel.html
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/RetainSuggestionInfoPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/DisabledKBWarning.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/KnowledgeBaseItemAutoCompleteField.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureTraitsEditor.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureTraitsEditor.java
- Require confirmation for disabling suggestion info retain switch
* Try enabling/disabling info retainment
* Check if states save
> #5534: Option to retain recommender scores when accepting an annotation

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/FeatureEditorListPanel.java
- Set tabindex on feature editors so that tab order starts with them in particular (but not only) when key bindings are used
* Create feature with key bindings
* Create annotation - note that focus is not set to feature editor
* Press tab, then focus should be in the feature editor
> #5519 - Improve tab navigation

- inception/inception-project-api/src/main/java/de/tudarmstadt/ukp/inception/project/api/ProjectService.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectAccessImpl.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-remote/pom.xml
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/RemoteApiAutoConfiguration.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/inception/remoteapi/Controller_ImplBase.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/inception/remoteapi/next/AnnotationController.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/inception/remoteapi/next/PermissionController.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/inception/remoteapi/next/UserController.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/inception/remoteapi/next/model/RUser.java
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/MockAeroClient.java
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/UserControllerTest.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/TaskAccessImpl.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/ProjectUserDetailPanel.java
- Added project-bound user management endpoints
- Added corresponding tests
* Try the new remote API calls
> #5589 - Management of project-bound users via remote API

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
- Improve layout of state icons
* Check if project overview looks good
> #5470 - Add state information to project overview

- inception/inception-assistant/src/main/ts_template/package-lock.json
- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-docker/src/main/docker/Dockerfile
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-io-xml/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts/audit-resolve.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts/audit-resolve.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-scheduling/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- pom.xml
- vite 6.3.4 -> 6.3.6
- Updated package-lock.json files
> #5614 - Upgrade dependencies

- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepository.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/open/OpenDocumentDialogPanel.java
- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashletController.java
- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashletControllerImpl.java
- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/panel/ActivityPanel.html
- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/panel/ActivityPanel.java
- inception/inception-ui-dashboard-activity/src/main/ts/src/ActivityPanel.svelte
- Added dropdown for managers
- Extended controller to allow fetching data for other uers
* Log in as manager and try the drop-down
* Log in as non-manager and check the drop-down is not there
> #5617 - Ability to see activities of other users in activity overview

- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashlet.html
- inception/inception-ui-dashboard-activity/src/main/ts/src/ActivitiesDashlet.svelte
- Improved layout
* Try documents with long names and how they appear in the sidebar
> #5628 - Fix layout of the activities sidebar for long document names

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/SparqlPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/SparqlPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/wicket-package.utf8.properties
- Display query and explanation execution time
- Display query plan / explanation
* Try the SPARQL panel (in dev mode)
> #5626 - Better SPARQL query panel on KnowledgeBase page

- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQuery.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryOptionalElements.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderAsserts.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderLocalTestScenarios.java
- Allow pre-resolving
- Pre-resolve in the concept linking service
> #5627 - Allow pre-resolving label and match properties to speed up main queries

- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.svelte.ts
- Use setTimeout or requestIdleCallback depending on availability
> #5606 - Jumping to an assistant source fails in Safari

- inception/inception-pivot/src/main/java/de/tudarmstadt/ukp/inception/pivot/page/PivotTablePage.html
- Improved labels
* No specific test instructions
> #5648 - Better UI labels in explorer

- inception/inception-pivot/src/main/java/de/tudarmstadt/ukp/inception/pivot/page/PivotTablePage.java
- inception/inception-pivot/src/main/java/de/tudarmstadt/ukp/inception/pivot/table/PivotTable.html
- inception/inception-pivot/src/main/java/de/tudarmstadt/ukp/inception/pivot/table/PivotTable.java
- inception/inception-pivot/src/main/java/de/tudarmstadt/ukp/inception/pivot/table/PivotTableDataProvider.java
- inception/inception-pivot/src/main/java/de/tudarmstadt/ukp/inception/pivot/table/PivotTableFilterState.java
- Added options to filter for uniform / non-uniform rows
- Added options to filter for rows with(out) empty values
* Try the options
> #5646 -Ability to filter rows by non-equal or empty values

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-annotation-storage-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/casstorage/CasSet.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporter.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporterTest.java
- inception/inception-documents-api/src/main/java/de/tudarmstadt/ukp/inception/documents/api/DocumentService.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentAccessImpl.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/curation/BulkCurationTask.java
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/task/curated/CuratedDocumentsProjectExportTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/LazyCasLoader.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/AnnotationDocumentExporter.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPageBase2.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationEditorExtension.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarBehavior.java
- Introduce a CasSet abstraction that represents the organization unit instead of a username string
- Cleaning up
> #5640 - Decouple annotation storage from user management
