inception-project/inception

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/model/Predictions.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
It will clear the predictions now, but with the current implementation it also clears active recommenders and trained models for other projects. Rather the activeRecommenders and trainedModels should be saved per Project.
> #63 - Recommender recommondations not reset on document reset

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingService.java
The covered text of Tokens retrieved by WebAnnoCasUtil.getSentence have not been converted to lower case. This lead to some errors, where the mention could not be found in the sentence.
> #83 - Mention context not computed correctly

- inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/scheduling/tasks/TrainingTask.java
- Store document in which recommendation exists instead of current document in the learning record
- Avoid exceptions when reacting to annotation update event
- Create annotation in the right document
- Made trainning code more robust
> #316 - Accepting AL recommendation while in other document fails

- inception-imls-core/pom.xml
- inception-imls-core/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/core/dataobjects/ExtendedResult.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/scheduling/TaskConsumer.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/scheduling/tasks/SelectionTask.java
- Catch throwable instead of exception in background thread runner
- Convert assert to IllegalArgumentException in ExtendedResult
> #337 - Recommender background thread crashes on throwable

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java
When checking whether a token is a named entity, also take documentUri into account.
> #333 - NE linking recommendations without NE annotation

- inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.html
- inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
If a project doesn't have recommenders, no layer can be selected in the active learning sidebar. In this case, active learning sidebar shouldn't return a `featureEditor`. Instead, it returns an empty invisible label.
Fixes #370.
> #370 - Active Learning Sidebar gives Internal Error

- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/IndexingConstants.java
- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- Use feature supports as much as possible to be generic and to avoid redundant code
- Introduce helper method addToIndex to reduce number of lines of code
- Renamed constants to separate word components via underscode
Fixes #385.
This PR also fixes #381 as the respective code has been refactored.
> #385 - Clean up MtasUimaParser code

- inception-ui-kb/pom.xml
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/PropertyFeatureSupport.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/initializers/FactLayerInitializer.java
- pom.xml
- Introduce Caffeine-based cache into ConceptFeatureSupport and PropertyFeatureSupport
- Cache lookup failures
- Reformatting and renaming in some parts to reduce the differences between the code in ConceptFeatureSupport and PropertyFeatureSupport for easier comparison
- Removed commented out code
> #465 - Reduce number of SPARQL queries during indexing/rendering

- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- Do not treat the query as basic text query if it contains a double-quote
- Duplicated test for basic text queries for simplified CQL token syntax
> #487 - Cannot using simple CQL token syntax `"some" "token"`

- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/editor/StringLiteralValueEditor.java
- safe language value on change
This PR, together with the changes from #51 fixes the issues when saving a language value.
The reason that the concept tree shows a node-id when the language of the default label is changed to for example 'de' , is that we only look for labels with language en or "" when we query for the root concepts. So getUiLabel won't find any label for that concept and returns the node-id. 
I don't know if and in what way we want to change that.
@naveen2507 Do you have any suggestions?
> #419 - language_field_in_kb_editor_broken

- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/editor/StringLiteralValueEditor.java
- remove LambdaAjaxFormComponentUpdatingBehavior in StringEditor
> #496 - two clicks necessary to save a value in the stringeditor on kb page

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/ConceptFeatureTraits.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/SubjectObjectFeatureEditor.java
- If no allowed value type is set for a ConceptFeatureTrait, then assume INSTANCE (the traditional setting)
> #504 - Entity linking not working

- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- No longer rename SYSTEM.off because that breaks RDF4J's internal upgrade mechanism. Need another approach.
> #498 - Upgrade to RDF4J 2.4.0

- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementGroupPanel.java
- only trigger StatementChangedEvent on statement group when the instance of the statementgroup is equal to the instace of the changed statement
> #533 - changing the name of an instance adds a label to the concept

- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplWikiDataIntegrationTest.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/util/TestFixtures.java
- assume that remote sparql endpoint is available before running tests against it
> #543 - Unit tests fail for Hucit due to SPARQL service being unavailable

- inception-app-webapp/pom.xml
- inception-imls-dl4j/pom.xml
- inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommender.java
- inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderFactory.java
- inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderProperties.java
- inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java
- pom.xml
- Unit tests store dataset in proper cache folder now
- During production, dataset is stored in INCEpTION home folder
- DL4J by default disabled, but can be enabled via property in settings.properties
- DL4J is part of build artifact again
> #605 - Unit tests leave dataset caches lying around in tmp

- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- Use the prefix configured in the KB to resolve relative IRIs
> #631 - RDF files with relative IRIs cannot be imported

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/ProjectRecommendersPanel.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.java
- set selected model object to null when project selection changes ( KbPanel and RecommendersPanel)
> #577 - Switching between projects does not hide kb details panel

- inception-imls-dl4j/pom.xml
- inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommender.java
- pom.xml
- Upgrade to DL4J 1.0.0-beta3
- Reduce dependency footprint by including only platform-specific dependencies for OS X, Windows and Linux on x64 and x86_64 hardware
> #635 - Exclude DL4J native binary JARs for some platforms

- inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommender.java
- inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTraits.java
- inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java
- Introduced trait to limit the training set size and use it during testing
- Reduce increment size in incremental evaluation test
- Made the batch size a trait and reduce it in testing
> #646 - Reduce runtime of DL4J unit tests

- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/IriConstants.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java
- Made IriConstants.IMPLICIT_NAMESPACES a proper constant
- Let KnowledgeBaseSerivce manage an extensible set of implicit namespaces
- Use that managed set in unit tests
> #654 - IriConstants.IMPLICIT_NAMESPACES is not really a constant

- inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Recommender.java
- inception-recommendation-api/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/model/db-changelog.xml
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/exporter/ExportedRecommender.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/exporter/RecommenderExporter.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/ProjectRecommendersPanel.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
- inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/exporter/RecommenderExporterTest.java
- Export and import the maxRecommendations and skipEvaluation settings
- Fix the database to set missing maxRecommendations to the default value (3)
- On project import, enforce the max recommendations cap
- On project import, set missing max recommendations to default value
- Updated import/export unit test to check for preservation of maxRecommendations and skipEvaluation settings
- Updated import/export unit test to check for cap enforcement and to set missing values to default
> #668 - Some recommender settings not preserved on export/import

- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java
- inception-imls-stringmatch/pom.xml
- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java
- Exclude training data without label in OpenNLP NER recommender
- Exclude training data without label in String matching recommender
- In OpenNLP POS, check if a label is empty using "isNoneBlank" instead of simply using "!= null" as before. Really just a cosmetic change.
> #676 - Annotations whose label is not set are considered as training data

- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBaseProperties.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
- inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/model/db-changelog.xml
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseExporterTest.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard$TypeStep.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java
- Introduce constant for query lower limit
- Fix maxResults = 0 in the DB on application start
- Apply maxResults caps during project import
- Set default value if maxResults = 0 on import
- Use a NumberTextField for the maxResults in the project settings instead of a RequiredTextField
> #650 - Auto Complete field doesn't show suggestion for concept linking

- pom.xml
- Set version of DKPro Core HTML reader explicitly because wrong version is inherited due to missing dependencyManagement entry in the DKPro Core 1.10.0 ASL POM
> #679 - Document import fails for HTML files

- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBObject.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandleTest.java
- Use the IRI if extracting the local name as a label would result in an empty label
> #694 - Some statement values are shown as empty but are not

- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- Use a dynamic-sized list instead of allocating a static array since we do not know how many annotations actually have a label and we cannot leave any array items to unset (null)
> #717 - Annotations without label causes OpenNLP NER recommender to crash

- inception-search-mtas/pom.xml
- inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- Give the async indexing more time
- Switch to use Awaility instead of hand-coded timeout checks
> #731 - MTAS tests failing occasionally

- inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- pom.xml
- Update the access timestamp in the annotator state when saving the CAS to avoid concurrent access warning
> #719 - Active learning sidebar triggers concurrent access error

- inception-app-webapp/src/main/resources/log4j2.xml
- Decrease log level for ResponseProcessCookies to avoid log being spammed on cookies that httpclient considers malformed (happens a *lot* with Wikidata)
> #739 - Cookie warnings spam log

- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception-imls-opennlp/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_opennlp.adoc
- Remember the end of the last annotation and do not accept any new annotation that starts earlier than that
> #758 - OpenNLP NER fails on overlapping annotations

- inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.html
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.properties
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception-recommendation/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation.adoc
- Add a proper validator for the name field which checks if a recommender by the same name already exists and provides a suitable error message in this case
- Add an option to auto-generate the recommender name to avoid forcing the user into inventing names all the time
**How to test**
* try creating new recommenders and editing existing recommenders with and without auto-generating the name
* try changing the recommender configuration with auto-generation enabled/disabled to see if/when the name is updated based on the configuration
* try creating recommenders with emtpy names and duplicate names
> #746 - Creating two recommenders with same configuration throws

- inception-doc/src/main/resources/META-INF/asciidoc/common/migration.adoc
- inception-doc/src/main/resources/META-INF/asciidoc/common/systemrequirements.adoc
- pom.xml
- Enforce minimum Java version 9 using maven enforcer plugin
- Updated system requirements
- Fixed some license headers
* Build using Maven on the command line on a Java 9 or higher
> #735 - Fix building on Java 11 (again)

- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
* If the optional concept is not present, throw a proper exception which is handled by client code and causes a the error to be shown as a feedback message
* Closes #813
1. Create a new local KB
2. Add a root concept which is in the KB
3. Clear the KB
4. Try opening the KB in the KB page
> #813 - Error page when root concept does not exist in KB

- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptInfoPanel.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ImportantStatementComparator.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/InstanceInfoPanel.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/PropertyPanel.java
* subproperty labels are taken into account by the statementgroup comarator of Concept-/Instance-/Property-InfoPanel
- check if the property is a subproperty
- prefer baseProperties in the PropertyPanel
* check if subproperty labels appear at the top of the statement group 
(base properties/domain/range can be above)
> #815 - Sub-properties not taken into account for getStatementGroupComparator()

- inception-app-webapp/src/main/resources/application.properties
- inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
- inception-kb/pom.xml
- inception-scheduling/pom.xml
- inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java
- inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/config/SchedulingProperties.java
- inception-scheduling/src/main/resources/META-INF/asciidoc/admin-guide/settings_scheduler.adoc
- inception-scheduling/src/test/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceTest.java
- Do not enqueue tasks if task of the same kind is already queued
- Add Spring configuration for scheduler properties
0. Maybe reduce the value for `scheduler.threads` to 1 or 2
1. Create a project with a slow running recommender
2. Annotate things very quickly
3. Look in the log whether you see `Task already in queue`
> #860 - Tasks are added even if same kind is already in queue

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
* Start TrainingTask instead of PredictionTask
1. Configure a project with a recommender (string matching is sufficient, do not enable "always active")
2. Create a few annotations such that the recommender generates suggestions
3. Restart application
4. Open the document again
5. See that there are annotations
> #877 - Recommendations not generated when opening a document

- inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebar.java
- Inject DocumentImporter via interface into Wicket component instead of via implementation to avoid serialization/proxying problems
* Open annotation page and *sometimes* observe strange errors in the log about DocumentImporterImpl not implementing some methods.
* https://github.com/inception-project/inception/pull/846 also observed problems because DocumentImporterImpl was used for injection.
> #825 - Split-screen external search and annotation view

- inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommender.java
- inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderTraits.java
- inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderTraitsEditor.html
- inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderTraitsEditor.java
- inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderTraitsEditor.properties
- inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngine.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- Skip training if there is no data to train on and provide a proper log message
- Construct the recommender within the try/catch block to allow catching problems that occur in the recommender construction
* Try using an external recommender on unannotated documents
> #922 - External recommender fails training when giving no casses

- inception-app-webapp/src/main/resources/application.properties
- Add default setting for remember layer turning it ON
> #928 - Remember layer default setting missing in application.properties

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- Remove scheduling of prediction cycle on DocumentOpened event because when opening a document, also an AfterAnnotationUpdateEvent is generated and we already react to that
> #931 - Training/prediction runs twice when document is opened

- pom.xml
* Setting the version maven enforces to `1.8`
* Build INCEpTION on the command line
> #936 - maven-enforcer-plugin enforces wrong Java version

- inception-pdf-editor/src/main/js/pdfanno/src/page/pdf/PDFAnnoPage.js
* remove caching on GET request for PDF file and pdftxt which fixes loading wrong PDF files
* open a PDF file
* restart INCEpTION
* open another PDF file
> #939 - PDF editor loads wrong PDF

- inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/config/ExternalSearchAutoConfiguration.java
- inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/exporter/DocumentRepositoryExporter.java
- Instantiate exporter component via auto-configuration and only if external search is at all enabled
* Start up INCEpTION without external search being enabled (default configuration)
> #277 - Import/export external search settings when importing/exporting project

- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- Forgot to actually skip processing the annotation before the NPE happens...
* See issue...
> #966 - Annotations not starting/ending at Token boundaries cause OpenNlpNerRecommender to crash

- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBConcept.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBInstance.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBProperty.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/RdfUtils.java
- Removing unused code
- Inline a method in RdfUtils which was only used internally in RdfUtils after the code has been removed
* There is no need to test anything. If it still compiles, it should be good.
> #1027 - Remove unused read() methods from KBObject subclasses

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- Disable the threshold for using the user's query in prefix/contains searches for local KBs
1. Import this OLiA ontology: http://purl.org/olia/penn.owl
2. Configure the label IRI as `http://purl.org/olia/system.owl#hasTag`
3. Search for `J` on the KB page
> #1038 - Optimize differently for large (remote) and small (local) KBs

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryPrimaryConditions.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- Actually consider scope when generating candidates
- Allow using the children axis not only for class queries, but also for instance and item queries
- Added additional tests for the children axis
* Create remote KB connecting to `http://nlp.dainst.org:8888/sparql` (OWL mapping)
* Edit the `identifier` feature of the `NamedEntity` layer, limit it to the KB just created, allow only instance and limit to `work` (`org/efrbroo/F1_Work`) - check the IRI appearing in the feature list because there are probably at least two items called `work` in the KB.
* Annotate a word as named entity
* Enter `Liba` into the identifier field
* Only items starting with the IRI `http://purl.org/hucit/kb/works/` should appear (cf. issue #958 for screenshot showing …
> #958 - KB instance not properly filtered when annotating

- inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchResult.java
- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- Cleaned up and simplified code which converts the Mtas results into sidebar results
- Properly fill in whitespace between tokens based on the original whitespace in the text
- Always search for tokens even if for some reason the token layer is marked as "disabled" in the database
> #975 - Search sidebar does not find last token in a document

- inception-pdf-editor/src/main/js/pdfanno/src/core/src/render/renderKnob.js
- inception-pdf-editor/src/main/js/pdfanno/src/core/src/render/renderSpan.js
* make knob color for span annotations the layer color instead of blue
* Open a PDF in PDF editor
* if no is present create a span annotation
* see color of span annotation knob
> #1056 - Knob color in PDF editor

- inception-imls-dl4j/pom.xml
- inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommender.java
- inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTraits.java
- inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java
- inception-imls-dl4j/src/test/resources/log4j2.xml
- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java
- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTraits.java
- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderTraits.java
- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java
- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderTraits.java
- inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTest.java
- inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderTest.java
- inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderTest.java
- enable multi-threading for OpenNLP recommenders during test runs
- Introduce the ability to limit the training and prediction size to DL4J and OpenNLP recommenders
- Limit training size and prediction size in tests to 250 units
* This is about automatic builds/testing - no need to test manually
> #1079 - Reduce build times

- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/editor/StatementEditor.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/editor/StatementEditor.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/IriValueSupport.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/NumericLiteralValueSupport.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/StringLiteralValueSupport.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/editor/IRIValueEditor.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/editor/StringLiteralValueEditor.java
- Require value when saving a string or IRI statement to avoid NPE - display message if value is missing
- Explicitly check again on actionCreate in case the form validator was somehow bypassed - display message if value is missing
- Improved layout of statement editor
- Changed names of value types (now: String, Resource, Number, Boolean)
> #1095 - Creating a statement with KB resource and empty value throws

- inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommender.java
- inception-imls-dl4j/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTest.java
The sequences in the DL4j recommender are padded with NO_LABEL if no annotation exists yet for a token. This e.g. happens during the NER evaluation test. In this case, the predictions for this test are only NO_LABEL.
* not applicable
> #1101 Evaluating DL4J as NER recommender only predicts NO-LABEL

- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- Send a trivial query to a remote repo before running the actual test. If that query fails, assume the repo is not available for testing.
* Run unit tests without UKP VPN enabled.
> #1115 - Run tests against remote repos only if they are available

- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/traits/ElasticSearchProviderTraitsEditor.html
- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/traits/ElasticSearchProviderTraitsEditor.java
- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/traits/ElasticSearchProviderTraitsEditor.properties
- inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/project/DocumentRepositoryEditorPanel.java
- inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/project/ProjectDocumentRepositoriesPanel.java
* Max. number of returned results for external search is now configurable in the repository traits. The hard-coded upper limit is 25000.
* Min. number is also hard-coded at 1.
* resolves #988 
* Enter "Document Repositories" tab in project settings
* Specify result size (play around and try illegal numbers)
* Execute external search query and observe whether number of returned results matches the specified result size
> #988 Make max. results configurable for ElasticSearch repos

- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/ElasticSearchProvider.java
- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/traits/ElasticSearchProviderTraits.java
- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/traits/ElasticSearchProviderTraitsEditor.html
- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/traits/ElasticSearchProviderTraitsEditor.java
- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/traits/ElasticSearchProviderTraitsEditor.properties
* make the default_field configurable for ElasticSearch queries
* resolves #1128
* configure the "Field" trait in the document repository traits for the gigaword document repository to `metadata.id`
* execute search query `NYT_ENG_20000114.0283`
* exactly one result should be returned
> #1128 Make default_field configurable for ElasticSearch queries

- inception-pdf-editor/src/main/js/pdfanno/src/page/textLayer.js
- inception-pdf-editor/src/main/js/pdfanno/src/pdfanno.js
- Avoid accessing the first rendered page if it has not been rendered yet
* Basically open and PDF - for me the error described in the issue happened *always* when opening a PDF document after coming from the dashboard page
> #1089 - PDF Editor Viewport undefined

- inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/sidebar/ImageSidebar.html
- Move the "scrolling" class one element up in the hierarchy to avoid the list jumping back to the beginning when it is updated
- Show the "open in new window" button translucently unless mouse hovers over it
* Add many annotations with image features linking to some images such that the image sidebar starts showing a scroll bar
* scroll a bit down in the sidebar
* select annotations or add/remove annotations and observe that the scroll position does not change
* check that the "open in new window" button in the top-right of every image in the sidebar is translucent unless you move the mouse over it
> #1119 - Images jump back to top after new annotation tag

- inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/LearningCurveChartPanel.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
The anchoring mode (e.g. lock-to-token) can be changed by the user even after a layer has been created. Recommenders usually do not work for all modes - only for certain ones. This means that the layer configuration can become inconsistent with the configured recommenders.
- When a recommender job is run (train/evaluate/predict) the scheduler must check if the recommender still accepts the layer configuration - if not, display an error to the user and skip the recommender
- On the recommender tab in the project settings warnings should be shown if recommenders
are inconsistent with the configuration of the layer they are defined on
* Create a layer with a given anchoring mode
* Create a recommender that supports this mode
* Change the …
> # 542 recommender layer anchor mismatch

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/LearningCurveChartPanel.java
* Learning curve is shown when enabled.
* Enable the display of the learning curve in the projects.settings
* Configure and enable a recommender.
* Annotate.
* Open the recommender sidebar to show the learning curve.
* not applicable
> #1137 Learning curve is not shown on annotation page

- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderFactory.java
- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderFactory.java
- Allow concept features for the OpenNLP pos tagger
- Formatting
* Set up a local KB from the "OLiA - Penn Treebank tagset (morphosyntax)"
* Set up a custom layer with single-token granularity and a concept feature
* Set up OpenNLP POS recommender for that layer/feature
> #1178 - Allow OpenNLP POS tagger for concept features

- inception-app-webapp/pom.xml
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/TeiFormatSupport.java
- Added TeiFormatSupport integrating the DKPro Core TEI reader/writer
- Added dependency on DKPro Core TEI module
* Import a TEI file, e.g. http://www.perseus.tufts.edu/hopper/dltext?doc=Perseus%3Atext%3A1999.03.0025
* View the file
* Export it again - mind that it is not expected that all data from the original file will be present in the export!
> #1201 - Support reading TEI format

- inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/feature/ImageFeatureEditor.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
- Change feature label HTML code such that a span is used instead of a wicket:container as no style/JS can be attached to the latter
> #1219 - Description tooltips not showing for feature labels

- inception-app-webapp/pom.xml
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/PerseusFormatSupport.java
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/PerseusReader.java
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/perseus/internal/model/PerseusSentence.java
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/perseus/internal/model/PerseusWord.java
- pom.xml
- Added reader for the Perseus XML format - may not cover the whole format semantics, but most of the part which INCEpTION can easily understand, e.g. POS, Lemma and Dependencies
* Import files from the Perseus treebank
> #1223 - Support reading the XML format for the Perseus treebank

- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/ElasticSearchProvider.java
Related:
* inception-project/inception/pull/1181
* isi-vista/curated-training-annotator/issues/16
* inception-project/inception/issues/987
* Fixed bug in `ElasticSearchProvider.java` where the term match score overshadows the random noise for randomly ordering search results
* In previous version with random order enabled, if you search a term, then more relevant results still show first. Now, results are really random
**Remaining Problems**
* **Seeding is not working.** In one session, if you search the same term twice, then you will get results in a different order.
> Fix random search for java api

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/event/RecommenderEvaluationResultEvent.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/log/RecommenderEvaluationResultEventAdapter.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/LearningCurveChartPanel.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
After having now implemented more than one score for the recommender I want to add them to the Details field of the LoggedEvent. This will allow us to retrieve and show different metrics in the learning curve on the annotation page (see #1103).
Store the EvaluationResult object from the evaluation that is done in the SelectionTask in the RecommenderEvaluationResultEvent and then put the respective scores in the details json in the RecommenderEvaluationResultEventAdapter.
* Add recommender to your project
* Annotate and check that learning curve is still drawn accurately
> #1215 Write recommender evaluation scores to event log

- inception-support/pom.xml
- inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/ui/LinkProvider.java
- inception-ui-core/pom.xml
- inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/ActivitiesDashlet.html
- inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/ActivitiesDashlet.java
- inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.java
After accessing a last activity via the link in the project dashboard, one can no longer open another document via the Open menu item on the annotation or curation page.
* Implemented a provider for external links with manually built url
* Using this in SearchPage and LastActivitiesDashlet
* Annotate or curate two documents
* Open one via the last activities link on the project dashboard page
* Try to open the other.
* Configure a document repository
* Search it on the search page
* Make sure that imported documents can still be opened via the Open link.
> #1238 Cannot open pages from last activities

- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/ElasticSearchProvider.java
- inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebar.java
* query does not return source document information (e.g. text)
* therefore ExternalSearchResult does not store text anymore
* ExternalSearchProvider.getDocumentText() is used to get the text through a separate request
* resolves #628 
* search for documents in an external search repository (should be faster hopefully)
> #628 Improve performance of loading results from external search

- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/DocumentOpenedEventAdapter.java
Webanno added a new field to the DocumentOpenedEvent to account for events where a different user opened the document than the original annotator. The adapter will need to be changed to log the correct users involved.
* changed DocumentOpenedAdapter to report user and annotator of opened event
Additional context
Due to a change in Webanno webanno/webanno#1329
* Open documents for annotation as the logged in user and for another user
* check the database for logged events related to these actions
> #1260 Adapt DocumentOpenedEventAdapter to Webanno Change

- inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchQueryRequest.java
- inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
* bugfix for #790 
* make a DB query for all SourceDocuments that have an AnnotationDocuments once before iteration over all the documents of a span
* change SearchQueryRequest to save the User instead of just the Username
* make queries in the search sidebar, see if it still works and if possible test if it is faster then before for large projects 
> #790 - DB accesses during in-project search slow down process

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
- Initialize training states only when creating a new recommender
> #1300 - Disabled training states reset when re-opening recommender

- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java
- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderFactory.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- Close and post recommender context for recommenders where training is not supported
- Do not close and post recommender context if training is required by no CASes are available for training
- Fix handling of gazeteer in StringMatchingRecommender
1. Create a string matching recommender
2. Upload a gazeteer
3. Make an annotation on the predicted layer
4. See how the gazeteer is now used to make predictions
5. Disable all the training states on the gazeteer
6. Log out and log back in again (to clear the recommender state)
7. Go to the annotation page again and see that nothing is recommended anymore
> #1273 - Explicit recommender training capabilities

- inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommender.java
- External recommender is always ready to predict if it is not trainable
* Create an external recommender and see if you get recommendations
> #1327 - Untrainable external recommender thinks it cannot predict

- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AfterCasWrittenEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/RelationEventAdapter.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- Adjust to changes in upstream API
- Listen to DocumentOpened and Annotation events to trigger recommendations
- Don't trigger training run when a recommender is deleted - this can wait until the next time annodations are edited / documents are opened
- Don't trigger training run when a recommender was deleted, removing its predictions from the context is sufficient
- Use RecommendationStateKey instead of a Pair for the trainingTaskCounter as well
- Clear recommendation state for all users of a project when a new document is added or when a document is removed
* Switch between documents and check that no training run is triggered
* Open a document and/or make a change and see that a training run is triggered …
> #1342 - Training run scheduled whenever a CAS is saved even if there were no changes

- inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception-imls-lapps/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/lapps/LappsGridRecommenderFactory.java
- inception-imls-lapps/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_lappsgrid.adoc
- inception-imls-opennlp/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_opennlp.adoc
- inception-imls-stringmatch/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_string.adoc
- Added rudimentary documentation
- Always enable LAPPS recommender (but leave setting to allow turning it off)
- Fixed some copyright headers
* Have a look at the documentation
* Start INCEpTION and check if the LAPPS recommender is enabled by default (remove the `recommenders.lappsgrid.enabled=true` line from the `settings.properties` before if it is there)
> #950 - Add LAPPS Grid external recommender support

- inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.properties
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/VisibilityCalculationTests.java
- inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/Task.java
- Remove call to upgrade "original" CAS
- Changed TrainingTask "containsTargetAnnotation" to be able to deal with the case where the target type and/or feature are not defined in a CAS yet
- Changed RecommendationServiceImpl "calculateVisibility" to be able to deal with the case where the target type and/or feature are not defined in a CAS yet
- Added button to the recommender sidebar to explicitly trigger a retraining
* Assume a project with multiple documents
* Create a new span layer with a new string feature
* Define some recommender on that string feature (best a StringMatchingRecommender)
* Open the first document in the annotation page (meaning the first document is upgraded to the new type system, but the other documents are still on …
> #1335 - Recommendationservice performance

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/MetricSelectDropDownPanel.html
- bug fix. The drop scrolls with the chart. 
* On the recommendation sidebar, the dropdown for the evaluation-metric change place when scrolling down. This means it sticks to the chart when the chart scrolls up.
* Configure several recommenders for the project.
* Go to the annotation page, open the recommendation sidebar.
* Scroll down
* the metric dropdown should also scroll with
> #1316 - Sidebar drop down does not scroll down

- inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBarEventAdapter.java
- Check if session exists before trying to get it to avoid exception when project is deleted via remote API
* See python script in issue description
> #1349 - Delete project endpoint fails with python's requests library

- inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
- inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/WrongFileFormatPanel.html
- inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/WrongFileFormatPanel.java
- add output of file format if it does not match PDF in the PDF editor
- add check for document format and display a message if format is PDF instead of showing the editor for PDF editor
* Open a non-pdf document in the PDF editor and see message that the format is wrong.
* Open a pdf document in the PDF editor and see the PDF editor as usual.
> #1082 - Editor loads files of wrong format

- inception-log/pom.xml
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java
- Increase batch size for persisting events
- Added a cache for looking up source documents to avoid having to look up the documents from the DB on every event
- Fixed bug that batch was not cleared after persisting
> #1356 - Importing of large event logs too slow

- inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
- fix check if feature is a slot feature in DocumentMetadataAnnotationDetailPanel
1. Create a document annotation layer with one or more features
2. Create a document annotation
3. Fill the features
4. Close and reopen the document annotation
5. The values should have changed
> #1362 - Document annotation feature values not saved

- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUtils.java
- inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java
- inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUtilsTest.java
- inception-search-mtas/src/test/resources/log4j2.xml
- inception-ui-kb/src/test/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupportTest.java
- Serialize CAS using a binary serialization
- Encode bytes into characters at the binary level to channel the serialized CAS into the MTAS core
- Use CAS instead of JCas in MtasUimaParser
> #1370 - Indexing crashes if document contains illegal XML character

- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/ConllUFormatSupport.java
- pom.xml
- Switch to WebAnno 3.6.0-beta-14 which has a patched CoNLL-U writer backported from DKPro Core
* Export a text with line breaks to CoNLL-U
> #1373 - Invalid Conll-U export of text reference (not on the same line)

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryPrimaryConditions.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/WikidataEntitySearchService.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- Disable FTS if a scoping function is called on the SPARQLQueryBuilder to ensure that the FTS doesn't take candidates away too early
- Added a test and JavaDoc documentation
* x ] PR includes unit tests
> #1382 - Scoped a concept feature may not generate any candidates

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_concept-features.adoc
- inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/knowledge_base.adoc
- Also return descendants
- Document new behavior
* Create an empty local KB
* Add a root concept
* Add a child and a child-child concept
* Add instances to the root, child and child-child concepts
* Configure Named Entity to be scoped to the child concept
* Try linking on the annotation page and make sure you can only reach instances from the child and child-child concept
> #1384 - Scoping a concept feature should also return descendants

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchResult.java
- inception-search-core/src/main/resources/META-INF/asciidoc/user-guide/search-core.adoc
- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Search results in finished documents can no longer be selected
- Do not show results from ignored documents
- Additional safeguards to not apply changes to finished documents
- Feedback messages for bulk operations
- Create BulkAnnotationEvent instead of generating an event for every added/changed/deleted annotation
> #1397 - annotation propagation changes the status of already finished documents

- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
If a user is viewing others' documents (as admin or for curation):
- disable recommendation sidebar forms
- do not show predictions
- do not trigger training
Closes #1388, #1377
For #1388 
* Configure recommenders for your project
* Get some suggestions for a user
* Log in as an admin user
* Open a document of the other user
* Make sure that no recommendations are shown and the recommendation sidebar is disabled
For #1377 
* Switch to curation page after annotating with recommendations
* Make sure that no recommendations are shown on the curation page
> #1388 Should not show recommendations for others

- inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
- fix handling for disabled layers for document metadata panel
1. Have a disabled document annotation layer
2. Open Document Metadata Panel
3. Click dropdown to select a layer
4. Disabled layer should'nt show up
Also already created annotatios in afterwards disabled layers should not show up anymore
> #1453 - Document metadata panel shows disabled layers

- inception-recommendation-api/marker-wicket-module
- There is a Wicket HTML template now in the recommender-api module (DefaultTrainableRecommenderTraitsEditor.html), so it must be marked as a Wicket module otherwise this file is missing from the JAR/WAR.
* Build on the command line
* Run JAR on the command line
* Try creating a trainable recommender (e.g. String Matching Recommender)
> #1467 - Attempting to create recommender with traits fails

- inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
- catch if pdfExtractFile and documentModel are null when creating span annotations in the PDF editor
1. Open a PDF document in PDF editor
2. Open the `Open` dialog to change the document
3. Select a document in the dialog
4. You need to be quick so make the selection by pressing enter and immediately select some text in the old document
5. There no should be an error warning instead of a NPE which lead to a complete crash
> #1090 - Crash when changing PDF document

- inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
- inception-pdf-editor/src/main/js/pdfanno/src/core/src/annotation/abstract.js
- pom.xml
- disable clearing armed slot when double clicking non-recommendation span annotations
- disable deselecting annotations in PDF editor in the PDF panel via annotation knobs
1. Arm a slot of a link feature
2. Double click a non-recommendation span annotation
3. Single click a non-recommendation span annotation to link it
> #1465 - Annotation linking after double click not working

- inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommender.java
- inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderFactory.java
- An external trainable recommender should be TRAINING_REQUIRED instead of TRAINING_SUPPORTED since we need some (training) CAS to get the type system from...
* See issue
> #1480 - External recommender crashes if there are no CASes

- inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/feature/ImageFeatureEditor.java
- inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/PropertyFeatureEditor.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/QualifierFeatureEditor.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/SubjectObjectFeatureEditor.java
- adapt feature editors to new method signature for getFocusComponent
- adapt document metadata panel to choice component handling changes from annotation panel
1. Have a string feature in a document annotation
2. Have a rating feature in a document annotation
3. Edit the string feature text
4. Click on a value of the rating feature
5. String feature changes should be saved
> #1490 - Adapt changes for Choice Components from WebAnno

- inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditorFactory.java
- Enable PDF UI support by default - it is already in the documentation, not having it enabled is a bit confusing, in particular since the documentation does not say how to enable it.
* Remove the `ui.pdf.enabled=true` from the `settings.properties`
* Restart
* Import a PDF file
* Open the file in the annotation view
* Try switching to the PDF editor mode
> #1505 - PDF (PDFAnno) Editor not shows up in Settings

- inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderFactory.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- Adjusted suggestion extraction for the different anchoring modes
- Allow configuring external recommenders for all anchoring modes
* Try the usual recommenders on different levels of granularity
* Try using an external recommender on the character-level granularity
> #1508 - Support character-level external recommenders

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
- Load all features of a layer once during rendering instead of repeatedly fetching individual features from the DB
* Use a project with recommenders and see if the suggestions show up ok
> #1528 - Reduce database accesses during recommendation rendering

- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java
- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderFactory.java
- inception-imls-stringmatch/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_string.adoc
- inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderTest.java
- Allow using the string matching recommender on layers with character granularity and document behavior on these
- Allow using the string matching recommender on layers which allow cross-sentence annotations
* Create a text file with contents like this:
```
blah blah blah
blah blah blah
blah blah blah
```
* Import the file as "Plain text (one sentence per line)"
* Configure a span layer with character granularity and allowing cross sentence. Mind the layer must have one string feature
* Configure a string matching recommender for that string feature
* Annotate using this layer on the annotation page and check how recommendations behave
> #1539 - String-based recommender on layers with character-level granularity

- inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
Searching of other people's annotations is now possible.
* Searching for user saved in state not the current one
* If admin is searching other people's annotations, she should not be able to manipulate the annotations
* As an admin have some annotations.
* Open the document of another user (via the Open Document Dialog).
* Search for annotations using the search sidebar.
* Make sure that the results are annotations that the selected user made.
> #1391 Searching others' docs will search own annotations

- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_concept-features.adoc
- Allow filtering candidates by description using `::` separator
- Allow filtering candidates by label using `"..."` quoting
- Added documentation for the new features
* Configure Wikidata as the KB
* Annotate a document on the Named Entity layer
* See documentation how to use the quote and :: operators
* Try using them to filter candidates return by Wikidata
> #1549 - Filter entity candidates by description

- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/css/inception.css
- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandle.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/KnowledgeBaseItemAutoCompleteField.java
- Disable auto-sizing the dropdown list in favor of using a fixed 30% of the screenwidth and a minimum of 300 pixels
- Use more vertical space for the dropdown if such space is available
- Added footer to concept feature editor indicating the number of items found
- Added rank information to the matching concepts
- Fixed issue that dropdown closes when the surrounding document scrolls (e.g. due to a scroll-down rubberband effect)
* Try linking some concepts and check if the dropdown appears ok
> #1517 - Description of KB items is cut in the concept editor

- inception-layer-docmetadata/pom.xml
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/KnowledgeBaseItemAutoCompleteField.java
- Fixes issue of items with the same label being confused by frontend and backend by using IRI as an identifier
- Improve performance of linking an entity by not fetching the choices again if we still have them from filling the dropdown
- Avoid sending redundant data to the UI
- Add area with entity description below the entity linking field
> #1559 - Problems if multiple entities have the same label

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategy.java
- If mention or query are missing, then calculate weighted distance only on the present information
- Give the query a slight edge over the mention in case both are the same distance
* See issue
> #1561 - Ranking is off if there is no mention to work with

- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/settings/StringMatchingRecommenderTraitsEditor.html
- inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.html
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/MetricSelectDropDownPanel.html
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
- inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
- inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.html
- inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage$ResultRowView.html
- inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.html
- inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebar.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/AbstractInfoPanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptListPanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/ConceptTreePanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/InstanceListPanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/IriInfoBadge.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/PropertyListPanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/DisabledKBWarning.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/SubjectObjectFeatureEditor.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/less/inception-ui-kbp.less
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSpecificSettingsPanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/RootConceptsPanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/QualifierEditor.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementGroupPanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementsPanel.html
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/editor/StatementEditor.html
- inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.html
- Switch to modern fontawesome classes
- Improve the flex layout of the statement editors
* Edit KB (see issue description)
* Can also click a bit through the rest of the UI to make sure I didn't accidentally break some HTML due to missing brackets or such while upgrading the CSS classes
> #1565 - Some fontawesome glyphs are no longer visible

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/ConceptFeatureValueType.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- Add the option for linking to properties
* Configure a KB to provide properties, e.g. Wikidata
* Configure the `identifier` property of the `Named entity` layer to link to properties
* Annotate some named entities and link them to properties (semantically doesn't make sense of course, but tests the functionality)
> #1563 - Allow configuring concept feature for properties

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImplTest.java
- inception-kb/pom.xml
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBaseProperties.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBasePropertiesImpl.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception-kb/src/main/resources/META-INF/asciidoc/admin-guide/settings_knowledgebase.adoc
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplImportExportIntegrationTest.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplQualifierIntegrationTest.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplWikiDataIntegrationTest.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceRemoteTest.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseSubPropertyLabelTest.java
- inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- Introduce a cache at the level of the KnowledgeBaseService which caches queries on a per-KB basis
- Invalidate caches if the configuration of the KBs of a project is changed
- Use cache for read-only KBs for most queries
- Introduce settings to configure the KB cache behavior
* Use entity linking
* Use the KB page
* To see cache usage, set the log level for the KB service to `TRACE`
> #1567 - Cache knowledge base query results

- inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommender.java
- Do not throw on 429
* Setup an external recommender that trains (preferably long) and see the log for errors regarding 429
> #1576 - External recommender should interpret 429 as busy

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.java
- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- First rank, then filter, then limit
- Turn parallel stream into stream
* Check that Paris is in Wikidata when linking it and searching via `paris::capital`
* Check that KB editor has maximum of display limit = 100 entries
> #1595 - KB entity not displayed in candidates' dropdown

- inception-app-webapp/pom.xml
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/ImsCwbFormatSupport.java
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/LifFormatSupport.java
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/NifFormatSupport.java
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/PerseusFormatSupport.java
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/TeiFormatSupport.java
- inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/UimaInlineXmlTeiFormatSupport.java
- inception-external-search-pubannotation/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/pubannotation/format/PubAnnotationSectionsFormatSupport.java
- inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/HtmlFormatSupport.java
- inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfFormatSupport.java
- inception-ui-core/pom.xml
- inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.java
- Adjust to upstream changes
- Remove unnecessary dependency on commons-fileupload (Wicket needs it and draws it in transitively)
- Mark the servlet-api as provided so we don't include it in the JAR/WAR builds
- Fix issue on external search page causing feedback messages not to be displayed when an import completes/fails
> #1623 - Reduce time when importing a large number of documents via the UI

- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/ElasticSearchProvider.java
- inception-external-search-elastic/src/main/resources/META-INF/asciidoc/user-guide/external-search-repos-elasticsearch.adoc
- Parse the URL and properly forward protocol, hostname and port info to the ElasticSearch client
- Centralize building of client to a single method
> #1658 - Port and protocol information for external document repositories ignored

- pom.xml
- DKPro Parent POM 23 -> 24
- Mockito 2.28.2 -> 3.3.3
- AssertJ 3.14.0 -> 3.15.0
- Spring 5.2.2 -> 5.2.6
- Spring Boot 2.2.4 -> 2.2.6
- Spring Security 5.2.2 -> 5.2.3
- Wicket 8.6.1 -> 8.8.0
- Wicketstuff 8.6.0 -> 8.8.0
- Log4J 2.12.1 -> 2.13.2
- Asciidoctor 2.2.0 -> 2.3.0
- Asciidoctor Diagram 2.0.2 -> 2.0.3
> #1688 - Upgrade dependencies (0.16.0)

- inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/config/ActiveLearningAutoConfiguration.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/metrics/RecommendationMetricsImpl.java
Active Learning sidebar was no longer shown.
* Fixed AL autoconfiguration to be conditional on recommendersidebar factory instead of the sidebar itself.
* Made RecommendationMetrics conditional on recommenders enabled.
* Open the annotation page and check that the AL sidebar is there
* Check e.g. with jconsole that metric on enabled recommenders is calculated
* Test with settings `recommender.enabled=false`-> neither recommendersidebar nor AL sidebar should be shown
* Test with settings `recommender.active-learning.enabled=false`-> recommendersidebar should be shown but not AL sidebar
> #1715 AL sidebar is missing

- inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationServiceImpl.java
* Check that user list is not null or empty before querying database.
1. Go to Annotation Page with curation sidebar enabled in properties file `curation.sidebar.enabled=true`.
2. Click on Curationsidebar
3. No error should occur
> #1742 CurationSidebar: error when no users are selected

- inception-doc/src/main/resources/META-INF/asciidoc/user-guide/getting-started.adoc
- inception-ui-core/src/main/resources/META-INF/asciidoc/user-guide/dashboard_menubar.adoc
- inception-ui-core/src/main/resources/META-INF/asciidoc/user-guide/dashboard_project-view.adoc
The user guide mentioned the *home* link in the header. However, this link only exists in webanno.
* Removed home mentions
* updated menu bar description
* Build the user guide
* Read the introduction in *getting started* and the section on the menu bar
> #1763 Change Home Button references in documentation

- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java
* Do not send empty FTS queries to Fueski
* Have a text with "1-1" or "vs." and try to entity link that span
> #1792 - Specific token spans cause SPARQL queries to fail in Fuseki

- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
Dismissing recommendations by double-click did no longer work because the document was not re-rendered.
* Trigger reloading differently in editor extension
* Have a recommender enabled and start annotating
* dismiss a recommendation, it should disappear immediately
> #1810 Dismissing recommendations no longer works

- inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/footer/resources/tutorial.js
- inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/settings/ProjectWorkloadSettingsPanelFactory.java
Tutorial failed because of change from previous tab order of the setting tabs. Naming the recommender tab that we want to select here does not work, because they are represented as links at the time. We will have to keep identifying the correct tab by order.
* Change back to previous tab order.
* go through the tutorial and check that everything works
> #1812 Tutorial fails on setting tabs

- inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUtils.java
- pom.xml
- Add explicit type cast to avoid linking to a non-Java-8 version of the `flip()` method
- Strictly speaking, this does not fix the import issue (the import issue is fixed by an upstream fix in [WebAnno](https://github.com/webanno/webanno/issues/1795)), but it fixes the same problem in the project search.
```
2020-10-27 08:58:51 ERROR [SYSTEM] [dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
at de.tudarmstadt.ukp.inception.search.index.mtas.MtasUtils.decodeFSAddress(MtasUtils.java:63) ~[inception-search-mtas-0.17.0.jar!/:?]
at …
```
> #1828 - Error in importing projects

- inception-external-search-elastic/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/elastic/traits/ElasticSearchProviderTraits.java
- inception-external-search-elastic/src/main/resources/META-INF/asciidoc/user-guide/external-search-repos-elasticsearch.adoc
- Update default object type to "_doc"
- Added simple testing example of ElasticSearch to the documentation
> #1852 - Default ElasticSearch document repository settings do not work

- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
- pom.xml
- Improve synchronization on event log to avoid empirically observed deadlock with huge tagsets on HSQLDB
* Import project with huge tagset while running with embedded DB
> #1868 - Deadlock importing project with large tagset on HSQLDB

- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
- Mark the KB read-only only at the end of the import process to fix the issue
> #1921 - Import of project with read-only KB fails

- inception-log/pom.xml
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/TagEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/config/EventLoggingAutoConfiguration.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/config/EventLoggingProperties.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/config/EventLoggingPropertiesImpl.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/model/TagDetails.java
- inception-log/src/main/resources/META-INF/spring.factories
- Convert logging module to auto-configuration
- Add setting for excluding events from being logged
- Exclude some events by default
- Added a proper adapter for tag events
* Add/remove tag and check event log
* Check that default-excluded events are not written to the event log but other events are
> #1919 - Allow excluding events from being logged

- inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/log/ActiveLearningRecommendationEventAdapter.java
- inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/log/ActiveLearningSuggestionOfferedAdapter.java
- inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/log/ExternalSearchQueryEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AfterDocumentCreatedEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AfterProjectCreatedEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AnnotationStateChangedEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/DocumentStateChangedEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/EventLoggingAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/FeatureValueUpdatedEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/GenericEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/ProjectStateChangedEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/RelationEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/SpanCreatedEventAdapter.java
- inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/SpanDeletedEventAdapter.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/log/RecommendationAcceptedEventAdapter.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/log/RecommendationRejectedEventAdapter.java
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/log/RecommenderEvaluationResultEventAdapter.java
- inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/log/SearchQueryEventAdapter.java
- Let the adapters throw an exception when generating the details so they do not have to return "<ERROR>"
- If an adapter generates and exception, let the EventLoggingListener report the error and then just skip logging the event
* Check if exporting and importing still works - in particular if the events are exported/imported
> #1923 - Error during log writing creates unparseable JSON

- inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- Redraw badge and link when updating the feature value
* See issue
> #1954 - Info badge and link to not appear immediately when linking concept

- inception-app-webapp/pom.xml
Asciidoctor images directory attribute was not used and therefore no images showed up in the documentation.
* Moved imagesDir into attributes
* Build with Maven and look at the generated documentation. There should be pictures.
> #1966 No images in guides

- inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- When not using FTS, line breaks in the SPARQL query can break the query - so we need to remove them / replace them with spaces
* See recent comment on issue
> #1600 - Annotations crossing a line border and linking to a knowledge base are not possible

- inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
* Moved query for label to secondary pattern for query with regex in *matchAnyOf...* if Fulltextsearch is not available. This is still slow, but we get a result.
* Add wikidata as your knowledge base
* Configure a layer with a concept feature, restrict the feature to properties
* Annotate a text span and try setting the feature by searching for something
> #1971 Cannot annotate properties only concept feature with wiki-data

- inception-support/pom.xml
- inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/spring/BeanInitializationTimesLogger.java
- Disable BeanInitializationTimesLogger by default
- Even if it is enabled, kill it once the application has started up
* I put a breakpoint into the bean and checked it is not called during startup if the property enabling it is not set
> #1996 - Memory leak in BeanInitializationTimesLogger

- inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java
- Fixed comparison of coverage against threshold
> #2034 - OpenNlpPosRecommender provides no suggestions if tagged token is set to 100%

- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java
- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/trie/Trie.java
- inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/trie/TrieTest.java
- Fixed handling of prefix length when retrieving a trie node
> #2031 - StringMatchingRecommender fails to find some matches

- pom.xml
- Update Font Awesome to a version that includes the icon that was missing
> #2050 - Cannot see agreement menuitem icon

- inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/config/DashboardAutoConfiguration.java
- inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/ProjectSettingsDashboardMenuItem.java
- inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/ProjectSettingsPageMenuItem.java
- Fix issue that admins do not see the settings menu item
- Make the new dashboard-like settings the default
* Log in as admin
* Enter a project where the admin user does not have any role
* Check if the settings button is there
* Check if clicking on the settings button takes you to the dashboard-like settings page
> #2043 - Turn the project settings into a dashboard-like construct

- inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationEditorExtension.java
- inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/CurationVID.java
- inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/CurationVIDTest.java
- Fix issue by adapting CurationVID parsing / generation
- Use ! character to separate username from payload because ! is not allowed in usernames
> #2077 - Unable to merge via curation siderbar if username contains "."

- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java
- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderFactory.java
- inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngine.java
- inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngineFactory.java
- inception-recommendation/pom.xml
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.html
- inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- Added option to export the current model from the recommender sidebar on the annotation page
* Configure a string matching recommender (currently the only supported one)
* Make some annotations
* Open the recommender sidebar 
* Export the model
> #1117 - Ability to export recommender model

- inception-imls-stringmatch/pom.xml
- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java
- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderTraits.java
- inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/gazeteer/GazeteerServiceImpl.java
- Allow additional columns in gazeteers
- Avoid potential exception when serializing StringMatchingRecommenderTraits
- If a gazeteer is set, do not mark the evaluation as skipped even if there is no evaluation data so that the recommender may get activated
* Import some pre-annotated data (e.g. Part-of-speech from GUM)
* Create String matching recommender for POS
* Export its model
* Create new project with fresh document
* Also create String matching recommender for POS
* Import the previously exported model as a gazeteer
> #2086 - Import string matcher models as gazetters

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/TokenWrappingPagingStrategy.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratTokenWrappingAnnotationEditorFactory.java
- inception/inception-brat-editor/src/test/java/de/tudarmstadt/ukp/clarin/webanno/brat/message/BratRendererTest.java
- inception/inception-brat-editor/src/test/resources/longlines.json
- inception/inception-brat-editor/src/test/resources/longlines.txt
- Added a new "brat wrapping" mode which tries to wrap lines at 120 characters respecting token boundaries
* Import a document
* Switch to "brat (wrapping @ 120 chars)" mode
* Check if rendering, paging, annotation works
> #1516 - Long annotations (e.g. sentences) don't allow lines to wrap

- inception/inception-imls-stringmatch/pom.xml
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommender.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderFactory.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderTraits.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/settings/StringMatchingRecommenderTraitsEditor.html
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/settings/StringMatchingRecommenderTraitsEditor.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/settings/StringMatchingRecommenderTraitsEditor.properties
- inception/inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderTest.java
- inception/inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/gazeteer/GazeteerServiceImplTest.java
- inception/inception-ui-core/pom.xml
- Add case-sensitivity switch to string matcher
- Make string matcher unit tests run again
- Fix a bunch of bugs that got undetected because the unit tests did not run
* Enable case insensitivity in string recommender
* Have a text in which a word appears in different capitalizations
* Annotate one of the words, look for suggestion on the other
> #2105 - Gazetteer Case Sensitive

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorFactory.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorRegistry.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorRegistryImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/NoPagingStrategy.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/AnnotationPreferencesDialogContent.java
- inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/HtmlAnnotationEditorFactory.java
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditorFactory.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- Added "auto" option to the list of viewers and made it the default for new projects
- Added API for editors to say how well they support a certain format and whether they should be preferred
* In a project with multiple types of documents (text, html, pdf) set the editor to "auto" in the annotation page preferences
* Switch between the documents
> #2126 - Open proper editor for document

- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer_ui.js
- inception/inception-io-text/src/main/java/de/tudarmstadt/ukp/clarin/webanno/text/TextFormatSupport.java
- Added support for lazy details on relations in the brat visualization
* Create relation layer
* Add wikidata knowledge base
* Add concept feature on the relation layer
* Annotate a relation with a concept that has a description
* Hover over the relation to see the concept description in the popup
> #2133 - Support lazy details on relations

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_general.adoc
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorPage.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorPage.java
- Display a message that a stack trace was not shown because a user has no permissions to see it - tell user to ask admin
- Remove the documentation for "debug.showExceptionPage"
> #2151 - Clearer handling of stack traces on the error page

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/config/ActiveLearningAutoConfiguration.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebarFactory.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/LayerSupportRegistryImpl.java
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
- inception/inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/ExternalSearchService.java
- inception/inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/ExternalSearchServiceImpl.java
- inception/inception-image/src/main/java/de/tudarmstadt/ukp/inception/image/sidebar/ImageSidebarFactory.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/config/DocumentMetadataLayerSupportAutoConfiguration.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataSidebarFactory.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebarFactory.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/docinfo/DocumentInfoSidebarFactory.java
- inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPageMenuItem.java
- inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/config/ExternalSearchUIAutoConfiguration.java
- inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebarFactory.java
- Show external search sidebar only if there are external repos
- Show document metadata sidebar only if there is am enabled layer of type document metadata
- Show the recommender / active learning sidebars only if there are enabled recommenders
- Show image sidebar only if there is an enabled feature of type image-url on any enabeld layer
- Disable the document info sidebar - that was mainly a toy to get the sidebar off the ground
* Disable search in the settings.properties file
* Enter into a project as a plain annotator
* See that there is no sidebar anymore at all
* Fulfill any of the prerequisites for sidebar items to show up and check that the corresponding sidebars appear
> #2156 - Sidebar cluttered with unused items

- inception/inception-telemetry/pom.xml
- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/TelemetryServiceImpl.java
- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/TelemetrySupport.java
- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/config/TelemetryServiceAutoConfiguration.java
- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/config/TelemetryServiceProperties.java
- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/config/TelemetryServicePropertiesImpl.java
- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetrySupportImpl.java
- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/model/TelemetrySettings.java
- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/ui/TelemetrySettingsInterceptor.java
- inception/inception-telemetry/src/main/resources/META-INF/spring.factories
- Switch module to auto-configuration including adding a switch to turn it off
- Added an auto-respond setting
- Fixed properly setting the "created" timestamp in the telemetry setting DB entry
* Add e.g. `telemetry.auto-respond=ACCEPT` to the properties file
> #2159 - Ability to accept/reject telemetry without user interaction

- inception/inception-security/pom.xml
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDao.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityProperties.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityPropertiesImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/model/User.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
- Added option to set an encoded default admin PW
- Added option to allow remote API access to default admin user
* Try the new settings
> #2164 - Override default admin password and allow remote access

- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
- inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/SearchPage.html
- inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebar$ResultRowView.html
- inception/inception-ui-external-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/externalsearch/sidebar/ExternalSearchAnnotationSidebar.html
- Fix importing a document via the external search sidebar by wrapping the import in a separate storage session - this avoids the INITIAL_CAS being locked by the current session while it is then later again attempted to be locked by an isolated session that runs as part of initializing the annotation document in order to load it in the editor
- Fix scroll position jumping when importing a document via the external search page
- Fix external search sidebar exploding when a document has a long title
> #2172 - Importing documents from external search sidebar gives errors

- inception/pom.xml
- Hibernate 5.4.15 -> 5.4.30
- Hibernate Validator 6.1.4 -> 6.2.0
- Javassist 3.26.0 -> 3.27.0
- byte-buddy 1.10.2 -> 1.10.22
> #2161 - Upgrade dependencies

- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/AgreementUtils.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/cohenkappa/CohenKappaAgreementMeasure.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/fleisskappa/FleissKappaAgreementMeasure.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalpha/KrippendorffAlphaAgreementMeasure.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/CodingAgreementMeasure_ImplBase.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/CodingAgreementResult.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/PairwiseCodingAgreementTable.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/unitizing/PairwiseUnitizingAgreementTable.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureTestSuite_ImplBase.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementTestUtils.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/CohenKappaAgreementMeasureTest.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/FleissKappaAgreementMeasureTest.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/KrippendorffAlphaNominalAgreementMeasureTest.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/KrippendorffAlphaUnitizingAgreementMeasureTest.java
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
- If there is a tagset, forward it to the agreement calculation measure
- Added unit tests for KrippendorffAlphaUnitizingAgreement
> #2191 - Agreement does not take tagset into account

- .gitignore
- inception/inception-ui-curation/pom.xml
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- Use a splitter to make the height of the top-part adjustable
* Try using the curation page and adjusting the splitter
* Mind that the splitter position is not remembered across page loads - but accepting an annotation, paging and switching between documents should (probably) not make the splitter jump
> #2195 - UX / Curation / Bad UX with multiple annotators

- inception/inception-imls-opennlp/pom.xml
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- Upgrade to OpenNLP 1.9.3
- Fix bug that single adjacent token at end is always considered part of the training data (e.g. full stops)
- Avoid NPE if score or prediction flag features are missing from type system
> #2216 - Multi-Token Sequence Classifier (OpenNLP NER) matches an additional token

- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalphaunitizing/KrippendorffAlphaUnitizingAgreementMeasure.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureTestSuite_ImplBase.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/CohenKappaAgreementMeasureTest.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/FleissKappaAgreementMeasureTest.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/KrippendorffAlphaNominalAgreementMeasureTest.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/KrippendorffAlphaUnitizingAgreementMeasureTest.java
- Fixed issue by ensuring that annotations extracted from CASes are re-based using the offset of the document containing them within the batch continuum
* See issue
> #2219 - Krippendorff's Alpha Agreement = 1.0 (Unitization) although documents differ completely

- inception/inception-sharing/pom.xml
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.html
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/InviteService.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/InviteServiceImpl.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/model/Mandatoriness.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/model/MandatorinessType.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/model/ProjectInvite.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/InviteProjectSettingsPanel.html
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/InviteProjectSettingsPanel.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/InviteProjectSettingsPanel.properties
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/exporters/ExportedProjectInvite.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/exporters/ProjectInviteExporter.java
- inception/inception-sharing/src/main/resources/de/tudarmstadt/ukp/inception/sharing/model/db-changelog.xml
- Optionally ask or require user to enter a mail address when accepting an invite
- If the mail address provided does not match a previously provided one, then login fails
* Configure invite with different levels of mandatoriness for the email address
* Accept invites and try also providing two different email addresses for the same nick
> #2231 - Allow asking user for mail address on the accept invite page

- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/relation/StringMatchingRelationRecommender.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.html
- If the threshold is 0, do not fail evaluation if there is insufficient training data
- Slightly improve layout of recommender sidebar
* Try e.g. string matching or OpenNLP recommenders
> #2247 - Insufficient eval data should not fail eval if threshold is 0

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/StringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/config/PrimitiveUimaFeatureSupportProperties.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/NumberFeatureTraits.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RadioGroupStringFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RadioGroupStringFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraits.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.java
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_annotation-editor.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/webanno-custom.scss
- inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
- inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_tagsets.adoc
- Add radio-group-based editor
- Add option to select the preferred editor in the feature traits
* Use with tagset <= 5 tags
* Manually configure which editor to use in the feature settings
* Also try with tagsets that have or have not descriptions
> #2243 - Directly select tags for small tagsets

- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserSelectionPanel.java
Fix create button.
* Check if realm id is null i.e. the global realm is selected and we should be able to create new users.
* Sign in as an admin
* Go to **Administration** -> **Users** and try to create a new user
* To check if user creation is still disabled for project specific realms (should be). 
* Add `sharing.invites.enabled=true` and `sharing.invites.guests-enabled=true` to your project settings. 
* Create invite links for a project in **Settings** -> **Sharing** and check `Allow guest annotators`
* Copy invite link and follow it after logging out to create a new project specific user
* As an admin again, check that you can switch in **Administration** -> **Users** between realms and only create users in the global realm
> #2279 No longer able to create new users

- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
- inception/inception-versioning/src/test/resources/log4j2.xml
- inception/inception-workload-dynamic/pom.xml
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImpl.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/config/DynamicWorkloadManagerAutoConfiguration.java
- inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/DefaultWorkflowExtensionTest.java
- inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/Fixtures.java
- inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/workflow/types/DynamicWorkloadExtensionImplTest.java
- inception/inception-workload-dynamic/src/test/resources/log4j2.xml
- inception/inception-workload/pom.xml
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/model/WorkloadManagementService.java
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/model/WorkloadManagementServiceImpl.java
- Move DB query method from WorkloadManagementService to DocumentService
- Use already existing method from DocumentService in favor of new method from WorkloadManagementService
- Added unit tests for default workflow policy including that abandoned documents immediately become available to users when switching to the next document
* No particular testing procedure
> #2264 - Risk of permanently unfinished documents using dynamic workflow

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
- inception/inception-imls-external/pom.xml
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommender.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderFactory.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/config/ExternalRecommenderAutoConfiguration.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/config/ExternalRecommenderProperties.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/config/ExternalRecommenderPropertiesImpl.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/messages/PredictionRequest.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/messages/PredictionResponse.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/messages/TrainingRequest.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/model/Document.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/model/Metadata.java
- inception/inception-imls-external/src/main/resources/META-INF/asciidoc/admin-guide/settings_recommendation_external.adoc
- inception/inception-imls-external/src/main/resources/META-INF/spring.factories
- inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderIntegrationTest.java
- inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/RemoteStringMatchingNerRecommender.java
- inception/inception-recommendation/src/main/resources/META-INF/asciidoc/admin-guide/settings_recommender.adoc
- inception/inception-sharing/src/main/resources/META-INF/asciidoc/admin-guide/settings_sharing.adoc
- inception/inception-versioning/src/main/resources/META-INF/asciidoc/admin-guide/settings_versioning.adoc
- inception/inception-websocket/src/main/resources/META-INF/asciidoc/admin-guide/settings_websocket.adoc
- Switched to auto-configuration
- Added feature switch
- Added settings for the connection / read timeouts
- Moved messages to own package
- Moved model classes to own package
- Update documentation
> #2263 - External recommender timeout too short and not configurable

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningServiceImpl.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.html
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ClearSelectionAndJumpToSuggestionKey.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorBase.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtension.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtensionRegistry.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtensionRegistryImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/model/VMarker.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/LogDialogContent.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/SpanSuggestionVisibilityCalculationTests.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
- Switch to new predictions when rendering is requested, not when rendering is performed
- This gives the AL sidebar the opportunity to change the viewport depending on the latest prediction information (which it couldn't do when rendering had already started)
- Add a flag to the request cycle indicating whether moving to a new suggestion should actually affect the viewport
- This flag helps disambiguating between actions triggered from the AL sidebar (do jump) vs. actions triggered via the main viewport (do not jump)
* Use active learning (also normal recommenders without active learning)
> #1182 - AL does not always jump to the text passage

- inception/pom.xml
- An upgrade to UIMA 3.2.0 seems to fix the issue. Note that the problematic file needs to be deleted and re-imported
> #2317 - Error: Feature "webanno.custom.EntiteitenArg_misdaadLink:role" is not defined for type "webanno.custom.EntiteitenArg_activiteitLink"

- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- Instead of falling back to WebAnno TSV, throw an exception if annotations cannot be exported in the requested or original format
> #2070 - Remote API should fail when unsupported format is requested

- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/event/ProjectPermissionsChangedEvent.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/event/ProjectPermissionsEvent.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/ProjectPermissionsChangedEventAdapter.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserPermissionsPanel.html
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/users/UserSelectionPanel.html
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImpl.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.html
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/support/AnnotationStateList.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/MatrixWorkloadExtensionImpl.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/event/MatrixWorkloadStateWatcher.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.html
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.properties
- inception/inception-workload/pom.xml
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/config/WorkloadManagementAutoConfiguration.java
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/event/RecalculateProjectStateTask.java
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/extension/WorkloadManagerExtension.java
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/model/WorkloadManagementServiceImpl.java
- inception/pom.xml
- After switching the workload manager (or rather after pressing save on the workload manager settings panel) recalculate the document state for the entire project
> #2335 - Document states not properly updated when switching betweeen workload managers

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_general.adoc
- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialogManager.java
- Added `commands.open-browser` setting.
* Set a custom command and start the standalone version
> #2347 - Allow setting command to open browser

- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/trie/Trie.java
- inception/inception-imls-stringmatch/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/trie/TrieTest.java
- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StandaloneShutdownDialogManager.java
- When matching against the trie, we need to obtain the match length and not the key length to check if the match has the expected length
> #2349 - String matching recommender not working with Windows linebreaks

- inception/inception-imls-dl4j/pom.xml
- inception/inception-imls-dl4j/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/dl4j/pos/DL4JSequenceRecommenderTraits.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderTraits.java
- inception/inception-imls-lapps/pom.xml
- inception/inception-imls-lapps/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/lapps/LappsGridRecommenderFactory.java
- inception/inception-imls-lapps/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/lapps/traits/LappsGridRecommenderTraits.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTraits.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderTraits.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommenderTraits.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/StringMatchingRecommenderTraits.java
- inception/inception-imls-weblicht/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/weblicht/traits/WeblichtRecommenderTraits.java
We now ignore unknown fields in recommender traits to not fail when switching recommender types and then reusing old traits with potentially unknown fields in them.
* Change from a saved string matcher to a remote one and see whether you get the error
> #2358 - Unrecognized fields when switching recommender type

- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
Clicking on the monitoring/workload menu item on the dashboard did not show the page but resulted in an `java.lang.IllegalArgumentException: Superclass has no null constructors but no arguments were given` error.
* Use named Springbeans to inject concrete ProjectMenuItems into specific workload pages.
* Go to Dashboard and click on the workload page
* See the workload page
* Re-Configure to use the dynamic workload via settings
* Go to the workload page again and check that this one can also be loaded
> #2375 Monitoring page is not shown

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/ChainRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/RelationRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/SpanRenderer.java
* typesystem.getlayer does not throw an exception when the type is not found instead it returns null, therefore check for null so types are not rendered if they are not in the typesystem 
* see issue
> #2377 Using activity link after layer creation NPE

- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/LiquibaseLockCheckAutoConfiguration.java
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/LiquibaseLockManager.java
- inception/inception-app-webapp/src/main/resources/META-INF/spring.factories
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/CurationServiceTest.java
- inception/inception-project/src/test/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImplTest.java
- inception/inception-support-standalone/pom.xml
- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/LoadingSplashScreen.java
- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/StartupErrorHandler.java
- inception/inception-support/pom.xml
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/db/LiquibaseLockManager.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/db/LockRemovedException.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/db/NotLockedException.java
- Hook in between DB initialization and Liquibase
- If there is a lock, generate an exception immediately
- Provide helpful message how to recover when running in standalone mode
- Actual unlocking when user requests is is not yet done
- Added system property which can be set to force-remove the lock
* Run INCEpTION with MySQL (for easier DB access)
* Manually enter locking information in the table `DATABASECHANGELOGLOCK`
* Start the application in desktop mode and see message
* Start again with `-DforceReleaseLock=true` and see message
* Start a second time with `-DforceReleaseLock=true` and see message
* Start normally
> #2382 - Allow unlocking of liquibase from command line/tray icon

- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureSupportRegistryImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorExtensionRegistryImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorRegistryImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/LayerBehaviorRegistryImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/LayerSupportRegistryImpl.java
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentImportExportServiceImpl.java
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportServiceImpl.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-external-search-core/src/main/java/de/tudarmstadt/ukp/inception/externalsearch/ExternalSearchProviderRegistryImpl.java
- inception/inception-kb/pom.xml
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommenderFactoryRegistryImpl.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/FeatureIndexingSupportRegistryImpl.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/index/PhysicalIndexRegistryImpl.java
- inception/inception-support-standalone/pom.xml
- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/LoadingSplashScreen.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/ExtensionPoint_ImplBase.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/interceptors/GlobalInterceptorsRegistryImpl.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/spring/StartupProgressInfoEvent.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/spring/StartupWatcher.java
- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/TelemetryServiceImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebarRegistryImpl.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/footer/FooterItemRegistryImpl.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/menu/MenuItemRegistryImpl.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/settings/ProjectSettingsPanelRegistryImpl.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/coloring/StatementColoringRegistryImpl.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/value/ValueTypeSupportRegistryImpl.java
- Move detail information about what is found by the registries to debug level and only log the number of the extensions in each registry
- Send info events when a auto-config module in an application package is being initialized
- Slightly improve visual style of the splash screen
* Start the app (in desktop mode)
> #2390 - More fine-grained info during startup

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/overview/CurationUnitOverviewLink.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- When checking if a position has been curated, we need to look at all configurations, not only at the ones with differences between the annotators
> #2399 - Sentence overview wrongly indicates agreement

- inception/inception-app-webapp/pom.xml
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- Remove assumption that FSes being compared must have the same number of features
- Ensure that curation CAS is upgraded when re-merging/initializing
* Upload document
* Create new custom layer with one feature
* Create annotation of that layer
* Mark document as finished
* Start curating the document
* Re-open the document for annotation
* Add second feature
* Open document for annotation
* Mark document as finished
* Go back to curation
* Re-merge document
> #2407 - NPE in curation after adding a feature

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/CurationDocumentServiceImpl.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/config/CurationDocumentServiceAutoConfiguration.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-curation/pom.xml
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- Prevent switching to a document which is not in the list of accessible documents that is shown in the open document dialog
- Align listCuratableDocuments with listFinishedDocuments by not showing any documents of users that have been removed from the project
- Slightly reorganize and format the code in ProjectServiceImpl.listProjectUsersWithPermissions
- Build CurationPage.listAccessibleDocuments (used by the open document dialog) on getListOfDocs (used by the navbar)
- Build CurationPage.listAccessibleDocuments (used by the open document dialog) on getListOfDocs (used by the navbar)
- When trying to open the CurationPage on a document that is not curatable via a URL parameter, send user back to the project dashboard and show error
- In CurationPage.getlistOfDocs() …
> #2415 - Stale document states may cause error when accessing the curation page

- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/TeiFormatSupport.java
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/formats/backports/TeiWriter.java
- Added backported TeiWriter from DKPro Core
- Exclude lapps module because it drags in ancient Axis dependencies which provide XML API classes that are already part of the JDK which causes Eclipse to complain about packages not being unique to modules
- Also exclude dependencies on xmi-apis JAR for the same reason
* Annotate a word as a named entity without setting the value feature and try exporting as TEI
> #2461 - NPE when exporting named entities with empty value feature as TEI

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- Avoid NPE when user tries to accept best but there are actually no predictions
* Not really sure how to reproduce the situation where a recommender is considered as active but then there are no predictions. Maybe open the recommender sidebar, look for an active recommender that has a long training time, reset recommenders and then click accept best then.
> #2497 - Exceptions during task selection and accept best

- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
This is a fix for bug #2467 and it also partially address #2442 (I realised it also only looked at the first annotation and so would create a duplicate even if one of the others was a match).
Assuming you use the named entity layer. Using a search for words you should be able to create multiple sets using a different value feature tag, with repeated calls with the same tag not creating duplicates. You will also then be able to delete any matching annotation using any of the tag values you have created (assuming you have more than one stacked up).
Note the exact behaviour on creating multiple annotations when one exists with matching values alongside the override isn't really defined well so I went with just trying to avoid creating duplicates …
> Bugfix for #2467 and partially addresses #2442

- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/config/WebsocketAutoConfiguration.java
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/config/WebsocketSecurityConfig.java
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/controller/LoggedEventMessageControllerImpl.java
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/controller/RecommendationEventMessageControllerImpl.java
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/footer/LoggedEventFooterItem.java
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/footer/RecommendationEventFooterItem.java
- inception/inception-websocket/src/main/resources/META-INF/spring.factories
- inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/LoggedEventMessageControllerImplTest.java
- Ensure that each of the websocket beans uses only a single property in the @ConditionalOnProperty
- Enable basic websocket support by default
* Run with websocket / websocket logging enabled and disabled and check if it works as expected
> #2517 - Avoid multiple property conditions for websocket-related features

- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/PatternMatchingCrossOriginEmbedderPolicyRequestCycleListener.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- Unregister the default COEP listener from Wicket
- Register an alternative COEP listener which also supports regex-based matching
- Remove unused parameter from a private method
> #2526 - Allow selective disabling of COEP for developers

- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/PdfAnnoPanel.java
- Add a hack that fixes the URL to the annotation API callback when coming from the recent activity list
> #2449 - Jumping from annotation editor to PDF annotation via recent activity does not work

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/ConceptFeatureValueType.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBaseProperties.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBasePropertiesImpl.java
- inception/inception-kb/src/main/resources/META-INF/asciidoc/admin-guide/settings_knowledgebase.adoc
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/KnowledgeBasePanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/config/KnowledgeBaseServiceUIAutoConfiguration.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupport.java
- inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/knowledge_base.adoc
- inception/inception-ui-kb/src/test/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupportTest.java
- inception/inception-ui-kb/src/test/java/de/tudarmstadt/ukp/inception/ui/kb/search/ConceptFeatureIndexingSupportTest.java
- Make lookup of KB items consistent for the concept feature editor dropdown and the rendering process
- Change lookup type "any concept/instance" to "any" because in fact it would also return properties
- Update documentation
- Expose KB render cache settings in properties file and document them
* Also, search for `http://www.wikidata.org/entity/Q2314257` on the KB page and try to open it (should given an error)
> #2426 - Difference in labelling of annotation marker vs identifier lookup

- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/export/ProjectExportPanel.html
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/export/ProjectExportPanel.java
* Hide progressbar and message when download is not in progress
* Add download behavior to form instead of progressbar to avoid conflict between behaviors
* Go to the export tab on the settings page and try exporting (whole project or only curated docs)
* The progress bar and accompanying message should only be visible during export
> #2543 Show export progress only on export

- inception/inception-search-core/src/main/resources/META-INF/asciidoc/user-guide/search-core.adoc
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Ignore slot features when comparing for bulk-annotation or bulk-deletion
- Do not copy slow feature values when bulk-annotating
* Create an annotation with slot fillers and then use the annotation as a template for a bulk-create or bulk-delete operation
> #2505 - Slot features should be ignored when comparing annotations for the purpose of bulk-annotation

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation.adoc
Behaviour on what happens when recommendations for stacked annotations are accepted had already been implemented. Now, a new annotation is always created even if annotations of the same layer type already exist at the position. This PR describes this in the user guide.
* Build and read the documentation of this in the user guide, section on settings and recommenders
> #1614 Inconsistent behaviour when two recommenders are set

- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.html
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.properties
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadFilterPanel.html
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadFilterPanel.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.html
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/event/FilterStateChangedEvent.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/AnnotatorColumn.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/DocumentMatrixDataProvider.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/DocumentMatrixRow.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/support/Filter.java
- inception/inception-workload-matrix/src/main/resources/META-INF/asciidoc/user-guide/workload_matrix.adoc
* Added ability to filter static workflow management page by document name and user names - bulk action can then be performed limitd to the items matching the filter
* Apply filters on the static workflow management page (i.e. "monitoring") and combine them with bulk actions. Check that actions are performed but only to the matching/visible items
> #2462 - Ability to bulk assign texts to annotators based on filter

- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMerge.java
- inception/inception-curation-legacy/src/test/java/de/tudarmstadt/ukp/clarin/webanno/curation/casmerge/CasMergeTestBase.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/LayerExporter.java
- inception/inception-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedAnnotationFeature.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationFeature.java
- inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
- inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
- Added "curatable" flag to AnnotationFeature (enabled by default)
- Added import/export support for new flag (value is true if missing in imported project)
- Ignore non-curatable features when comparing CASes
- Do not copy feature value when merging
* Disable curatable flag on a feature and see what happens - try with layers that have more than one feature
* Import a project that was exported from a version of INCEpTION where the flag did not exist yet and check that the curatable flag is turned on on all features
> #2495 - Ignorable features for curation mode

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/LayerBehaviorRegistryImpl.java
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/ProjectExportServiceImpl.java
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/export/config/ProjectExportServiceAutoConfiguration.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/ProjectService.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/storage/config/CurationDocumentServiceAutoConfiguration.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/CurationServiceTest.java
- inception/inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/adapter/FeatureValueUpdatedEventAdapterTest.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Project.java
- inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
- inception/inception-project/pom.xml
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/config/ProjectInitializersAutoConfiguration.java
- inception/inception-project/src/test/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImplTest.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/LegacyRemoteApiController.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/model/RProject.java
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/AeroRemoteApiControllerTest.java
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookServiceTest.java
- inception/inception-scheduling/src/test/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceTest.java
- inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- inception/inception-sharing/src/test/java/de/tudarmstadt/ukp/inception/sharing/InviteServiceImplTest.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.html
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/detail/ProjectDetailPanel.java
- inception/inception-versioning/src/test/java/de/tudarmstadt/ukp/inception/versioning/VersioningServiceImplTest.java
- inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/LoggedEventMessageControllerImplTest.java
- inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/WebSocketIntegrationTest.java
- Drop unique index on name
- Change hashCode / equals on Project from name to slug
- Automatically add slugs to all project which do not have one yet during startup
- No longer create unique name when importing a project and the name was already taken
- No longer check if project name is already used when setting project name in project details / dashboard
- Adjustments to the remote APIs: the project "name" parameter in the remote API requests and responses is actually the URL slug and the "title" parameter is the project name. In the legacy remote API responses, the slug replaces the name.
- The first line of a project description is now shown as a short description in the project overview page
* Start up with external or embedded DB and …
> #2562 - Project name no longer unique

- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
- If providing an email has been turned off, do no try to validate it
> #2571 - Email validation kicks in even if it is turned off

- inception/inception-brat-editor/pom.xml
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratLazyDetailsLookupService.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratLazyDetailsLookupServiceImpl.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratProtocolNames.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratRequestUtils.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratVisualizer.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/util.js
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.java
- Factor part of the code for handling brat-related requests out into a utility class so it can be shared between the BratAnnotationEditor and the BratSuggestionVisualizer (curation)
- Enable the popover in the BratSuggestionVisualizer
- Enable lazy details for the BratSuggestionVisualizer so that the curator may see some features in the popover (requires that these features have "show in popup" enabled)
* Enable "show in popup" for some features of a layer
* Make annotations on this layer using different users
* Mark the users as finished so curation becomes available
* Hover the mouse over the annotations of the users in the lower part of the screen
* Check if popup comes up and shows the correct data
> #2496 - Activate tooltip for annotation in curation mode

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/yaml/KnowledgeBaseProfile.java
- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/bootstrap/shim-bootstrapselect.scss
- inception/inception-ui-kb/pom.xml
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSpecificSettingsPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java
- Add AGROVOC profile
- Allow KB profile info to use markdown
- Improve visual of auto-complete fields by removing padding override
- Fix bug accessing a KB profile which defines a default dataset
- No longer offer British Museum SPARQL endpoint because it seem to be gone
* Set up AGROVOC from the profile and try it
> #2585 - Add AGROVOC Thesaurus kb profile

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebar.html
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/sidebar/CurationSidebar.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarTabbedPanel.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- When expanding/collapsing the sidebar, we must not add the entire page to the AJAX request target because then Wicket tires to "optimize" by redirecting to the current URL which resets the URL fragment parameters. Instead, we use WicketUtil.refreshPage() which adds all top-level updatable children
- Add support for having the user to view in the URL
- If the curation sidebar really needs to switch the user, we use a redirect instead of an AJAX refresh which may come too late to be allowed
- Disable curation sidebar when viewing annotations from another user
* Open annotation page as a project manager user in a project with multiple users
* Open a document as another user
* Open a sidebar
* Switch to another document via the open dialog or …
> #2590 - Error page when opening annotations as manager of different annotator

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java
- If a username/pw is specified in the URL of a knowledge base, parse it out and pass it as username/pw to the SPARQLRepository
* Try with a remote repository that has authentication enabled
> #2589 - SPARQL Endpoint URL with authentication

- inception/inception-ui-annotation/pom.xml
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/AnnotationSidebarState.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarTabbedPanel.java
- Store the sidebar state (selected tab and expansion state) as a per-user/per-project preference.
* Open a sidebar on the annotation page, leave the page, come back
* Try with and without leaving the sidebar in an expanded state
> #2610 - Remember sidebar state

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/BeforeDocumentOpenedEvent.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/event/DocumentOpenedEvent.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorState.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateImpl.java
- inception/inception-layer-docmetadata/pom.xml
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/config/DocumentMetadataLayerSupportAutoConfiguration.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerSingletonCreatingWatcher.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerSupport.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerTraits.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerTraitsEditor.html
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerTraitsEditor.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerTraitsEditor.properties
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.html
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/LayerSelectionPanel.java
- Add option to mark a document metadata layer as a singleton
- Route DocumentOpenedEvents to the UI so the DocumentMetadataSidebar can react and initialize the singletons
- Put delete button direclty into the sidebar without wrapping it in a dropdown
* Mark a document metadata layer as singleton
* Open annotation page, open metadata sidebar, enter data, switch between documents
> #2612 - Add possibility to enforce singelton document level annotations

- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratRenderer.java
- inception/inception-curation-legacy/pom.xml
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/FeatureEditorListPanel.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/AnnotatorsPanel.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/AnnotationState.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/render/AnnotationStateColoringStrategy.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/render/CurationRenderer.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/render/CurationRendererImpl.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/overview/CurationUnit.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/overview/CurationUnitOverviewLink.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- inception/inception-ui-curation/src/main/resources/META-INF/asciidoc/user-guide/curation.adoc
- Clean up code and remove some legacy/redundant crusts here and there
- Add ability to CasDiff to exclude certain annotators (e.g. Curator) when calculating completeness and agreement
- Updated coloring in the annotator views to largely match the coloring in the left sidebar
- Pulled coloring strategy and curation renderer out from the AnnotatorsPanel
* Use curation and report anything that looks odd
> #2621 - Incomplete and disagreeing annotations have the same color code in curation

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/DynamicTextAreaFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/InputFieldTextFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/TextAreaFeatureEditor.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.html
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.html
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/FeatureEditorListPanel.java
- Removed `AjaxPreventSubmitBehavior()` from the DynamicTextAreaFeatureEditor, the InputFieldTextFeatureEditor and the TextAreaFeatureEditor - this was preventing saving in the document metadata sidebar and for some reason apparently had no effect whatsoever in the right annotation detail sidebar
- Clean up layout of document metadata sidebar a bit more
- Slightly clean up code
* Use the document metadata sidebar as well as the right annotation detail sidebar with tab/enter and with different kinds of feature editors
> #2619 - Cannot save feature value using enter in document-level annotations

- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/resource/visualizer.js
- Fix variable scope in JavaScript
- Fix displaying of sentence number when there is a sentence-level comment
- Fix displaying the sentence comment popover
* Import a file from the Perseus Treebank 2.1 and open in the annotation editor
* Alternatively, open any other file including a sentence ID
> #2692 - Perseus treebank XML 2.1 not visible to annotate

- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicAnnotatorWorkflowActionBarItemGroup.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.html
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.properties
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/trait/DynamicWorkloadTraits.java
- Added option to disable the confirmation dialog when finishing a document in dynamic mode
* Enable dynamic workload
* Go to the workload management page
* Turn off the confirmation dialog in the settings on that page and save
* Visit the annotation page as an annotation user (curation users get the default workflow management action bar, not the dynamic one which doesn't consider the new setting)
> #2691 - Make confirm dialog when finishing documents configurable required

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/ConceptFeatureTraits.java
- Changed default object type for concept features from "instance" to "any"
* Create a new project
* Check if the "identifier" feature on the named entity layer has "any" as the setting for the permitted object types
> #2714 - Make "any" the default setting for "allowed values"

- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- Do not use fuzzy searches for very long queries because that makes things waaaay to slow
- If there was an exact IRI match, do not bother trying to search by label
- Break candidate generation up into smaller methods it is easier to see in the profiler which part takes longest
* Use a reasonably-sized KB local, annotate a long mention and try to link it against a concept either by label search or by IRI
> #2683 - Improve query performance for long mentions

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/DefaultPagingNavigator.java
* Hide paging if the unit count is smaller or equal to the window size
* Have a project with two documents, a large and a small one
* Set the window size of the brat editor such that for the small one everything fits on one page
* Switch between the two documents
> #2676 - Hide page navigation if there is only one screen full of lines

- inception/inception-workload-dynamic/pom.xml
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImpl.java
- inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImpl2Test.java
- inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImplTest.java
- inception/inception-workload-matrix/pom.xml
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/MatrixWorkloadExtension.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/MatrixWorkloadExtensionImpl.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraits.java
- inception/inception-workload-matrix/src/test/java/de/tudarmstadt/ukp/inception/workload/matrix/Fixtures.java
- inception/inception-workload-matrix/src/test/java/de/tudarmstadt/ukp/inception/workload/matrix/MatrixWorkloadExtensionImplTest.java
- Added condition to not change document state that is already in curation or with curation finished
- Added a test checking that
1) Created a new project
2) Imported a document into the project
3) Added a few annotations to the project as the admin user
4) Marked the document as "finished"
5) Opened the document for curation as the admin user
6) Removed one of the pre-merged annotations from the curation view (to see if manual curation actions are preseved)
7) Marked the curation document as finished
8) Added a new annotation user to the project
9) Check that state is still "curation finished"
> #2697 - Curation Overview list reset

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/TagSetExporter.java
- inception/inception-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedTag.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Tag.java
- inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/JsonImportUtil.java
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/ProjectTagSetsPanel.html
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/ProjectTagSetsPanel.properties
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSelectionPanel.html
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSelectionPanel.java
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.java
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetImportPanel.java
- Added new column "rank" to the tags
- Added new call to re-order tags in the annotation schema service without genrating tons of "tag updated" events
- Added buttons to move tags up and down to the tag selection panel
- Set rank on tags while importing tagsets
* Re-order tags in the tagset editor
* See if re-ordering and making changes in the tag detail editor are independent
* Check if the tags appear in the right order on the annotation page
> #2671 - Make tagsets order aware

- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
- inception/inception-brat-editor/.gitignore
- inception/inception-html-recogito-editor/.gitignore
- inception/inception-image/pom.xml
- inception/inception-ui-dashboard/pom.xml
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- inception/pom.xml
- pom.xml
- Move a few more versions to the parent POM
- Dropped dependency on wicket-datetime
- Spring 5.3.9 -> 5.3.13
- Spring Boot 2.5.4 -> 2.5.7
- Spring Security 5.5.2 -> 5.5.3
- SpringDoc 1.5.10 -> 1.5.13
- Swagger 2.1.10 -> 2.1.11
- Log4j 2.15.0 -> 2.16.0
- JBoss Logging 3.4.1 -> 3.4.2
- Groovy 3.0.3 -> 3.0.9
- Tomcat 9.0.52 -> 9.0.56
- Hibernate 5.5.7 -> 5.5.8
- owasp-java-html-sanitizer -> 20211018.2
- ant -> 1.10.12
- ElasticSearch 6.8.17 -> 6.8.21
- Added exclusion for tempusdominus-bootstrap-4
- Added exclusion for jquerypp
- Added exclusion for summernote
- Added exclusion for maven-model
> #2750 - Upgrade dependencies

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose-mysql5.yml
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose.yml
- Set version back to 2.4
* Try running the compose script
> #2747 - Depends_on in docker compose 3 not supported

- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-brat-editor/src/main/ts_template/package.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package.json
- inception/inception-html-recogito-editor/src/main/ts_template/package.json
- inception/pom.xml
- Added groovy script to derive a semver from the project version
- Inject that into the package.json files
- Ensure that the Groovy plugin which is used to generate the semver also executes in Eclipse
* Run build on CLI
* Run build in Eclipse
> #2761 - Generate valid semver and use it for the NPM dependencies

- inception/inception-api-dao/pom.xml
- inception/inception-api-dao/src/test/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImplDatabaseTest.java
- inception/inception-concept-linking/pom.xml
- inception/inception-curation/pom.xml
- inception/inception-diam/pom.xml
- inception/inception-imls-stringmatch/pom.xml
- inception/inception-kb/pom.xml
- inception/inception-log/pom.xml
- inception/inception-preferences/pom.xml
- inception/inception-project-export/pom.xml
- inception/inception-project/pom.xml
- inception/inception-project/src/test/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImplTest.java
- inception/inception-recommendation/pom.xml
- inception/inception-remote/pom.xml
- inception/inception-search-mtas/pom.xml
- inception/inception-sharing/pom.xml
- inception/inception-ui-curation/pom.xml
- inception/inception-versioning/pom.xml
- inception/inception-websocket/pom.xml
- inception/inception-workload-dynamic/pom.xml
- inception/inception-workload-matrix/pom.xml
- inception/pom.xml
- JUnit 5.8.1 -> 5.8.2
- AssertJ 3.20.3 -> 3.21.0
- Spring 5.3.13 -> 5.3.14
- Spring Security 5.5.3 -> 5.6.0
- SpringDoc 1.5.11 -> 1.6.1
- Log4J 2.16.0 -> 2.17.0
- Hibernate 5.5.8 -> 5.6.3
- Wicket 9.6.0 -> 9.7.0
- Wicketstuff 9.6.0 -> 9.7.0
- Bootstrap 5.1.2 -> 5.1.3
- FastUtil -> 8.5.6
- HSQLDB 2.5.0 -> 2.6.1
- Commons IO 2.7 -> 2.11.0
- Commons Text 1.8 -> 1.9
- Commons Lang3 3.11 -> 3.12.0
- Commons Validator 1.6 -> 1.7
- Caffeine 2.8.0 -> 2.9.3
- H2 1.4.197 -> 2.0.202
- Docker Maven Plugin 0.34.1 -> 0.38.0
- Maven Versions Plugin 2.7 -> 2.8.1
- Checkstyle 8.29 -> 8.45.1
> #2630 - Upgrade dependencies

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoAutoCompleteTextFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/ReorderableTagAutoCompleteField.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/StyledComboBox.java
- Extract tag auto-complete field into a re-usable class
- Use it also in the link feature editor for the roles if there are more than 100 tags in the tagset
- Slight UI layout fix in the link feature editor
(cherry picked from commit 752a0383ad0047b02182ebd8052537d0c9348f6f)
> #2775 - Ability to work with really large tagsets for link features

- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/InviteServiceImpl.java
- inception/inception-sharing/src/main/resources/META-INF/asciidoc/admin-guide/settings_sharing.adoc
- Use the project slug in the generated invite link
- Document the invite link base URL setting
> #2803 - invitation link behind reverse proxy

- inception/inception-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/Conll2000FormatSupport.java
- inception/inception-io-conll/src/main/java/de/tudarmstadt/ukp/clarin/webanno/conll/Conll2002FormatSupport.java
- inception/pom.xml
- Readers and writers in CoNLL 2000 and CoNLL 2002 support were mixed up
- Remove exclusion of dependency which can cause a ClassNotFoundException at runtime when importing files with readers that support tagset mapping
- Fixed Log4J BOM import which moved some dependencies wrongly to the test scope - because we imported "log4j" instead of "log4j-bom"...
* Try importing a CoNLL 2000, 2002, 2003 file
> #2819 - Cannot import CoNLL file

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorBase.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
- inception/inception-brat-editor/src/main/ts/brat/annotator_ui/AnnotatorUI.ts
- inception/inception-brat-editor/src/main/ts/brat/protocol/Protocol.ts
- inception/inception-brat-editor/src/main/ts/brat/visualizer/Visualizer.ts
- inception/inception-brat-editor/src/main/ts/brat/visualizer_ui/VisualizerUI.ts
- Pull code that cancels rendering if an editor was already rendered or that's already part of the AJAX target out into the AnnotationEditorBase class
- Pull error handling code into AnnotationEditorBase
- Remove collection and document information from brat
> #2822 - Clean up (brat) rendering code

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/DocumentViewFactory.java
- inception/inception-api-formats/pom.xml
- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/ExternalAnnotationEditor.java
- inception/inception-external-editor/src/main/ts/src/ExternalEditorFactory.ts
- inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentIFrameViewFactory.java
- inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentViewFactory.java
- inception/inception-html-recogito-editor/src/main/java/de/tudarmstadt/ukp/inception/recogitojseditor/RecogitoHtmlAnnotationEditor.java
- inception/inception-imls-elg/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/elg/ElgCatalogClientImplTest.java
- inception/inception-js-api/src/main/ts/src/editor/AnnotationEditorFactory.ts
- Allow sending the editor ID to the view
- Allow formats to specify CSS stylesheets that should be used when being rendered in styleable editors
- Pass target element to external editor only as element and not as ID
- Improve CSS and JavaScript injection in external editor factory
> #2833 - Enhance (external) editors API

- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SuggestionGroup.java
- inception/inception-recommendation/pom.xml
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/Fixtures.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RelationSuggestionVisibilityCalculationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/SpanSuggestionVisibilityCalculationTest.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java
- Do not skip visibility calculation if there are no annotations
- Ensure that suggestions in the current window are un-hidden as part of visibility calculation check - and then hidden again if necessary
- Added tests
> #878 - Unhide annotation suggestions immediately if an overlapping annotation is deleted

- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
- Ignore zero-width annotations and annotations on whitespace only during training/evaluation
* See issue
> #2855 - Exclude empty annotations from String Matcher and OpenNLP recommenders

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/adapter/TypeAdapter_ImplBase.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/FeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/LinkFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/StringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/UimaPrimitiveFeatureSupport_ImplBase.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoAutoCompleteTextFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/LinkFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/ReorderableTagAutoCompleteField.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/StringFeatureTraitsEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/Renderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/util/WebAnnoCasUtil.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/MultiValueMode.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Boolean feature rendering is handled in the boolean feature support - no need to do it in the base class
- Allow rendering feature values of multi-value features
- Link features are multi-value features but they should never be rendered in the label - so always return null
- Change setFeatureValue such that it may throw an AnnotationException
- Better factoring out of the ReorderableTagAutoCompleteField
* No particular test procedure
> #2861 - Towards multi-value features

- inception/inception-app-webapp/pom.xml
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CurationWorkflowActionBarExtension.java
- inception/inception-workload-dynamic/pom.xml
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowActionBarExtension.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/trait/DynamicWorkloadTraits.java
- inception/inception-workload-matrix/pom.xml
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarExtension.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.html
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/config/MatrixWorkloadManagerAutoConfiguration.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.html
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.properties
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraits.java
- inception/inception-workload-matrix/src/main/resources/META-INF/asciidoc/user-guide/workload_matrix.adoc
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/extension/WorkloadManagerExtension.java
- Added a trait to the matrix workload which should allow annotators to re-open a document - settable in the workload management page, but has no effect yet
* Enable the setting on the matrix workload management page
* Try closing and then re-opening a document on the annotation page
> #898 - Annotators should be able to reopen a finished document

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/DocumentServiceImpl.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/dialog/ConfirmationDialog.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxButton.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxEventBehavior.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxFormChoiceComponentUpdatingBehavior.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxFormComponentUpdatingBehavior.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxFormSubmittingBehavior.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxLink.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxSubmitLink.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaButton.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaForm.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaMenuItem.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/model/BratSuggestionVisualizer.properties
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- inception/inception-ui-curation/src/main/resources/META-INF/asciidoc/user-guide/curation.adoc
- Added option to re-open document directly from the curation page
- Documented the new feature
- Fixed issue that redirecting to another page would not work in many cases because the exception handles would catch the Wicket redirect exception
> #2411 - Possibility to reopen documents of an annotator in the curation

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- Lack of training annotations is no reason to skip prediction
* Should be reproducible using a string recommender
> #2891 - Predictions are not cleared after deleting the last annotation

- inception/pom.xml
- Mockito 3.12.4 -> 4.4.0
- Awaitility 3.1.3 -> 4.2.0
- Spring 5.3.15 -> 5.3.17
- Spring Boot 2.6.3 -> 2.6.5
- Spring Security 5.6.1 -> 5.6.2
- SpringDoc 1.6.5 -> 1.6.6
- Swagger 2.1.12 -> 2.1.13
- SLF4J 1.7.35 -> 1.7.36
- LOG4J 2.17.1 -> 2.17.2
- Groovy 3.0.9 -> 3.0.10
- Tomcat 9.0.58 -> 9.0.60
- Wicket 9.7.0 -> 9.8.0
- Wicketstuff 9.7.0 -> 9.8.0
- Wicket JQuery 9.7.0 -> 9.8.0
- Asciidoctor 2.5.2 -> 2.5.3
- Jackson 2.13.1 -> 2.13.2
- okhttp 4.9.1 -> 4.9.3
- fastutil 8.5.6 -> 8.5.8
- javassist 3.27.0 -> 3.28.0
- bytebuddy 1.10.22 -> 1.12.8
- caffeine 3.0.5 -> 3.0.6
> #2912 - Upgrade dependencies (24.0)

- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/DiamAjaxBehavior.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/EditorAjaxRequestHandlerExtensionPointImpl.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/extensionpoint/ExtensionPoint_ImplBase.java
- Fix iteration through request handlers to allow for the side-effect of the ImplicitUnarmSlotHandler
> #2924 - Filling in slots via DIAM-based editors does not work

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoChoiceDescriptionScriptReference.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/KendoComboboxTextFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RadioGroupStringFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/feature/editor/RadioGroupStringFeatureEditor.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/ReorderableTag.java
- Filter suggestions to reorder by the recommender which provided the currently active-learning-selected suggestion because scores may not be comparable across recommenders
- Display score (detail) in dropdown in the combo box
- Handle case that there may be multiple recommendations for the same label (which might actually not be necessary anymore due to the change above)
* Configure two recommenders e.g. Token Sequence Classifier and String Matcher on a POS-annotated document
* In active learning mode, find a location where both suggest the same label
* There should not be an error
> #2943 - Duplicate key error in active learning

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/ThresholdBasedMergeStrategyTraitsEditor.java
- Scale the confidence threshold to a value between 0 and 100 on screen.
* Set a confidence threshold value
> #2937 - Value shown as 0-1 decimal number instead of 0-100 percentage

- inception/inception-app-webapp/src/main/resources/application.yml
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose-mysql8.yml
- Update MySQL docker compose example from MySQL 5 to MySQL 8
- Add global quoting of identifiers for hibernate so we do not run into problems with case sensitivity on different types/versions of database backends
* Try running INCEpTION against MySQL 8
> #2967 - Schema validation fails on MySQL 8

- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUtils.java
- inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- Fix the issue by including `<` and `>` in the "simple query" detection
- Added unit test checking for a regex matching in a query and for a multi-token query without conditions
> #2957 - Search can't find all tokens of a layer

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/config/AnnotationEditorProperties.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/RelationLayerTraitsEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/layer/SpanLayerTraitsEditor.java
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/annotationservice/config/AnnotationEditorPropertiesImpl.java
- Hiding feature behind a feature flag before removing it entirely in a later version
* Span and relation layers should no longer show the configurable JS action option
> #2990 - Remove "Javascript action on click" feature

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/AnnotationSchemaService.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/model/AnnotatorStateImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/PagingStrategy.java
- inception/inception-api-annotation/src/main/resources/META-INF/asciidoc/user-guide/editable-segmentation.adoc
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/AnnotationSchemaServiceImpl.java
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/annotationservice/config/AnnotationSchemaServiceAutoConfiguration.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratSentenceOrientedAnnotationEditorFactory.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationMergeServiceImpl.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/SentenceLayerInitializer.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/TokenLayerInitializer.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- Disable sentence layer by default
- Better checking if sentence/token layer are editable
- Better handling of curation CAS initialization when sentence layer is present but not editable
* Try re-merging when sentence editing is not enabled
> #1778 - Make tokenization editable

- inception/inception-pdf-editor/src/main/js/pdfanno/src/core/src/render/renderSpan.ts
- inception/inception-pdf-editor/src/main/js/pdfanno/src/core/src/version.ts
- Remove reference to undeclared version in package.json which causes client-side code to crash and PDF annotations to not work anymore
> #2997 - Editing PDFs no longer works

- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/pdfanno/model/PdfExtractFile.java
- inception/inception-pdf-editor/src/main/js/pdfanno/src/core/index.ts
- inception/inception-pdf-editor/src/main/js/pdfanno/src/core/src/render/renderRelation.ts
- inception/inception-pdf-editor/src/main/js/pdfanno/src/page/textLayer.ts
- inception/inception-pdf-editor/src/main/js/pdfanno/src/page/util/analyzer.ts
- Server-side: if a page cannot be found, look for the start/end of the next/prev existing page instead.
- Client-side: look for page by page number, not by index in page array
> #3001 - Error when PDF has a blank page inside

- inception/inception-diam-editor/pom.xml
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/experimental/editor/diamdebugeditor/DiamDebugEditorFactory.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/websocket/ViewportDefinition.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController.java
- inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController_ViewportRoutingTest.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventFooterPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventWebsocketController.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventWebsocketControllerImpl.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/config/DashboardAutoConfiguration.java
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/config/WebsocketAutoConfiguration.java
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/controller/LoggedEventsWebsocketController.java
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/controller/LoggedEventsWebsocketControllerImpl.java
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/footer/LoggedEventFooterPanel.java
- inception/inception-websocket/src/main/resources/META-INF/asciidoc/admin-guide/settings_websocket.adoc
- inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/LoggedEventsWebsocketControllerImplTest.java
- inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/WebSocketIntegrationTest.java
- Renamed controller classes to make clearer they use Websocket
- Added a @ConditionalOnExpression to the DiamWebsocketController
- Automatically switch back to the legacy export page when WebSocket is disabled
- Disable the DIAM debug editor when WebSocket is disabled
> #3013 - Application does not start when websocket support is disabled

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AdditionalMatchingPropertiesPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/RootConceptsPanel.java
- Reject empty root concepts and matching properties
- Improve error message
- Reject property IRIs that do not look like (absolute) IRIs
> #3049 - Can add empty IRI as additional property

- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/task/ProjectExportTask_ImplBase.java
- Make the SimpMessagingTemplate optional in the export task base class
- Use the non-notifying monitor when WebSocket is not available
> #3052 - Cannot export project when websocket is disabled

- inception/inception-layer-docmetadata/pom.xml
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/log/DocumentMetadataEventAdapter.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/BulkAnnotationEventAdapter.java
- Added event logging adpaters for DocumentMetadataEvent and BulkAnnotationEvent
* Create annotations and check the events table in the database or the event log in an exported project
> #3055 - Some logged events to not contain document/project information

- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashletControllerImpl.java
- Filter out events without documents
- When picking out curated documents, we should probably use the "curatableSourceDocuments" list and not the "annotatableSourceDocuments" list?
* Check if the activities dashlet works ok
> #3057 - Exception in activities dashlet

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/IriConstants.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/StardogEntitySearchService.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FusekiRepositoryTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/Rdf4JRepositoryTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/StardogRepositoryTest.java
- inception/inception-kb/src/test/resources/data/wordnet-ontolex-ontology.owl
- inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/projects_knowledge-base.adoc
- Added Stardog FTS option
* Install stardog in a way that provides the CLI interface
* Create a database with search enabled: `stardog-admin db create -n myDatabase -o search.enabled=true -- file.ttl`
* Configure a KB accessing that database `http://USERNAME:PASSWORD@localhost:5820/myDatabase/query`
* Configure the KB to use the `tag:stardog:api:search:textMatch`
* Configure a layer with a concept feature
* Test accessing and searching the KB on the knowledge base page
* Test entity linking on the annotation page
> #3059 - Add support for the Stardog SPARQL FTS service 

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FusekiRepositoryTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/Rdf4JRepositoryTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/RepositoryTestSuite.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/StardogRepositoryTest.java
- inception/pom.xml
- Refactor the tests to be reusable across different backends
- Separate test classes for each backend
- Bit of cleaning up in the SPARQLQueryBuilder
- Fix RDF4J FTS potentially returning labels not matching the query if an item has multiple labels
* No particular test procedure
> #3064 - Refactor KB tests

- inception/inception-concept-linking/pom.xml
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-kb/NOTICE.txt
- inception/inception-kb/pom.xml
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBasePropertiesImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/ExportedKnowledgeBase.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/model/KnowledgeBase.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryPrimaryConditions.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/backport/Bind.java
- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/model/db-changelog.xml
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.properties
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/QuerySettingsPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/QuerySettingsPanel.java
- inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/projects_knowledge-base.adoc
- Added option to disable fuzzy search (off by default)
- Improve timing logging/reporting in the concept linking service
- Improve information on why FTS is disabled when performing certain kinds of queries
- Fix fuzzy label matching for RDF4J when an item has multiple labels potentially with different languages
- Factor language matching out into a separate method and simplify the query by removing a redundant/duplicate regex condition
- Update KB settings documentation
* Compare in particular entity linking without fuzzy matching to entity linking with fuzzy matching
* Check if matching results are ok
> #3038 - Search on large local knowledge base is much slower than expected

- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/config/EntityLinkingServiceAutoConfiguration.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/feature/CasingFeatureGenerator.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/feature/LevenshteinFeatureGenerator.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/model/CandidateEntity.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategy.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategyTest.java
- inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImplTest.java
- Modify ranking algorithm to put more weight on the query entered by the user
* Search for entities to link, in paricular such that do not match the annotated text
> #3076 - Items matching text entered in to concept feature editor often appear late

- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/AnnotationDocumentExporter.java
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/settings/ProjectExporterPanelImplBase.java
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/settings/RunningExportsPanel.vue
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/task/curated/CuratedDocumentsProjectExportTask.java
- Display error message in running exports list if WebSocket connection cannot be established
- Fix NPE trying to delete exported file when export had previously failed
- Use getFallbackFormat() instead of directly falling back to WebAnnoTSV
- Minor cleaning up
* Access the export page on a system where WebSocket does not work
> #3092 - Export doesn't work

- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurity.java
- Add actuator
- Allow all access to health endpoint at `/actuator/health`
- Exclude auto-config for Solr and ElasticSearch since they enable health checks because we have the Solr/Elastic libs as dependencies - but we really do not use them via Spring Boot anyway
* Access `/actuator/health`
* Try adding this to the `settings.properties` and then see health
```
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
```
> #3107 - Add Spring Boot Actuator for health checking

- inception/inception-recommendation-api/pom.xml
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/RecommenderGeneralSettings.java
- inception/inception-recommendation/pom.xml
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/ProjectRecommendersPanel.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/ProjectRecommendersPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.properties
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/NonTrainableRecommenderActivationTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/RecommendationTask_ImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RelationSuggestionVisibilityCalculationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/SpanSuggestionVisibilityCalculationTest.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingService.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java
- Added a per-project option to wait for non-trainable recommenders to provide suggestions before accessing a document (off by default)
- Refactoring of the recommender tasks
- Refactoring of the selection task to be more readable
* Configure a non-trainable recommender, e.g. a non-trainable external recommender or an ELG recommender
* Access the annotation page with the option disabled - access should be immediate, recommendations may appear only later
* Log out - log back in
* Enable the wait option and then access the annotation page - access should be blocked until recommendations have been retrieved (or until ELG runs into a timeout...)
> #3113 - Option to wait for recommendations before showing document

- inception/inception-api-dao/pom.xml
- inception/inception-api-dao/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/dao/casstorage/CasPersistenceUtils.java
- inception/pom.xml
- Backport the code for detecting and reading compressed CASes from 24.x
* Run 24.x and update annotations in some document
* Go back to 23.x and check if the annotation document can be loaded
> #3136 - Support reading compressed CASes from 24.0

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/AnnotationEditorBase.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/TokenWrappingPagingStrategy.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/annotation/BratAnnotationEditor.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java
- inception/inception-diag/pom.xml
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/CasDoctor.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsStartAndEndWithinSentencesCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NegativeSizeAnnotationsCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoMultipleIncomingRelationsCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/TokensAndSententencedDoNotOverlapCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorAutoConfiguration.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/CoverAllTextInSentencesRepair.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/SwitchBeginAndEndOnNegativeSizedAnnotationsRepair.java
- inception/inception-diag/src/main/resources/META-INF/asciidoc/user-guide/casdoctor.adoc
- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsStartAndEndWithinSentencesCheckTest.java
- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NegativeSizeAnnotationsCheckTest.java
- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NoMultipleIncomingRelationsCheckTest.java
- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/TokensAndSententencedDoNotOverlapCheckTest.java
- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/CoverAllTextInSentencesRepairTest.java
- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingRelationsRepairTest.java
- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/SwitchBeginAndEndOnNegativeSizedAnnotationsRepairTest.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
- Added new checks and repairs including documentation and tests: SwitchBeginAndEndOnNegativeSizedAnnotationsRepair, NegativeSizeAnnotationsCheck, AllAnnotationsStartAndEndWithinSentencesCheck, CoverAllTextInSentencesRepair, TokensAndSententencedDoNotOverlapCheck
- Improved error reporting in the annotation editor code when a document cannot be rendered
* Try the CAS doctor on a few funky XMI files
> #3134 - Improved CAS Doctor checks

- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/model/RPermission.java
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/AeroRemoteApiControllerTest.java
- Added calls to manage project permissions
* Use the Swagger UI to test the calls
> #3142 - Ability to add/remove project permissions via remote API

- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurity.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorPage.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorPage.java
- Allow access to error page without login (thus avoiding the redirection to the login page when trying to render the error page to an anonymous user)
- Do not render OS, Java, etc. details to unauthorized users on the error page
- When the client says to accept JSON or the request URL looks like an API url, return a JSON response instead of rendering the page as HTML
* Try providing bad credentials to the remote API
> #3146 - Bad credentials to remote API redirect to login HTML page

- inception/inception-remote/pom.xml
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/RemoteApiAutoConfiguration.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookService.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhooksConfiguration.java
- inception/inception-remote/src/main/resources/META-INF/asciidoc/admin-guide/remote-api-webhooks.adoc
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookServiceTest.java
- inception/pom.xml
- Switch webhooks to auto configuration
- Configure remote API and webhooks only when running as a web application
> #3162 - Limited retry for webhooks

- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/event/AnnotationStateChangeEvent.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/adapter/AnnotationStateChangedEventAdapter.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookService.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/json/AnnotationStateChangeMessage.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/json/DocumentStateChangeMessage.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/json/ProjectStateChangeMessage.java
- inception/inception-remote/src/main/resources/META-INF/asciidoc/admin-guide/remote-api-webhooks.adoc
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookServiceTest.java
- inception/inception-remote/src/test/resources/log4j2.xml
- Include timestamp information
- Triggering user in the `ANNOTATION_STATE` events
- State set by annotator in the `ANNOTATION_STATE` events
* Configure a webhook and check if the notifications you get contain the additional information
> #3164 - Include additional information in webhook notification

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_unsupervised.adoc
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/NameUtil.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityProperties.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityPropertiesImpl.java
- inception/inception-security/src/test/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImplTest.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/InviteServiceImpl.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
- inception/pom.xml
- Added ability to set the default admin username
- Update documentation
- Added test
- Moved NameUtil to the security module
- Add space to the list of characters excluded for usernames
> #3167 - Ability to set default admin username

- inception/pom.xml
- assertj 3.22.0 -> 3.23.1
- spring-boot 2.7.0 -> 2.7.1
- spring-security 5.7.1 -> 5.7.2
- log4j 2.17.2 -> 2.18.0
- jboss-logging 3.4.2 -> 3.5.0
- groovy 3.0.10 -> 3.0.11
- hibernate 5.6.8 -> 5.6.9
- asciidoctor 2.5.3 -> 2.5.4
- asciidoctor-diagram 2.2.1 -> 2.2.3
- okhttp 4.9.3 -> 4.10.0
- caffeine 3.0.6 -> 3.1.1
- okio 2.10.0 -> 3.2.0
> #2912 - Upgrade dependencies

- inception/inception-js-api/src/main/ts/src/model/compact/CompactAnnotatedText.ts
- inception/inception-pdf-editor2/src/main/ts/src/PdfAnnotationEditor.css
- inception/inception-pdf-editor2/src/main/ts/src/PdfAnnotationEditor.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/span.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/abstract.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/container.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/relation.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/span.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/render/renderKnob.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/render/renderRelation.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/render/renderSpan.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/page/textLayer.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.css
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.ts
- Also render annotations on the page before and after the current page if possible
- Slightly change the rendering style for annotations to only a border below
- Pointer cursor over knobs
- Remove opacity setting from annotation highlights and rely on the semitransparent highlight background
- The knob should always be halt-transparent
- Add selection highlight to the currently selected annotation
- Improve support for annotation/text markers
- Removed unused code for client-side selection management
- Add selection highlight to the knob of the selected annotation
* Use PDF editor to test it
> #3096 - New PDF editor

- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.html
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Fixes jumping to the top when (un)selecting a checkbox in the results list after scrolling down - when clicking on a result triggers a switch of the document, it still jumps
- Only show group-level checkbox if there are any editable results in the group
- Ignore non-editable results in a group when determining the group-level checkbox state
* Use the sidebar
> #1606 - Search result list jumps back to top

- inception/inception-brat-editor/src/main/ts/brat/annotator_ui/AnnotatorUI.ts
- Clear spanDragJustStarted flag when a span annotation is created to avoid mouse move after span creation registering as drag action
> #3209 - Reactivity lost after creating an annotation

- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchQueryRequest.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/StatisticRequest.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.html
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Handle lower-casing of the query differently such that layer names and feature names are not affected
- When writing a CQL query against a case-insensitive index, the user needs to take case of not upper-casing search terms
- For simple text queries, we do lower-case automatically
* Switch to a case-insensitive index configuration
* Try CQL query against layers that have upper-case characters in their names
> #2433 - Case Insensitive Token Search

- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/AcceptInvitePage.java
- Force-logout a project-bound users when they try to join another project so a new identity is created when joining the new project
> #3185 - Two guest users with same UI name

- inception/inception-model/pom.xml
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationFeature.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationLayer.java
- inception/inception-search-core/pom.xml
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/PrimitiveUimaIndexingSupport.java
- inception/inception-search-mtas/pom.xml
- inception/inception-search-mtas/src/main/resources/META-INF/asciidoc/user-guide/search-mtas.adoc
- inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParserTest.java
- inception/inception-search-mtas/src/test/resources/META-INF/org.apache.uima.fit/types.txt
- inception/inception-search-mtas/src/test/resources/desc/type/TestTypes.xml
- inception/inception-search-mtas/suppressions.xml
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/uima/JCasClassUtil.java
- Add builders to AnnotationLayer and AnnotationFeature
- Add support for indexing multi-value string features
- Index boolean feature values as true/false
- Added tests
* Define a layer with a boolean feature and search for it e.g. as `[MyLayer.boolFeature="true"]`
* Define a layer with a multi-value string feature, then search for one value or more values, e.g. `[MyLayer.value="a" & MyLayer.value="b"]`
> #2972 - Simplify search for boolean values

- inception/inception-ui-search/pom.xml
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- Hide option to search all documents when random access is disabled
- Always limited to the current document when random access is disabled
> #3223 - Search sidebar can bypass workload management

- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/span.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/span.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/render/renderSpan.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.ts
- inception/inception-pdf-editor2/src/main/ts/src/vmodel/Rectangle.ts
- inception/inception-pdf-editor2/src/main/ts/src/vmodel/VGlyph.ts
- Consider the page of each glyph when merging rectangles
- Consider the page of rectangles when rendering
- Fixes rendering of annotations that go across page boundaries
- Also fixes selection of text across page boundaries (#1087)
* Create an annotation in the brat view that goes across a page boundary, then look at it in the PDF view
* Drag a selection across a page boundary to create  a cross-page annotation
> #1088 - Create spans across page boundaries in PDF editor

- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasStorageSession.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentImportExportService.java
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-uimajson-legacy.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/formats-uimajson.adoc
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-io-json/pom.xml
- inception/inception-io-json/src/main/java/de/tudarmstadt/ukp/inception/io/jsoncas/LegacyUimaJsonFormatSupport.java
- inception/inception-io-json/src/main/java/de/tudarmstadt/ukp/inception/io/jsoncas/UimaJsonCasFormatSupport.java
- inception/inception-io-json/src/main/java/de/tudarmstadt/ukp/inception/io/jsoncas/UimaJsonCasReader.java
- inception/inception-io-json/src/main/java/de/tudarmstadt/ukp/inception/io/jsoncas/UimaJsonCasWriter.java
- inception/inception-pdf-editor/src/main/ts/build.js
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- inception/pom.xml
- Added r/w support for new UIMA CAS JSON format (marked as experimental but active by default)
- Marked old CAS JSON format as legacy
- Fixed issue in CasStorageSession that may cause a misleading error message if the session contains a CasHolder which does not yet have a CAS set
- Made a package-private method in AnnotationSchemaServiceImpl public to enable a workaround for missing lenient deserialization in new CAS JSON library
* Import some document, make some annotations and then export as UIMA JSON CAS (experimental)
* Import the exported JSON back as UIMA JSON CAS (experimental)
> #3281 - Support the new UIMA JSON CAS format

- inception/inception-app-webapp/src/main/resources/application.yml
- Try setting the Wicket markup encoding to UTF-8 so it does not fall back to the system encoding
> #3265 - Wrong character encoding in the page footer

- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package.json
- inception/pom.xml
- recogito-js 1.6.0 -> 1.7.1
- recogito-client-core 1.6.0 -> 1.7.4
- spring-boot 2.7.2 -> 2.7.3
- spring-security 5.7.2 -> 5.7.3
- springdoc 1.6.9 -> 1.6.11
- swagger 2.2.1 -> 2.2.2
> #3317 - Update dependencies (24.2)

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/SourceDocument.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/LearningRecordService.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/LearningRecord.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/LearningRecordServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/Fixtures.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/LearningRecordServiceImplIntegrationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RelationSuggestionVisibilityCalculationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/SpanSuggestionVisibilityCalculationTest.java
- Add new query to get only learning records for current document to better hide rejections/skips
- Better checking that a learning record actually belongs to the right doc/layer/feature when hiding rejections/skips
- Added a few new builders
> #3335 - Hiding rejected suggestions wrongly leaks into other documents

- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/relation.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/span.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/utils.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/view.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/abstract.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/container.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/relation.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/annotation/span.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/render/appendChild.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/render/renderSpan.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/page/pdf/PDFAnnoPage.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/page/textLayer.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/page/util/window.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/shared/coords.ts
- Improve robustness of the rendering code and add more helpful logging
- Use `globalThis` instead of `window` to remove errors from the TypeScript compiler
- Address various linter issues
- Fix bug that zero-width annotations are created at wrong position
- Fix rendering of zero-width annotations
* Try pressing shift and clicking on text in the PDF editor to create a zero-width annotation
> #3365 - Creating a zero-width annotation breaks PDF rendering

- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationLayer.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Recommender.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplTest.java
- Determine the covered text based on the aligned offsets instead of simply calling getCoveredText() on the suggested annotation
* Build an external recommender that provides sub-token suggestions for a token-aligned layer
> #3367 - Suggestion covered text may be wrong

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xml/XmlDocumentViewControllerImpl.java
- First check if XmlDocument exists in the CASes type system before trying to use it
> #3384 - Trying to used an HTML/XML-based editor on an old document may fail

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/export/ExportDocumentDialogContent.java
- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentImportExportService.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentService.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporter.java
- inception/inception-documents/pom.xml
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportServiceImpl.java
- inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceControllerImplTest.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/LegacyRemoteApiController.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/AnnotationDocumentExporter.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/UserDaoImpl.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/AjaxDownloadBehavior.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/AjaxDownloadLink.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/InputStreamResourceStream.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java
- Improve naming of files in exports via the export document dialog on the annotation page
- Improve naming of files in exports via the project export
- Try improving cleaning up of temporary files generated when exporting from the annotation page
- Make "." an illegal character in usernames (because it is the extension separator and we use usernames in filenames....)
* Export document through the annotation page
* Export via the project export feature and inspect ZIP contents
> #3403 - Fix name of ZIP file used for exported XMIs

- inception/inception-app-webapp/src/main/resources/META-INF/spring.factories
- inception/inception-diam/pom.xml
- inception/inception-diam/src/test/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController_ViewportRoutingTest.java
- inception/inception-external-editor/pom.xml
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewController.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xml/XmlDocumentViewController.java
- inception/inception-html-editor/pom.xml
- inception/inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/docview/HtmlDocumentViewController.java
- inception/inception-project-export/pom.xml
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceController.java
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceControllerImpl.java
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/task/ProjectExportTask_ImplBase.java
- inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/controller/ExportServiceControllerImplTest.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/InceptionSecurityRemoteApiAutoConfiguration.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/InceptionSecurityActuatorAutoConfiguration.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/InceptionSecurityWebUIApiAutoConfiguration.java
- inception/inception-security/src/main/resources/META-INF/spring.factories
- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashletController.java
- inception/inception-websocket/pom.xml
- inception/inception-websocket/src/test/java/de/tudarmstadt/ukp/inception/websocket/WebSocketIntegrationTest.java
- Enable Spring MVC CSRF protection on UI API and view endpoints
- Move UI API security configuration and actuator security configuration to security module
- Adjust URL space for views and UI-related APIs to be more manageable and shorter
* Check if different views and Spring-MVC based UI elements still work (e.g. project export, activities dashlet)
> #3452 - Enable Spring MVC CSRF protection on UI API and view endpoints

- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-oauth2.adoc
- Fix auto-login property name
- Fix typo
- Remove "roles" from the scope in the example because INCEpTION only supports external authentication, not authorization and some IDPs may not support the "roles" anyway
> #3468 - Wrong auto-login property in documentation

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/bool/BooleanFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/NumberFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/NumberFeatureTraits.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/number/NumberFeatureTraitsEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureTraits.java
- inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/feature/FeatureSupport.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/JSONUtil.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
- Change handling of the required checkbox to kick in when primitive values are used
- Set required to "true" as a save action on the number and boolean features
> #3462 - "Required" greyed out but NOT checked for integer features

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiSelectTextFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoAutoCompleteTextFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoChoiceDescriptionScriptReference.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoComboboxTextFeatureEditor.html
- inception/inception-bootstrap/src/main/ts/bootstrap/shim-kendo.scss
- Adjust style to fix extra space
- Expand item text to cover full width such that tooltips appear when hovering anywhere over the item and not only when the mouse is directly over the label
> #3502 - Combo-box and auto-complete field dropdown layout is broken

- inception/inception-app-webapp/src/main/resources/application.yml
- Exclude /api from the Wicket filter
> #3506 - No sessions should be created when remote API is accessed

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/link/LinkFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/ClassicKendoComboboxTextFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/DynamicTextAreaFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/InputFieldTextFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoAutoCompleteTextFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoComboboxTextFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/RadioGroupStringFeatureEditor.html
- inception/inception-bootstrap/src/main/ts/bootstrap/shim-kendo.scss
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/kendo/KendoFixDisabledInputComponentStylingBehavior.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- Add marker classes to the different editor types so we can see which of them is used even if no other styling has been set up
- Globally fix disabled Kendo components styling
> #3527 - Disabled combo boxes and auto-completes have no styling

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/link/LinkFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Make ADEP and document-metadata sidebar properly disable feature editors on non-editable layers
- Prevent creation and deletion of non-editable annotations in the document metadata sidebar
- Improve layout of the LinkFeatureEditor
- Fix bug that the ADEP would not show if there are only read-only layers in the document meaning one could not inspect them
- Fix NPE in the lazy details when using a multi-value string feature
* Try having only read-only layers in a document and viewing its annotations
* Try using the link feature editor
* Try playing around with finishing documents and/or marking layers read-only 
* Switch between annotations on editable and non-editable layers
> #3519 - Read-only layer's links are removable

- inception/inception-js-api/src/main/ts/src/util/OffsetUtils.ts
- inception/inception-js-api/src/main/ts/src/util/ViewportTracker.ts
- Added a generic and reusable ViewportTracker to the JavaScript API for use in editors
> #3537 - Load only visible annotations for Markup-based editors

- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
- Display gazeteer reading errors in the recommender log
- If a gazeteer could be loaded successfully, display how many entries were read from it
* Create an invalid gazeteer, e.g. one containing a line without a tab
* Go to the annotation page, trigger a recommendation, look at the recommender log in the recommender sidebar to see the error
> #3545 - Error reading a gazeteer is not visible to the user

- inception/pom.xml
- JUnit 5.9.0 -> 5.9.1
- JUnit Platform 1.9.0 -> 1.9.1
- Swagger 2.2.4 -> 2.2.6
- MariaDB driver 2.7.5 -> 2.7.7
- Hibernate 5.6.10 -> 5.6.14
- Hibernate validator 6.2.3 -> 6.2.5
- ElasitcSearch 7.17.6 -> 7.17.7
- OpenSearch 1.3.5 -> 1.3.6
- RDF4J 4.1.2 -> 4.1.3
- Asciidoctor 2.5.5 -> 2.5.7
- FontAweseom 5.15.3 -> 5.15.4
- Fastutil 8.5.8 -> 8.5.9
- byte-buddy 1.12.10 -> 1.12.18
- jaxb-api 2.3.0 -> 2.3.1
- jaxb-impl 2.3.0 -< 2.3.7
- ivy -> 2.5.1
> #3555 - Update dependencies (25.5)

- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-curation/pom.xml
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporterTest.java
- inception/inception-export/pom.xml
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/config/DocumentImportExportServiceAutoConfiguration.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/config/DocumentImportExportServiceProperties.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/config/DocumentImportExportServicePropertiesImpl.java
- inception/inception-export/src/main/resources/META-INF/asciidoc/admin-guide/settings_document-import-export.adoc
- inception/inception-export/src/test/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImplTest.java
- inception/inception-io-json/src/main/java/de/tudarmstadt/ukp/inception/io/jsoncas/UimaJsonCasFormatSupport.java
- inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv1FormatSupport.java
- inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv2FormatSupport.java
- inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/WebAnnoTsv3FormatSupport.java
- inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/clarin/webanno/xmi/BinaryCasFormatSupport.java
- inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/clarin/webanno/xmi/XmiFormatSupport.java
- inception/inception-io-xmi/src/main/java/de/tudarmstadt/ukp/clarin/webanno/xmi/XmiXml11FormatSupport.java
- inception/inception-project-export/pom.xml
- inception/inception-project-export/src/test/java/de/tudarmstadt/ukp/inception/project/export/AnnotationDocumentsExporterTest.java
- inception/inception-search-mtas/pom.xml
- inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndexTest.java
- inception/inception-search-mtas/src/test/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUpgradeTest.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java
- inception/inception-versioning/pom.xml
- inception/inception-versioning/src/test/java/de/tudarmstadt/ukp/inception/versioning/VersioningServiceImplTest.java
- Add option to configure CAS doctor during import - default is "AUTO"
- Add ability to ask format if it should be validated during import
- Turned this option on for flexible formats like CAS formats and TSV
- Add optional CAS Doctor checking to document import
- Display CAS Doctor results to the user in the document import panel
* Import an XMI with inconsistent data that CAS Doctor would be able to detect
> #2068 - Validate documents during import

- inception/inception-image/src/main/resources/META-INF/asciidoc/user-guide/annotation_images.adoc
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/config/CoreUiAutoConfiguration.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/config/CspProperties.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/config/CspPropertiesImpl.java
- inception/inception-ui-core/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- Allow adding image servers to CSP through configuration
- Unrelated: display namespace prefix on logged sanitized elements in the SanitizingContentHandler
* Try linking to an image on an external server
* ... without the external server in the CSP setting
* ... then with the external server in the setting
> #2285 - Enable Wicket CSP

- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- Run CAS doctor checks only after tokenization and sentence splitting, just before returning the final initial CAS
> #3589 - Import CAS Doctor check runs too early

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupportTest.java
- inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupportTest.java
- inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/AnnotationSchemaService.java
- inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/adapter/IllegalFeatureValueException.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- inception/inception-schema/src/test/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImplTest.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/WicketExceptionUtil.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureSupport.java
- IllegalArgumentException when trying to use an out-of-tagset tag in a string feature using a closed tagset changed to IllegalFeatureValueException
- Pull duplicate code for creating missing tags out of StringFeatureSupport and MultiValueStringFeature into the schema service
- Moved IllegalFeatureValueException to schema api module so we can use it in the schema service
* Try using a tag value that is not in the tag set in a string feature editor
> #2356 - Reduce exceptions thrown to reduce log pollution

- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/JsonImportUtil.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/TagsetImportExportUtils.java
- inception/inception-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedTagSetConstant.java
- inception/inception-project-initializers/pom.xml
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/CoreferenceRelationTagSetInitializer.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/CoreferenceTypeTagSetInitializer.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/DependencyTypeTagSetInitializer.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/NamedEntityTagSetInitializer.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/PartOfSpeechTagSetInitializer.java
- inception/inception-ui-tagsets/pom.xml
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.html
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.java
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetEditorPanel.properties
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetImportPanel.html
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetImportPanel.java
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetSelectionPanel.html
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetSelectionPanel.java
- Clicking on a format directly downloads the tagset - selection via a radio-group is no longer necessary
- Importing a tagset auto-detects the format - choosing a format is no longer necessary
- Improve layout of various buttons
- Extract more code from UI layer to service / utils
* Try exporting and importing tagsets in different formats
> #3474 - Tagset export dropdown disappears when selecting format

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiSelectTextFeatureEditor.java
- Use a non-lazy multi-select when the input is disabled because the lazy multi-select has this bug not showing values when disabled
> #3609 - Feature editors do not show annotations in locked documents for multilabel String features

- inception/inception-api-formats/pom.xml
- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportServiceImpl.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/LegacyRemoteApiController.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/io/FileUploadDownloadHelper.java
- Pad temp file names to three char prefix if necessary
> #3630 - Export of single document fails when username is too short

- inception/pom.xml
- mockito 4.6.1 -> 4.9.0
- wicket 9.11.0 -> 9.12.0
- wicketstuff 9.11.0 -> 9.12.0
- rdf4j 4.1.3 -> 4.2.2
- jackson 2.13.4 -> 2.14.1
- axios -> webjars removed from maven
- oauth2-oidc-sdk 9.35 -> 9.43.1
- commons-compress 1.21 -> 1.22
- picocli 4.6.3 -> 4.7.0
> #3616 - Upgrade dependencies

- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VDocument.java
- Fixed bug in VDocument that if a layer has both arcs and spans, only the spans would be returned by `objects()` but not the arcs
> #3522 - No color distinction of merged vs unmerged links in curation page

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/MoveSpanAnnotationRequest.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanAdapter.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanAnchoringModeBehavior.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanAnnotationRequest_ImplBase.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanCrossSentenceBehavior.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanLayerBehavior.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanMovedEvent.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanOverlapBehavior.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/MoveSpanAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/config/DiamAutoConfig.java
- inception/inception-diam/src/main/ts/src/diam/DiamAjaxImpl.ts
- inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
- inception/inception-js-api/src/main/ts/src/util/OffsetUtils.ts
- Introduce a new MoveSpanAnnotation action that allows changing the boundaries of a span without deleting/recreating it
* The is no (built-in) editor supporting this yet, so no way of testing
> #283 - Resize span

- inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/Tsv3XCasDocumentBuilder.java
- inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/Tsv3XCasSchemaAnalyzer.java
- inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/model/TsvDocument.java
- inception/inception-io-webanno-tsv/src/main/resources/META-INF/asciidoc/user-guide/formats-webannotsv3.adoc
- inception/inception-io-xmi/src/main/resources/META-INF/asciidoc/user-guide/formats-uimaxmi.adoc
- Avoid error when trying to export layers with multi-value string features
- Update documentation saying that WebAnno TSV is now considered legacy and doesn't support everything
* Create a project with a multi-value string feature on a span layer and a relation layer attaching to that span layer
* Create annotations of the span layer and connect them using a relation
* Export the document as WebAnno TSV 3
> #3679 - NullPointerException during export in WebAnno format

- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/webanno.js
- Apply default scripts/fonts/styles only to pages inheriting from ApplicationPageBase
- Fix error if spinner element cannot be found on page
> #3695 - Use default styles and scripts only on application pages

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByPositionList.svelte
- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- inception/inception-diam-editor/src/main/ts/src/SpanText.svelte
- inception/inception-diam-editor/src/main/ts/src/Utils.ts
- Do not repeat the annotation label for every item since it is already shown in the group heading. Instead just display a layer-colored bubble
- Show an indicator whether an annotation is a relation or a span
- Display something like "empty span" for zero-width annotations to avoid the sidebar item collapsing in height
- Make the group headings stick while scrolling so we always know in which group we are
- Sort by text instead of position when grouping by label
* Use annotation sidebar
> #3701 - Improve grouped-by-label visuals

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/UserPreferencesServiceImpl.java
- Funnel page size property into the legacy bridge class that still fills in the legacy annotation editor preferences
> #3705 - annotation.default-preferences.page-size is ignored even if defined in settings.properties

- inception/inception-app-webapp/pom.xml
- inception/inception-constraints/pom.xml
- inception/inception-docker/pom.xml
- inception/inception-imls-external/pom.xml
- inception/inception-io-lif/pom.xml
- inception/pom.xml
- groovy -> removed (actually scoped to lif module which is no longer part of the final JAR)
- asciidoctor 2.2.1 -> 2.2.2
- ph-javacc-maven-plugin 4.1.4 -> 4.1.5
- swagger2markup-maven-plugin 1.3.3 -> 1.3.7
- exec-maven-plugin 3.0.0 -> 3.1.0
- maven-war-plugin 3.1.0 -> 3.3.2
- docker-maven-plugin 0.39.1 -> 0.40.4
- versions-maven-plugin 2.10.0 -> 2.14.2
- build-helper-maven-plugin 3.2.0 -> 3.3.0
- maven-checkstyle-plugin 3.1.2 -> 3.2.0
> #3571 - Update dependencies (27.0)

- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.java
- make icon reflect curation state instead of annotation document state if curation target is set to curation user in curation sidebar
- allow curators to re-open documents (skipping the confirmation dialog entirely)
- properly toggle curation state instead of annotation state if curation target is set to curation user in curation sidebar
* Try using the curation sidebar with and without targeting the curation document
> #3716 - Workflow broken when curating to curation user using curation sidebar

- inception/inception-io-webanno-tsv/src/main/java/de/tudarmstadt/ukp/clarin/webanno/tsv/internal/tsv3x/Tsv3XDeserializer.java
- Add better error message if number of fields in a line is wrong
- If the error is not an IOException, do not chain the cause and instead give a message saying at which point the error occurs and include the error message of the cause
* Try importing a broken TSV file
> #3725 - Importing broken TSV file may give unhelpful error message

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/misc/ReorderableTagAutoCompleteField.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiSelectTextFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoChoiceDescriptionScriptReference.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoChoiceDescriptionScriptReference.js
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/KendoComboboxTextFeatureEditor.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureEditor.java
* Switch to a way of initializing the tooltips that does not require inline script
* Try various feature editors which come with tooltips (single-/multi-value string, single-/multi-value concept)
> #3703 - Concept feature editor tooltips no longer work

- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectImportRequest.java
- inception/inception-export/src/test/java/de/tudarmstadt/ukp/inception/export/exporters/ProjectPermissionsExporterTest.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Project.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/exporters/ProjectPermissionsExporter.java
- Added more unit tests to user and permission import
- Added builders to some data classes
- Make sure that no permissions are created for project-bound users that could not be created during import
> #3729 - Project permissions for project-bound users of foreign project might be created

- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/event/TransientAnnotationStateChangedEvent.java
- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/service/DiamWebsocketController.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/event/RecommendationRejectedEvent.java
- Display suggestions with accept/reject buttons
- Fix issue that rejecting an annotation does not update the annotation sidebar
* Use the annotation sidebar in a project with reocmmenders
> #3734 - Better visual representation of suggestions in the annotation sidebar

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiSelectTextFeatureEditor.java
- Add missing JS reference
* See issue
> #3742 - Feature editors do show multi value lists in locked documents for multilabel String features which looks bad

- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.css
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.ts
- Display a temporary animated highlight at the target of a scroll-to action to draw the users attention
* Open a PDF document
* Create some annotations
* Open the annotation sidebar
* Click on the text of an annotation to trigger a jump-to action without a selection
* See the highlight
**Demo**
https://user-images.githubusercontent.com/1410238/214895859-606f81e8-1680-4132-8997-df193584d5ec.mp4
> #3745 - Highlight scrolling target after jump in PDF editor

- inception/inception-diam-editor/src/main/ts/src/SpanText.svelte
- Display a tooltip for long annotations when hovering with the mouse over the covered text in the annotation sidebar
* Create a long annotation > 50 characters
* Open the annotation sidebar
* Hover with the mouse over the covered text
* See tooltip
**Demo**
https://user-images.githubusercontent.com/1410238/214902328-86dca391-c862-4ea2-b4d3-f38b127bb2a1.mp4
> #3747 - Tooltip with longer text on annotations truncated in sidebar

- inception/inception-bootstrap/src/main/ts/bootstrap/shim-wicket.scss
- Slightly increase the z-index of the modal backdrop
* See issue
> #3752 - Section headers in annotation sidebar are above modal backdrop

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- Support zero-width annotations when extracting recommendations on layers anchored to TOKENS
> #3750 - Cannot create zero-width recommendations

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByPositionList.svelte
- Added ability to delete annotation from sidebar
- Added animated placeholder while annotations in the sidebar are still loading
* Try deleting an annotation from the left sidebar, in particular try one that has relations attached to see if the confirmation dialog also pops up
**Demo**
> #3749 - Delete annotation from annotation sidebar

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/InputFieldStringFeatureEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/InputFieldStringFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/IriInfoBadge.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/IriInfoBadge.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- If a string feature value in a single-value string feature editor without a tagset is a valid URL (http or https), a button appears to open that URL in a new window
- Also apply this design to the concept feature editor
* Create a string feature without a tagset
* Create annotation with that feature and enter an URL into it
* Try linking a concept feature to a concept that has a valid URL as its IRI
**Demo**
> #3728 - Allow opening URL feature values in new browser window

- inception/inception-io-xml/pom.xml
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/Cas2SaxEvents.java
- inception/inception-io-xml/src/test/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/Cas2SaxEventsTest.java
- inception/inception-io-xml/src/test/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/CasXmlHandlerTest.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/DefaultHandlerToContentHandlerAdapter.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/XmlEventLoggingFilter.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/XmlParserUtils.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ElementPolicy.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionIOUtils.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionIOUtilsTest.java
- inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandlerTest.java
- inception/inception-support/src/test/resources/SanitizingContentHandler/Policy.yaml
- Support recovering namespace information as SAX events in the Cas2SaxEvents class
- Support recovering and handling namespace information in the SanitizingContentHandler
- Support for namespaces in the PolicyCollectionIOUtils when reading policy files
- Added several tests
> #3765 - Support for namespaces in SanitizingContentHandler

- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Project.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/CurrentProjectDashlet.java
- Decouple input field from project
- If the project name is invalid, give an error message and do not leave edit mode
> #3767 - Trying to set invalid project name produces error page

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_internal-backup.adoc
- Improved documentation
* Read documentation
> #3771 - Documentation says internal backups disabled by default but they are not

- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-external-editor/pom.xml
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewController.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- Allow format supports to offer resources
- Allow to access such resources via the XHtmlXmlDocumentViewController
> #3773 - Support loading resources from documents that are actually archives

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationDocumentService.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationDocumentServiceImpl.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/AnnotatorsPanel.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarService.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- inception/inception-ui-curation/src/test/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationServiceTest.java
- Change method in curation service(s) to return list of curatable documents (which includes closed broken documents and not only finished documents)
* Close a document and mark it as problematic in the close dialog
* Try curating it
> #3809 - Unable to curate documents marked as broken by annotators

- inception/inception-bootstrap/src/main/ts/bootstrap/inception-custom.scss
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.html
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxButton.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/lambda/LambdaAjaxLink.java
- Changed LambdaAjaxLink and LambdaAjaxButton to always add the disabled class if they are not enabled in the hierarchy
- Fix border of radio button group items disappearing on hover
> #3807 - Button to add document level annotations not looking disabled when document is finished

- inception/inception-bootstrap/src/main/ts/bootstrap/inception-feature-editors.scss
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/feature/LevenshteinFeatureGenerator.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/model/CandidateEntity.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandle.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FusekiRepositoryTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/Rdf4JRepositoryTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- inception/inception-kb/src/test/resources/queries/additional_search_properties_2/rdf4j.sparql
- inception/inception-kb/src/test/resources/turtle/data_additional_search_properties.ttl
- inception/inception-kb/src/test/resources/turtle/data_additional_search_properties_2.ttl
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/KBHandleTemplate.java
- Properly additional match labels in the SPARQLQueryBuilder
- Use the additional match labels when ranking using the LevenshteinFeatureGenerator
- If the best match term differs from the KBHandle primary UI label, display it also in the dropdown
> #3822 - Order of matches found in knowledge base search is not correct

- inception/inception-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- inception/pom.xml
- junit 5.9.1 -> 5.9.2
- junit-platform 1.9.1 -> 1.9.2
- spring 5.3.24 -> 5.3.25
- spring-data 2.7.6 -> 2.7.8
- spring-boot 2.7.7 -> 2.7.8
- spring-security 5.7.6 -> 5.7.7
- groovy 4.0.7 -> 4.0.9
- swagger 2.2.7 -> 2.2.8
- mariadb-driver 2.7.7 -> 2.7.8
- postgres-driver 42.5.1 -> 42.5.4
- hibernate 5.6.14 -> 5.6.15
- elasticsearch 7.17.8 -> 7.17.9
- opensearch 1.3.7 -> 1.3.8
- asciidoctor-diagram 2.2.3 -> 2.2.4
- jackson 2.13.4 -> 2.13.5
- node 16.18.1 -> 16.19.1
- esbuild 0.14.53 -> 0.16.17
- esbuild-sass-plugin 2.3.3 -> 2.5.0
- esbuild-svelte 0.7.1 -> 0.7.3
- jquery 3.6.1 -> 3.6.3
- commons-fileupload 1.4 -> 1.5
- dom4j 2.1.3 -> 2.1.4
- bytebuddy 1.12.20 -> 1.12.23
- jsoup 1.15.3 -> 1.15.4
- caffeine 3.1.2 -> 3.1.4
- jaxb-impl 2.3.7 -> 2.3.8
- ant 1.10.12 -> 1.10.13
- update …
> #3826 - Update dependencies

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/component/DocumentNamePanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ProjectPageBase.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/config/DashboardProperties.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/config/DashboardPropertiesImpl.java
- inception/inception-ui-dashboard/pom.xml
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/config/DashboardAutoConfiguration.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/project/ProjectDashboardPage.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/menubar/MenuBar.java
- inception/inception-ui-dashboard/src/main/resources/META-INF/asciidoc/admin-guide/settings_dashboard.adoc
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImpl.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowDocumentNavigationActionBarExtension.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/MatrixWorkloadExtensionImpl.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowDocumentNavigationActionBarExtension.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/config/MatrixWorkloadManagerAutoConfiguration.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraits.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraitsEditor.html
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraitsEditor.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraitsEditor.properties
- inception/inception-workload-matrix/src/main/resources/META-INF/asciidoc/user-guide/workload_matrix.adoc
- inception/inception-workload-ui/src/main/java/de/tudarmstadt/ukp/inception/workload/project/WorkloadSettingsPanel.html
- inception/inception-workload-ui/src/main/java/de/tudarmstadt/ukp/inception/workload/project/WorkloadSettingsPanel.java
- inception/inception-workload/pom.xml
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/extension/WorkloadManagerExtension.java
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/extension/WorkloadManagerExtensionPoint.java
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/extension/WorkloadManagerExtensionPointImpl.java
- Added global setting to determine which project roles should be able to access the project dashboard
- Hide the menubar if users are not allowed to access the project dashboard
- If project dashboard access is disabled, do not redirect user to dashboard e.g. if a document is not accessibly on the annotation page - instead show a respective message on that page
- Added option in the project settings to configure if random access to documents is supported for the matrix workload
- Added trait editors to workload modes
* Disable random access to documents and try accessing directly accessible as well as non-accessible documents, try closing them, etc.
* Disable dashboard access e.g. for annotators and see what happens if you still try to access …
> #3831 - Better support a direct-access workflow

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-documents/src/test/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImplConcurrencyTest.java
- Make sort-by-score the default
- Make the DocumentServiceImplConcurrentyTest run faster again (fewer iterations and less concurrency)
* Open the sidebar and check if sorting is enabled by default
> #3762 - Ability to sort annotation sidebar by recommender scores

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/DashboardMenu.java
- Configure InputBehavior to not trigger when the focus is in an input field
> #3836 - Keyboard shortcuts on dashboard should not trigger when editing project title

- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/view/pdfjs/PdfJsViewerPage.java
- inception/inception-pdf-editor2/src/main/ts/pdfjs-web/viewer.css
- inception/inception-pdf-editor2/src/main/ts/pdfjs-web/viewer.html
- inception/inception-pdf-editor2/src/main/ts/pdfjs-web/viewer.js
- Disable keyboard shortcuts for unused functionality
- Also disable presentation mode because it does not work well with INCEpTION
* Use the PDF editor
> #3846 - PDF editor keyboard shortcuts for unused functionality still active

- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
- inception/inception-support-standalone/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/standalone/LoadingSplashScreen.java
- Catch exception caused by AWT being initialized on a headless Java which doesn't know it is headless and handle it
* See issue
> #3854 - Webserver should run on a headless setup

- inception/inception-workload-matrix/pom.xml
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraits.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraitsEditor.html
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraitsEditor.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/trait/MatrixWorkloadTraitsEditor.properties
- Added option in the workload panel of the project settings to hide the reset button (for matrix workload only)
* Enable/disable the option
* Visit the annotation page
> #3865 - Option to hide the reset button on the annotation page

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- Add toggle to change whether suggestions should be shown above or below annotations (default below)
* Show the annotation sidebar in a project with recommenders
* Enable sort by score (on by default)
* Get to a state where both annotations and suggestions are shown
* Use the toggle to switch between recommendations appearing first or last
> #3869 - Suggestions should be shown below annotations in annotation sidebar

- inception/inception-brat-editor/src/main/ts/src/visualizer_ui/VisualizerUI.ts
- Added "crossorigin" attribute to allow the browser to load images across domains
> #3874 - Images not shown in hover popup

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose-mysql8.yml
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/docker-compose.yml
- inception/inception-doc/src/main/resources/META-INF/asciidoc/developer-guide/release.adoc
- inception/inception-docker/README.md
- inception/inception-docker/pom.xml
- Updated documentation to refer to the GitHub packages repository instead of DockerHub
- Update compose example files accordingly as well
* Check if e.g. deploying docker images as part of a release still works
* Check if the docker compose files still work
> #3879 - Update documentation for move of Docker containers to GitHub

- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetrySupportImpl.java
- inception/inception-telemetry/src/main/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/ToggleBox.java
- inception/inception-telemetry/src/test/java/de/tudarmstadt/ukp/clarin/webanno/telemetry/matomo/MatomoTelemetrySupportImplTest.java
- Fix telemetry toggle button
- Bump settings version so users need to confirm telemetry again on the next admin login (implicitly disabled until then)
> #3884 - Telemetry enable setting toggle logic inverted

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningServiceImpl.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasStorageServiceImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/events/DocumentOpenedEvent.java
- inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/AnnotationEditorBase.java
- inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/AnnotationEditorExtension.java
- inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/AnnotationEditorExtensionRegistry.java
- inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/AnnotationEditorExtensionRegistryImpl.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/editorstate/AnnotatorState.java
- inception/inception-imls-external/src/main/resources/META-INF/asciidoc/developer-guide/external_recommender.adoc
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/AnnotationSuggestion.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/AutoAcceptMode.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/RelationSuggestion.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SpanSuggestion.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngine.java
- inception/inception-recommendation-api/src/test/java/de/tudarmstadt/ukp/inception/recommendation/api/model/AnnotationSuggestionTest.java
- inception/inception-recommendation-api/src/test/java/de/tudarmstadt/ukp/inception/recommendation/api/model/PredictionGroupTest.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.properties
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- inception/inception-recommendation/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation.adoc
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/Fixtures.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/LearningRecordServiceImplIntegrationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplTest.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- Extended recommender API to allow force-accepting suggestions into a document when the document is opened for the first time
- Documented the extension
* Create a non-trainable recommender and hook it up to a project - ensure that the recommender sets `<feature-name>_auto_accept` to `on-first-access` on at least one recommendation
* Enable the option "wait for non-trainable recommenders when opening a project" in configuration panel of the recommender list in the project settings
* Open a document and see that the auto-accept recommendation is auto-accepted
> #3868 - Allow a recommender to force-create annotations

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor_ImplBase.java
- inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/annotation_create-annotations_concept-features.adoc
- Consider the canonical term as well when filtering
* Create a knowledge base that uses additional matching properties
* Have a concept that e.g. has the label `foo (bar)` and an additional label `boo`
* Locate the concept on the annotation page by entering `boo::bar`
> #3903 - Enable filtering by canonical term

- inception/inception-export/pom.xml
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-export/src/test/java/de/tudarmstadt/ukp/inception/export/SegmentationTest.java
- Add an additional parameter to the sentence splitting function that allows specifying zoning annotations.
> #3905 - Allow sentence splitting to consider document structure

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByPositionList.svelte
- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- inception/inception-diam-editor/src/main/ts/src/SpanText.svelte
- Display part of the text after the covered text as muted text
- No smart cut-off
- Trailing text may cause annotation item to wrap and thereby take up more vertical space
* Create a few annotations and check what they look like in the annotation sidebar
**Demo**
> #3877 - Show a bit of context in the annotation sidebar

- inception/inception-diam-editor/pom.xml
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/DiamAnnotationBrowser.java
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/preferences/DiamSidebarManagerPrefPanel.html
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/preferences/DiamSidebarManagerPrefPanel.java
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/preferences/DiamSidebarManagerPrefPanel.properties
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/preferences/DiamSidebarManagerPrefs.java
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/preferences/PinnedGroupsPanel.html
- inception/inception-diam-editor/src/main/java/de/tudarmstadt/ukp/inception/diam/sidebar/preferences/PinnedGroupsPanel.java
- inception/inception-diam-editor/src/main/resources/META-INF/asciidoc/user-guide/annotation-sidebar.adoc
- inception/inception-diam-editor/src/main/resources/META-INF/asciidoc/user-guide/projects_annotation_sidebar.adoc
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/DiamAnnotationBrowser.svelte
- inception/inception-diam-editor/src/main/ts/src/Utils.ts
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/getting-started.adoc
- inception/inception-ui-dashboard/pom.xml
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/settings/annotation/AnnotationPreferencesProjectSettingsPanel.java
- inception/inception-ui-dashboard/src/main/resources/META-INF/asciidoc/user-guide/projects_annotation.adoc
- inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_documents.adoc
- Add ability to add pinned categories in project settings
- Use the pinned categories in the annotation sidebar when in group-by-label mode
* Add some pinned categories in the project settings on the annotation panel
* Open the annotation page, open the annotation sidebar, put it into "group-by-label" mode and see the pinned categories
* Add an annotation with one of the pinned labels
> #3914 - Allow pinning label groups to the annotation sidebar

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- Move "accept best" buttons (and other buttons) out of the results group so they are visible even when no evaluation results are available
* Configure an external recommender (or another recommender without evaluation)
* Open the recommender sidebar
* Check if the "accept best" button is available
> #3909 - Accept best button missing from recommendation sidebar

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- Index was not properly increased when a feature is disabled causing VID to be wrong
* Create a layer with two features, one is a slot feature and the other is a primitive feature
* Ensure that the slot feature's name comes alphabetically after the primitive feature's name
* Annotate something so that the slot is filled
* Disable the primitive feature
* Try curating this, in particular try merging the slot filler
> #3921 - Unable to merge slot filler when a feature in the project is disabled

- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- inception/inception-websocket/pom.xml
- inception/inception-websocket/src/main/java/de/tudarmstadt/ukp/inception/websocket/controller/LoggedEventsWebsocketControllerImpl.java
- Avoid deleting an index again if the index is already being deleted
- Do not roll back a running transaction if a project cannot be found by ID or name
- If a project or document has been deleted, do not generate a WebSocket event notification for it
* Set `websocket.logged-events.enabled=true` in the `settings.properties`
* Try deleting a project
> #3926 - Projects may not delete if WebSocket-based event notification is enabled

- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- Fix search in case the user only searches for a start or end of an annotation, e.g. only `<blah>` or `</blah>`
* Try search only for the start or end of an annotation
> #3922 - Search results not showing

- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasUimaParser.java
- Sanitize feature names in the same way as layer names when indexing
* Create a feature with a space in its name and try searching for it, replacing the space with an underscore in the query
> #3929 - Spaces in feature names not treated same as in layer names when indexing

- inception/pom.xml
- spring 5.3.25 -> 5.3.26
- spring-boot 2.7.8 -> 2.7.10
- spring-data 2.7.8 -> 2.7.10
- postgres-driver 42.5.4 -> 42.6.0
- wicket-jquery 9.11.0 -> 9.12.0
- byte-buddy-agent -> 1.14.0
- commons-compress 1.22 -> 1.23.0
> #3932 - Upgrade dependencies

- inception/inception-app-webapp/src/main/resources/log4j2-spring.xml
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/logging.adoc
- inception/pom.xml
- Use log4j2-spring.xml instead of log4j2.xml so Spring gets a chance of initializing before the logging framework is initialized
- Remove package-scanning from the config file and instead properly configure the annotation processor to set up the log4j plugin descriptor during build
> #3951 - Lots of errors and warnings from logging system during startup

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- When checking if there is a candidate without a label, consider **all** candidates and not just the arbitrary first one
> #3963 - Merging the label into the unlabeled concept issue while stacking is enabled

- inception/pom.xml
- pom.xml
- dkpro-parent-pom 28 -> 30
- spring-boot 2.7.10 -> 2.7.11
- spring-data 2.7.10 -> 2.7.11
- tomcat 9.0.71 -> 9.0.74
- wicket-bootstrap 6.0.1 -> 6.0.3
- asciidoctor-plugin 2.2.2 -> 2.2.3
- asciidoctor 2.5.7 -> 2.5.8
- asciidoctor-diagram 2.2.4 -> 2.2.7
- jackson 2.14.1 -> 2.14.2
> #3975 - Upgrade dependencies (27.7)

- inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/AnnotationSchemaService.java
- inception/inception-model-export/src/main/java/de/tudarmstadt/ukp/clarin/webanno/export/model/ExportedAnnotationFeature.java
- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/AnnotationFeature.java
- inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/LayerExporter.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.java
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/ProjectTagSetsPanel.properties
- Add buttons to change order of features
- Sort features primarily by rank when fetching them from the DB
- Rewrite some DB queries using the criteria API
* Create multiple features on a layer
* Change their order using the arrow buttons that appear when selecting a layer
* Check if the order is reflected in the annotation sidebar on the annotation page
> #1592 - Allow re-ordering of features

- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/UI/span.ts
- Restore ability to select text after doing a double-click
> #4008 - PDF highlighting disables after double-clicking on a recommended annotation

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/model/AnnotationEditorProperties.java
- inception/inception-external-editor/src/main/ts/src/ExternalEditorFactory.ts
- inception/inception-js-api/src/main/ts/src/editor/AnnotationEditorProperties.ts
- inception/inception-pdf-editor/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor/PdfAnnotationEditor.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/PdfAnnotationEditor.java
- Display loading indicator if the editor takes a bit longer to load
- Allow editors that do not need this to turn it off
* Try opening a large document in the PDF editor (editor should come up quickly and loading indicator of pdfjs should be used)
* Try opening a large document e.g. using the Apache Annotator external editor plugin (loading indicator should show)
> #4018 - Display loading indicator in editor view area

- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- Allow empty queries when rendering extension-level lazy details
- Normalize empty query to null because suggestions with no label have null as a label and not the empty string
> #4022 - Hiding reason not shown if suggestion has no or empty label

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/exporter/OverlapIteratorTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/SpanSuggestionVisibilityCalculationTest.java
- Fix that annotations that have already been processed should be ignored - not suggestion groups
- Fix that collocation is considered when checking if overlapping annotation with same label should be hidden or not
- Added test
> #4024 - Suggestion that are not exactly matching an annotation should not be hidden if stacking is enabled

- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/resource/ContextSensitivePackageStringResourceLoader.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/wicket/resource/Strings.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- Add getStrings() mechanism that could be used from backend code
- Remove support for `.vue` files which are no longer used by INCEpTION
> #4032 - Allow using externalized strings from backend code

- inception/inception-build/src/main/resources/inception/checkstyle.xml
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommender.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/xml/ContentHandlerAdapter.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/IllegalXmlCharacterSanitizingContentHandler.java
- inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/IllegalXmlCharacterSanitizingContentHandlerTest.java
- Sanitize data before passing it to the XMI serializer - replacing problematic characters with spaces in text nodes and attributes
* Set up a project with an external recommender
* Import a document that contains control characters, e.g. `\u0000` somewhere
* See if sending the document to the external recommender fails or works (should work now)
> #1511 - External recommender fails when CAS contains control characters

- inception/inception-io-json/pom.xml
- inception/inception-io-json/src/main/java/de/tudarmstadt/ukp/inception/io/jsoncas/LegacyUimaJsonFormatSupport.java
- inception/inception-io-json/src/main/java/de/tudarmstadt/ukp/inception/io/jsoncas/config/LegacyUimaJsonCasFormatProperties.java
- inception/inception-io-json/src/main/java/de/tudarmstadt/ukp/inception/io/jsoncas/config/UimaJsonCasSupportAutoConfiguration.java
- inception/inception-io-json/src/main/resources/META-INF/asciidoc/user-guide/formats-uimajson-legacy.adoc
- Disable omission of default values for legacy UIMA JSON format
- Add option to switch to previous behavior of omitting default values
* Export basically any file as legacy JSON and check if the sofa string item has a `begin: 0` property.
> #1496 - Some spans are missing begin offset field

- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentAccess.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentAccessImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/docnav/DocumentNavigator.java
- inception/inception-ui-curation/pom.xml
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CurationDocumentNavigator.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowDocumentNavigationActionBarExtension.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/config/MatrixWorkloadManagerAutoConfiguration.java
- Centralize permission check for exporting documents into DocumentAccess class
- Permission check for exporting should consider the session owner, not the document owner
* Create a new project
* Import a document
* Add another user with the annotator and curator roles to the project
* Enable the "Disable export in annotation views" options in the "Details" tab of the project settings
* Disable the "Allow annotators to freely navigate between documents" in the "Workflow" tab of the project settings
* Visit the annotation page as the user that created the project (which should be a user with the "manager" permission level) and check that the document navigation and export buttons are present
* Use the open document dialog to open the document …
> #4048 - Document navigation options not visible to manager when viewing other users document

- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.java
- Change role filter such that admin users see everything
* Log in as `admin`
* Create some user `testuser`
* Create a new project
* Add `testuser` as manager to the project and remove `admin` from the project
* Go to the project overview page
* Check if the project can be found (should be since administrators should be able to see any project even if they have no role in it)
> #4052 - Admins no longer see all projects in the project overview

- inception/inception-brat-editor/src/main/ts/src/BratEditor.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer_ui/VisualizerUI.ts
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarTabbedPanel.java
- Re-render only the sidebar when its size is changed instead of the whole page
- Make brat editor get notified when its container element changes size so it can resize/rerender accordingly
> #4055 - Editor scrolls up when left sidebar is opened/closed

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/logging.adoc
`log4j2.xml` was replaced by `log4j2-spring.xml` in #3951.
> update dead link to the new file

- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/DocumentImportExportService.java
- inception/inception-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExporter.java
- inception/inception-constraints/src/main/java/de/tudarmstadt/ukp/clarin/webanno/constraints/export/ConstraintsExporter.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporter.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/export/CurationWorkflowExporter.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/exporters/ProjectSettingsExporter.java
- inception/inception-guidelines/src/main/java/de/tudarmstadt/ukp/inception/guidelines/exporters/GuidelinesExporter.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/gazeteer/exporter/GazeteerExporter.java
- inception/inception-imls-weblicht/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/weblicht/exporter/ChainExporter.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/ProjectExportServiceImpl.java
- inception/inception-project-export/src/main/java/de/tudarmstadt/ukp/inception/project/export/task/ProjectExportTask_ImplBase.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/exporters/ProjectPermissionsExporter.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/AnnotationDocumentExporter.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/LayerExporter.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/TagSetExporter.java
- inception/inception-sharing/src/main/java/de/tudarmstadt/ukp/inception/sharing/project/exporters/ProjectInviteExporter.java
- inception/inception-workload/src/main/java/de/tudarmstadt/ukp/inception/workload/event/exporter/WorkloadManagerExporter.java
- Refactor error handling to be better able to capture a helpful error message that includes the document name
* Create some ZIP file (small one)
* Import it as plain text
* Try exporting the project with this file choosing "CAS XMI (XML 1.0)" as secondary format
> #4066 - Display document name on export failure

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringRulesConfigurationPanel.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/coloring/ColoringRulesConfigurationPanel.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/clarin/webanno/support/Coloring.java
- Port text-color-selection code used in frontend to backend and use it in the coloring rule editor
- Nicer style for coloring rule editor
* Create a coloring rule with a light color (e.g. `#eeeeee`)
* Create a coloring rule with a dark color, (e.g. `#111111`)
* Check that the rules are rendered using a dark/light text color such that rule text is always readable
> #4074 - Text color does not change depending on background color in color rule editor

- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureEditor.java
- Make sure that the feature-update behavior is attached when switching between the read-only and the editable feature editor
> #4088 - Cannot save multi-value concept feature after closing another document

- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- Check if the SVG is still part of a document before starting to render. If it is not, do not render.
* Switch between documents when the brat editor is active and monitor the JS console in the browser
> #4090 - Error in brat editor when switching between documents

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- Reset editor state before loading CAS
- In particular on the curation page, that ensures that the selection is cleared before a re-merge is attempted (which was causing a problem because a callback listening for the merge-bulk-action tried to fetch the editor CAS too early to check if the selected annotation is still there)
* ... otherwise try opening and switching between documents in general
* ... try changing the annotation schema (i.e. add/remove layers or features) before opening/switching documents
> #4093 - Problem loading document in curation editor

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureTraitsEditor.java
- Refresh form when changing the tagset
> #4104 - Editor type choice does not become available after selecting a tagset

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeLinkTest.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/BratSuggestionVisualizer.java
- Added the message when merging slots has no effect
- Fix bad copy/pasted error message in BratSuggestionVisualizer while we are at it
* Try on a link feature with role labels as well as one without role labels
> #3691 - No message when merging already existing slot filler

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiSelectTextFeatureEditor.java
- Make sure that the feature-update behavior is attached when switching between the read-only and the editable feature editor
> #4116 - Cannot save multi-value string feature after closing another document

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.html
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- Implement the change
- Hide the entire card header when no annotation is selected, leaving only the no-data notice
- Remove deprecated code
> #4128 - Display layer type in annotation detail panel header

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/metrics_monitoring.adoc
Documentation of the most common settings used to activate and use the Sentry SDK (#4026).
> #4026 - Support for error tracking with Sentry

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderer.java
- inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRendererTest.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VCommentType.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/AnnotationComment.java
- inception/inception-brat-editor/src/main/ts/src/protocol/Protocol.ts
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compactv2/CompactSerializerV2Impl.java
- inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
- Remove "Yield" as a separate comment type - it is just a regular info comment
> #4139 - Reusable popover component for annotation editors

- Jenkinsfile
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningService.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningServiceImpl.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/strategy/UncertaintySamplingStrategy.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/pos/OpenNlpPosRecommender.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/AnnotationSuggestion.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/ExtendedId.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Recommender.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/RelationSuggestion.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SpanSuggestion.java
- inception/inception-recommendation-api/src/test/java/de/tudarmstadt/ukp/inception/recommendation/api/model/PredictionsTest.java
- inception/inception-recommendation-api/src/test/java/de/tudarmstadt/ukp/inception/recommendation/api/model/RelationSuggestionTest.java
- inception/inception-recommendation-api/src/test/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SpanSuggestionTest.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/LogDialog.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplTest.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationInfoPanel.java
- inception/pom.xml
- Defer setting annotation suggestion IDs until they are added to the predictions object
- If an extracted suggestion matches an existing one, inherit the existing suggestion (and its ID) instead
- Inherit the ID counter across prediction generations
- Upgrade to Java 17 (so we can use records)
* Use the recommenders
> #4155 - Better annotation suggestion IDs

- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasHolder.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasStorageServiceImpl.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/PooledCasHolderFactory.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/config/CasStorageCacheProperties.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/config/CasStorageCachePropertiesImpl.java
- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/driver/filesystem/FileSystemCasStorageDriver.java
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_cas-storage.adoc
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/exporters/SourceDocumentExporter.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- Do not use the exclusive-access pool when exporting annotations
- Log eviction of CASes from the shared-access cache and exclusive-access pool at trace level
- Actually enable periodic cleaning up of the shared-access pool using the system scheduler
- Introduce a new setting "min-idle-cas-time"
- Improve readability of the validateObject function in PooledCasHolderFactory
- Improve logging messages
> #4173 - Using too much memory when exporting large project

- inception/inception-bootstrap/src/main/ts/bootstrap/shim-kendo.scss
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/component/DocumentNamePanel.java
- inception/inception-ui-annotation/src/main/resources/META-INF/asciidoc/user-guide/annotation_navigation.adoc
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.properties
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicAnnotatorWorkflowActionBarItemGroup.html
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicAnnotatorWorkflowActionBarItemGroup.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicAnnotatorWorkflowActionBarItemGroup.properties
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.html
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.java
- Add shortcut for toggling the document state
- Fix display of "read-only" marker in document name panel on curation page
* Try it on the curation and annotation pages
> #4167 - Keyboard shortcut for the padlock

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicy.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicy.yaml
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/SafetyNetDocumentPolicy.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- inception/inception-external-editor/src/test/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicyTest.java
- inception/inception-external-editor/src/test/java/de/tudarmstadt/ukp/inception/externaleditor/policy/SafetyNetDocumentPolicyTest.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ElementAction.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionBuilder.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandlerTest.java
- Introduce a SKIP option for elements that skips the element but passes text node children
- Allow certain HTML4 tags like font or center or such to pass
- Read default HTML policy from monitored resource to simplify development
* Try out different HTML files
> #4184 - Improve handling of XML and HTML files

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_general.adoc
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/ErrorPage.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/config/CoreUiAutoConfiguration.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/config/ErrorPageProperties.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/inception/ui/core/config/ErrorPagePropertiesImpl.java
- Add new configuration option to disable details on error page
* Enable developer mode `-Dinception.dev=true`
* Enable the setting `-Dui.error-page.hide-details=true`
* Visit `.../whoops/test`
> #4188 - Option to reduce information on error page

- inception/inception-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-dependencies/pom.xml
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- inception/pom.xml
- inception/update-package-lock.sh
- pom.xml
- mockito 5.4.0 -> 5.5.0
- spring 5.3.29 -> 5.3.30
- spring-boot 2.7.14 -> 2.7.15
- spring-data 2.7.14 -> 2.7.15
- spring-security 5.8.5 -> 5.8.7
- slf4j 2.0.7 -> 2.0.9
- sentry 6.27.0 -> 6.29.0
- tomcat 9.0.78 -> 9.0.80
- mariadb-driver 2.7.9 -> 2.7.10
- wicket 9.14.0 -> 9.15.0
- wicket-jquery-selectors 3.0.5 -> 3.0.6
- elasticsearch 7.17.12 -> 7.17.13
- opensearch 1.3.11 -> 1.3.12
- rdf4j 4.3.5 -> 4.3.6
- okio 3.4.0 -> 3.5.0
- jquery 3.7.0 -> 3.7.1
- checkstyle 10.12.1 -> 10.12.3
- nimbus-jose-jwt 9.31 -> 9.35
- slf4j-reload4j -> 2.0.9
- openjson 1.0.12 -> 1.0.13
- byte-buddy 1.14.5 -> 1.14.8
- json-schema-validator 1.0.83 -> 1.0.87
- oauth2-oidc-sdk 9.43.1 -> 9.43.3
- commons-compress 1.23.0 -> 1.24.0
- caffeine 3.1.7 -> 3.1.8
- ant 1.10.13 -> 1.10.14
- picocli …
> #4192 - Upgrade dependencies

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-api-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/feature/FeatureUtil.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureSupport.java
- Adjust link features and multi-value features to not store empty arrays
* Try using link features and multi-value features and look for NullPointerExceptions
> #4196 - Save memory by not creating empty arrays in CAS

- Jenkinsfile
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/span/SpanDiffAdapter.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsStartAndEndWithinSentencesCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/UnreachableAnnotationsCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorAutoConfiguration.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/UpgradeCasRepair.java
- inception/inception-diag/src/main/resources/META-INF/asciidoc/user-guide/casdoctor.adoc
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/model/CasToBioC.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/xml/Cas2BioCSaxEvents.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/format/VisualPdfReader.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Replace calls to SelectFS with calls to CASUtil which does not create temporary annotations
- Added new CAS Doctor check for unreachable feature structures
- Updated UpgradeCasRepair to report garbarge-collected feature structures
- Updated description of UpgradeCasRepair
* Run CAS Doctor the clean up all unreachable annotations in a project
* Perform some annotations etc
* Run CAS Doctor check if there are any unreachable annotations in the project
> #4158 - Exception when annotating something after a longer pause

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/actionbar/RecommenderActionBarExtension.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/actionbar/RecommenderActionBarPanel.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/actionbar/RecommenderActionBarPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/actionbar/RecommenderActionBarPanel.properties
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RRecommenderLogMessage.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/footer/RecommendationEventWebsocketControllerImpl.java
- inception/inception-recommendation/src/main/ts/src/RecommendationEventFooterPanel.svelte
- Add a action bar button to refresh the document in case there are recommenders
- Wiggle the button a bit if there are pending suggestions
* Create a project with recommenders
* Create some annotations
* Note that the button starts wiggling after a "new recommendations" flash message
* Note that button stops wiggling when it is clicked on when otherwise an action is made that refreshes the document
> #4205 - Ability to refresh document to load pending suggestions

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSpecificSettingsPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java
- Move default setting of read-only flag to a different location
- For local KBs, temporarily make the KB writable while updating the base properties
> #4212 - Unable to mark local KB as read-only

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- Set a default fuzzy query length of 3 for local KB queries
- Enable limiting the results returned internally by local KBs
* Import a very large KB
* Try auto-completion
> #4209 - Improve query speed for large KBs when using RDF4J Lucene FTS

- inception/inception-bootstrap/src/main/ts/bootstrap/inception-actionbar.scss
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/closesession/CloseSessionActionBarExtension.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/closesession/CloseSessionPanel.html
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/closesession/CloseSessionPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/config/AnnotationUIAutoConfiguration.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/LoginPage.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/logout/LogoutPanel.java
- Added logout button to the annotation action bar if the menu bar is not accessible
- If menubar is accessible, the logout button should always be there
- If logging out while auto-login is enabled, make sure to pass the skip-auto-login parameter to the login page
- Allow items in the annotation action bar to grow which allows the logout button to be positioned at the far right
- Improve scaling of the annotation action bar when window is resized
* Try annotation page with menu bar enabled / disabled
* Try logout button on the annotation page
> #4226 - Display logout button on annotation page if dashboard access is disabled

- inception/inception-docker/src/main/docker/Dockerfile
- inception/inception-docker/src/main/docker/launch.sh
- Added ENV variables to define the APP_UID and APP_GID
- Added a wrapper boot script which ensures that all relevant files belong to these UID/GID
* Build INCEpTION (`mvn clean install -DskipTests`)
* Build the Docker image in `inception/inception-docker` using `mvn -Pdocker clean docker:build`
* Run the image using e.g. `docker run -e APP_UID=1234 -e APP_GID=4321 -it ghcr.io/inception-project/inception-snapshots:latest`
* Check that the UID/GID used by the INCEpTION process and files are as specified
> #4215 - Ability to specify GID and UID for the user used inside the Docker image

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- inception/inception-brat-editor/src/main/ts/src/util/Util.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- inception/inception-diam-editor/src/main/ts/src/SpanText.svelte
- inception/inception-js-api/src/main/ts/src/model/Annotation.ts
- inception/inception-js-api/src/main/ts/src/model/Relation.ts
- inception/inception-js-api/src/main/ts/src/model/Span.ts
- inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactRelation.ts
- inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactSpan.ts
- inception/inception-js-api/src/main/ts/src/widget/AnnotationDetailPopOver.svelte
- Move the text from the HTML tooltip into the popover
- Show the text in all popovers, not only on the left annotation sidebar
- If the text is shown is controlled by the "show in hover" layer setting
- Extend client-side annotations with a reference to their respective document
* Try the right annotation sidebar in both modes and see if the popover replaces the HTML tooltip well
**Screenshots**
> #4223 - Covered text should show in popover

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderer.java
- inception/inception-api-annotation/src/test/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRendererTest.java
- Improve the yield calculation speed
* Try showing the yield of a relation on the UD test data set of the portugues Bosque dataset
> #4251 - Improve speed of yield calculation

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByPositionList.svelte
- inception/inception-diam-editor/src/main/ts/src/DiamAnnotationBrowser.svelte
- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- Limiting annotations for the sidebar to 25k - not sure if this still is too many
* Load the test set from the UD bosque dataset and try viewing the yield of a relation
> #4252 - Limit number of annotations displayed in annotation sidebar to avoid crash

- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- inception/inception-ui-dashboard-activity/pom.xml
- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashletExtension.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/DocumentHintDashletExtension.java
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/projectlist/ProjectsOverviewPage.html
- Enable preference saving only after the editor has properly initialized
- Changes to preferences should only trigger annotation reloads once the editor has fully initialized
- Fix small layout issue on ProjectsOverviewPage
- Fix dashlet order on ProjectsOverviewPage .
* Try using the Apache Annotator editor
> #4256 - Avoid saving preferences immediately on load

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPageMenuItem.java
- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashletControllerImpl.java
- Add target user to the link URL so we can open the document as the requested user
> #4259 - Opening a document viewing a specific annotator from the activities list does not work

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- Fix workaround to UIMA leaking temporary annotations using the same begin offset as in the original non-workaround code
* Import a document with two sentences
* Create an annotation covering both sentences
* Configure the brat-by-sentence viewer to show only one sentence
* Switch to the second page
> #4263 - Spans starting before the current viewport are not rendered as partial spans

- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionApplicationContainerConfiguration.java
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/startup/StartupNoticeValve.java
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/settings_server.adoc
- Added option to disable startup notice
- Added content-type to startup-notice page
* Disable the startup screen using the respective option
* Check the content type reported to the browser on the startup page
> #4279 - Ability to disable startup notice

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xml/XmlDocumentViewControllerImpl.java
- Detect multi-line-breaks and inject p-tags accordingly
> #4294 - Infer paragraph boundaries when displaying plain text files in HTML-based editors

- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommender.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraits.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraitsEditor.html
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraitsEditor.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraitsEditor.properties
- Added checkbox in external recommender settings that can be used to disable certificate checks
* Set up an external recommender and point it to `https://expired.badssl.com/`
* With certificate checks enabled, it should fail with a PKIX exception
* Without certificate checks it should fail with a 404
> #4289 - Ability to skip SSL certificate validation on external recommenders

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- inception/inception-io-html/pom.xml
- inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/HtmlFormatSupport.java
- inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/config/HtmlSupportAutoConfiguration.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- The HtmlFormatSupport now returns the default HTML content policy
- When logging masked element, also log the name of the respective policy
- Do not pass the body element through the sanitizer - it should always pass
* See issue
> #4302 - Files imported as HTML do not show properly in HTML-based editor

- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.ts
- inception/inception-js-api/src/main/ts/src/util/ViewportTracker.ts
- Allow providing a CSS selector for elements to be ignored to the viewport tracker
- Ignore the SVG element injected by RecogitoJS
* Try opening a large document using the RecogitoJS editor and check that partial loading of the visible annotations works
> #4310 - Viewport tracking does not work well in RecogitoJS editor

- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception/inception-external-editor/src/main/resources/META-INF/asciidoc/developer-guide/external-editor.adoc
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/CustomXmlFormatLoader.java
- inception/inception-io-xml/src/main/resources/META-INF/asciidoc/user-guide/formats-xml-custom.adoc
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/AttributeAction.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- Added documentation
- Turned it into an experimental feature that is disabled by default
> #4308 - Support for custom XML formats

- inception/inception-imls-external/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation_external.adoc
- inception/inception-imls-external/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderSslTest.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookService.java
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookServiceTest.java
- Added tests
- Disabling certificate checks for WebHooks also disables host name checking
- Can currently not disable host name checking when using the Java 11 HTTP client
* Try disabling certificate checking and then connecting to different bad endpoints as listed on https://badssl.com
> #4289 -  Ability to skip SSL certificate validation on external recommenders

- inception/inception-dependencies/pom.xml
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController_Authentication_Jwt_Test.java
- pom.xml
- nimbus-jose-jwt 9.36 -> 9.37.1
- commons-dbcp2 2.10.0 -> 2.11.0
- byte-buddy 1.14.9 -> 1.14.10
- commons-io 2.14.0 -> 2.15.0
- commons-text 1.10.0 -> 1.11.0
- commons-lang3 3.13.0 -> 3.14.0
- commons-compress 1.24.0 -> 1.25.0
- mockito 5.5.0 -> 5.7.0
- uimafit 3.4.0 -> 3.5.0
- spring 5.3.30 -> 5.3.31
- spring-boot 2.7.17 -> 2.7.18
- spring-data 2.7.17 -> 2.7.18
- swagger 2.2.16 -> 2.2.19
- jjwt 0.11.5 -> 0.12.3
- log4j 2.20.0 -> 2.22.0
- sentry 6.30.0 -> 6.34.0
- tomcat 9.0.82 -> 9.0.83
- elasticsearch 7.17.14 -> 7.17.15
- jackson 2.15.3 -> 2.16.0
- okhttp 4.11.0 -> 4.12.0
- okio 3.5.0 -> 3.6.0
> #4150 - Upgrade dependencies

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_docker.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_kubernetes.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/scripts/kubernetes.yml
- inception/inception-docker/src/main/docker/Dockerfile
- inception/inception-docker/src/main/docker/launch.sh
- Adjust launch script to not try to fix file ownership and drop privileges when container is already not running as root
- Added additional VOLUME declarations in Dockerfile for tmp and log folders so the container can run with a read-only root filesystem (hopefully)
- Added a very very very very basic documentation on how one might consider using Kubernetes
* Try running in Kubernetes
* Try running normally using `docker run`
> #4324 - Allow configuring UID GID etc in Kubernetes

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicy.yaml
- inception/inception-external-editor/src/test/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicyTest.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ExternalPolicyCollection.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionBuilder.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionIOUtils.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- Add "defaultNamespace" setting to policy to add a default namespace to all elements defined in the policy (also allowing there non-NS versions)
- Fix cases where an element or attributeconsists only of a prefix and no local part (we filter those out)
> #4328 - HTML files are not rendered if they use the HTML namespace

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicy.yaml
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/CasXmlHandler.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/AttributePolicyBuilder.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ElementAction.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ElementPolicy.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/ExternalPolicyCollection.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionBuilder.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionIOUtils.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandlerTest.java
- Allow pruning a subtree
- Allow configuring whether the default namespace also matches elements without namespace
- Allow configuring whether the default namespace is applied to attributes as well
> #4340 - Allow pruning elements in XML policy

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollection.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionBuilder.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionIOUtils.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/PolicyCollectionIOUtilsTest.java
- If the format defines a default namespace in its policy, then we inject it
- Fix bug that default namespace is not considerd for global attribute rules
> #4344 - Allow format to inject default namespace if document does not specify one

- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-documents/src/test/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImplConcurrencyTest.java
- inception/inception-export-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/DocumentImportExportService.java
- inception/inception-export/src/main/java/de/tudarmstadt/ukp/inception/export/DocumentImportExportServiceImpl.java
- inception/inception-schema/src/test/java/de/tudarmstadt/ukp/inception/documents/service/DocumentServiceImplDatabaseTest.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/casdoctor/ProjectCasDoctorPanel.java
- inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImpl2Test.java
- inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImplTest.java
- inception/inception-workload-matrix/src/test/java/de/tudarmstadt/ukp/inception/workload/matrix/MatrixWorkloadExtensionImplTest.java
- Disable implicit CAS doctor check when creating the INITIAL_CAS since either CAS Doctor on the panel is run immediately after or the usual option CAS Doctor check is run on document open
> #4347 - CAS doctor fails to generate a proper report on projects not containing INITIAL_CASes

- inception/inception-io-tei/pom.xml
- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/TeiXmlDocumentCssReference.java
- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/TeiXmlDocumentFormatSupport.java
- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/TeiXmlDocumentPolicy.yaml
- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/TeiXmlDocumentReader.java
- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/config/TeiFormatsAutoConfiguration.java
- inception/inception-io-tei/src/main/resources/META-INF/asciidoc/user-guide/formats-tei.adoc
- inception/inception-io-tei/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- inception/inception-io-tei/src/main/ts/.eslintrc.yml
- inception/inception-io-tei/src/main/ts/build.mjs
- inception/inception-io-tei/src/main/ts/src/TeiXmlDocument.scss
- inception/inception-io-tei/src/main/ts/src/layout.scss
- inception/inception-io-tei/src/main/ts/src/notes.scss
- inception/inception-io-tei/src/main/ts/src/tables.scss
- inception/inception-io-tei/src/main/ts/src/typography.scss
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package.json
- inception/update-package-lock.sh
- Added new experimental TEI support and styling based on the DraCor example that was originally done to showcase the capabilities of the Apache Annotator Editor plugin
* Try importing a TEI file and viewing / annotating it in the annotation editor
> #4334 - New take on TEI support based on generic XML support

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/link/LinkFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/misc/ReorderableTagAutoCompleteField.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainLayerSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationCrossSentenceBehavior.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationLayerSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationOverlapBehavior.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanLayerSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationRelationRenderer.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationTypeRenderer.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/SuggestionExtraction.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/WebAnnoConst.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/WicketUtil.java
- Deprecate layer type constants in WebAnnoConst and prefer type constants in layer supportts
> #4360 - Clean up code

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-ui-kb/pom.xml
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseWrapper.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.properties
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/local/LocalRepositorySettingsPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/local/LocalRepositorySettingsPanel.java
- Display repository size and index size
- Also display repository size but make it approximate if the repository size is quite large
> #4369 - Display size of knowledge bases

- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/PipedStreamResource.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.properties
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/local/LocalRepositorySettingsPanel.java
- Download immediately without first buffering into a temporary file
- GZip exported KBs
- Add Turtle to list of supported formats
- Removed unused property
* Download a KB
* Import it back again
> #4370 - Download knowledge bases in compressed form

- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandlerTest.java
- Namespace declarations should always pass
> #4375 - SanitizingContentHandler blocks namespace mappings

- inception/inception-api-annotation/src/main/resources/META-INF/asciidoc/admin-guide/settings_segmentation.adoc
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- Inject URL into live objects as part of setting up a connection
- Clear query cache when changing the KB configuration
- Unrelated documentation fix
> #916 - Changing URL of remote KB requires server restart

- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashletControllerImpl.java
- Filter out events where the annotator is null - these are not relevant for the recent activity sidebar
> #4386 - User "null" sometimes shows up in recent activity

- inception/inception-diam-compactv2/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compactv2/CompactAnnotationAttributes.java
- inception/inception-diam-compactv2/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compactv2/CompactSerializerV2Impl.java
- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderFactory.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraits.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraitsEditor.html
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraitsEditor.java
- inception/inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/v1/ExternalRecommenderTraitsEditor.properties
- inception/inception-js-api/src/main/ts/src/model/Annotation.ts
- inception/inception-js-api/src/main/ts/src/model/Relation.ts
- inception/inception-js-api/src/main/ts/src/model/Span.ts
- inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactAnnotationAttributes.ts
- inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactRelation.ts
- inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactSpan.ts
- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VObject.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SuggestionGroup.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngineFactory.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationRelationRenderer.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationSpanRenderer.java
- Added flag to VDoc annotations to indicate if a score should be hidden
- Added a flag to the external recommender that indicates if it is a ranker - for rankers, the score should be hidden
- Hide the score in the annotation sidebar if the hide flag is set
* Configure an external recommender
* Set the "ranker" flag on it
* Check the annotation sidebar
> #4383 - Hide negative scores in annotation sidebar but still sort by it

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- Only display such a message if the label of the suggestion is actually not empty and still not in the tagset
> #4406 - Useless "not in tagset" message on suggestions without a label

- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/Predictions.java
- inception/inception-recommendation-api/src/test/java/de/tudarmstadt/ukp/inception/recommendation/api/model/PredictionsTest.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplTest.java
- Fix aging
- Pass reconciliation result info into the predictions object
- Two methods, one for inheriting suggestions, the other for putting new ones
- Display the number of documents containing new suggestions in the flash message
> #4414 - Number of new suggestions not displayed correctly

- inception/inception-constraints/src/test/java/de/tudarmstadt/ukp/clarin/webanno/constraints/ComplexTypeTest.java
- inception/inception-imls-ollama/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/response/MentionsSampleTest.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommender.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderFactory.java
- inception/inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderTraits.java
- inception/inception-imls-opennlp/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/ner/OpenNlpNerRecommenderTest.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/RecommendationTask_ImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/span/SpanSuggestionExtractionTest.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/AnnotationBuilder.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/SegmentationUtils.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/WebAnnoCasUtil.java
* Siding-window training for OpenNLP NER when cross-sentence annotations are allowed
* Switch layer to cross-sentence mode and try recommender
> #4399 - Allow open nlp multi token sequence classifier to work for cross sentence layers

- .github/workflows/maven.yml
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor_ImplBase.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureTraitsEditor.html
- inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/knowledge_base.adoc
- inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/projects_knowledge-base.adoc
- Improve translation of query terms into suitable regular expression
- Log slow queries at debug level
- Better generation of query terms from mention in the concepf feature editor
> #4428 - Slow knowledge-base lookups on relation layers

- inception/inception-pdf-editor2/src/main/ts/src/PdfAnnotationEditor.css
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/render/renderSpan.ts
- Remove the scale factor from the merge margin calculation to fix the issue
- Improve border and selection marker widths as scale factor increases (i.e. do not scale them along linarly)
- Make the border and selection marker a bit more transparent so text is better readable
* See issue description / play around with different scale factors in PDF editor
> #4430 -Highlight rows may get merged in PDF editor at high scale factors

- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/trait/DynamicWorkloadTraits.java
- Changed the default number of annotators in dynamic workload to 3
* Create new project with dynamic workload and check number of annotators on workload management page
> #4436 - Change default dynamic workload annotator number to uneven

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/yaml/KnowledgeBaseInfo.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/yaml/KnowledgeBaseProfile.java
- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseProfileDeserializationTest.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseInfoPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseInfoPanel.java
- Added HPO (and IAO) ontology profiles
- Improve information displayed in the KB info panel
* Create a new local KB
* Select the HPO profile
* Check out named entity linking on the annotation page and/or the the KB page
> #4463 - Add human phenotype ontology knowledge base profile

- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/util/TestFixtures.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/IriConstants.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/SchemaProfile.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/ExportedKnowledgeBase.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBHandle.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/graph/KBObject.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/model/KnowledgeBase.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryOptionalElements.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/yaml/KnowledgeBaseMapping.java
- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/model/db-changelog.xml
- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseExporterTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseProfileDeserializationTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnwoledgeBaseSchemaProfileTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderGenericTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/util/TestFixtures.java
- inception/inception-kb/src/test/resources/kb_test_profiles.yaml
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/KBHandleTemplate.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseIriPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseIriPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.properties
- Add a new configurable IRI for a property that - when present - marks a concept, property or instance as deprecated
* Import e.g. the HPO ontology using the new HPO local profile
* On the knowledge-base page search for "obsolete" - that should mostly (only) return items that are deprecated and they should be marked as such
> #4379 - Suppress or mark concepts in the search that are marked as owl:deprecated

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/util/OverlapIterator.java
- If a is already null, no need to try and comparing against its end position
> #4476 - Exception while rendering recommendations

- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.scss
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- inception/inception-js-api/src/main/ts/src/style/InceptionEditorColors.scss
- Add visual cues to annotation sidebar and Apache Annotator editor
- Change Apache Annotator editor such that when inline labels are disabled, the position of words in the text is no longer changed
- Made the resize handles slightly transparent
* Enable "required" on some feature
* Create annotations where the feature is not set 
* Observe the annotation sidebar 
* Try this also in the Apache Annotator(HTML) editor
> #4480 - Show validation problems in annotation sidebar and Apache Annotator editor

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide.adoc
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/processor/BulkProcessingPage.java
- inception/inception-recommendation/src/main/resources/META-INF/asciidoc/admin-guide/settings_bulk_processing.adoc
- Disable the bulk-processing feature by default
- Add documentation of the feature switch
* Enable the feature switch and check if the feature appears in the project dashboard menu
> #4434 - Ability to apply a recommender to all documents in a project

- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventLoggingListener.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/config/EventLoggingProperties.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/config/EventLoggingPropertiesImpl.java
- inception/inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/EventLoggingListenerTest.java
- inception/inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/config/EventLoggingPropertiesImplTest.java
* Deprecated exclude events.
* Introduced include and exclude patterns.
* Including everything (.*) by default, and excluding a predefined set of events by default.
* Refactored EventLoggingListener to use the new include and exclude patterns.
* Added tests.
* N/A
> #4377 - Configure include and exclude patterns for logged events

- inception/inception-dependencies/pom.xml
- inception/inception-kb/pom.xml
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/IriConstants.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/BlazegraphFtsQuery.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/yaml/KnowledgeBaseMapping.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/yaml/KnowledgeBaseProfile.java
- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/yaml/knowledgebase-profiles.yaml
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/BlazegraphRepositoryTest.java
- pom.xml
- Add Blazegraph FTS mode
- Added unit tests (running on testcontainers)
* Try on https://ubergraph.apps.renci.org/sparql
> #4513 - Support full text search in knowledge bases running on Blazegraph

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningServiceImpl.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-annotation-storage/src/test/resources/log4j2-test.xml
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/TypeAdapter_ImplBase.java
- inception/inception-concept-linking/src/test/resources/log4j2-test.xml
- inception/inception-curation-legacy/src/test/resources/log4j2-test.xml
- inception/inception-documents/src/test/resources/log4j2-test.xml
- inception/inception-external-editor/src/test/resources/log4j2-test.xml
- inception/inception-external-search-solr/src/test/resources/log4j2-test.xml
- inception/inception-imls-ollama/src/test/resources/log4j2-test.xml
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
- inception/inception-imls-stringmatch/src/test/resources/log4j2-test.xml
- inception/inception-project-export/src/test/resources/log4j2-test.xml
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/SuggestionSupport_ImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/relation/RelationSuggestionSupport.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/span/SpanSuggestionSupport.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/span/MultiValueFeatureSuggestionVisibilityCalculationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/span/SpanSuggestionMultiValueFeatureSuggestionVisibilityCalculationTest.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/span/SpanSuggestionVisibilityCalculationTest.java
- inception/inception-recommendation/src/test/resources/log4j2-test.xml
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/AnnotationSchemaService.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/adapter/TypeAdapter.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/FeatureSupport.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- inception/inception-ui-dashboard/pom.xml
- inception/inception-ui-dashboard/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/dashlet/LayerHintDashlet.java
- inception/inception-ui-kb/pom.xml
- Recommenders: When a recommendation is on a multi-value feature, do not hide overlapping suggestions (same as when stacking is enabled) - unless label matches existing annotation
* Create span layer with multi-value string feature
* Create string matching recommender for that feature
* Annotate a word in a text with two labels on the same annotation
* Check suggestions projected onto other instances of the same word
> #2879 - Improve multi-value features

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- Fix issue by setting the knowledge base on KB items (concepts, properties, instances) when creating them in a KB.
> #4519 - Trying to add a subclass on the knowledge base page creates an error

- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/BioCComponent.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/BioCXmlDocumentFormatSupport.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/BioCXmlDocumentReader.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/BioCXmlDocumentWriter.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/model/BioCObject.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/model/CasToBioC.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/xml/BioC2XmlCas.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/xml/BioCXmlUtils.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/xml/Cas2BioCSaxEvents.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/xml/DocumentWrappingXmlInputReader.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/xml/SplittingContentHandler.java
- inception/inception-io-bioc/src/main/resources/META-INF/asciidoc/user-guide/formats-bioc.adoc
- inception/inception-io-bioc/src/test/java/de/tudarmstadt/ukp/inception/io/bioc/BioCReaderWriterTest.java
- inception/inception-io-bioc/src/test/java/de/tudarmstadt/ukp/inception/io/bioc/BioCXmlDocumentReaderTest.java
- inception/inception-io-bioc/src/test/java/de/tudarmstadt/ukp/inception/io/bioc/BioCXmlDocumentReaderWriterTest.java
- inception/inception-io-bioc/src/test/resources/bioc-suite/annotation-with-single-multi-valued-feature-typed/data.xml
- inception/inception-io-bioc/src/test/resources/bioc-suite/annotation-with-single-multi-valued-feature-typed/reference.xml
- inception/inception-ui-tagsets/pom.xml
- inception/inception-ui-tagsets/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/tagsets/TagSetImportPanel.java
- Added support for loading and saving multi-value string features
* Create project with a multi-value string annotation feature (or multi-value concept feature)
* Annotate some text with multiple feature values
* Export the document to BioC to check if the multiple values are exported
* Import the document as BioC to see if the values properly come back
> #4517 - Multi-value features are not included in BioC output

- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/BioCReaderImplBase.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/BioCWriter.java
- inception/inception-io-bioc/src/test/java/de/tudarmstadt/ukp/inception/io/bioc/BioCReaderTest.java
- inception/inception-io-bioc/src/test/java/de/tudarmstadt/ukp/inception/io/bioc/BioCWriterTest.java
- inception/inception-io-bioc/src/test/resources/bioc/example-with-incomplete-metadata.xml
- Make sure that key, date and source are generated if they are not present in the CAS when writing BioC
- Make reading BioC more robust so that it does not fail if key, date or source are missing
* Export BioC from INCEpTION
* Import it back again
> #4533 - BioC exported from INCEpTION cannot be imported again due to missing mandatory metadata

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- When a CAS is read-only, do not upgrade it
> #4538 - Lazy details and selecting annotations my break after opening a read-only document and not performing actions for a short time

- inception/inception-dependencies/pom.xml
- pom.xml
- nimbus-jose-jwt 9.37.1 -> 9.37.3
- jinjava 2.7.1 -> 2.7.2
- fastutil 8.5.12 -> 8.2.13
- byte-buddy 1.14.10 -> 1.14.12
- json-schema-validator 1.0.87 -> 1.0.88
- commons-io 2.15.0 -> 2.15.1
- commons-codec 1.16.0 -> 1.16.1
- junit 5.10.1 -> 5.10.2
- junit-platform 1.10.1 -> 1.10.2
- spring 5.3.31 -> 5.3.32
- spring-security 5.8.8 -> 5.8.10
- swagger 2.2.19 -> 2.2.20
- jjwt 0.12.3 -> 1.12.5
- slf4j 2.0.9 -> 2.0.12
- log4j 2.22.0 -> 2.22.1
- tomcat 9.0.83 -> 9.0.86
- mariadb-driver 2.7.10 -> 2.7.12
- postgres 42.6.0 -> 42.6.1
- lucene 8.11.2 -> 8.11.3
- solr 8.11.2 -> 8.11.3
- elasticsearch 7.17.15 -> 7.17.18
- opensearch 1.3.13 -> 1.3.14
- rdf4j 4.3.8 -> 4.3.9
- jackson 2.16.0 -> 2.16.1 …
> #4541 - Upgrade dependencies

- inception/inception-brat-editor/src/main/ts/src/brat_curation.ts
- Add the new annotation detail popover to the lower curation panels
> #4552 - No details shown when hovering over annotations in lower part of the curation page

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- inception/inception-api-editor/src/main/java/de/tudarmstadt/ukp/inception/editor/AnnotationEditorExtension.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupService.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupServiceImpl.java
- inception/inception-js-api/src/main/ts/src/widget/AnnotationDetailPopOver.svelte
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/rendering/Renderer.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationEditorExtension.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/config/CurationSidebarAutoConfiguration.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRenderer.java
- Display non-curatable featues that are show-in-hover in curation suggestions
- Improve layout of the annotation detail popover
* Try curating using the annotation sidebar
* Configure a string feature `comment` that is non-curatable, not showing in the label and has show-on-hover enabled.
> #4554 - Allow displaying comments from annotators on hover when curating using curation sidebar on the annotation page

- .github/workflows/maven.yml
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainLayerSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationLayerSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanLayerSupport.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerSupport.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/AnnotationSchemaService.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/layer/LayerSupport.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/layer/LayerSupport_ImplBase.java
- inception/inception-schema/pom.xml
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- inception/inception-schema/src/test/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImplTest.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/WebAnnoConst.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/SubclassCreationDialog.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
- Factor layer verification code out of the UI layer into the backend
* Create features with valid and invalid names
> Issue #4558: Better verification for feature names

- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- Remove "optional" to speed up query on AllegroGraph backends
> #4570 - Inefficient Knowledge Base SPARQL query for labels

- inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/util/TestFixtures.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/IriConstants.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/AllegroGraphFtsQuery.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterAllegroGraph.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterFuseki.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterRdf4J.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterStardog.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLVariables.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/FullTextIndexUpgradeTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/AllegroGraphRepositoryTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/Rdf4JRepositoryTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/util/TestFixtures.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/lambda/LambdaChoiceRenderer.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSettingsPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSpecificSettingsPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/GeneralSettingsPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseIriPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.properties
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/QuerySettingsPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java
- inception/inception-ui-kb/src/main/resources/META-INF/asciidoc/user-guide/projects_knowledge-base.adoc
- Added FTS support for AllegroGraph
- Added test suite for AllegroGraph
- Clean up a bit
1. Set up a SPARQL KB with endpoint `https://query.wikibus.org/query` (IRI schema RDF)
2. Configure the AllegroGraph FTS support
3. Set up a layer property to use that KB (for example instances-only)
4. Try finding an instance in annotated (type "Yutong")
> #4572 - Support full text search in knowledge bases running on AllegroGraph

- inception/inception-app-webapp/pom.xml
- inception/inception-bom/pom.xml
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide.adoc
- inception/inception-doc/src/main/resources/META-INF/asciidoc/user-guide/formats.adoc
- inception/inception-io-rdf/LICENSE.txt
- inception/inception-io-rdf/pom.xml
- inception/inception-io-rdf/src/main/java/de/tudarmstadt/ukp/inception/io/rdf/RdfReader.java
- inception/inception-io-rdf/src/main/java/de/tudarmstadt/ukp/inception/io/rdf/RdfWriter.java
- inception/inception-io-rdf/src/main/java/de/tudarmstadt/ukp/inception/io/rdf/UimaRdfCasFormatSupport.java
- inception/inception-io-rdf/src/main/java/de/tudarmstadt/ukp/inception/io/rdf/config/RdfFormatAutoConfiguration.java
- inception/inception-io-rdf/src/main/java/de/tudarmstadt/ukp/inception/io/rdf/internal/BasicIRI.java
- inception/inception-io-rdf/src/main/java/de/tudarmstadt/ukp/inception/io/rdf/internal/Rdf2Uima.java
- inception/inception-io-rdf/src/main/java/de/tudarmstadt/ukp/inception/io/rdf/internal/RdfCas.java
- inception/inception-io-rdf/src/main/java/de/tudarmstadt/ukp/inception/io/rdf/internal/Uima2Rdf.java
- inception/inception-io-rdf/src/main/resources/META-INF/asciidoc/user-guide/formats-rdfcas.adoc
- inception/inception-io-rdf/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- inception/inception-io-rdf/src/test/java/de/tudarmstadt/ukp/inception/io/rdf/RdfWriterTest.java
- inception/inception-io-rdf/src/test/resources/conll/2006/README.txt
- inception/inception-io-rdf/src/test/resources/conll/2006/fi-orig.conll
- inception/inception-io-rdf/src/test/resources/conll/2006/fi-ref.ttl
- inception/inception-io-rdf/src/test/resources/log4j2-test.xml
- inception/inception-io-rdf/src/test/resources/ttl/fi-orig.ttl
- inception/inception-io-rdf/src/test/resources/ttl/fi-ref.conll
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/LayerExporter.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- inception/pom.xml
- Ported RDF reader/writer from DKPro Core
- Added PARAM_IRI_FEATURES so we can represent KB concepts are proper IRIs in the export instead of strings
- Added test using PARAM_IRI_FEATURES
* Export a document as RDF
* Check if the exported TTL looks good
* Import it back again
> #4567 - Add support for a generic CAS RDF export format

- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
- Skip listing annottions for layers that do not exist in the CAS yet
> #4578 - Error in document metadata sidebar when document has not yet been upgraded to new layers

- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/render/renderSpan.ts
- Adjustment has to be made not only if first page is larger but also if first page is smaller than subsequent pages
> #4587 - Annotations are misaligned when PDF pages vary in dimensions

- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/AgreementSummary.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/PairwiseCodingAgreementTable.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/unitizing/PairwiseUnitizingAgreementTable.java
- Fix aggregation logic for "empty" and "all null" flags
- When calculating the macro average agreement, skip results for which agreement calculation was not possible (NaN)
- Display in the tooltip for how many documents agreement calculation was attempted and how many of those actually produced usable results
* Try running agreement on your projects and check if the results appear to be sensible
> #4590 - Agreement report shows only "no position"

- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_ssl_apache.adoc
Closes #4595. Changes only documentation.
* Remove the `ProxyPass /inception/ws ws://localhost:8080/inception/ws` directive in favor of adding `upgrade=websocket` to the general `ProxyPass` directive (this allows us to remove the [deprecated `mod_proxy_wstunnel`](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) and corresponds to the [recommended alternative](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#wsupgrade))
* Add the tested Apache version
* Remove the `<Proxy>` section because it wasn't needed in my configuration and [seems to only be needed for ForwardProxies](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#examples)
* Use `ProxyPassReverse` with the same parameters as `ProxyPass` because I think that's how it is used (also corresponds to the [basic …
> #4595 - Update apache reverse proxy docs to make Web Sockets work

- inception/inception-preferences/src/main/java/de/tudarmstadt/ukp/inception/preferences/PreferencesServiceImpl.java
- inception/inception-preferences/src/main/java/de/tudarmstadt/ukp/inception/preferences/exporter/DefaultProjectPreferencesExporter.java
- inception/inception-preferences/src/main/java/de/tudarmstadt/ukp/inception/preferences/exporter/UserProjectPreferencesExporter.java
- inception/inception-preferences/src/main/resources/de/tudarmstadt/ukp/inception/preferences/model/db-changelog.xml
- Add non-null constraints to user and project columns in the preferences tables
- Add null-checks to the Preferences service to be able to catch nulls early
> #4602 - Project-specific user preferences may be saved without a user

- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/core/src/render/renderSpan.ts
- Improve the code to check if the pages are not properly aligned and then compensate accordingly
* See the PDF attached to the issue linked in the issue
> #4610 - Annotations are misaligned when PDF pages vary in dimensions

- inception/inception-active-learning/pom.xml
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/config/ActiveLearningAutoConfiguration.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.html
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.properties
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebarFactory.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/RecommenderGeneralSettings.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/config/RecommenderServiceAutoConfiguration.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/event/RecommendersResumedEvent.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/event/RecommendersSuspendedEvent.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderListPanel.properties
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/render/RecommendationRenderer.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebar.properties
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommendationSidebarFactory.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderSidebarIcon.html
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderSidebarIcon.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- inception/inception-recommendation/src/main/resources/META-INF/asciidoc/user-guide/projects_recommendation.adoc
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarTab.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/SidebarTabbedPanel.java
- Added options in the project settings to enable/disable displaying suggestions when in curation mode or when looking at annotations from other users
- Added a status badge to the icon of the recommender sidebar
- Switch icons of the recommedner sidebar and active learning sidebar
- Disable recommender and active learning sidebar when recommenders are disabled in curation mode etc.
* Use the options in the project settings
* Try their effect on the annotation page
> #4616 - Option to disable displaying suggestions in sidebar curation mode

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- Issue warnings in the log in cases where the user may be surprised that the recommender is not running or where the recommender may be misconfigured
> #4622 - No helpful error message when recommender is not called due to feature being disabled

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/export/ExportDocumentDialogContent.java
- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/AjaxDownloadLink.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/InputStreamResourceStream.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java
- Using var
- Added ability to set content type on InputStreamResourceStream
> #4550 - Clean up code

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLayerList.svelte
- Added buttons to collapse the groups including buttons to collapse/expand all
* Use the new buttons in the annotation sidebar
> #4636 - Ability to collapse groups in annotation sidebar

- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinkerFactory.java
- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/client/OllamaGenerateRequest.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/event/PredictionsSwitchedEvent.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngineFactory.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngineFactoryImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- Added ability to internally mark recommenders as synchronous. Such recommenders are run immedately after creating an annotation during the very same request such that suggestions appear immediately.
* Use the Named Entity Linker recommender
> #4614 - Display suggestions from Named Entity Linker immediately

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/config/AnnotationAutoConfiguration.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainLayerSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationAdapter.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationEndpointFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationEndpointFeatureTraits.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationLayerSupport.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupServiceImpl.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationDetailPanel.java
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkRecommenderPanel.java
- inception/inception-project-initializers-basic/src/main/java/de/tudarmstadt/ukp/inception/project/initializers/basic/BasicRelationLayerInitializer.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/CoreferenceLayerInitializer.java
- inception/inception-project-initializers/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/initializers/DependencyLayerInitializer.java
- inception/inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/DocumentAnnotationPanel.java
- inception/inception-review-editor/src/main/java/de/tudarmstadt/ukp/inception/revieweditor/SpanAnnotationPanel.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/rendering/Renderer.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/FeatureSupport.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/layer/LayerSupport.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationTextPanel.html
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationTextPanel.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/LayerDetailForm.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/ProjectLayersPanel.html
- Added a new relation endpoint feature support
- Allow editing relation endpoint names (only UI names)
- Create these features when creating new relation layers (existing layers don't get them)
* Try working with existing relation layers
* Try creating new projects with new relation layers
* Try changing the names of the relation endpoints and check that the change reflects e.g. in the annotation detail panel
> #4641 - Ability to assign names to endpoints of relations

- inception/inception-dependencies/pom.xml
- inception/pom.xml
- pom.xml
- woodstox 6.5.1 -> 6.6.1
- json-schema-validator 1.0.88 -> 1.4.0
- oauth2-oidc-sdk 9.43.3 -> 9.43.4
- commons-compress 1.26.0 -> 1.26.1
- checkstyle 10.12.3 -> 10.14.2
- mockito 5.10.0 -> 5.11.0
- assertj 3.24.2 -> 3.24.2
- testcontainers 1.19.5 -> 1.19.7
- awaitlity 4.2.0 -> 4.2.1
- spring 5.3.32 -> 5.3.33
- log4j 2.23.0 -> 2.23.1
- tomcat 9.0.86 -> 9.0.87
- postgres-driver 42.7.2 -> .42.7.3
- rdf4j 4.3.9 -> 4.3.10
- asciidoctor 2.5.10 -> 2.5.12
- asciidoctor-diagram 2.2.9 -> 2.3.0
- asciidoctor-pdf -> 2.3.15
- jackson 2.16.1 -> 2.17.0
- okio 3.8.0 -> 3.9.0
> #4545 - Upgrade dependencies

- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerAdapter.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerSupport.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- Introduce "uiOrder" feature on document metadata layer
- Declare "uiOrder" as invalid name on this layer so users cannot create a feature by that name
- Sort annotations according to uiOrder
- Set uiOrder properly when creating a new annotation
> #4449 - Adding new document level non-singleton annotations adds them in strange order

- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasStorageServiceImpl.java
- inception/inception-annotation-storage/src/test/java/de/tudarmstadt/ukp/inception/annotation/storage/CasStorageServiceImplTest.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/editor/state/AnnotatorStateImpl.java
- inception/inception-api-render/pom.xml
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/editorstate/AnnotatorDocumentNavigation.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/editorstate/AnnotatorState.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationMergeServiceImpl.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationServiceImpl.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarBehavior.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarService.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/config/CurationSidebarAutoConfiguration.java
- inception/inception-ui-curation/src/test/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceTest.java
- inception/pom.xml
- Auto-merge when accessing a document in curation sidebar mode if the document has not been curated yet - however - for the moment only when curating to the curation user
- When reading annotations in another mode than exclusive-write-access, do not persist the annotations to disk e.g. after loading them from the initial CAS and upgrading
* Try using the curation sidebar, switching between documents, enabling/disabling curation mode and check if the initial merges happen as expected
* Use the monitoring page to reset the curation from time to time
> #4655 - Opening a document in sidebar curation mode does not trigger auto-merge

- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- Improve detection of whether a fallback to the source document is necessary and do that fallback not only if there is no annotation document metadata record in the DB, but also when the state there is NEW
> #4669 - Results missing from search when annotation document exists but is in state NEW

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/detail/AnnotationDetailEditorPanel.java
- Remember the armed feature because the arm status will be cleared and once that happens, the exception would be thrown when we try checking if the annotation is visible in the editor sidebar and needs to be updated
* See issue
> #4677 - Error when trying to fill a link feature slot

- inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/exporters/AnnotationDocumentExporter.java
- Added a new index to the annotation_document table
* You'd need a **very** large project to feel the difference
> #4683 - Improve speed of DB queries to find annotation documents for a project and user

- inception/inception-documents-api/src/main/java/de/tudarmstadt/ukp/inception/documents/api/DocumentService.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.html
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
- Added option to move multiple documents into active curation
- Use bulk state update for reseting curation documents instead of updating the state for each document individually
* Enable bulk actions
* Select one or more documents or the curator column
* Select "Resume curation"
> #2412 - Possibility to reopen all curated documents at once

- inception/inception-html-apache-annotator-editor/pom.xml
- inception/inception-html-apache-annotator-editor/src/main/java/de/tudarmstadt/ukp/inception/apacheannotatoreditor/ApacheAnnotatorHtmlAnnotationEditorFactory.java
- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/TeiXmlDocumentFormatSupport.java
- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/TeiXmlDocumentPolicy.yaml
- inception/inception-io-tei/src/main/ts/src/TeiXmlDocument.scss
- inception/inception-io-tei/src/main/ts/src/bibliography.scss
- inception/inception-io-tei/src/main/ts/src/figures.scss
- Add more styling for stuff produced by grobid
- Make Apache Annotator the default editor for TEI XML files
* Process a PDF to TEI using grobid, e.g. https://grobid.readthedocs.io/en/latest/Grobid-service/
* Import the TEI file as TEI XML (experimental)
* Open it in the annotation editor
> #4702 - Improve TEI styling for scientific publications processed with grobid

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationAdapter.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingRelationsRepair.java
- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveDanglingRelationsRepairTest.java
- Detect relation layers using the adapter mechanism
> #4709 - Rely on layer type instead of feature presence for relation repair action

- inception/inception-agreement/pom.xml
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/AgreementUtils.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/config/AgreementAutoConfiguration.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureSupport.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureSupport_ImplBase.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/cohenkappa/CohenKappaAgreementMeasureSupport.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/fleisskappa/FleissKappaAgreementMeasureSupport.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalpha/KrippendorffAlphaAgreementMeasureSupport.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalphaunitizing/KrippendorffAlphaUnitizingAgreementMeasureSupport.java
- inception/inception-agreement/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureTestSuite_ImplBase.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/CohenKappaAgreementMeasureTest.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/FleissKappaAgreementMeasureTest.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/KrippendorffAlphaNominalAgreementMeasureTest.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/KrippendorffAlphaUnitizingAgreementMeasureTest.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/ConfigurationSet.java
- inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementPage.java
- inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementService.java
- inception/inception-ui-agreement/src/main/java/de/tudarmstadt/ukp/inception/ui/agreement/page/AgreementServiceImpl.java
- Include incomplete / stacked positions and include annotator's values on these as well in the diff export
- Fix a bug where a configuration set might not be marked as "difference" when there are more than two annotators
* Export diff from the agreement page and inspect the result
> #4704 - Per-document agreement across all annotators

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/ActionBar.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/ActionBarExtension.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/actionbar/ActionBarExtensionPointImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/NoPagingStrategy.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/svelte/SvelteBehavior.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/AnnotationDocumentNavigatorActionBarExtension.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/docnav/DocumentNavigator.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/actionbar/open/OpenDocumentDialog.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/page/ApplicationPageBase.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CurationWorkflowActionBarExtension.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/component/render/CurationRendererImpl.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/config/CurationUIAutoConfiguration.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/actionbar/opendocument/CurationOpenDocumentDialog.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarAutoOpenDialogBehavior.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarDocumentNavigator.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarDocumentNavigatorActionBarExtension.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/config/CurationSidebarAutoConfiguration.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowDocumentNavigationActionBarExtension.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowNoRandomAccessDocumentNavigationActionBarExtension.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/config/MatrixWorkloadManagerAutoConfiguration.java
- Use the OpenCurationDocument dialog if the sidebar curation mode is active
- Refresh the footer when changing footer items such that we can properly switch between the dialogs and auto-open behaviors
- Avoid error message when trying to destroy an already destroyed Svelte component
- Allow action bar extensions to remove themselves from the footer (needed when we switch between the dialogs)
* Try entering/leaving/switch documents, etc. - stress switching between curation and annotation modes in all combinations
> #4728 - Leaving the annotation page and coming back when sidebar curation is active leaves the editor in a strange state

- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts_template/package.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/.gitignore
- inception/inception-support-bootstrap/pom.xml
- inception/inception-support-bootstrap/src/main/ts/build.js
- inception/inception-support-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/src/main/ts_template/package.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-scheduling/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- inception/pom.xml
- pom.xml
- Update package-lock files
- nodejs 18.18.0 -> 20.12.2
- dayjs 1.11.4 -> 1.11.10
- eslint 8.31.0 -> 8.57.0
- eslint-plugin-chai-friendly 0.7.2 -> 0.7.4
- eslint-config-standard 17.0.0 -> 17.1.0
- eslint-plugin-import 2.26.0 -> 2.29.1
- eslint-plugin-mocha 10.2.0 -> 10.4.3
- eslint-plugin-n 15.6.0 -> 16.6.2
- eslint-plugin-svelte 2.33.2 -> 2.37.0
- types-chai 4.3.1 -> 4.3.14
- fs-extra 10.1.0 -> 11.2.0
- sass 1.68.0 -> 1.75.0
- typescript 5.2.2 -> 5.4.5
- typescript-eslint-eslint-plugin 6.7.4 -> 7.7.0
- typescript-eslint-parser 6.7.4 -> 7.7.0
- esbuild 0.19.5 -> 0.20.2
- esbuild-sass-plugin 2.16.0 -> 3.2.0
> #4745 - Upgrade dependencies

- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/model/Range.java
- inception/inception-concept-linking/pom.xml
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinkerFactory.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinkerTraits.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinkerTraitsEditor.html
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinkerTraitsEditor.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinkerTraitsEditor.properties
- inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/NamedEntityLinkerTest.java
- inception/inception-documents-api/src/main/java/de/tudarmstadt/ukp/inception/documents/api/DocumentService.java
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/RecommendationEngineFactory.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/NonTrainableRecommenderActivationTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/TrainingTask.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- inception/inception-testing/pom.xml
- inception/inception-testing/src/main/java/de/tudarmstadt/ukp/inception/support/test/recommendation/RecommenderTestHelper.java
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- Added option to suggest entites only if there is a free target feature
- Added option to disable synchronous behavior of entity linker
- Expand entity linker to additional layer configurations
- No longer require sentences for entity linker to work
- Added new tests
- Properly inherit suggestions if a recommender is skipped because a particular run does not include (a)sync recommenders
- Avoid running synchronous recommenders twice when opening a document
* Try using the entity linker recommender, e.g. in a wikidata linking project
> #4752 - Suggest entities for linking only if there an empty feature in a target annotation to be linked

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- When requesting only a single recommender, make sure to inherit data for the others
> #4751 - Suggestions flicker when Entity Linker recommender is used in combination with other recommenders

- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- Do not force-enable server-side timings in dev mode
> #4764 - No longer force-enable server-side timings when dev mode is disabled

- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationMergeService.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/service/CurationMergeServiceImpl.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeRemergeTest.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeSuiteTest.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/CurationPage.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/MergeDialog$ContentPanel.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/page/MergeDialog.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarBehavior.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarService.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- Added the switch
* In curation sidebar mode, partially curate manually, then use the merge dialog to merge the rest, disabling the "discard curated annotations" option
> #4774 - Ability to not reset curation when performing a manual merge (sidebar curation)

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarBehavior.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/MatrixWorkloadManagementPage.java
- Trigger merge based on source document state and not based on whether the curation CAS exists
- Delete curation CAS as part of bulk reset
> #4739 - Auto-merge on open document in curation mode

- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/view/pdfjs/PdfJsViewerPage.java
- Disable annotations in the PDF viewer
- Print a Wikipedia page to PDF using the print-to-PDF functionality on macOS and then import the resulting PDF into INCEpTION
> #4778 - Links and other active elements in PDFs interfere with annotation and should be disabled

- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/model/Index.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/scheduling/tasks/IndexSourceDocumentTask.java
- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/documents/ImportDocumentsPanel.java
- Fix the issue by only persisting the DB record if we actually change the "invalid" flag
> #4782 - Avoid duplicate key error when importing documents very rapidly

- inception/inception-annotation-storage/src/main/java/de/tudarmstadt/ukp/inception/annotation/storage/CasMetadataUtils.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/editor/state/AnnotatorStateImpl.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/paging/PagingStrategy.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/CASMetadataTypeIsPresentCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/NegativeSizeAnnotationsCheck.java
- Copy the CASMetadata over when clearing the CAS in preparation for the merge
- Make rendering a bit more robust in case a CAS goes completely broken
> #4787 - When re-merging a document CASMetadata is not retained

- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/DocumentTextStartsWithBomCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorAutoConfiguration.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveBomRepair.java
- inception/inception-diag/src/main/resources/META-INF/asciidoc/user-guide/casdoctor.adoc
- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveBomRepairTest.java
- inception/inception-io-brat/src/main/java/de/tudarmstadt/ukp/inception/io/brat/dkprocore/internal/mapping/TypeMappings.java
- inception/inception-io-text/pom.xml
- inception/inception-io-text/src/main/java/de/tudarmstadt/ukp/clarin/webanno/text/LineOrientedTextReader.java
- inception/inception-io-text/src/main/java/de/tudarmstadt/ukp/clarin/webanno/text/PretokenizedLineOrientedTextReader.java
- inception/inception-io-text/src/main/java/de/tudarmstadt/ukp/clarin/webanno/text/TextFormatSupport.java
- inception/inception-io-text/src/main/java/de/tudarmstadt/ukp/clarin/webanno/text/TextReader.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/aero/AeroRemoteApiController.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/ICasUtil.java
- Use BOMInputStream to strip BOM in the plain-text readers
* Import a file with a BOM
> #4791 - BOM not removed when importing plain text files

- inception/inception-brat-editor/src/main/ts/src/BratEditor.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.ts
- inception/inception-html-recogito-editor/src/main/ts/src/recogito/RecogitoEditor.ts
- inception/inception-js-api/src/main/ts/src/widget/AnnotationDetailPopOver.svelte
- inception/inception-pdf-editor2/src/main/ts/src/PdfAnnotationEditor.ts
- inception/inception-pdf-editor2/src/main/ts/src/pdfanno/pdfanno.ts
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/svelte/SvelteBehavior.java
- Destroy the popover in brat, apache annotator, pdf and recogito editors
- Fix an exception in the popover when a rendering/moving is triggered while the element the component is attached to is already gone
> #4796 - Annotation popover is not destroyed when switching between documents

- inception/inception-dependencies/pom.xml
- pom.xml
- mockito 5.11.0 -> 5.12.0
- xmlunit 2.9.1 -> 2.10.0
- testcontainers 1.19.7 -> 1.19.8
- tomcat 9.0.88 -> 9.0.89
- elasticsearch 7.17..20 -> 7.17.21
- jackson 2.17.0 -> 2.17.1
- woodstox 6.6.1 -> 6.6.2
- bytebuddy 1.14.13 -> 1.14.15
- commons-codec 1.16.1 -> 1.17.0
- picocli 4.7.5 -> 4.7.6
> #4785 - Upgrade dependencies

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/NopRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationLayerTraits.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationLayerTraitsEditor.html
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationLayerTraitsEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderMode.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderModeSelect.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/rendering/Renderer.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRenderer.java
- inception/inception-ui-project/src/main/resources/META-INF/asciidoc/user-guide/projects_layers.adoc
- Added option to render the arc of a relation only when the relation or one of its endpoints is selected
* Change the render mode for a relation layer to "when selected"
> #4826 - Option to show relation arcs only when span is selected

- inception/inception-app-webapp/pom.xml
- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/INCEpTION.java
- inception/inception-dependencies/pom.xml
- inception/pom.xml
- Added JUL-to-SLF4J bridge
- Enable the bridge only in dev mode for performance reasons
* Enable dev mode (`-Dinception.dev=true`)
* Configure Tomcat logging in `settings.properties` using `logging.level.org.apache.catalina=TRACE`
> #4830 - Cannot enable logging for JUL-based libraries

- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- Normalize DOM after removing markers because Apache Annotator can fail to create marker annotations in a fragemented DOM
* Requires an affected document
> #4839 - Scrolling to selection does sometimes not work in Apache Annotator Editor

- inception/inception-agreement/pom.xml
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/results/coding/AbstractCodingAgreementMeasureSupport.java
- inception/inception-curation-legacy/pom.xml
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/api/DiffAdapter.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/api/DiffAdapter_ImplBase.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/docmeta/DocumentMetadataDiffAdapter.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/docmeta/DocumentPosition.java
- Added a diff adapter for document-level annotations
- Allow document-level layers in coding agreements
* Create a document-level annotation layer with a string feature
* Annotate it using two annotators
* Calculate agreement
> #4064 - Support for agreement calculation on document-level annotations

- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkPredictionTask.java
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkRecommenderPanel.html
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkRecommenderPanel.java
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkRecommenderPanel.properties
- Added the option
* Set up a string-matching recommender and a document without any annotations
* Run the recommender using the bulk processing without enabling the option - the document should be "in progress" afterwards
* Run the recommender with the option enabled - the document should be "finished" afterwards
> #4858 - Option to not finish bulk-processed documents if no annotations were accepted

- inception/inception-build/src/main/resources/inception/checkstyle.xml
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/config/EntityLinkingServiceAutoConfiguration.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/feature/LevenshteinFeatureGenerator.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/feature/MatchingTokenOverlapFeatureGenerator.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/model/CandidateEntity.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategy.java
- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImpl.java
- inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/feature/MatchingTokenOverlapFeatureGeneratorTest.java
- inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/ranking/BaselineRankingStrategyTest.java
- inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/service/ConceptLinkingServiceImplTest.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBaseProperties.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBasePropertiesImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterAllegroGraph.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterBlazegraph.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterFuseki.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterNoFts.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterRdf4J.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterStardog.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterVirtuoso.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterWikidata.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderRemoteServicesTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderTest.java
- pom.xml
- Decompose the query into terms and match them independently of their order
- Internally retrieve more items from the FTS before filtering them down
- Additional testing
- Cleaning up
* E.g if a KB contains an entry "long beach", try searching for "beach long"
> #4860 - Knowledge base items should be matched even if query contains terms out of order

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/curation/actionbar/CuratorWorkflowActionBarItemGroup.java
- Validate only when marking document as finished, but not when putting back into progress
* Close a curated document with some string feature that has an empty value
* Make the string feature mandatory in the project settings
* Try re-opening the curated document from the action bar in the curation page
> #4867 - Cannot re-open document for curation if it contains an invalid feature value

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/SentenceOrientedPagingStrategy.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/paging/TokenWrappingPagingStrategy.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/Offsets.java
- inception/inception-brat-editor/src/main/ts/src/BratEditor.ts
- inception/inception-brat-editor/src/main/ts/src/annotator_ui/ResizeManager.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Chunk.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Row.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VRange.java
- Create a virtual chunk at the end of the viewport if necessary to avoid the brat rendering process crashing later because the end-of-page fragment `rel:1-after` cannot be assigned to a chunk
- Fix span clipping in the backend
* In general, view documents with (long) spans and relations in brat mode
> #4889 - Document sometimes not rendered in by line brat render modes

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-scheduling/src/main/java/de/tudarmstadt/ukp/inception/scheduling/SchedulingServiceImpl.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- Ensure the curation sidebar service reacts to the logout before the session information is cleared from the registry
> #4892 - Curation sidebar state not cleared when logging out

- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/AnnotationPage.java
- Ensure that the proper editor has been created before clearing the state which then triggers a selection-change event that the editor reacts to
> #4727 - Switching between editors can cause the old and the new editors to be loaded and initialized

- inception/inception-kb/pom.xml
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBaseProperties.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/config/KnowledgeBasePropertiesImpl.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterAllegroGraph.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterBlazegraph.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterFuseki.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterRdf4J.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FtsAdapterWikidata.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryPrimaryConditions.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplIntegrationTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/FusekiRepositoryTest.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/RepositoryTestSuite.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilderLocalTestScenarios.java
- inception/inception-kb/src/test/resources/turtle/data_labels_and_descriptions_with_language.ttl
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- Added ability to globally configure fallback languages via settings.properties file (to be changed for 34.x)
- Added simpel test
* Add e.g. `knowledge-base.default-fallback-languages[0]=es` to the `settings.properties` file
> #4896 - Ability to search for additional languages in knowledge-base

- inception/inception-export-api/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/export/ProjectExporter.java
- inception/inception-imls-weblicht/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/weblicht/exporter/ChainExporter.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
- inception/inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseExporterTest.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/exporter/LoggedEventExporter.java
- Standardize entry paths when writing ZIP to remove the problem with ZIP entries starting with a slash that seems to have been introduced in 33.0
- Be more robust when loading entries from the export ZIP to allow loading ZIPs exported using 33.0
> #4898 - Unable to import project with knowledge-based exported by INCEpTION 33.0

- inception/inception-io-xml/pom.xml
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/CustomXmlFormatFactory.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/CustomXmlFormatPluginDescripion.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/CasXmlHandler.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/XmlDocumentReader.java
- inception/inception-io-xml/src/main/resources/META-INF/asciidoc/user-guide/formats-xml-custom.adoc
- inception/inception-io-xml/src/main/resources/xml/block-elements.xml
- inception/inception-io-xml/src/test/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/CasXmlHandlerTest.java
- inception/inception-io-xml/src/test/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/XmlDocumentReaderTest.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/SegmentationUtils.java
- Added options to define block elements in XML files which are considered when doing sentence splitting
* Add new configuration options to custom XML format JSON, e.g.
```
{
"name": "TMX (external)",
"stylesheets": [ 
"styles.css"
],
"blockElements": [
"seg"
],
"splitSentencesInBlockElements": false
}
```
> #4901 - Consider document structure when splitting sentences in custom XML formats

- inception/inception-app-webapp/pom.xml
- inception/inception-dependencies/pom.xml
- inception/inception-plugin-parent/pom.xml
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/ServletContextUtils.java
- inception/inception-ui-core/pom.xml
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.java
- inception/pom.xml
- pom.xml
- WicketStuff Core 10.1.0 -> 10.1.1
- Exclude jcl-over-log4j, commons-logging and commons-logging-api in favor of spring-jcl
- liquibase-slf4j -> 5.0.0
- Remove Wicket Webjars workaround for bug in WicketStuff 10.1.0
- Remove/exclude dependencies on all commons-logging stuff except spring-jcl
- Route liquibase logging through SLF4J
> #4909 - Upgrade dependencies

- inception/inception-external-search-core/src/main/resources/de/tudarmstadt/ukp/inception/externalsearch/model/db-changelog.xml
- inception/inception-imls-elg/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/imls/elg/model/db-changelog.xml
- inception/inception-imls-stringmatch/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/model/db-changelog.xml
- inception/inception-imls-weblicht/src/main/resources/de/tudarmstadt/ukp/inception/recommendation/imls/weblicht/model/db-changelog.xml
- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/model/db-changelog.xml
- inception/inception-log/src/main/resources/de/tudarmstadt/ukp/inception/log/model/db-changelog.xml
- inception/inception-model/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/model/db-changelog.xml
- inception/inception-search-core/src/main/resources/de/tudarmstadt/ukp/inception/search/model/db-changelog.xml
- inception/inception-security/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/security/model/db-changelog.xml
- inception/inception-telemetry/src/main/resources/de/tudarmstadt/ukp/clarin/webanno/telemetry/model/db-changelog.xml
- Removed the migrations from the WebAnno era that delete indexes that were created before Liquibase was introduced
> #3407 - Remove old database migrations that seem to get always executed

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.properties
- Do not hide the users list when document is finished
- Hide the remerge button though
* Enable curation sidebar
* Mark document as finished
* Toggle users
> #4925 - Retain ability to select users in curation sidebar in finished documents

- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRenderer.java
- Hide overlapping curation suggestions if the layer does not support overlapping annotations
> #4929 - Unmergable annotations should be hidden in integrated curation mode

- .github/workflows/maven.yml
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/export/CuratedDocumentsExporter.java
- Skip exporting curation CASes that are not there and log a warning
- Backport github action configuration from main
> #4933 - Exporting project fails if a curation CAS is missing or document state is wrong

- inception/inception-project/pom.xml
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-security/pom.xml
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/Realm.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/config/SecurityAutoConfiguration.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/oauth/OAuth2AdapterImpl.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/saml/Saml2AdapterImpl.java
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-authentication-oauth2.adoc
- inception/inception-security/src/main/resources/META-INF/asciidoc/admin-guide/security-authentication-saml2.adoc
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/login/OAuth2LoginPanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/ManageUsersPage.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/users/UserDetailPanel.java
- inception/pom.xml
- Include servlet context path in URLs for SAML/OAuth login
- Update OAuth/SAML documentation
- Better display of realms on user management page
- Include SAML realm in user-detail realm dropdown
- Issue OAuth/SAML login failures as warning
> #4940 - OAuth and SAML logins do not work if a servlet path is used

- inception/inception-app-webapp/pom.xml
- inception/inception-build/src/main/resources/inception/rules.xml
- inception/inception-dependencies/pom.xml
- inception/inception-project-export/pom.xml
- inception/inception-remote/pom.xml
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/RemoteApiAutoConfiguration.java
- inception/pom.xml
- pom.xml
- junit 5.10.2 -> 5.10.3
- junit-platform 1.10.2 -> 1.10.3
- spring 6.1.8 -> 6.1.11
- spring-boot 3.3.0 -> 3.3.2
- spring-data 3.2.4 -> 3.3.2
- spring-security 6.3.0 -> 6.3.1
- springdoc 1.8.0 -> 2.6.0
- jjwt 0.12.5 -> 0.12.6
- jboss-logging 3.5.3 -> 3.6.0
- assertj 3.26.0 -> 3.26.3
- testcontainers 1.19.8 -> 1.20.0
- tomcat 10.1.24 -> 10.1.26
- jetty 12.0.11 -> 12.0.12
- mysql-driver 8.0.27 -> 8.0.33
- hibernate-validator
- opensearch 2.14.0 -> 2.15.0
- asciidoctor 2.5.12 -> 2.5.13
- asciidoctor-diagram 2.3.0 -> 2.3.1
- asciidoctor-pdf 2.3.15 -> 2.3.17
- jackson 2.17.1 -> 2.17.2
- byte-buddy 1.14.17 -> 1.14.8
- commons-lang3 3.14.0 -> 3.15.0
- commons-codec 1.17.0 -> 1.17.1
- commons-dbcp2 2.11.0 -> 2.12.0
- jgit 6.9.0.202403050737-r -> 6.10.0.202406032230-r
- …
> #4909 - Upgrade dependencies (34.0)

- inception/inception-app-webapp/src/main/java/de/tudarmstadt/ukp/inception/app/config/InceptionSecurityWebUIBuiltInAutoConfiguration.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/clarin/webanno/security/WicketSecurityUtils.java
- inception/inception-security/src/main/java/de/tudarmstadt/ukp/inception/security/config/InceptionSecurityWebUIApiAutoConfiguration.java
- Change the way that CSRF is not applied to Wicket UI calls but still register Spring CSRF token in the request
- Update some of the Spring Security configuration to non-deprecated calls
> #4975 - Cancelling background jobs no longer works

- inception/inception-support-bootstrap/src/main/ts/bootstrap/inception-custom.scss
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/footer/WarningsFooterPanel.html
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/footer/WarningsFooterPanel.java
- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/management/AssignWorkDialogContentPanel.java
> #4984 - Warnings drop-up in the footer no longer opens

- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- The inheritable annotations may be in the incoming predictions and not in the active predictions, so look at incoming first, if none are there, then look in active.
> #4990 - Non-trainable recommender may be invoked even though inheritable predictions exist

- inception/inception-processing/pom.xml
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/AnnotationDocumentStatesChoice.java
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkPredictionTask.java
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkRecommenderPanel.html
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkRecommenderPanel.java
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkRecommenderPanel.properties
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/DefaultTrainableRecommenderTraitsEditor.properties
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/recommender/TrainingStatesChoice.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/project/RecommenderEditorPanel.java
- inception/inception-ui-core/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/core/WicketApplicationBase.properties
- Added option to select states for bulk recommender processing
* Try out processing only new or only in-progress or both
> #4995 - Ability to select states of documents to include in bulk recommender processing

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/LabelRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/CasDiff.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/api/DiffAdapter_ImplBase.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/api/Position.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/api/Position_ImplBase.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/relation/RelationPosition.java
- inception/inception-curation-legacy/src/main/java/de/tudarmstadt/ukp/clarin/webanno/curation/casdiff/span/SpanPosition.java
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLayerList.svelte
- inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactAnnotatedText.ts
- inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactArgument.ts
- inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactRelation.ts
- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VArc.java
- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VSpan.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRenderer.java
- Make browser component more robust to even render if arc targets are missing (ignoring those arcs)
- Improve curation sidebar renderer to handle cases where a link source is hidden due to an already merged annotation
- Add hashCode and equals to Positions because it also implements compareTo
* Try sidebar curation mode
> #4994 - Annotation browser sometimes does not load in sidebar curation mode

- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/ChatGptRecommender.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/ChatGptRecommenderTraits.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/ChatGptRecommenderTraitsEditor.html
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/ChatGptRecommenderTraitsEditor.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/ChatGptRecommenderTraitsEditor.properties
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/ChatGptResponseFormatSelect.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/Preset.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/client/ChatCompletionRequest.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/client/ResponseFormat.java
- inception/inception-imls-chatgpt/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/chatgpt/client/ResponseFormatType.java
- inception/inception-imls-chatgpt/src/test/java/de/tudarmstadt/ukp/inception/recommendation/imls/azureaiopenai/client/OpenAiClientTest.java
- Switch to using `reponse_format` parameter
- Add several default URLs for the recommender including OpenAI, Groq and Cerebras
* Try using one of the endpoints with JSON response format
> #5031 - ChatGPT recommender fails because format is not a supported parameter

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanAnchoringModeBehavior.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsStartAndEndWithCharactersCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/TrimAnnotationsRepair.java
- inception/inception-diag/src/main/resources/META-INF/asciidoc/user-guide/casdoctor.adoc
- inception/inception-diag/src/test/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/AllAnnotationsStartAndEndWithCharactersCheckTest.java
- inception/inception-imls-stringmatch/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/stringmatch/span/StringMatchingRecommender.java
- inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/dkprocore/CasXmlNodeVisitor.java
- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/dkprobackport/TeiReader.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/span/SpanSuggestionSupport.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/text/TrimUtils.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/uima/SegmentationUtils.java
- inception/inception-support/src/test/java/de/tudarmstadt/ukp/inception/support/text/TrimUtilsTest.java
- Change the central trimming functions to consider NBSP and various other invisible Unicode characters as trimmable space
> #5035 - NBSPs should not be treated as tokens

- inception/inception-brat-editor/pom.xml
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/BratSerializerImpl.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/EntityAttributes.java
- inception/inception-brat-editor/src/main/java/de/tudarmstadt/ukp/clarin/webanno/brat/render/model/ScoreSerializer.java
- inception/inception-brat-editor/src/main/ts/src/protocol/Protocol.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Entity.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.html
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebar.properties
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarService.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/render/CurationSidebarRenderer.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImpl.java
- Added option to show the fraction as a score
- Added rendering of annotation scores to brat spans (not relations atm though!)
- Minor cleanup
- Curation scores will also be shown in the annotation overview
- Recommender scores now will also show up on span suggestions in the brat view
* Open a document in curation sidebar mode and enable the **Show percentage of annotators** option
> #5037 - Show fraction of annotators that chose a certain label in curation sidebar mode

- inception/inception-diam-compactv2/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compactv2/CompactLayer.java
- inception/inception-diam-compactv2/src/main/java/de/tudarmstadt/ukp/inception/diam/model/compactv2/CompactSerializerV2Impl.java
- inception/inception-diam-compactv2/src/test/resources/compactv2/reference.json
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLayerList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByPositionList.svelte
- inception/inception-diam-editor/src/main/ts/src/LabelBadge.svelte
- inception/inception-diam-editor/src/main/ts/src/SpanText.svelte
- inception/inception-diam-editor/src/main/ts/src/Utils.ts
- inception/inception-js-api/src/main/ts/src/model/Layer.ts
- inception/inception-js-api/src/main/ts/src/model/compact_v2/CompactLayer.ts
- Display start and end of a relation in layer-grouping mode
- Sort link targets under link sources in layer-grouping mode
- Generally try to impove the visuals a bit
* Try using the annotation sidebar in different modes
> #4949 - Showing the start and end points of relations in left side bar

- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/CreateSpanAnnotationHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/LazyDetailsHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupService.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/lazydetails/LazyDetailsLookupServiceImpl.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/RecommenderGeneralSettings.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- Use the session owner when loading lazy details for annotation suggestions instead of the data owner
- By default, disable displaying annotation suggestions when viewing annotations of another user
* See issue
> #5052 - No lazy details when viewing annotation suggestions for another user

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiSelectTextFeatureEditor.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureTraitsEditor.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/ExportedKnowledgeBase.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/exporter/KnowledgeBaseExporter.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/model/KnowledgeBase.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/querybuilder/SPARQLQueryBuilder.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/yaml/KnowledgeBaseProfile.java
- inception/inception-kb/src/main/resources/de/tudarmstadt/ukp/inception/kb/model/db-changelog.xml
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/GeneralSettingsPanel.html
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/GeneralSettingsPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseDetailsPanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/KnowledgeBaseWrapper.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/ProjectKnowledgeBasePanel.properties
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/wizard/KnowledgeBaseCreationWizard.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/management/DynamicWorkloadManagementPage.java
- Added setting for additional languages
* Import multi-language KB
* Add additional languages
* Search by a term not in the default language
> #5056 - Ability to configure additional languages for knowledge bases

- inception/inception-concept-linking/src/main/java/de/tudarmstadt/ukp/inception/conceptlinking/recommender/NamedEntityLinker.java
- inception/inception-concept-linking/src/test/java/de/tudarmstadt/ukp/inception/conceptlinking/NamedEntityLinkerTest.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/SuggestionGroup.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- Display score in entity linker recommender if index can provide a score
- Use the suggestion with the highest score as the canonical one
- Apply all synchronous recommenders in a single task and make sure they do not overwrite each other
* See issue
> #5061 - Multiple synchronous recommenders only the last one wins

- inception/inception-dependencies/pom.xml
- pom.xml
- rhino 1.7.14 -> 1.7.15
- ant 1.10.14 -> 1.10.15
- junit 5.11.0 -> 5.11.1
- junit-platform 1.11.0 -> 1.11.1
- mockito 5.12.0 -> 5.14.1
- testcontainers 1.20.1 -> 1.20.2
- spring 6.1.12 -> 6.1.13
- spring-boot 3.3.2 -> 3.3.4
- spring-security 6.3.1 -> 6.3.3
- swagger 2.2.22 -> 2.2.24
- log4j 2.23.1 -> 2.24.1
- tomcat 10.1.28 -> 10.1.30
- jetty 12.0.12 -> 12.0.14
- postgres-driver 42.7.3 -> 43.7.4
- wicket 10.1.0 -> 10.2.0
- wicketstuff 10.1.1 -> 10.2.0
- wicket-bootstrap 7.0.5 -> 7.0.8
- wicket-jquery-selectors 4.0.5 -> 4.0.6
- wicket-webjars 4.0.4 -> 4.0.5
- opensearch 2.16.0 -> 2.17.0
- jackson 2.17.2 -> 2.18.0
- snakeyaml 2.2 -> 2.3
- okio 3.9.0 -> 3.9.1
- byte-buddy 1.14.19 -> 1.15.3
- commons-csv 1.11.0 -> 1.12.0
- commons-lang3 3.16.0 -> 3.17.0
- …
> #5078 - Upgrade dependencies

- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/ollama/OllamaRecommender.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/model/EvaluatedRecommender.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/NonTrainableRecommenderActivationTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/PredictionTask.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/tasks/SelectionTask.java
- Remove the response limit for Ollama
- Distingish different auto-activation reasons in the recommender sidebar
- Mark interactive recommender as "active" so that the PredictionTask considers them (not yet sure if that is the best approach, but then at least also the "accept best" buttons in the recommender sidebar are there)
- Skip interactive recommenders unless they are explicitly included to be run in a PredictionTask
- Log a bit more timing information
* Try using the interactive recommender sidebar
> #5087 - Interactive recommender sidebar does not invoke the right recommender

- inception/inception-ui-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/project/layers/FeatureDetailForm.java
- Do not offer the "Show only when constraints match" option for non-string features
> #5098 - Conditional feature option for integer features should not be offered

- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalpha/KrippendorffAlphaAgreementMeasureSupport.java
- Fixed name
* Go to the agreement page and check if the measures are properly named
> #5104 - Agreement measure has wrong name

- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/annotation/DynamicWorkflowActionBarExtension.java
- inception/inception-workload-dynamic/src/main/java/de/tudarmstadt/ukp/inception/workload/dynamic/config/DynamicWorkloadManagerAutoConfiguration.java
- Use the session owner instead of the data owner when checking for curator role
* Open a project using dynamic workload where all documents are finished
* As a curator, try opening a document from a non-curator on the curation page or annotation page with curation sidebar enabled
> #5129 - Dynamic workflow may kick in for curator when try to view document from non-curator

- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLayerList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByPositionList.svelte
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/EditorAjaxRequestHandler.java
- inception/inception-diam/src/main/java/de/tudarmstadt/ukp/inception/diam/editor/actions/ScrollToHandler.java
- inception/inception-diam/src/main/ts/src/diam/DiamAjaxImpl.ts
- inception/inception-js-api/src/main/ts/src/diam/DiamAjax.ts
- Change the scrollTo JS API function to accept multiple offsets (although only the first one is currently ever used)
- Fix ScrollToHandler to jump without taking the window offset into consideration
- Fix the annotation sidebar to properly jump
* See issue
> #5135 - Cannot jump to curation suggestion without accepting it

- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkRecommenderPanel.java
- Skip interactive recommenders on the bulk processing panel
* Mark a recommender as interactive
* Check it does not appear on the bulk processing page
> #5141 - Interactive recommenders should not be listed in the bulk-processing

- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/DanglingRelationsCheck.java
- Cache the adapter by type so we don't hammer the DB trying to find an adapter for each relation
> #5142 - DanglingRelationsCheck hammers database and runs very slow

- inception/inception-workload-matrix/src/main/java/de/tudarmstadt/ukp/inception/workload/matrix/annotation/MatrixWorkflowActionBarItemGroup.java
- Check if the user is a manager/curator on the current project before rejecting re-opening the document
> #5145 - Managers and curators should be able to re-open their documents

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderer.java
- Render relations in never mode when rendering for the annotation sidebar
> #5147 - Relations should be visible in the annotation sidebar when render mode is never

- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/SectionAnnotationCreator.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/SectionAnnotationVisualizer.ts
- Reorganize code to reduce layout calculation by the browser
- Avoid calling SectionAnnotationCreator.ensureVisibility during scrolling - not necessary because the position of the section creators do not change when scrolling
- No need to align panels with spacers in render method because ensurePanelVisibility is called directly after
- Switch between absolute and fixed position for section labels to make the rendering look smoother
* Look at performance console in browser while rendering a large document
> #5159 - Improve HTML render performance

- inception/inception-html-apache-annotator-editor/src/main/java/de/tudarmstadt/ukp/inception/apacheannotatoreditor/ApacheAnnotatorHtmlAnnotationEditorFactoryUserPreferences.schema.json
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.scss
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorState.ts
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorToolbar.svelte
- Added corresponding switches
* Open MHTML document with images / tables
* Use the switches (note that tables may be used for layout which may cause the entire document to disappear...)
> #5157 - Ability to hide images/tables in HTML files

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationEndpointChangeListener.java
- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/config/AnnotationSchemaServiceAutoConfiguration.java
- Added listener that reacts when a span moves and updates the attaching relations
> #5178 - Resizing a span does not update offsets of attached relations

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- Use the feature name as arc label if roles are turned off
* Configure a slot feature to not have a role
* Fill a slot
* See what is rendered on the arc to the slot filler
> #5184 - Display slot name instead of layer name on slot arcs without a role

- inception/inception-schema/src/main/java/de/tudarmstadt/ukp/inception/schema/service/AnnotationSchemaServiceImpl.java
- Need to start a transaction when entering the schema service to avoid the bug
> #5188 - Export diff does not work when sentence and token editing is activate

- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.scss
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorVisualizer.ts
- inception/inception-js-api/src/main/ts/src/util/ViewportTracker.ts
- Use pre-line whitespace handling when displaying a plain text file in the HTML edior
- Assist the viewport tracker by introducing span annotations at the line level
* Try viewing a plain text file using the Apache Annotator HTML editor
> #5196  - Improve display of plain text files in HTML editor

- inception/inception-model/src/main/java/de/tudarmstadt/ukp/clarin/webanno/model/Project.java
- Disable export flag for new projects
* Create a new project
* Access the annotation page as a user who is just an annotator
* Check if export is available
> #5203 - Disable export of data for annotators by default

- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/documents/DocumentContextRetriever.java
- inception/inception-assistant/src/main/ts/src/AssistantPanel.svelte
- Require less transfer thinking when referring to a chunk
- Handle cases where a model insists on referring to chunks as "document XXX"
* Try deepseek-r1...
> #5241 - Improve assistant attribution functionality

- inception/inception-external-editor/src/main/ts/src/ExternalEditorFactory.ts
- Add missing head element client-side if necessary
* See issue
> #5261 - HTML files without a head element will not open in annotation editor

- .github/workflows/maven.yml
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/TokenAttachedSpanChangeListener.java
- Only resize token-attached annotations if the annotation being resized is actually a token - not for any arbitrary annotations
> #5270 - Resizing a span also resizes other overlapping or stacked spans

- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/CasDoctor.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorProperties.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorPropertiesImpl.java
- Commented out relevant code
* Start SNAPSHOT or beta version and check if the CAS doctor checks are enabled
> #5328 - Stop enabling all CAS doctor checks on beta and SNAPSHOT versions

- inception/inception-brat-editor/src/main/ts/src/curation/CurationMod.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- Fixed handling of the dummy chunks at start and end of the rendering window used for rendering partial relations - as well as other empty chunks - in RTL mode
* Try using the brat editors in RTL mode
> #5342 - Document sometimes not rendered in RTL mode

- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/AgreementServiceImpl.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/CodingStudyUtils.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/cohenkappa/CohenKappaAgreementMeasure.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/fleisskappa/FleissKappaAgreementMeasure.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalpha/KrippendorffAlphaAgreementMeasure.java
- inception/inception-agreement/src/main/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/krippendorffalphaunitizing/KrippendorffAlphaUnitizingAgreementMeasure.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/AgreementServiceImplTest.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementMeasureTestSuite_ImplBase.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/AgreementTestUtils.java
- inception/inception-agreement/src/test/java/de/tudarmstadt/ukp/clarin/webanno/agreement/measures/KrippendorffAlphaUnitizingAgreementMeasureTest.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanOverlapBehavior.java
- inception/inception-ui-agreement/src/main/resources/META-INF/asciidoc/user-guide/agreement.adoc
- Filter out all but the first and longest of the overlapping annotations with the same label in Krippendorff Unitzing Alpha
> #5348 - Krippendorff Alpha Unitizing does not filter out self-overlapping annotations

- inception/inception-assistant/src/main/java/de/tudarmstadt/ukp/inception/assistant/sidebar/WatchAnnotationTask.java
- inception/inception-assistant/src/main/ts/src/AssistantPanel.svelte
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/policy/DefaultHtmlDocumentPolicy.yaml
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlConstants.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlDocumentViewControllerImpl.java
- inception/inception-external-editor/src/main/java/de/tudarmstadt/ukp/inception/externaleditor/xhtml/XHtmlXmlMarkdownProcessor.java
- inception/inception-html-apache-annotator-editor/src/main/ts/src/apache-annotator/ApacheAnnotatorEditor.scss
- Display language name in fenced code block
- Cleaning up
* Try annotating markdown documents containing code blocks
> #5350 - Interpret plain text documents as Markdown when displaying in HTML-based editor

- inception/inception-imls-llm-support/pom.xml
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/response/Mention.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/response/MentionResult.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/response/MentionsFromStructuredOutputExtractor.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/response/ResponseAsLabelExtractor.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/response/ResponseExtractor.java
- inception/inception-imls-llm-support/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/support/traits/ChatBasedLlmRecommenderImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/span/SpanSuggestionRenderer.java
- Add allows tags to JSON schema instead of just having them in the task description
- Warn marker should only be displayed for corrections, not generally on all suggestions
> #5375 - Enforce use of tagset by LLM recommender

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- Abbreviate tag in lazy detail
* Create tag with long description and use it in an annotation
* Hover over the annotation to cause the popover to come up
* Ensure the tag description is abbreviated
> #5377 - Abbreviate long tag descriptions in popover

- inception/pom.xml
- pom.xml
- maven-versions-plugin 2.17.1 -> 2.18.0
- mariadb driver 3.5.2 -> 3.5.3
- hibernate 6.6.11 -> 6.6.12
- opensearch 2.18.0 -> 2.19.1
- byte-buddy 1.17.4 -> 1.17.5
- jna 5.15.0 -> 5.17.0
* No specific test procedure 
> #5380 - Upgrade dependencies

- inception/inception-brat-editor/src/main/ts/src/annotator_ui/AnnotatorUI.ts
- inception/inception-brat-editor/src/main/ts/src/visualizer/Visualizer.ts
- Fixed issue by handling selection differently depending on whether the user presses shift or not
> #5373 - Creating zero-width annotations does not work on Firefox

- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/text/TextUtils.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/xml/sanitizer/SanitizingContentHandler.java
- Change SanitizingContentHandler to replace illegal XML characters with space during rendering
> #5408 - Text files with certain control characters break HTML-based editors

- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/config/DocumentMetadataLayerSupportPropertiesImpl.java
- Set enabled flag to true by default (same as it is in the Spring auto-configuration)
> #5413 - Document metadata type is not available to be selected for Document classification task layer definition

- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception/inception-support/src/main/java/de/tudarmstadt/ukp/inception/support/wicket/WicketUtil.java
- inception/inception-ui-curation/src/main/java/de/tudarmstadt/ukp/inception/ui/curation/sidebar/CurationSidebarServiceImpl.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/CreateAnnotationsOptionsMetaDataKey.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/DeleteAnnotationsOptionsMetaDataKey.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebarFactory.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchOptionsMetaDataKey.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsProvider.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsProviderMetaDataKey.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchResultsProviderWrapper.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchSidebarIcon.html
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchSidebarIcon.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/StatisticsAnnotationSidebar.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/options/SearchOptions.java
- Store the state along with the page so it get retained when we switch to other sidebars.
- Move the rendering code from the sidebar itself to the icon so it does not get disabled when switching away from the sidebar.
- Trigger search when hitting ctrl-enter in the search field
* Search for something in the search sidebar
* Switch to another sidebar
* Reload page
* Switch back to search sidebar
* Search state and highlights should always be retained
> #5424 - Keep search state and highlights when search sidebar is not active

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/NopRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/rendering/Renderer.java
- Remove special handling of longArcs in SpanRenderer since RelationRenderer supports placeholders now
- A wee bit of cleaning up
* Try using the Intertext plugin on large richly annotated documents
> #5443 - Intertext plugin renders too slow for large richly annotated documents

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/preferences/UserPreferencesServiceImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/rendering/PreRendererImpl.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/ChainRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/RelationRenderer.java
- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/SpanRenderer.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/editorstate/AnnotationLayerVisibilityState.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/editorstate/AnnotationPreference.java
- inception/inception-api-render/src/main/java/de/tudarmstadt/ukp/inception/rendering/request/RenderRequest.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/sidebar/DocumentMetadataAnnotationSelectionPanel.java
- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VArc.java
- inception/inception-model-vdoc/src/main/java/de/tudarmstadt/ukp/inception/rendering/vmodel/VSpan.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/relation/ArcSuggestionRenderer_ImplBase.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/rendering/Renderer.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/FeatureSupport.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/TypeUtil.java
- inception/inception-support-bootstrap/src/main/ts/bootstrap/shim-checkboxx.scss
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/layer/LayerVisibilitySidebar.html
- inception/inception-ui-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/ui/annotation/sidebar/layer/LayerVisibilitySidebar.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureSupport.java
- Display features of each layer below the layer in the sidebar
- Allow toggling visibility of individual features
- Hide features that are toggled off in annotations
- Display tagsets under string features
- Allow toggling visibility of individual tags
- Hide tags that are toggled off in annotations
- Persist user-specific visibility settings across sessions
- Persist settings per user and per project
- Include settings in project export
- Restore settings on project import
- Support hiding individual labels from multi-label features
* Try the visibility feature in different configurations, e.g. with single-values string features, multi-valued string features, annotations with multiple features with the same or different tagsets, etc. …
> #5451 - Ability to control visibility of features and tags via sidebar

- inception/inception-curation/pom.xml
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeDocument.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeDocumentTest.java
- inception/inception-curation/src/test/java/de/tudarmstadt/ukp/inception/curation/merge/CasMergeTestBase.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/CreateDocumentAnnotationRequest.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentAnnotationRequest_ImplBase.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/ui/core/docanno/layer/DocumentMetadataLayerAdapter.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/adapter/TypeAdapter.java
- Added the merge implementation
* Add document-level annotations with different annotators and mark the documents as finished
* Open the document in the integrated curation page (should trigger auto-merging the first time)
* also try the bulk-processing auto-curation
> #5509 - Support document-level annotations in auto-curation

- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchQueryRequest.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchService.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/index/PhysicalIndex.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- inception/inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchSidebarIcon.java
- inception/inception-workload-dynamic/src/test/java/de/tudarmstadt/ukp/inception/workload/dynamic/DynamicWorkloadExtensionImplTest.java
- Searches done as part of the rendering process (SearchSidebarIcon.onRenderAnnotations) do not wait for changes to the MTAS index to have been committed anymore (which can take up to several seconds for large documents)
> #5540 - Slow reaction times on large documents when search is active

- inception/inception-api-formats/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/format/FormatSupport.java
- inception/inception-curation/pom.xml
- inception/inception-curation/src/main/java/de/tudarmstadt/ukp/inception/curation/merge/CasMerge.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/PdfStructurePresentInNonInitialCasCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/XmlStructurePresentInCurationCasCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/checks/XmlStructurePresentInNonInitialCasCheck.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/config/CasDoctorAutoConfiguration.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemovePdfStructureFromNonInitialCasRepair.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/RemoveXmlStructureFromNonInitialCasRepair.java
- inception/inception-diag/src/main/java/de/tudarmstadt/ukp/clarin/webanno/diag/repairs/ReplaceXmlStructureInCurationCasRepair.java
- inception/inception-diag/src/main/resources/META-INF/asciidoc/user-guide/casdoctor.adoc
- inception/inception-documents/pom.xml
- inception/inception-documents/src/main/java/de/tudarmstadt/ukp/inception/documents/DocumentServiceImpl.java
- inception/inception-io-bioc/src/main/java/de/tudarmstadt/ukp/inception/io/bioc/BioCXmlDocumentFormatSupport.java
- inception/inception-io-docx/src/main/java/de/tudarmstadt/ukp/inception/io/docx/DocxFormatSupport.java
- inception/inception-io-docx/src/main/java/de/tudarmstadt/ukp/inception/io/docx/DocxToCas.java
- inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/HtmlArchiveFormatSupport.java
- inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/HtmlFormatSupport.java
- inception/inception-io-html/src/main/java/de/tudarmstadt/ukp/inception/io/html/MHtmlFormatSupport.java
- inception/inception-io-tei/src/main/java/de/tudarmstadt/ukp/inception/io/tei/TeiXmlDocumentFormatSupport.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/CustomXmlFormatFactory.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/XmlFormatSupport.java
- inception/inception-io-xml/src/main/java/de/tudarmstadt/ukp/inception/io/xml/dkprocore/Cas2SaxEvents.java
- inception/inception-pdf-editor2/src/main/java/de/tudarmstadt/ukp/inception/pdfeditor2/format/PdfFormatSupport.java
- Added new checks and repairs to remove PDF/XML structure from non-initial CASes
- Added ability for format supports to prepare the CASes for annotators/curators (i.e. remove docment structure)
* ...
> #5542 - Keep document structure only in INITIAL_CAS to reduce user CAS sizes

- inception/inception-api-annotation/src/main/java/de/tudarmstadt/ukp/clarin/webanno/api/annotation/page/AnnotationPageBase.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseService.java
- inception/inception-kb/src/main/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImpl.java
- inception/inception-project/src/main/java/de/tudarmstadt/ukp/clarin/webanno/project/ProjectServiceImpl.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureEditor.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureEditor.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureTraitsEditor.java
- Add more read-only transactions
- Use more var
- Use a LoadableDetachableModel on the annotation page for the read-only status to avoid potential multiple DB lookups for this
> #5536 - Use read-only transactions when possible

- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningService.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/ActiveLearningServiceImpl.java
- inception/inception-active-learning/src/main/java/de/tudarmstadt/ukp/inception/active/learning/sidebar/ActiveLearningSidebar.java
- inception/inception-feature-link/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/link/recommender/LinkSuggestionSupport.java
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/multistring/MultiValueStringFeatureSupport.java
- inception/inception-feature-string/src/main/java/de/tudarmstadt/ukp/inception/annotation/feature/string/StringFeatureSupport.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/document/recommender/MetadataSuggestionSupport.java
- inception/inception-layer-docmetadata/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/document/sidebar/DocumentMetadataAnnotationSelectionPanel.java
- inception/inception-layer-relation/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/relation/recommender/RelationSuggestionSupport.java
- inception/inception-layer-span/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/recommender/SpanSuggestionSupport.java
- inception/inception-processing/src/main/java/de/tudarmstadt/ukp/inception/processing/recommender/BulkPredictionTask.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/RecommendationService.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/SuggestionSupport.java
- inception/inception-recommendation-api/src/main/java/de/tudarmstadt/ukp/inception/recommendation/api/SuggestionSupport_ImplBase.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/RecommendationEditorExtension.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
- inception/inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/sidebar/RecommenderInfoPanel.java
- inception/inception-recommendation/src/test/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImplIntegrationTest.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/annotation/type/RecommenderDeclUtil.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/annotation/type/StringSuggestionUtil.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/FeatureSupport.java
- inception/inception-schema-api/src/main/java/de/tudarmstadt/ukp/inception/schema/api/feature/SuggestionStatePanel.html
- inception/inception-schema-api/src/main/resources/de/tudarmstadt/ukp/inception/annotation/type/inception-static.xml
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/ConceptFeatureSupport.java
- inception/inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/feature/MultiValueConceptFeatureSupport.java
- Create utility function for getting or creating a new RecommenderDecl in the CAS
- Change score type in CAS from float to double
- Record the scores of all recommenders that predicted the same label
- Replace retained suggestions on single-value features and append on multi-value features when overriding a label (or setting one)
- Append on multi-value features
- Fix layout of SuggestionsStatePanel
* Enable the retain scores option and try with single/multi valued string/concept features and multiple recommenders
> #5534 - Option to retain recommender scores when accepting an annotation

- inception/inception-app-webapp/src/test/java/de/tudarmstadt/ukp/inception/db/InceptionMariadb_11_6_IntegrationTest.java
- inception/inception-app-webapp/src/test/resources/mariadb_11_6/my.cnf
- inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_database_mariadb.adoc
- inception/inception-search-core/src/main/java/de/tudarmstadt/ukp/inception/search/SearchServiceImpl.java
- inception/inception-search-mtas/src/main/java/de/tudarmstadt/ukp/inception/search/index/mtas/MtasDocumentIndex.java
- Add an override file which should disable snapshot isulation
- Added info to MariaDB setup guide about disabling snapshot isolation
* Wait and see if the integration tests run more stable now
> #5567 - Disable snapshot isolation in MariaDB 11.6.2 integration test

- inception/inception-assistant/src/main/ts_template/package-lock.json
- inception/inception-brat-editor/src/main/ts_template/package-lock.json
- inception/inception-diam-editor/src/main/ts_template/package-lock.json
- inception/inception-diam/src/main/ts_template/package-lock.json
- inception/inception-external-editor/src/main/ts_template/package-lock.json
- inception/inception-html-apache-annotator-editor/src/main/ts_template/package-lock.json
- inception/inception-html-recogito-editor/src/main/ts_template/package-lock.json
- inception/inception-io-tei/src/main/ts_template/package-lock.json
- inception/inception-io-xml/src/main/ts_template/package-lock.json
- inception/inception-js-api/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor/src/main/ts/audit-resolve.json
- inception/inception-pdf-editor/src/main/ts_template/package-lock.json
- inception/inception-pdf-editor2/src/main/ts/audit-resolve.json
- inception/inception-pdf-editor2/src/main/ts_template/package-lock.json
- inception/inception-project-export/src/main/ts_template/package-lock.json
- inception/inception-recommendation/src/main/ts_template/package-lock.json
- inception/inception-support-bootstrap/src/main/ts_template/package-lock.json
- inception/inception-ui-dashboard-activity/src/main/ts_template/package-lock.json
- inception/inception-ui-kb/src/main/ts_template/package-lock.json
- inception/inception-ui-scheduling/src/main/ts_template/package-lock.json
- inception/inception-ui-search/src/main/ts_template/package-lock.json
- pom.xml
* bootstrap 5.3.6 -> 5.3.8
* byte-buddy 1.17.6 -> 1.17.7
* caffeine 3.2.1 -> 3.2.2
* commons-codec 1.18.0 -> 1.19.0
* commons-compress 1.27.1 -> 1.28.0
* commons-csv 1.14.0 -> 1.14.1
* commons-io 2.19.0 -> 2.20.0
* commons-text 1.13.1 -> 1.14.0
* groovy 4.0.27 -> 4.0.28
* hibernate 6.6.20.Final -> 6.6.27.Final
* hibernate-validator 8.0.2.Final -> 8.0.3.Final
* jackson 2.19.1 -> 2.20.0
* jena 5.4.0 -> 5.5.0
* jetty 12.0.23 -> 12.0.25
* jjwt 0.12.6 -> 0.13.0
* json-schema-validator 1.5.6 -> 1.5.8
* junit-jupiter 5.13.3 -> 5.13.4
* junit-platform 1.13.3 -> 1.13.4
* mariadb-driver 3.5.4 -> 3.5.5
* mockito 5.18.0 -> 5.19.0
* mysql-driver 9.3.0 -> 9.4.0
* okio 3.15.0 -> 3.16.0
* rdf4j 5.1.3 -> 5.1.4
* snappy 1.1.10.7 -> 1.1.10.8
* solr 9.8.1 -> 9.9.0
* spring 6.2.8 -> …
> #5474 - Upgrade dependencies

- inception/inception-layer-chain/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/pivot/ChainCoveredTextExtractor.java
- inception/inception-layer-chain/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/chain/pivot/ChainRangeExtractor.java
- inception/inception-layer-span/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/pivot/SpanCoveredTextExtractor.java
- inception/inception-layer-span/src/main/java/de/tudarmstadt/ukp/inception/annotation/layer/span/pivot/SpanRangeExtractor.java
- Need to use non-prefixed names for text and range extractors, otherwise text and ranges from different layers cannot conflate
* Try explorer
> #5570 - Exploring and aggregating annotation data using a pivot table

- inception/inception-remote/pom.xml
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/config/RemoteApiAutoConfiguration.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/HttpWebhookDriver.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/KafkaWebhookDriver.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/Webhook.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookDriver.java
- inception/inception-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/WebhookService.java
- inception/inception-remote/src/main/resources/META-INF/asciidoc/admin-guide/remote-api-webhooks.adoc
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/HttpWebhookDriverTest.java
- inception/inception-remote/src/test/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/webhooks/KafkaWebhookDriverTest.java
- inception/inception-testing/src/main/java/de/tudarmstadt/ukp/inception/support/test/http/HttpTestUtils.java
. Modularized code
- Added basic Kafka driver (no authentication or advanced configuratiion)
- Added topic mapping options
* Try configuring INCEpTION to send messages to a Kafka broker:
```
webhooks.globalHooks[0].url=<kafkahost>:<kafkaport>
webhooks.globalHooks[0].driver=kafka
webhooks.globalHooks[0].topics[0]=DOCUMENT_STATE
webhooks.globalHooks[0].topic-aliases.DOCUMENT_STATE=MyAlternativeDocumentStateTopic
```
> #5596 - Send webhook events via Kafka instead of HTTP

- inception/inception-imls-ollama/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/llm/ollama/OllamaRecommender.java
- Send "json" instead of "json_object" if structured mode is not enabled and we cannot set a full schema
> #5599 - Calling Ollama in non-structured mode is broken

- inception/inception-app-webapp/src/test/java/de/tudarmstadt/ukp/inception/db/InceptionMariadb_11_7_IntegrationTest.java
- inception/inception-app-webapp/src/test/java/de/tudarmstadt/ukp/inception/db/InceptionMariadb_11_8_IntegrationTest.java
- inception/inception-app-webapp/src/test/resources/mariadb_11_7/my.cnf
- inception/inception-app-webapp/src/test/resources/mariadb_11_8/my.cnf
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepository.java
- inception/inception-log/src/main/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImpl.java
- inception/inception-log/src/test/java/de/tudarmstadt/ukp/inception/log/EventRepositoryImplIntegrationTest.java
- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/ActivitiesDashletControllerImpl.java
- inception/inception-ui-dashboard-activity/src/main/java/de/tudarmstadt/ukp/inception/ui/core/dashboard/activity/panel/ActivityPanel.java
- Added option to view activites on documents owned by the curation user
* Open the "show all" panel in the activity sidebar
* Select the curation user and check if the data looks sensible
> #5637 - Allow viewing activity by curators on curation

- inception/inception-diam-editor/src/main/ts/build.mjs
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLabelList.svelte
- inception/inception-diam-editor/src/main/ts/src/AnnotationsByLayerList.svelte
- Use derivedBy instead of effect to avoid endless update loop
> #5657 - Filter in annotation sidebar causes browser to lock up

- inception/inception-js-api/src/main/ts/src/widget/AnnotationDetailPopOver.svelte
- Fix empty element when no annotation comments are provided
- Preserve manual line-breaks in popover. This currently affects all detail groups including the "text". Need to see if this is a good idea.
> #5660 - Line breaks from multi-line string features are removed in annotation popover

- inception/inception-io-lif/pom.xml
- pom.xml
- hibernate 6.6.30 -> 6.6.31
- wicketsfuff 10.6.0 -> 10.7.0
- wicket-bootstrap 7.0.11 -> 7.0.12
- wicket-jquery-selectors 4.0.11 -> 4.0.13
- wicket-webjars 4.0.11 -> 4.0.13
- mime4j 0.8.11 -> 0.8.13
- mariadb-client 3.5.5 -> 3.5.6
- fastutil 8.5.17 -> 8.5.18
> #5610 - Upgrade dependencies
